### ISSUE TITLE
Chaos thoughts or scenarios

### ISSUE THREAD

**Issue by umamukkara** [litmuschaos/litmus#1001]
This issue is created to seek feedback from community on chaos scenarios or use cases. Please add your feedback as a comment to this issue in the following format:

Use case:
What more can Litmus project do to help me practice chaos engineering better:

**Comment by rajdeepbhattacharya** [comment]
Introducing security as a chaos experiments. This will help to measure what happens if the security and compliance tool itself fail.

**Comment by ksatchit** [comment]
We have been receiving feedback from offline channels on areas to improve - including out-of-the-box chaos experiments  and enhanced orchestration/mgmt capabilities. 

Closing this issues on account of the same.
