### ISSUE TITLE
(feat): Gitlab ci for litmuschaos/chaos-operator 

### ISSUE THREAD

**Issue by uditgaurav** [litmuschaos/litmus#1005]
- Creating Gitlab CI/CD pipeline for the [chaos-operator](https://github.com/litmuschaos/chaos-operator)
- Following are the stages added in Gitlab configuration file
     - Setup:- This is the first phase, In this phase a cluster gets setup. The additional information about the cluster is provided by the user i.e number of nodes, CPU, memory, of the cluster, It involves 
          - Creation of VPC
          - Creation of cluster
          - Checking the availability of the cluster
          -  Creating firewall 
     - Build:- After setting up a cluster next phase comes is build phase. This phase the dependencies will be built for running BDDs.
     - Test:- This stage is used for running BDDs.
     - Push:- It includes Build & Push of chaos-operator docker image
     - Cleanup:- This is the final stage where the cluster along with VPC and firewall which was created is removed.

**Comment by rajdas98** [comment]
Issue added to the 1.0 project board

**Comment by rajdas98** [comment]
PR has been merged
