### ISSUE TITLE
(feat): Gitlab ci for litmuschaos/chaos-exporter

### ISSUE THREAD

**Issue by uditgaurav** [litmuschaos/litmus#1007]
- Creating Gitlab CI/CD pipeline for the [chaos-exporter](https://github.com/litmuschaos/chaos-operator)
- The pipeline is of three stages:
   - setup: The cluster setup stage
   - build: The build stage which contains the building dependencies.
   - test: The test phase will contain the running of BDDs.
   - push: The push phase contains the building and pushing of chaos-exporter Image. 
   - cleanup: The cluster cleanup stage.

**Comment by rajdas98** [comment]
Issue added to the 1.0 project board
