### ISSUE TITLE
(feat): Performance Scale/Benchmark litmus experiment

### ISSUE THREAD

**Issue by uditgaurav** [litmuschaos/litmus#1027]
Performance Scale/Benchmark litmus experiment
- Scaling FIOs

**Comment by ksatchit** [comment]
Initial approach: Usage of ansible-based operator (operator-sdk) with an fio role to trigger fio jobs

**Comment by ksatchit** [comment]
This is available in an initial here: https://github.com/litmuschaos/litmus-go/tree/master/experiments/generic/pod-fio-stress
