### ISSUE TITLE
Separate the view in chart-hub chaos-experiments  for app-level or Infra level chaos

### ISSUE THREAD

**Issue by is-ashish** [litmuschaos/litmus#1034]
Categorized chaos experiments -
1 - App Lavel 
2 -  Infra Lavel 

An Icon will indicate each chaos experiment with App-level or Infra-level.

**Comment by ksatchit** [comment]
This is fixed by: https://github.com/litmuschaos/charthub.litmuschaos.io/pull/89

The app-level/infra-level chaos experiments are differentiated by an icon on the experiment cards indicating the blast radius.
