### ISSUE TITLE
Test playbook of EBS Volume & GPD Disk Creation work from a container

### ISSUE THREAD

**Issue by chandankumar4** [litmuschaos/litmus#105]
## FEATURE REQUEST?
 
**What happened**:
- Test create-ebs-volume.yml & create-gpd-disk.yml playbook work from a container as like as `cluster-creation` working

**What you expected to happen**:
- After running playbook `ebs volume` in AWS and `gpd disk` in GCP successfully attached and mounted 

**Anything else we need to know?**:
- AWS ebs-volume file location :- https://github.com/openebs/litmus/tree/master/k8s/aws/ebs-volumes
- GCP gpd-dsik file location :-

**Comment by ksatchit** [comment]
Moved to https://github.com/mayadata-io/litmus/issues/129
