### ISSUE TITLE
Litmus Tests should be available as modules and should not be packed into image

### ISSUE THREAD

**Issue by ashishranjan738** [litmuschaos/litmus#111]
FEATURE REQUEST

-> Litmus Tests should be available as modules and should not be packed into the ansible runner image itself.
-> Currently litmus tests are packed on ansible-runner image which means for running any test the user has to download all the tests which may not be of any use for him.
-> Litmus Tests can be converted to ansible roles and can be pushed to the galaxy or can be packed into a zip and pushed to some other hosting platform.
-> Since Litmus tests are ansible playbooks which means these playbooks should be reusable.

**What happened**:
-> Currently when we run any litmus job the ansible-runner image is pulled which contains the test.

**What you expected to happen**:
-> Ansible-runner image should have the business logic to get any specific test and execute it.
-> Separating tests from the image will help managing tests in a better way.

**Comment by ksatchit** [comment]
The litmus tests are now primarily written and maintained in golang. The litmus-go repo can be cloned and experiment business logic executed with the right environment variables passed to the <experiment>.go files. 

In fact, the test approach for litmus experiments is based on a similar principle: https://github.com/litmuschaos/litmus-go/tree/master/contribute/developer-guide
