### ISSUE TITLE
(feat): Use ansible runner image tag[ci/latest] in pipeline as per branch(master/release)

### ISSUE THREAD

**Issue by uditgaurav** [litmuschaos/litmus#1121]
This is a feature request for litmus-e2e pipelines. 

**_It includes_**

- The triggering of the pipeline according to the branch i.e if the branch is release then trigger the pipeline with jobs that contains the latest image tag and if the branch is the master (other than release) branch then the pipeline should trigger with the ci image tag.

**_why it is required?_**

- It is required as the latest image contains the changes in the last release while the ci image tag contains the most recent change in the code and the pipeline needs to run accordingly to satisfy its purpose.

**Comment by ksatchit** [comment]
cc: @uditgaurav is this already available today?

**Comment by uditgaurav** [comment]
Yes, @ksatchit we can setup any image but it is not as per branch

**Comment by uditgaurav** [comment]
This is now achieved with a custom image/image tag run.
