### ISSUE TITLE
(feat): Litmus-e2e repository management passing history of the pipeline runs.

### ISSUE THREAD

**Issue by uditgaurav** [litmuschaos/litmus#1122]
It is a feature request for litmus-e2e pipeline:

**_It includes_**

- The Litmus-e2e repository management passing the history of the pipeline runs.

**_why it is required?_**

- Showing the history of the total runs with results and logs in the litmus-e2e repository will help to keep an easy track of the status of the pipelines.

**Comment by ksatchit** [comment]
cc: @uditgaurav How do we plan to go about this?

**Comment by uditgaurav** [comment]
PRs to fix the issue for generic pipelines:
1. https://github.com/litmuschaos/litmus-e2e/pull/110
2. https://github.com/litmuschaos/litmus-e2e/pull/111

We are updating the pipeline history of generic experiment under generic_pipeline folder->Readme of baseline branch cc: @ksatchit

**Comment by ksatchit** [comment]
Fixed by https://github.com/litmuschaos/litmus-e2e/pull/110 https://github.com/litmuschaos/litmus-e2e/pull/111

A separate issue will be created to track this for OpenEBS pipelines.
