### ISSUE TITLE
Can we start a chaos test by event trigger?

### ISSUE THREAD

**Issue by del-zhenwu** [litmuschaos/litmus#1123]
Chaos usually intend to use experiments to discover issues in systems, but sometimes, testers and developers test system by triggering event (some tools like fiu what do), for example:
A function may not be executed by running chaos in some days, but if we call this function then trigger chaos experiment, it will be highly efficient to find problems in this function

**Comment by ksatchit** [comment]
Thats an interesting one @del-zhenwu , thank you for the issue. Can you share some more examples?

**Comment by ksatchit** [comment]
@del-zhenwu , when you say function level, do you mean: 

- (a) a broad occurrence within the cluster - like when such-and-such pod is created/deleted? 

-- or is it -- 

- (b) a particular code path is traversed within an application? 

If it is the latter - (b), can it manifest itself in some form for an external watcher to act upon it. Say, via a kubernetes event or something. It would be great to add such event triggered automation capability into Litmus.

cc: @AmitKumarDas

**Comment by ksatchit** [comment]
@del-zhenwu , it would be great to hear more thoughts from you regarding this. We would also like to welcome you to the litmus slack channel (K8s workspace): https://app.slack.com/client/T09NY5SBT/CNXNB0ZTN

**Comment by del-zhenwu** [comment]
> @del-zhenwu , when you say function level, do you mean:
> 
> * (a) a broad occurrence within the cluster - like when such-and-such pod is created/deleted?
> 
> -- or is it --
> 
> * (b) a particular code path is traversed within an application?
> 
> If it is the latter - (b), can it manifest itself in some form for an external watcher to act upon it. Say, via a kubernetes event or something. It would be great to add such event triggered automation capability into Litmus.
> 
> cc: @AmitKumarDas
This project is amazing.
What I thought it's an API-calling function in Litmus, make trigger event more manageable

**Comment by AmitKumarDas** [comment]
@del-zhenwu I am still trying to understand the meaning of event here.
AFAIK Litmus experiments can be triggered by applying a K8s custom resource.
This also means that one can invoke K8s APIs that creates this custom resource & hence trigger the chaos.

**Comment by del-zhenwu** [comment]
> @del-zhenwu I am still trying to understand the meaning of event here.
> AFAIK Litmus experiments can be triggered by applying a K8s custom resource.
> This also means that one can invoke K8s APIs that creates this custom resource & hence trigger the chaos.

I got it, users we can use k8s-api to trigger test like "CPU/GPU FULL" experiment now, then there is no need to call CHAOS-api

**Comment by ksatchit** [comment]
Yes, you are right @del-zhenwu ! As @AmitKumarDas mentioned & you understood correctly we can just use the K8s api to trigger the chaos test.

 Here is a simple illustration of that:

**Comment by ksatchit** [comment]
An event-triggered chaos functionality is now available. Ref: https://docs.litmuschaos.io/docs/concepts/gitops#event-driven-chaos-injection
