### ISSUE TITLE
(refactoring): Mobile View Optimisation#2

### ISSUE THREAD

**Issue by aditya109** [litmuschaos/litmus#1125]
#### What needs to be done ?

- [ ] Mobile UI needs to be fixed
> This requires making refactoring in the `styles` and `components` of [ChartHub] to fix bad mobile views(https://github.com/litmuschaos/charthub.litmuschaos.io).

##### Take-A-Point
- [ ] changes required in `src` directory of the [charthub.litmuschaos.io](https://github.com/litmuschaos/charthub.litmuschaos.io) repo

**Comment by ksatchit** [comment]
The charthub has been revamped with improvements in mobile view. New issues will be created to track specific enhancements.
