### ISSUE TITLE
(feature-request): Improve search-box functionality in Charthub

### ISSUE THREAD

**Issue by aditya109** [litmuschaos/litmus#1132]
#### What needs to be done ?

- [ ] Implementation of **flex-search** in search box logic so as to filter charts' and experiments according to keywords as well

##### Take-A-Point
- [ ] changes required in `src` directory of the [charthub.litmuschaos.io](https://github.com/litmuschaos/charthub.litmuschaos.io) repo

**Comment by ksatchit** [comment]
cc: @chandankumar4

**Comment by ksatchit** [comment]
The search has been improved to perform hub-wide search over page specific search.
