### ISSUE TITLE
(feat) Add mitmproxy chaoslib for http(s) proxy experiments

### ISSUE THREAD

**Issue by LaumiH** [litmuschaos/litmus#1179]
The goal is to provide experiments using [mitmproxy](https://github.com/mitmproxy/mitmproxy/) in form of a new chaoslib. Experiments then can intercept http(s) traffic and block/modify it or send own responses and so on. It is more fine-grained than the current network experiments provided by pumba, which was why I looked into it in the first place :).

A mitmproxy container shall run in a pod on the same node as the target and be accessible by a service. It is provided with a python script it executes through mitmdump. The script e.g. intercepts http traffic and sends a custom response from the proxy itself, or it blocks every http(s) traffic. [Here](https://github.com/mitmproxy/mitmproxy/tree/master/examples) are some example scripts.

To target resources in the cluster, `kubectl set env http(s)_proxy=proxy-ip` (see [the docs](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#-em-env-em-)) is executed. Hence, the target pod/ container/ deployment/ ... restarts its replicas with the new env and then proxies its traffic through the mitmproxy pod. I thought about messing with iptables or default routes, but dismissed the idea because it would be complicated to restore the previous state after the experiment is finished. With `kubectl set env http(s)_proxy-` this can be achieved very easily.

Concerning the python script two ideas came to mind (thanks @ksatchit !):
1. provide pre-built scripts that can be customized through args 
2. let the user load own scripts though configmaps

I already started implementing this and I can route traffic through the proxy and execute a hardcoded script.

Please let me know your ideas and suggestions :)

**Comment by LaumiH** [comment]
Please see https://github.com/LaumiH/litmus/tree/mitmproxy/chaoslib/mitmproxy/experiment for status

**Comment by LaumiH** [comment]
The proxy service ip is not yet set correctly (currently to 'svc-ip:8080' dummy value), and the restoration of http(s)_proxy values that existed before the experiment does not work correctly ('' is set if there weren't any, though there is a when condition). Also the configmap name is hardcoded to `mitmproxy-conf`.

But for demonstration purposes it works :)

1. Apply the changed rbac, because access to services is needed.
2. Build a custom ansible runner.
3. Create the ConfigMap from the script.py with `kubectl create configmap mitmproxy-conf --from-file=script.py`
4. Change the target app and apply the `mitmproxy_chaos_k8s_job_test.yml`.
5. Observe how the target app pods are restarted with the new env variables and how http-traffic is now blocked (because of dummy svc-ip proxy).
6. The experiment resources get cleaned up and everything should work like before.

**Comment by LaumiH** [comment]
TODO:
- Make ConfigMap configurable (waiting for litmus 1.1)
- Add a few prebuilt scripts that the user can choose and modify
- Change svc-ip to real extracted value
- Fix restoration of old proxy values

- Probably look into how proxies can be set without restarting the pods, e.a. via default route. Idk if it is cool to restart them before chaos ...

**Comment by LaumiH** [comment]
I am currently stuck at finding a solution for routing all TCP traffic from the target app through the proxy.
1. `kubectl set env` or `kubectl patch` work perfectly, but as the env vars are setted, a new replicaSet of the pod is created. This would mean that the chaos experiments mess with update/rollback strategies, which is a nogo.
2. I could be possible to modify the iptabes directly, but I don't know how to do this for only one pod.

I try to find another solution. Maybe creating a service and disabling any existing services would work?

**Comment by ksatchit** [comment]
Http chaos in litmus are now supported. Reference: https://litmuschaos.github.io/litmus
