### ISSUE TITLE
(typo) litmus-docs: extra comma appears

### ISSUE THREAD

**Issue by aditya109** [litmuschaos/litmus#1182]
Extra single inverted comma appears in GCP Project ID of engine manifest of disk-loss

![image](https://user-images.githubusercontent.com/22005947/73333286-59a58e00-428f-11ea-93e8-c9935d8ef529.png)

**Comment by aditya109** [comment]
This is already fixed in staging-docs.

**Comment by shubhamchaudhary** [comment]
@aditya109 Thanks, This issue is fixed by PR: with PR: https://github.com/litmuschaos/litmus-docs/pull/178
