### ISSUE TITLE
facing problem while applying the chaosexperiment

### ISSUE THREAD

**Issue by sumitnagal** [litmuschaos/litmus#1185]
**What happened**:
this command is failing 
`kubectl create -f https://hub.litmuschaos.io/api/chaos?file=charts/generic/experiments.yaml`

**What you expected to happen**:
It should apply and we get values from below command
kubectl get chaosexperiments 

**How to reproduce it (as minimally and precisely as possible)**:
try on new cluster with a name space which is not default

**Anything else we need to know?**:
here is error
unable to recognize "experiments.yaml": no matches for kind "ChaosExperiment" in version "litmuschaos.io/v1alpha1"
unable to recognize "experiments.yaml": no matches for kind "ChaosExperiment" in version "litmuschaos.io/v1alpha1"
unable to recognize "experiments.yaml": no matches for kind "ChaosExperiment" in version "litmuschaos.io/v1alpha1"
unable to recognize "experiments.yaml": no matches for kind "ChaosExperiment" in version "litmuschaos.io/v1alpha1"
unable to recognize "experiments.yaml": no matches for kind "ChaosExperiment" in version "litmuschaos.io/v1alpha1"
unable to recognize "experiments.yaml": no matches for kind "ChaosExperiment" in version "litmuschaos.io/v1alpha1"
unable to recognize "experiments.yaml": no matches for kind "ChaosExperiment" in version "litmuschaos.io/v1alpha1"
unable to recognize "experiments.yaml": no matches for kind "ChaosExperiment" in version "litmuschaos.io/v1alpha1"
unable to recognize "experiments.yaml": no matches for kind "ChaosExperiment" in version "litmuschaos.io/v1alpha1"
unable to recognize "experiments.yaml": no matches for kind "ChaosExperiment" in version "litmuschaos.io/v1alpha1"

**Comment by rahulchheda** [comment]
Please install Litmus Card's before installing the chaos experiments.

**Comment by rahulchheda** [comment]
Can you please provide the Chaos-operator installation step log's

**Comment by sumitnagal** [comment]
I did install the litmus and was following the steps mentioned as started doc. 
➜  litmus git:(master) ✗ k get pod -n litmus    
NAME                                READY   STATUS    RESTARTS   AGE
chaos-operator-ce-f97dd466b-vbx46   1/1     Running   0          6m42s
➜  litmus git:(master) ✗ k get crds | grep lit  
chaosengines.litmuschaos.io               2020-02-03T16:06:59Z
chaosexperiments.litmuschaos.io           2020-02-03T16:06:59Z
chaosresults.litmuschaos.io               2020-02-03T16:06:59Z

**Comment by rajdas98** [comment]
Can you send the logs after applying `kubectl logs -f chaos-operator-ce-f97dd466b-vbx46 -n litmus`

**Comment by rahulchheda** [comment]
Can you also provide logs after this:

**Comment by sumitnagal** [comment]
> Can you send the logs after applying `kubectl logs -f chaos-operator-ce-f97dd466b-vbx46 -n litmus`

{"level":"info","ts":1580795395.0626378,"logger":"cmd","msg":"Go Version: go1.10.3"}
{"level":"info","ts":1580795395.0626674,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1580795395.062676,"logger":"cmd","msg":"Version of operator-sdk: v0.12.0"}
{"level":"info","ts":1580795395.0627246,"logger":"leader","msg":"Trying to become the leader."}
{"level":"info","ts":1580795395.8854094,"logger":"leader","msg":"No pre-existing lock was found."}
{"level":"info","ts":1580795395.8897326,"logger":"leader","msg":"Became the leader."}
{"level":"info","ts":1580795396.8323474,"logger":"metrics","msg":"Metrics Service object created","Service.Name":"chaos-operator-metrics","Service.Namespace":"litmus"}
{"level":"info","ts":1580795397.637368,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":"0.0.0.0:8383"}
{"level":"info","ts":1580795397.6379955,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"chaosengine-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1580795397.638222,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"chaosengine-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1580795397.6383955,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"chaosengine-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1580795397.6386302,"logger":"cmd","msg":"Starting the Chaos-Operator..."}
{"level":"info","ts":1580795397.6388304,"logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
{"level":"info","ts":1580795397.7389066,"logger":"controller-runtime.controller","msg":"Starting Controller","controller":"chaosengine-controller"}
{"level":"info","ts":1580795397.83913,"logger":"controller-runtime.controller","msg":"Starting workers","controller":"chaosengine-controller","worker count":1}

**Comment by sumitnagal** [comment]
> Can you also provide logs after this:
> `kubectl api-resources | grep litmus`

  litmus git:(master) kubectl api-resources  | grep litmus
chaosengines                                   litmuschaos.io                 true         ChaosEngine
chaosexperiments                               litmuschaos.io                 true         ChaosExperiment
chaosresults                                   litmuschaos.io                 true         ChaosResult

**Comment by sumitnagal** [comment]
please add validation for this ` litmus git:(master) kubectl api-resources | grep litmus ` and then execute the `kubectl create -f experiments.yaml
