### ISSUE TITLE
Add a functional BDD test for checking Deletion of resources from Chaos-operator

### ISSUE THREAD

**Issue by rahulchheda** [litmuschaos/litmus#1190]
- This Issue ID for tracking the additional BDD Testcase for Chaos-operator
     - After the PR's
        - https://github.com/litmuschaos/chaos-operator/pull/133,
        - https://github.com/litmuschaos/chaos-operator/pull/123
     - Need a BDD to check deletion of chaos resources

**Comment by ksatchit** [comment]
This is fixed via https://github.com/litmuschaos/chaos-operator/pull/166
