### ISSUE TITLE
How litmus provide support for library which is exposed via rest API

### ISSUE THREAD

**Issue by sumitnagal** [litmuschaos/litmus#1204]
As discussed with Karthik in detail giving information on how can we integrate chaoslib (custom docker resources), which is exposed as a rest api. 

- Example to implement chaostoolkit you invoke `chaos run <json>`

- To implement our library, you have to make a call, given we give the container which exposes api/v1 endpoint like http://localhost/api/v1 with Post call using json body as 

`{ "name": "killpod", "label":"<YOUR_APP_LABEL>"}`

- Now the API, will be enhanced and support many use cases which vary with various payload similar way the above json payload.

**Comment by ksatchit** [comment]
Thank you @sumitnagal ! This is great feedback. We shall get back on this soon.

**Comment by ksatchit** [comment]
### Chaos CRDs as K8s API endpoints 

Litmus makes use of Kubernetes custom resources to describe the chaos intent. By default, creation of the chaos custom resource definitions (CRDs) create RESTful API endpoints, which can be made use by any external client to trigger experiments or extract information about ongoing experiments.  

- List of available chaos endpoints (*http://localhost:8001/apis/litmuschaos.io/v1alpha1*)

```json
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "litmuschaos.io/v1alpha1",
  "resources": [
    {
      "name": "chaosresults",
      "singularName": "chaosresult",
      "namespaced": true,
      "kind": "ChaosResult",
      "verbs": [
        "delete",
        "deletecollection",
        "get",
        "list",
        "patch",
        "create",
        "update",
        "watch"
      ],
      "storageVersionHash": "8pNoFUtooF8="
    },
    {
      "name": "chaosresults/status",
      "singularName": "",
      "namespaced": true,
      "kind": "ChaosResult",
      "verbs": [
        "get",
        "patch",
        "update"
      ]
    },{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "litmuschaos.io/v1alpha1",
  "resources": [
    {
      "name": "chaosresults",
      "singularName": "chaosresult",
      "namespaced": true,
      "kind": "ChaosResult",
      "verbs": [
        "delete",
        "deletecollection",
        "get",
        "list",
        "patch",
        "create",
        "update",
        "watch"
      ],
      "storageVersionHash": "8pNoFUtooF8="
    },
    {
      "name": "chaosresults/status",
      "singularName": "",
      "namespaced": true,
      "kind": "ChaosResult",
      "verbs": [
        "get",
        "patch",
        "update"
      ]
    },
    {
      "name": "chaosengines",
      "singularName": "chaosengine",
      "namespaced": true,
      "kind": "ChaosEngine",
      "verbs": [
        "delete",
        "deletecollection",
        "get",
        "list",
        "patch",
        "create",
        "update",
        "watch"
      ],
      "storageVersionHash": "HicW+LiLIPY="
    },
    {
      "name": "chaosexperiments",
      "singularName": "chaosexperiment",
      "namespaced": true,
      "kind": "ChaosExperiment",
      "verbs": [
        "delete",
        "deletecollection",
        "get",
        "list",
        "patch",
        "create",
        "update",
        "watch"
      ],
      "storageVersionHash": "Uvul/V717JM="
    },
    {
      "name": "chaosexperiments/status",
      "singularName": "",
      "namespaced": true,
      "kind": "ChaosExperiment",
      "verbs": [
        "get",
        "patch",
        "update"
      ]
    }
  ]
}
    {
      "name": "chaosengines",
      "singularName": "chaosengine",
      "namespaced": true,
      "kind": "ChaosEngine",
      "verbs": [
        "delete",
        "deletecollection",
        "get",
        "list",
        "patch",
        "create",
        "update",
        "watch"
      ],
      "storageVersionHash": "HicW+LiLIPY="
    },
    {
      "name": "chaosexperiments",
      "singularName": "chaosexperiment",
      "namespaced": true,
      "kind": "ChaosExperiment",
      "verbs": [
        "delete",
        "deletecollection",
        "get",
        "list",
        "patch",
        "create",
        "update",
        "watch"
      ],
      "storageVersionHash": "Uvul/V717JM="
    },
    {
      "name": "chaosexperiments/status",
      "singularName": "",
      "namespaced": true,
      "kind": "ChaosExperiment",
      "verbs": [
        "get",
        "patch",
        "update"
      ]
    }
  ]
}
```
### Sample Chaos Experiment Trigger via API

- Here is an example of a chaos experiment run via API call (which creates the chaosengine resource) along with the sample JSON body consisting of a typical "chaos payload" looks like this: 

*curl -s http://localhost:8001/apis/litmuschaos.io/v1alpha1/namespaces/default/chaosengines -XPOST -H 'Content-Type: application/json' -d@pod-delete-chaosengine.json* 

A sample JSON body consisting of a typical "chaos payload" looks like this: 

```json
{
    "apiVersion": "litmuschaos.io/v1alpha1",
    "kind": "ChaosEngine",
    "metadata": {
        "name": "nginx-chaos",
        "namespace": "default"
    },
    "spec": {
        "appinfo": {
            "appns": "default",
            "applabel": "app=nginx",
            "appkind": "deployment"
        },
        "annotationCheck": "true",
        "engineState": "active",
        "auxiliaryAppInfo": "",
        "chaosServiceAccount": "nginx-sa",
        "monitoring": false,
        "jobCleanUpPolicy": "delete",
        "experiments": [
            {
                "name": "pod-delete",
                "spec": {
                    "components": {
                        "env": [
                            {
                                "name": "TOTAL_CHAOS_DURATION",
                                "value": "30"
                            },
                            {
                                "name": "CHAOS_INTERVAL",
                                "value": "10"
                            },
                            {
                                "name": "FORCE",
                                "value": "false"
                            }
                        ]
                    }
                }
            }
        ]
    }
}
```
- Results of the chaos experiments (verdict) retrieved via an API call 

*curl -s http://localhost:8001/apis/litmuschaos.io/v1alpha1/namespaces/default/chaosresults/nginx-chaos-pod-delete | jq '.spec.experimentstatus.verdict'*

```json
"Pass"
```

**Comment by ksatchit** [comment]
The REST calls to the kubernetes API server in the manner above have to be made either by running kubectl in proxy mode or via authentication tokens. Programmatic access via the go/python clients is another approach, with the kubeconfig file being passed to the client binaries. 
Litmus as a framework already does lend itself to API-based control/operations for chaos in the described manner. 

Having said that, Litmus can itself provide a dedicated API server, that helps translating chaos requirements to the actual definitions and aid other helpful user-functions around available listing & describing experiments, grouping them, generation of new experiments, reports along with a simple client or kubectl plugin.

**Comment by sumitnagal** [comment]
Thanks, @ksatchit , just to simply these calls we have implemented it as python command line, for example, `python  killpod  lavel=<label name>` these calls will be packaged in our chaoslib docker container, which could invoke via above call or invoke via above command line.

**Comment by ksatchit** [comment]
Thats a good way to simplify these calls. We have been thinking on the same lines. A kubectl plugin would be handy here, I suppose.

**Comment by rajdas98** [comment]
Added a issue for `kubectl plugin` - https://github.com/litmuschaos/litmus/issues/1307
A WIP Repository- https://github.com/rajdas98/litmus-cli
