### ISSUE TITLE
Experiments do not appear to work properly in the non-default namespace.

### ISSUE THREAD

**Issue by cpitstick-argo** [litmuschaos/litmus#1214]
**What happened**: I'd like to use the pod-delete and the node-cpu-hog Litmus experiment on services that are in namespaces other than default, and thus far I get errors like this:

`time="2020-02-17T20:57:56Z" level=info msg="Unable to get the Default ENV from ChaosExperiment, error : chaosexperiments.litmuschaos.io \"node-cpu-hog\" is forbidden: User \"system:serviceaccount:litmus:cloud-platform-chaos-admin\" cannot get resource \"chaosexperiments\" in API group \"litmuschaos.io\" in the namespace \"hello-world-example\"`

` Unable to set values from ChaosRunner, error: Unable to get runner pod in namespace: hello-world-example: pods "engine-hello-world-pod-delete-runner" not found`

`Unable to set values from chaosExperiments Unable to get ChaosExperiment instance in namespace: hello-world-example: chaosexperiments.litmuschaos.io "pod-delete" not found`

**What you expected to happen**: In some of the documentation for Litmus 1.0.0, there was the allusion to the ability to run experiments in non-default namespaces. Right now, however, that doesn't appear to be working.

**How to reproduce it (as minimally and precisely as possible)**:
- Deploy [Google's Hello World Example](https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/tree/master/hello-app) in your Kubernetes cluster in something other than the default namespace (I used "hello-world-example")
- Attempt to configure Litmus such that you are able to do pod delete or node cpu hog on the service.

**Anything else we need to know?**: Yep!
1. ChaosExperiments are defined in the default namespace because the ChaosExperiment CRD is namespaced. Why? I'm not sure this is necessary. Experiments should be able to be applied to any part of a Kubernetes cluster. Without unlocking this, you'd need to copy the CR into every namespace you need to use.
2. This is a blocker for using Litmus. If this isn't supported or fixed, it violates least-privileges. None of our apps run in default, and I would argue very little should other than core parts of the cluster.
3. If this is supported, could you document it well? I've spent a day and a half banging my head against a wall trying to get this to work!

**Comment by ksatchit** [comment]
Hi @cpitstick-argo , the experiment CRs can be created in any namespace where the target app resides (along with the experiment serviceaccount and chaosengine). That is how it is being used right now. The example used an app in the default ns, and in general seems misleading. It is being fixed via https://github.com/litmuschaos/litmus-docs/pull/208

Could you please take a look at this and let us know if it makes more sense?

**Comment by cpitstick-argo** [comment]
I view this as "necessary but not sufficient." There are a couple issues with this update:

1. It doesn't use Kubernetes Best Practices -- The right way here is to template the manifests using a templating engine (and that engine probably should be Helm). By leaving the namespace off of the manifest its less explicit, which is generally a bad thing.

2. The requirement still remains that everything  (experiment CRs, experiment engines, and the app under test) all be in the same namespace. This should be optional, as there is a use-case [see 1219](https://github.com/litmuschaos/litmus/issues/1219) for experiments to be in a separate namespace from the applications they test.

**Comment by ksatchit** [comment]
> I view this as "necessary but not sufficient." There are a couple issues with this update:
> 
> 1. It doesn't use Kubernetes Best Practices -- The right way here is to template the manifests using a templating engine (and that engine probably should be Helm). By leaving the namespace off of the manifest its less explicit, which is generally a bad thing.
> 2. The requirement still remains that everything  (experiment CRs, experiment engines, and the app under test) all be in the same namespace. This should be optional, as there is a use-case [see 1219](https://github.com/litmuschaos/litmus/issues/1219) for experiments to be in a separate namespace from the applications they test.

- The item (1) is being tracked via issue https://github.com/litmuschaos/litmus/issues/1221
- The item (2) is being tracked via issue https://github.com/litmuschaos/litmus/issues/1219

As for the current issue - the docs not clear enough wrt running examples with non-default ns has been addressed in the docs PR https://github.com/litmuschaos/litmus-docs/pull/208

**Comment by ksatchit** [comment]
Helm charts & admin mode functionality (both available from 1.3) address this requirement. Closing this issue.
