### ISSUE TITLE
Remove requirement that experiments, engines, and application all be in the same namespace

### ISSUE THREAD

**Issue by cpitstick-argo** [litmuschaos/litmus#1219]
In [issue 1214](https://github.com/litmuschaos/litmus/issues/1214), I started the conversation about namespaces and Litmus. Essentially: Before 1214, there was no easy way to run your application in anything other than the **default** namespace. I'm glad that's changed, but we need to go further!

The problem still remains that the experiments CR, the engines themselves, and the application under test must all still be in the same namespace.

The ideal from my perspective would be to have the experiments (and maybe even the engines) have the ability to be defined in an "administrator" namespace (or the litmus namespace itself), and then have applications "opt in" to the experiments by the existing annotation system WITHOUT needing those additional resources in the application's namespace.

Advantages: 

1.  A an organization structured such that there is an infrastructure team maintaining the core Kubernetes cluster can have approved experiments such that any team can use without the risk of the teams themselves having to be burdened by maintaining or understanding the implementation details of the chaos tests other than opting into them.

2. Reduces clutter. The largest Kubernetes clusters can go up to 5k nodes. Let's assume that on such a cluster each application consumes 20 nodes. That means you have 250 applications. Do you really want 250 copies of each experiment? Multiply by the number of experiments that each may need, and you're talking thousands manifest deployments that can be eliminated.

I'm happy to answer further questions as to this request.

**Comment by ksatchit** [comment]
Very well explained! Thanks for raising these points. While I understand the need for centralised management of chaos by an admin (and therefore we will start supporting this very soon), litmus began with a more dev-oriented approach where they have more control over the experiment params, and have lower visibility/permissions wrt RBAC policies. Having said that, yes, both approaches need to be supported.

**Comment by cpitstick-argo** [comment]
Argo intends to use Litmus on an ongoing basis to validate the resiliency of our services long-term. That is chaos may be always running on services that opt into it. This helps prove out that our infrastructure can handle many types of catastrophic events and still run.

**Comment by sumitnagal** [comment]
@ksatchit , This is much needed feature to solve for admin use case via chaosengine. Looking forward for its rollout.

**Comment by ksatchit** [comment]
This feature is now available as part of release 1.2.2
