### ISSUE TITLE
Support Elastic Kubernetes Service (EKS) from AWS (Amazon Web Services)

### ISSUE THREAD

**Issue by cpitstick-argo** [litmuschaos/litmus#1220]
Please add EKS as a supported hosted Kubernetes framework. While a lot of experiments (such as node-cpu-hog and pod-delete) work fine on it, it's not officially supported, and in the case of node-cpu-hog, the following is required:

```yaml
- name: PLATFORM
  value: "GKE"
```
And specifying EKS causes the experiment to not work.

Note that node-cpu-hog is only an example here, the entire framework needs to be tested on and support EKS.

**Comment by ksatchit** [comment]
EKS is now officially supported on Generic chaos experiment suite.

**Comment by ksatchit** [comment]
Can we add EKS platform as a supported platform in docs/charts csv?

**Comment by ksatchit** [comment]
Node failure & Disk failure chaos will be supported next on EKS and tracked via separate issues.
