### ISSUE TITLE
Request for new experiment: node-memory-hog

### ISSUE THREAD

**Issue by cpitstick-argo** [litmuschaos/litmus#1222]
We all love the [node-cpu-hog](https://github.com/litmuschaos/litmus/tree/master/experiments/generic/node_cpu_hog) experiment. However, why only CPU?

Lets add memory! Nodes running out memory is just as interesting as a node's CPU "hogged" at 100%.

And by memory, I do not mean disk. I mean RAM.

**Comment by ksatchit** [comment]
Sure thing !!

**Comment by ksatchit** [comment]
This experiment has been added in 1.2 release. Please refer: 

- https://docs.litmuschaos.io/docs/node-memory-hog/
- https://hub.litmuschaos.io/charts/generic/experiments/node-memory-hog

**Comment by ksatchit** [comment]
This is available from the 1.3 release. Refer: https://hub.litmuschaos.io/charts/generic/experiments/node-memory-hog
