### ISSUE TITLE
Clarification request: License for litmus-docs

### ISSUE THREAD

**Issue by cpitstick-argo** [litmuschaos/litmus#1224]
All but one litmuschaos repository is released under Apache 2.0 (Jan 2004). However, [litmus-docs](https://github.com/litmuschaos/litmus-docs/blob/staging/LICENSE), is instead released under the MIT License.

Why is this? When requesting permission from my company to interact with Litmus, this makes the paperwork more complex. I can no longer say "It's Apache 2.0." Instead, I have to say "All but one is Apache 2.0 and the remaining one is MIT 2019."

Could this be addressed in an FAQ? Or even better, make the license for all of them consistent?

**Comment by ksatchit** [comment]
The litmus-docs repo too has been modified to hold Apache 2.0 license! Will be added into FAQ asap!

**Comment by ksatchit** [comment]
This FAQ item has been added. The respective NOTICE files into all the repos and a fossa report describing the unmodified dependencies are updated on the litmus repo.
