### ISSUE TITLE
Per-experiment annotations to allow for opt-in to unique experiments

### ISSUE THREAD

**Issue by cpitstick-argo** [litmuschaos/litmus#1227]
Currently, to opt into Litmus experiments, one must use this command:

`kubectl annotate deploy/hello-world litmuschaos.io/chaos="true"`

and similarly false or delete the annotation to "opt-out"

However, this doesn't allow for the selection of WHICH experiment you want to opt into. If various deployments only want certain experiments at a given time, that's not possible right now. You can't have the beer-brewing deployment in the namespace "alcohol" run pod-delete, and have the cider-brewing deployment, also in the namespace "alcohol" run node-cpu-hog, but 

Furthermore: If, in conjunction with [1219](https://github.com/litmuschaos/litmus/issues/1219) if the Kubernetes cluster has several experiments installed into an administrator/litmus namespace, it's important for each deployment to opt-in to individual experiments rather than chaos as a whole, as long-term one can envision many different experiments on a cluster but each deployment only wants one at a time (or many at a time, depending on the business context).

**Comment by ksatchit** [comment]
The latest versions of litmus no longer supports the `litmuschaos.io/chaos` annotation for apps to opt-in or out of experiments. Also, the mode of experimentation is via a consciously constructed workflow which allows the user to do what is described in the issue, i.e., *as long-term one can envision many different experiments on a cluster but each deployment only wants one at a time (or many at a time, depending on the business context)*
