### ISSUE TITLE
Versioning of Experiments on Litmus ChaosHub

### ISSUE THREAD

**Issue by dgildeh** [litmuschaos/litmus#1228]
We've had some breaking issues of our experiment runs because changes were made to the experiments without us being aware and subsequently our experiments started failing. We need to be able to lock down experiment runs to specific versions so they don't break our tests even if new updates to experiments are made.

When installing the experiments from ChaosHub's URL I would like to see a 'version' parameter so I can lock the experiment versions during deployment to a new cluster to a specific version. I.e.:

```
kubectl create -f https://hub.litmuschaos.io/api/chaos?file=charts/generic/experiments.yaml?version=1.1.0
```

In addition, the ChaosHub UI should have some way to see what versions are available, similar to Docker Hub here: https://hub.docker.com/_/mysql?tab=tags

**Comment by ksatchit** [comment]
Steps involved include: 

- Updates to the charthub go backend to checkout tags as part of locally maintained charts
- Updates to Js front-end to provide tabs/dropdown for the versioned bundle downloads
- Changes to buildscripts in chaos-charts to create concatenated experiments YAML for release branches
- Doc restructure to mention versioned charts respective doc versions

cc: @chandankumar4
