### ISSUE TITLE
RAMP_DOWN Variable for Experiments

### ISSUE THREAD

**Issue by dgildeh** [litmuschaos/litmus#1229]
We recently added a RAMP_UP variable for experiments, to put a delay between setting up the experiment and running the experiment. We have noticed that tearing down an experiment happens straight after the experiment runs also, adding a lot of noise to the logs which makes it harder to see the incident itself and logs only related to the experiment failure itself. 

We would like to add a RAMP_DOWN variable to the experiment YAML file that would allow you to optionally specify a delay after the experiment has finished running and the teardown/deletion of the experiment running occurs. In our case we would probably put a 660 second delay.

**Comment by ksatchit** [comment]
This is fixed by https://github.com/litmuschaos/litmus/pull/1232. 

A separate PR will be raised to make the RAMP waits more explicit in the logs, and in general, to improve the log structure.
