### ISSUE TITLE
Consistency in time variables in experiment YAML definitions

### ISSUE THREAD

**Issue by dgildeh** [litmuschaos/litmus#1230]
I've noticed that each experiment has a different format for specifying times in the experiment definition YAML file, some are in ms and some are in seconds.

For example, the disk fill experiment TOTAL_CHAOS_DURATION is in ms, but the Pod Delete experiment TOTAL_CHAOS_DURATION is in seconds. This leads to mistakes and also confusion when reviewing the experiment settings as its not clear if its 6000 seconds or 6000ms without jumping back to the docs.

Please pick one of the other for all experiments, I'm not sure ms is required as the tests aren't that granular, so would recommend seconds.

This feedback should also apply to any other common variable formats in the YAML file too if there are any.

**Comment by ksatchit** [comment]
This is now fixed by https://github.com/litmuschaos/litmus/pull/1246 & https://github.com/litmuschaos/chaos-charts/pull/160
