### ISSUE TITLE
Better Consistent Chaos Runner Logs

### ISSUE THREAD

**Issue by dgildeh** [litmuschaos/litmus#1235]
While running lots of experiments in a row, I'm watching the logs for each experiment's chaos running container while they run and find it hard to see what settings experiments are being run with to confirm it's following my YAML file settings (and any optional variables I didn't specify in the YAML, seeing what defaults have been set), seeing if the RAMP_UP time is being respected, and more detail on exactly what the experiment is doing.

Without looking at the framework code of the runner, I would put some consistent logging around an experiment so every experiment outputs a consistent startup and shutdown so its easy to see what was going on/settings - and request clearer logging for each experiment to understand what's going on during the running, which will be different depending on the experiment.

For startup I'd like to see:

1. Experiment name and all the variables its using with their values
2. If RAMP_TIME is set, something in the logs to indicate RAMP_TIME was set and the experiment is waiting for X seconds till it runs so I can confirm there definitely was a delay between setup and running the test
3. Some clear markers in the log to seperate setup/waiting/running/shutdown - I saw most have "Brace yourself, experiment begins!" in them, markers like this make the logs much clearer so add some more

For teardown:

1. A clear indication of overall experiment result, it shows this line but I'm not sure what all the numbers mean: : ok=36   changed=21   unreachable=0    failed=0
2. Any RAMP_TIME at end of test clearly marked out in logs

Seeing all the experiment variables and RAMP_TIME is most important, as in some experiments I'm setting things and don't know for sure if they're being set or used properly so having some logs for debugging would help!

**Comment by ksatchit** [comment]
To be incorporated into the task logs: 

- Experiment details: name, user vars (debug task)
- "Preliminary tasks" to say something to going to occur -- such as RAMP waits
- Task prefixes (consistent across experiments) to indicate the nature/phase:  [prereq], [prepare], [status], [ramp], [inject], [teardown]
- Make task names more descriptive than have cryptic statements 
- Log the experiment result in the final pass/rescue sections to say out explicitly (w/ experiment-specific context) the "result"

**Comment by ksatchit** [comment]
@dgildeh could you please take a look at this PR dealing with fixing this and let us know your thoughts ? That way we could carry over this / an updated template for rest of the experiments: https://github.com/litmuschaos/litmus/pull/1298
