### ISSUE TITLE
(feat): Request to add the ansible lint for litmus playbooks

### ISSUE THREAD

**Issue by rajdas98** [litmuschaos/litmus#1249]
Motivation
- Every developer has a different coding style guide. To make all litmus playbook's style concurrent, requesting the following features:
  - Add custom Ansible lint rules
  - Add that Ansible Lint rules to the CI
      - Add to docker image
      - Add to travis CI
  - Refactor the litmus playbooks to use the custom and existing ansible lint rules

**Comment by ksatchit** [comment]
cc: @ispeakc0de @uditgaurav

**Comment by ksatchit** [comment]
Fixed via #1233 , #1250
