### ISSUE TITLE
Custom Annotation support

### ISSUE THREAD

**Issue by sumitnagal** [litmuschaos/litmus#1252]
We need custom annotation support so that we can annotate the application where we want this chaos to be executed. currently, it supports default litmus annotation, which you can ignore via `annotationCheck: 'false'` we want a custom annotation support, which could reference it while putting an experiment, this way we can solve for the use case, where the application will participate in chaos or ignore it.

**Comment by ksatchit** [comment]
Fixed by https://github.com/litmuschaos/chaos-operator/pull/177
