### ISSUE TITLE
Override the image for ChaosExperiment Custom Resource 

### ISSUE THREAD

**Issue by sumitnagal** [litmuschaos/litmus#1253]
We need a way to override the container image for our framework. currently, we override many things including env, config map. but this is not supported yet. This will help the team to maintain their custom image with respect to their compliance and still leverage the core functionality for this framework.

**Comment by rahulchheda** [comment]
PTAL @sumitnagal : https://github.com/litmuschaos/chaos-operator/pull/150. Is this `runner` image the one you need to modify?

**Comment by ksatchit** [comment]
@rahulchheda , this issue corresponds to the ability to override the experiment image for debug purposes in `.spec.experiments[index].<experiment_name>.spec.components.image`

**Comment by ksatchit** [comment]
Fixed by https://github.com/litmuschaos/chaos-operator/pull/238
