### ISSUE TITLE
Chaos result should support json blob 

### ISSUE THREAD

**Issue by sumitnagal** [litmuschaos/litmus#1254]
Due to data insight as well as maintain data, it is important that we maintain certain metadata. this could be achieved when we provide a way of json object.  Adding this will help meaningful outcomes across the team over the organisation.

**Comment by ksatchit** [comment]
This ability to push such a data structure (json) in to chaosresult CR will help users create their own context wrt the result of a chaos experiment. The initial idea is to allow : `data: |` inside the chaosresult status to allow user-defined patches.

**Comment by ksatchit** [comment]
(a) Enhance the chaosresult schema to accept json blob in a data:|   field to push in custom info, here: https://github.com/litmuschaos/chaos-operator/blob/master/pkg/apis/litmuschaos/v1alpha1/chaosresult_types.go

(b) The python function could patch that jsob report here: https://github.com/litmuschaos/test-tools/blob/master/chaostoolkit/data/k8_wrapper.py#L29

**Comment by ksatchit** [comment]
The chaos workflows are based on argo which supports the ability to push output artifacts generated from experiment runs to a dedicated sink. This way, we don't have to store data blobs on CRDs like chaosresults.
