### ISSUE TITLE
[FeatureReq]: Execute hyperlink linter to find broken links in the documentation

### ISSUE THREAD

**Issue by k8s-dev** [litmuschaos/litmus#1255]
Objective: Check that all of the hyperlinks in a markdown text to determine if they are alive or dead.
With markdown text this is a generic issue where links are broken once in a while.

Some of the utilities could be :
https://github.com/tcort/markdown-link-check 
https://github.com/bmuschko/link-verifier 

Evaluate and use the one which makes least noise while providing higher accuracy. 
Some more tools are welcome for evaluation. Please comment if you have a success story with such tool to share.

PS: Sample output file generated by markdown-link-check tool is attached. As seen there is some amount of noise, Need to check the options/params to reduce it.

**Comment by ksatchit** [comment]
Fixed by https://github.com/litmuschaos/litmus-docs/pull/226
