### ISSUE TITLE
Dockerize the experiment scaffold tool to avoid managing dependencies 

### ISSUE THREAD

**Issue by ksatchit** [litmuschaos/litmus#1259]
As we start getting exp contributions (and also support python, go experiments) - the scaffold tool needs to be dockerized - so that developers can do a docker run with --type <go/python/ansible>, --config <attributes.yaml> and by mounting the litmus exp folder as volume - to generate all the required artefacts in desired path. It will prevent the need to install dependencies before using the scaffold tool.

**Comment by ksatchit** [comment]
cc: @AmitKumarDas

**Comment by AmitKumarDas** [comment]
is there any existing steps that does the same

**Comment by ksatchit** [comment]
The litmus-sdk is now available as a binary and does not need dependency setup: https://github.com/litmuschaos/litmus-go/tree/master/contribute/developer-guide
