### ISSUE TITLE
Create Grafana Dashboard for Litmus

### ISSUE THREAD

**Issue by divya-mohan0209** [litmuschaos/litmus#1280]
Creating a Granfana Dashboard for Litmus to display metrics. Design details to be updated soon.

**Comment by umamukkara** [comment]
General notes that helps in design of this feature/dashboard:

Litmus has a CR called "ChaosResult" which stores the detailed results of an experiment. [Chaos-exporter ](https://github.com/litmuschaos/chaos-exporter) acts as a metrics exporter into Prometheus. Litmus does not install a Prometheus instance, but we can expect that there will be a prometheus server in the Kubernetes environment by the time the SRE is thinking of Chaos Engineering or Litmus. 

While this issue deals with the creation of a Grafana dashboard, it is possible that we relook at the metrics being collected by the exporter and redefine them or add more to them. In general following are the requirements, others can add.

1. History of results of a given chaos experiment
2. History of experiments and results of a given application
3. History of experiments and results in a given namespace
4. History of experiments and results in the whole cluster

and more.

Do we have the right metrics being collected to achieve the above? cc @chandankumar4 @ksatchit

**Comment by ksatchit** [comment]
The current metrics are of prometheus metric type "gauge" where result wrt experiments (for an app), and total count are available in a given namespace, but no "historic data " is being presented as a metric. It can be constructed via grafana itself, I suppose, like you have mentioned.    

There are some enhancements planned in the chaos-exporter which might be necessary to achieve the dashboard we are discussing. This is captured in #1295

**Comment by umamukkara** [comment]
Couple of other important metrics to consider:
- MTTR (Mean Time To Recovery)
- Cloud Native Resilience Score or CNRS. This is a new metric that we are trying to define ( :) ) which can be quite complex. However, over a period of time, the meaning of CNRS can be defined specific to a service or a resource. For now, we can think of CNRS as the mean result of the experiment in the last 10 runs.

**Comment by ksatchit** [comment]
Some additional metrics to capture, as discussed, can be:

- MTTR (app's recovery time post chaos). Experiment in this case needs to allow for an indefinite recovery period instead of fixed recovery timeout as a post chaos check. 
- ..

**Comment by ksatchit** [comment]
@umamukkara , as discussed, experiment specific metrics with respective dashboards (or dashboard per parent level chart) would be helpful too.

**Comment by ksatchit** [comment]
cc: @rajdas98 @ajeshbaby

**Comment by rajdas98** [comment]
- Health of the cluster under the purview of the exporter. Candidate for the chaos grafana dashboard

**Comment by rajdas98** [comment]
- What are the challenges around public/on-premise clouds in terms of visualization?

**Comment by ksatchit** [comment]
There are sample dashboards available [here](https://github.com/litmuschaos/litmus/tree/master/demo/sample-applications/sock-shop) - these are more in the spirit of providing users with a technique on how they can instrument their app dashboards with chaos events/metrics. 

Also ref: https://github.com/litmuschaos/litmus/issues/1472#issuecomment-674439410

**Comment by ksatchit** [comment]
Based on maintainer consensus, the plan is to provide sample chaos-instrumented dashboards for popular demo applications within the litmus community - both for grafana as well as the litmus portal monitoring service. 

Some of them can be found here: https://github.com/litmuschaos/litmus/tree/master/monitoring
