### ISSUE TITLE
(Feat): Kubectl plugin for CLI based execution of chaos experiments

### ISSUE THREAD

**Issue by rajdas98** [litmuschaos/litmus#1307]
- Request to add kubectl plugin for CLI support for litmus
- Adding a kubectl plugin can help following funcationality:
  - Run the engine:
     - By running the `kubectl litmus run  -- name <experiment_name>`, CLI will take the inputs of all the envs like app_label, total_chaos_duration ... etc.
  - Stop/Abort engine
     - `kubectl litmus stop chaosengine --name <engine-name> --n <namespace>`
  - List of chaos engine `kubectl litmus chaosengines -n <namespace>`
  - List of chaos experiment `kubectl litmus chaosexperiments -n <namespace>`
  - More...
- Request for a new repository called `litmus-cli` under litmuschaos organisation.
- After having a full working `kubectl litmus plugin`, this can be index in the `krew` repository https://github.com/kubernetes-sigs/krew-index.

**Comment by rajdas98** [comment]
A work in progress repository- https://github.com/rajdas98/litmus-cli

**Comment by ksatchit** [comment]
With the introduction of litmuctl & workflows, this requirement has now changed to: support for constructing and launching chaos workflows through litmusctl, tracked here https://github.com/litmuschaos/litmus/issues/2516
