### ISSUE TITLE
(Feat): Request for a BDD of CoreDNS pod delete experiment

### ISSUE THREAD

**Issue by imrajdas** [litmuschaos/litmus#1322]
- Request for a BDD in Litmus E2E to test coreDNS pod delete experiment.
- BDD will run the experiment in minikube/GKE cluster and checks the chaosresult result verdict.
  - Expected Verdict: `Pass`
- Repository- https://github.com/litmuschaos/litmus-e2e

**Comment by rajdas98** [comment]
@ksatchit @uditgaurav Should we create a different branch for `coredns` experiments or put it into the `generic` branch ?

**Comment by uditgaurav** [comment]
My suggestion will be to add this to our `generic` branch only in a separate stage called `CoreDNS Experiment` along with `Generic Experiment` and `Infra experiment`. As looking forward we will be syncing up all branches into one. For the sake of simplicity right now we are maintaining two branches which are still ok for now but let's not increase this. Keeping less number of branches will help in adding a new feature we don't need to have multiple PRs in different branches we can do this in one. @rajdas98

**Comment by ksatchit** [comment]
Usage of `kind` cluster to run these experiments in e2e will be explored. cc: @rajdas98

**Comment by rajdas98** [comment]
Sure @ksatchit

**Comment by ispeakc0de** [comment]
We don't have a separate experiment for core-dns-pod-delete experiment. We can use generic pod-delete for the same purpose
