### ISSUE TITLE
Define the process of displaying charthub experiments icon

### ISSUE THREAD

**Issue by chandankumar4** [litmuschaos/litmus#1354]
## Why we need this?
- Setting up the correct location/path for icons of chaos experiment currently it's getting all the image from `staging` branch of `chaos-chart` which is defined inside the charthub

## How to solve this / What are the possible approach
1 - Define a repository in `litmuschaos` org and store all the image there instead of chaos-chart and provide the image link in CSV file

2 - Currently we are cloning the chaos-chart inside the charthub server repo which contains all the images but UI pod is separate from server pod so we have to use NFS volume to share the common directory then UI pod will able to access the icons

3 - All icons are available in chaos-chart so if we get the chaos-chart repo inside the UI pod then charthub will be able to get the icon

## Related repository
1 - https://github.com/litmuschaos/charthub.litmuschaos.io
2 - https://github.com/litmuschaos/chaos-charts

**Comment by chandankumar4** [comment]
Create a new Repo which will contain the icons for litmuschaos org https://github.com/litmuschaos/icons

**Comment by ksatchit** [comment]
We have decided upon the approach #3 where icons will be placed in a dedicated repo (refer https://github.com/litmuschaos/icons/pull/1) and the raw links will be provided in the experiment CS, for ex: [here](https://github.com/litmuschaos/chaos-charts/blob/staging/charts/generic/pod-delete/pod-delete.chartserviceversion.yaml#L42)
