### ISSUE TITLE
"undefined" string appearing in the doc links 

### ISSUE THREAD

**Issue by ksatchit** [litmuschaos/litmus#1366]
**What happened**:

Refer the below image: 
 
![image](https://user-images.githubusercontent.com/21166217/77407097-a616d100-6ddb-11ea-828f-4f9cbd44490c.png)

**Comment by k8s-dev** [comment]
https://github.com/litmuschaos/litmus-docs/pull/241 is proposed fix.

**Comment by ksatchit** [comment]
Fixed by https://github.com/litmuschaos/litmus-docs/pull/241
