### ISSUE TITLE
Docker socket mount error with pumba

### ISSUE THREAD

**Issue by nicoekkart** [litmuschaos/litmus#1389]
**What happened**:
When running the network latency experiment on a kind cluster, the pumba job correctly gets created, but it keeps hanging with the following error:
```
time="2020-03-31T12:23:41Z" level=error msg="failed to list containers" app=pumba error="Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?" function=github.com/sir
upsen/logrus.WithError source="container/client.go:90"
time="2020-03-31T12:23:41Z" level=error msg="failed to list containers" app=pumba error="Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?" function=github.com/sir
upsen/logrus.WithError source="netem/delay.go:144"
time="2020-03-31T12:23:41Z" level=error msg="failed to run chaos command" app=pumba error="Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?" function=github.com/s
irupsen/logrus.WithError source="chaos/command.go:79"
time="2020-03-31T12:23:41Z" level=fatal msg="Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?" app=pumba function=main.main source="cmd/main.go:162"
```

**What you expected to happen**:
Pumba should be able to run docker commands

**How to reproduce it (as minimally and precisely as possible)**:
Running the network latency chaos experiment on a kind cluster. 

**Anything else we need to know?**:
The problem is probably related to access rights of the docker socket. I don't yet get the structure of Litmus completely, so I don't know where it is mounted in the pumba job.

Thanks for the help!

**Comment by ksatchit** [comment]
Thank you for using litmus @nicoekkart !! We shall get back to you shortly on this!!

**Comment by rajdas98** [comment]
This is because pumba is unable to mount the docker sock. `Network latency chaos` is using pumba lib, but it has mounted https://github.com/litmuschaos/litmus/blob/master/chaoslib/pumba/pumba.j2#L29
Maybe, docker is not install correctly, that's why it is unable to mount.

**Comment by ksatchit** [comment]
@nicoekkart I suppose this is because KinD uses the containerd runtime & pumba only works on docker. Since you are already using the containerd LIB for the [container-kill](https://github.com/litmuschaos/litmus/issues/1547) experiment, will go ahead and close this issue. 

Also, network chaos will be supported on this runtime in upcoming releases.
