### ISSUE TITLE
Sometimes chaosengine install failed

### ISSUE THREAD

**Issue by badashanren** [litmuschaos/litmus#1392]
**What happened**:
I install litmus chaos by command "kubectl apply -f https://litmuschaos.github.io/pages/litmus-operator-v1.2.0.yaml"
![image](https://user-images.githubusercontent.com/6917923/78095826-8c444200-740a-11ea-9fd3-90a8763105a6.png)

**What you expected to happen**:
kubectl get crds 
verify if chaos CRDs are installed,but "chaosengines.litmuschaos.io" is missed
I reinstall it, successful!
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by ksatchit** [comment]
@badashanren , what is the K8s cluster type you are using? We have seen, on some clusters that the api resources take a bit more time to get created!

**Comment by badashanren** [comment]
> t is the K8s cluster type you are using? We have seen, on some clusters that the api resources take a bit more time to get crea

The k8s cluster is tke, tencent company. I have waited for a few minutes, check failed.So i reinstall it.

Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-14T21:04:32Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.3-tke.3", GitCommit:"a1d64d87004c0784e834fe8a5299d8b920403252", GitTreeState:"clean", BuildDate:"2020-03-09T05:36:02Z", GoVersion:"go1.12.14", Compiler:"gc", Platform:"linux/amd64"}

**Comment by ksatchit** [comment]
That is interesting. CRD creation is a K8s task that should generally succeed. Let me find out more on the "missing" case. One good way to ascertain installation is successful is to check if the chaos operator deployment in litmus namespace is in running state. If not, it typically means the chaosengine CRD is not successfully created.

**Comment by ksatchit** [comment]
Unable to reproduce this issue locally, please re-open with logs if seen again. Thank you!
