### ISSUE TITLE
Draining 100% memory of a Kubernetes pod running on a node for Certain duration

### ISSUE THREAD

**Issue by uditgaurav** [litmuschaos/litmus#1404]
This issue is for adding stress images for the pod memory hog experiment. The building of the image should be done in `litmuschaos/test-tools` repository. The image should contain a job that will basically be used to exec in a container and give a memory spike for the given chaos duration with a given memory consumption.

**Comment by uditgaurav** [comment]
I tried several commands to achieve this the best one which fits this usecase is:
`cat <( yes | tr \\n x | head -c $BYTES <(sleep $100) | grep n`
here `$BYTES` is replaced with memory in Megabytes  `$((1024*1024*800)))` and  `(sleep $100)` means sleeping for `100s`.
But one issue in this was:
The moment it reaches the memory we mentioned ( `((1024*1024*800)))` )
The command gets terminated. This means sleep here is not working fine in bash or sh

**Comment by uditgaurav** [comment]
Another very useful command which can do this task very easily is: 
`dd if=/dev/zero of=/dev/null bs=300M` (300M is memory in megabytes)
This runs multiple times in the background and will drain out the memory very rapidly which in result also use the `CPU` in very large amount if, we want to drain the memory  in very less time then this seems to be the best one

**Comment by uditgaurav** [comment]
In case we want to terminate `dd if=/dev/zero of=/dev/null bs=300M` this command after some time interval we can use `timeout` for this so the command will become `timeout ${chaos-duration} dd if=/dev/zero of=/dev/null bs=300M`

**Comment by ksatchit** [comment]
Fixed via https://github.com/litmuschaos/test-tools/pull/122
