### ISSUE TITLE
Need to write some scripts to setup AWS EKS to deploy the Litmus E2E components

### ISSUE THREAD

**Issue by rajdas98** [litmuschaos/litmus#1449]
- Need to write AWS EKS setup script
  - Create/Delete of Node Group.
  - Create/Delete of Cluster
- Able to run all litmus experiment (openebs, generic) in AWS EKS.

**Comment by uditgaurav** [comment]
@rajdas98 If we will use onperm for the target cluster then why do we need to setup EKS for Litmus components?

**Comment by rajdas98** [comment]
As of now, Onprem is only to run the gitlab runners

**Comment by uditgaurav** [comment]
The target cluster is set up in an on-prem cluster. 
PR for ref.
generic experiment pipeline - https://github.com/litmuschaos/litmus-e2e/pull/137
openebs experiment pipeline - https://github.com/litmuschaos/litmus-e2e/pull/138

**Comment by uditgaurav** [comment]
@rajdas98 Can we close this issue for now?

**Comment by ksatchit** [comment]
Available here: https://github.com/litmuschaos/test-tools/pull/183
