### ISSUE TITLE
(feat): Add support for switch the URL of hub.litmuschaos.io a/c to version switch

### ISSUE THREAD

**Issue by chandankumar4** [litmuschaos/litmus#1458]
What need's to be done:
- Add the support for changing the URL of hub.litmuschaos.io a/c to chart version switch

for example, the URL of hub should be
 1 - For the latest release tag: URL= https://hub.litmuschaos.io/latest
 2 - For older release tag: URL = https://hub.litmuschaos.io/{TAG}
 3 - For master barnch: URL = https://hub.litmuschaos.io/master

Issue related to repository: https://github.com/litmuschaos/charthub.litmuschaos.io

**Comment by ksatchit** [comment]
The ChaosHub has support for version based artifact download is now supported (via a dropdown on the hub screen)
