### ISSUE TITLE
(Bug/Issue): Fix the bug/issue in hub.litmuschaos.io

### ISSUE THREAD

**Issue by chandankumar4** [litmuschaos/litmus#1461]
**What happened**:

Fix the listed bug/issue related to hub.litmuschaos.io
- Fix the logic of filtering the video URL, Issue reference [here](https://github.com/litmuschaos/charthub.litmuschaos.io/blob/staging/src/pages/Experiments.js#L70)
- Fix the logic of getting the display name from JSON data, Issue reference [here](https://github.com/litmuschaos/charthub.litmuschaos.io/blob/staging/src/pages/Experiments.js#L145)
- Add the support to sync the chaos-chart repo a/c to github webhook instead of define time frame, Issue reference [here](https://github.com/litmuschaos/charthub.litmuschaos.io/blob/staging/server/pkg/gitops/gitwork.go#L35)

**How to reproduce it (as minimally and precisely as possible)**:

Run the hub locally, Check [here](https://github.com/litmuschaos/charthub.litmuschaos.io/blob/staging/README.md)

**Comment by gdsoumya** [comment]
Hi @chandankumar4 ,

I am working on fixing the video URL filtering logic.

**Comment by ajeshbaby** [comment]
[PR ](https://github.com/litmuschaos/charthub.litmuschaos.io/pull/140)

**Comment by gdsoumya** [comment]
Hi @chandankumar4,

**Comment by gdsoumya** [comment]
Hi @chandankumar4 ,

I have sent a PR for the the display name logic bug, [PR](https://github.com/litmuschaos/charthub.litmuschaos.io/pull/144) , review it and let me know.
