### ISSUE TITLE
Events watcher intergration with Litmus chaos-exporter/monitor

### ISSUE THREAD

**Issue by rahulchheda** [litmuschaos/litmus#1463]
Describe of the issue: 
    -  This issue is for tracking the integration of various event watcher tools such as event-router, botkube and many others.
    - We are trying to create an integration with Slack, and Elastic Search, to serve usability to SRE's and Developers.

**Comment by ksatchit** [comment]
Integrations are available here: https://github.com/litmuschaos/chaos-observability/tree/master/events
