### ISSUE TITLE
Introduce Chaos Chart for Redis 

### ISSUE THREAD

**Issue by ksatchit** [litmuschaos/litmus#1464]
Redis is an open source (BSD licensed), in-memory data structure store, used as a database, cache and message broker.

- Include external liveness checks for redis application
- Perform component failure (redis server/host) 
- (Optional/ stage-2 req) Add redis benchmark job as a sample load generation utility

**Comment by umamukkara** [comment]
https://technology.riotgames.com/news/controlled-chaos-fault-injection-testing could be useful in understanding chaos engieering for redis on Docker and kubernetes

**Comment by umamukkara** [comment]
@ankitnayan - You can update this issue if would like on the new chaos scenarios for Redis

**Comment by umamukkara** [comment]
https://redislabs.com/blog/start-to-finish-with-databases-on-kubernetes/?utm_source=twitter&utm_medium=social&utm_campaign=blog

**Comment by ksatchit** [comment]
Litmus has added multiple new faults as well as probe types - which allows users to target any Kubernetes service along with custom app-specific validations - thereby removing the need for separate category/type of experiments
