### ISSUE TITLE
Provide Scaffolding/sdk for Go experiments

### ISSUE THREAD

**Issue by rahulchheda** [litmuschaos/litmus#1466]
This issue is for tracking the creation of scaffolding for Go related experiments.

**Comment by rahulchheda** [comment]
Some thoughts:
    - Add a `go get pkg`
    - Add fns in these for easy accessibility
    - Functions should be such that, `initExperiment`, `bussinessLogic`, `exitCriteria` 
    - The output of these functions would be uploaded as the chaosResult verdict, reason or any other custom CR field, this would help us abstract our logic.

**Comment by ksatchit** [comment]
Just posting some discussion notes. Similar to @rahulchheda 's comment above: 

```
What is litmus SDK?



User action: "go get github.com/litmuchaos/litmus-go"
User action : "litmus-go create-experiment --name=myapp-kill --attributes=attributes.yaml "
What it does:
          (a) Create folder called myapp/myapp-pod-kill

          (b) Create myapp-pod-kill.go, myapp-pre-health.go, myapp-post-health.go

          (c) litmus-go check (lint) (scorecard) myapp/myapp-pod-kill

          (d) litmus-go build myapp/myapp-pod-kill

          (e) Dockerfile with COPY of binary and any other essentials

          (f) Kubernetes Job template with above container

          (g)  ChaosExperiment CR, ChaosExperiment CR
```

**Comment by ksatchit** [comment]
Introduced here: https://github.com/litmuschaos/litmus-go
