### ISSUE TITLE
Bug chaos experiment

### ISSUE THREAD

**Issue by ilyes-ihadjadene** [litmuschaos/litmus#1470]
**What happened:**
I am trying to apply container-kill experiement on a keycloak container.
 I got a security error :
AnsibleError: Unable to create local directories(/.ansible/tmp): [Errno 13] Permission denied: '/.ansible

**What you expected to happen**:
container-kill experiement

**How to reproduce it**:
I am working on openshift environnement with :
Openshift v4
Kubernetes v1.16.2

**Comment by ksatchit** [comment]
@ilyes-ihadjadene thanks for trying Litmus. We are in the process of including support for OpenShift (both in terms of CRIO runtime support as well as openshift resources such as deploymentConfigs). This should be available in the 1.4 release. 

Having said that, tagging @andreas131989  & @nsathyaseelan / @shashank855  for their experience around using Litmus on OpenShift. 

@ispeakc0de , could you also confirm if the `LIB: containerd` & `LIB_IMAGE: gprasath/crictl:ci` here https://docs.litmuschaos.io/docs/container-kill/ work on OpenShift as well (crictl should be effective here too)?
