### ISSUE TITLE
Request for Istio chaos experiments

### ISSUE THREAD

**Issue by imrajdas** [litmuschaos/litmus#1473]
Some rough ideas on the Istio related chaos
- Istio chaos
  - Delete the istio pods in `istio-system` namespace and check if it comes or not.
  - Istio fault inject- ref: https://istio.io/docs/tasks/traffic-management/fault-injection/

Health check
- Ref- https://istio.io/docs/ops/configuration/mesh/app-health-check/

**Comment by ksatchit** [comment]
Litmus has added multiple new faults as well as probe types - which allows users to target any Kubernetes service along with custom app-specific validations - thereby removing the need for separate category/type of experiments
