### ISSUE TITLE
Chaos experiments are not running in istio injected namespaces

### ISSUE THREAD

**Issue by rajdas98** [litmuschaos/litmus#1474]
Description:
- Chaos experiments are not running, if litmus chaos pods deployed in istio injected namespaces. Because after enabling the istio in any namespace it creates a sidecar container `istio-proxy` with any pod created in that namespace
`kubectl label namespace default istio-injection=enabled`

- Due to which it also create `istio-proxy` container with litmus pods.

- In the core litmus experiment's logic, it expects chaos pod to be in `completed` state. but it is still in running due to `istio-proxy` container is in running state.

**Comment by ksatchit** [comment]
The chaos-runner can track the status of the experiment container in the experiment pod over looking at the pod status itself to proceed with removal of chos exp pods. 

cc: @rahulchheda

**Comment by romeo-delta-sierra** [comment]
I have also had problems with network-based litmus experiments running correctly in an Istio-enabled namespace.  The container-kill experiment ran correctly but the pod-network-latency experiment failed.  

When I run the pod-network latency experiment, I get entries in the pod-network-latency-<random> log like
```
FAILED - RETRYING: [Wait]: Wait until the pumba netem pod is completed (1 retries left).

2020-07-15 14:46:25.922571 Step: [Wait]: Wait until the pumba netem pod is completed

task path: /chaoslib/pumba/network_chaos/network_chaos.yml:108

fatal: [127.0.0.1]: FAILED! => {"attempts": 120, "changed": true, "cmd": "kubectl get pods -l name=pumba-netem-l3vwx6 --no-headers -n nginx-test --no-headers -o custom-columns=:status.phase", "delta": "0:00:00.945991", "end": "2020-07-15 14:46:25.902944", "rc": 0, "start": "2020-07-15 14:46:24.956953", "stderr": "", "stderr_lines": [], "stdout": "Running", "stdout_lines": ["Running"]}

2020-07-15 14:46:25.953936 Step: [CleanUP]: Tear down pumba infrastructure, if setup

task path: /chaoslib/pumba/network_chaos/network_chaos.yml:153

fatal: [127.0.0.1]: FAILED! => {"msg": "The conditional check 'chaos_pod_result.rc == 0' failed. The error was: error while evaluating conditional (chaos_pod_result.rc == 0): 'dict object' has no attribute 'rc'\n\nThe error appears to have been in '/chaoslib/pumba/network_chaos/network_chaos.yml': line 153, column 13, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n          - name: \"[CleanUP]: Tear down pumba infrastructure, if setup\"\n            ^ here\nThis one looks easy to fix.  It seems that there is a value started\nwith a quote, and the YAML parser is expecting to see the line ended\nwith the same kind of quote.  For instance:\n\n    when: \"ok\" in result.stdout\n\nCould be written as:\n\n   when: '\"ok\" in result.stdout'\n\nOr equivalently:\n\n   when: \"'ok' in result.stdout\"\n"}
```

**Comment by rajdas98** [comment]
Hi @romeo-delta-sierra , This will be fixed by https://github.com/litmuschaos/litmus-go/pull/59

**Comment by ksatchit** [comment]
Here are the patch release artefacts with fixes for this issue: 

- Operator manifest: https://github.com/litmuschaos/pages/blob/master/docs/litmus-operator-v1.6.1.yaml
- Chaos experiment CR Bundle: https://hub.litmuschaos.io/generic (refer: https://github.com/litmuschaos/chaos-charts/blob/v1.6.x/charts/generic/pod-network-latency/experiment.yaml#L51)
