### ISSUE TITLE
Introduce hard stop for pod-delete chaos depending on TOTAL_CHAOS_DURATION

### ISSUE THREAD

**Issue by ksatchit** [litmuschaos/litmus#1482]
**What happened**:

There was a recent instance in a user setup (@cpitstick-argo) running pod-delete experiments with TOTAL_CHAOS_DURATION of 3600s & CHAOS_INTERVAL of 2s. The user expectation was that the experiment completes in the specified duration, but the chaos resources continued to be active for much longer. 

Here is the reason:

- The pod delete iterations are derived based on the total duration / interval. So in this case 1800.
However, some iterations much take longer than others due to app status checks / waiting for recovery of app pods withing a prescribed time period. Depending on the cluster state, pod type (i.e., stateful/stateless), this may vary for few to many seconds.

- This experiment lacks a hard stop upon passage of total_chaos_duration (depends on completion of derived iterations) unlike other experiments, for ex: cpu hog / network chaos etc., wherein duration is strictly adhered to. While this issue might not highlight itself for smaller durations or larger intervals (either of them resulting in smaller iteration count) it can shown up when the iteration count is very large as in this case.

**What you expected to happen**:

- Experiment ends at 3600s. 

**How to reproduce it (as minimally and precisely as possible)**:

- Run pod delete experiment as described above

**Anything else we need to know?**:

- We need to be fixing this to honor the hard stop based on chaos duration, while also setting an expectation in the docs that interval between subsequent pod kills are a minimum guaranteed interval, while the actual gap may depend on how quickly the app recovers. 

- Another thought is to introduce optional app checks b/w kills (though I wouldn't personally recommend it, one of the motives of the experiment is to also catch failed recovery)

**Comment by ksatchit** [comment]
cc: @cpitstick-argo

**Comment by cpitstick-argo** [comment]
Excellent, thank you!

**Comment by cpitstick-argo** [comment]
Another thought: The reason that the interval is so short in this case is that this service has 3 pods. I wanted a very aggressive chaos interval because I wanted to disrupt the service as much as possible.

Yes, I could use `KILL_COUNT` but at the time I hadn't familiarized myself with the documentation to know about that option, and when I did find out about it I was curious if aggressive shutdowns would work in spite of that.

Answer: They do, sorta. Depends on how fast your pods start up. Some pods, like the Google hello-world example service I'm testing on, are so fast that you have to put an initContainer that sleeps to make the service unresponsive.

**Comment by cpitstick-argo** [comment]
Using the following settings for 25 intervals per run:
`
cron: "@every 1h15m"
total_chaos_duration: 3600
chaos_interval: 144
`
The experiment runs for approximately 1 hour.

Using the next settings to try to get 36 intervals per run:
`
cron: "@every 1h15m"
total_chaos_duration: 3600
chaos_interval: 100
`
The experiment runs for longer than 1 hour and 15 minutes.

**Comment by cpitstick-argo** [comment]
More data here. The original chaos in this prompt, 3600 seconds with a pod delete every 1 second (on a service with 3 pods), runs for approximately 5 hours and 15 minutes:

![image](https://user-images.githubusercontent.com/57147871/81211097-e18ee880-8fa0-11ea-9962-4ccbf11380c5.png)
