### ISSUE TITLE
Migrate dep to mod in all litmus repos

### ISSUE THREAD

**Issue by rajdas98** [litmuschaos/litmus#1483]
Repos:
- [x] Chaos operator 
- [x] Chaos exporter
- [x] Chaos runner
- [x] Litmus E2E
- [x] Charthub repo

**Comment by rajdas98** [comment]
Only litmus e2e is left cc @uditgaurav

**Comment by uditgaurav** [comment]
For litmus-e2e repo:
Generic branch - https://github.com/litmuschaos/litmus-e2e/pull/142
openebs branch - https://github.com/litmuschaos/litmus-e2e/pull/143

**Comment by uditgaurav** [comment]
Is anyone doing for Charthub repo ? @rajdas98 @rahulchheda

**Comment by rajdas98** [comment]
Yes @uditgaurav . I am doing it. @gdsoumya required this migration for heroku integration

**Comment by ksatchit** [comment]
This is now available on all major repos of litmus
