### ISSUE TITLE
Dark mode for litmus websites

### ISSUE THREAD

**Issue by imrajdas** [litmuschaos/litmus#1484]
- Request for dark mode in the following websites:
  - hub.litmuschaos.io
  - litmuschaos.io
  - docs.litmuschaos.io

**Comment by arkajyotiMukherjee** [comment]
I can take it up, currently working on issue #1458
But can shift to this one change according to priority.

**Comment by rajdas98** [comment]
litmuschaos.io ---> @arkajyotiMukherjee

**Comment by Abhinandan-Purkait** [comment]
I can try it sir ! 
Request for dark mode in the following websites:
docs.litmuschaos.io

**Comment by rajdas98** [comment]
docs.litmuschaos.io --> @Abhinandan-Purkait

**Comment by arkajyotiMukherjee** [comment]
> litmuschaos.io ---> @arkajyotiMukherjee

I can get assigned hub.litmuschaos.io
Thank you.

**Comment by Ab-hishek** [comment]
I can work on the request for dark mode in the website- litmuschaos.io.

**Comment by rajdas98** [comment]
Thank you guys. Done

**Comment by arkajyotiMukherjee** [comment]
Let's follow a standard design language while designing Dark Theme layouts
I think would be a good reference
https://material.io/design/color/dark-theme.html
Let me know what you think.

**Comment by rajdas98** [comment]
I think litmuschaos website is using bootstrap UI framework. It would be great if you use bootstrap components to develop the dark mode. MaterialJS is different UI framework

**Comment by rajdas98** [comment]
Try to find, if bootstrap have any dark mode component. Otherwise materialjs is fine

**Comment by arkajyotiMukherjee** [comment]
No, I will not use the Material Ui library...just sharing dark mode best practices as design guides...but will surely look at bootstrap. Thanks.

**Comment by arkajyotiMukherjee** [comment]
Dark mode added for hub.litmuschaos.io as requested by issue #1484
Link for PR:
https://github.com/litmuschaos/charthub.litmuschaos.io/pull/146
