### ISSUE TITLE
Perform operations like kubectl apply -f with go-client

### ISSUE THREAD

**Issue by uditgaurav** [litmuschaos/litmus#1487]
This issue is for performing operations like `kubectl apply -f` using go-client. Currently, there are some of the commands which are in `kubectl apply -f` to create some `yaml` file. This is needed to be changed with a go client approach.
The changes need to be done in the following repositories:
litmus-e2e: https://github.com/litmuschaos/litmus-e2e
chaos-ci-lib : https://github.com/mayadata-io/chaos-ci-lib

**Comment by Divya063** [comment]
I would like to pick up this issue.

**Comment by uditgaurav** [comment]
Thanks @Divya063 for taking this up!!!

**Comment by uditgaurav** [comment]
Hi @Divya063, please let me know in case you need any help. Here is something similar we are looking for (https://gist.github.com/pytimer/0ad436972a073bb37b8b6b8b474520fc).

**Comment by Sonichigo** [comment]
@uditgaurav can i take this issue?

**Comment by uditgaurav** [comment]
Thanks @Sonichigo You can start working on this!

**Comment by Sonichigo** [comment]
basically we have to implement .yml using go client libraries right? @uditgaurav

**Comment by Sonichigo** [comment]
@uditgaurav basically we have to decode the YAML/JSON and then parse. So is this right? 
[Main.txt](https://github.com/litmuschaos/litmus/files/5369305/Main.txt)

**Comment by ksatchit** [comment]
fixed via https://github.com/litmuschaos/litmus-e2e/pull/259
