### ISSUE TITLE
Execute network experiments against specific application dependencies

### ISSUE THREAD

**Issue by andreas131989** [litmuschaos/litmus#1488]
Currently we can perform network experiments against a network interface and affect all egress traffic using netem.
This feature request is regarding adding the ability to choose which dependencies (essentially IPs) to target from the interface without affecting the rest.

Example: Three applications that talk to each other. Introducing latency between application A and B should keep intact the communication between A-C and B-C.

**Comment by ksatchit** [comment]
Fixed for Docker via https://github.com/litmuschaos/litmus-go/pull/103 & Containerd/CRI-O via https://github.com/litmuschaos/litmus-go/pull/104
