### ISSUE TITLE
Request to add heroku build & deploy intergration check for litmus websites.

### ISSUE THREAD

**Issue by rajdas98** [litmuschaos/litmus#1499]
- Request to add heroku build & deploy integration for the PRs in the following repos:
  - https://github.com/litmuschaos/charthub.litmuschaos.io
  - https://github.com/litmuschaos/website-litmuschaos
<img width="791" alt="1516299367-Screen-Shot-2018-01-18-at-9 35 09-AM" src="https://user-images.githubusercontent.com/20414564/81569264-acc5cb80-93bc-11ea-8bcf-6e6a4fd79c67.png">

**Comment by manishdangi98** [comment]
@rajdas98 can I take this

**Comment by rajdas98** [comment]
Hi @manishdangi98 Thanks for asking. Currently @gdsoumya is working on https://github.com/litmuschaos/charthub.litmuschaos.io
You can pick for https://github.com/litmuschaos/website-litmuschaos

**Comment by rajdas98** [comment]
This issue is fixed by a another approach with betterci.
