### ISSUE TITLE
support to specify the dynamic mount path for disk fill experiment

### ISSUE THREAD

**Issue by 922mbb** [litmuschaos/litmus#1500]
Description:
Recently I apply Litmus disk fill experiment on my k8s cluster to fill disk in one of my pod. However I found it was failed due to following error. Double checked with the disk_fill_pod playbook, it use mount path: /var/lib/docker/containers by default. However, my cluster is deployed with gravity and default path is /var/lib/gravity/docker/containers for instance. So my workaround is to ln two folders to make it bypass the error. So dynamic mount path support would be helpful in such cases.

`2020-05-11 02:26:08.113075 Step: [Prepare]: Exec into the pod to get ephemeral-storage size
task path: /chaoslib/litmus/disk_fill/disk_fill_by_litmus.yml:124
fatal: [127.0.0.1]: FAILED! => {"changed": true, "cmd": "kubectl exec -it disk-fill-lqrjwu -n dsp -- sh -c \"cd /diskfill && cd 6c0ecc7510753649c1ee58fd4b31d0d8337b1e1536c0e7350b39ec83104b853c && du -k |tail -n1 | awk '{print $1}'\"", "delta": "0:00:00.531791", "end": "2020-05-11 02:26:08.093405", "msg": "non-zero return code", "rc": 2, "start": "2020-05-11 02:26:07.561614", "stderr": "Unable to use a TTY - input is not a terminal or the right kind of file\nsh: cd: line 1: can't cd to 6c0ecc7510753649c1ee58fd4b31d0d8337b1e1536c0e7350b39ec83104b853c: No such file or directory\ncommand terminated with exit code 2", "stderr_lines": ["Unable to use a TTY - input is not a terminal or the right kind of file", "sh: cd: line 1: can't cd to 6c0ecc7510753649c1ee58fd4b31d0d8337b1e1536c0e7350b39ec83104b853c: No such file or directory", "command terminated with exit code 2"], "stdout": "", "stdout_lines": []}`

**Comment by ksatchit** [comment]
The changes in the litmus experiment playbook have been made. PRs into chaos-charts & litmus-docs are in order shortly! Thanks @rahulchheda !

**Comment by ksatchit** [comment]
This is now available in docs master! https://docs.litmuschaos.io/docs/next/disk-fill/

**Comment by ksatchit** [comment]
This is available in versioned docs as well. Closing this issue.
