### ISSUE TITLE
Remove the gcloud utils from ansible-runner docker image and use via sidecar/helper pod 

### ISSUE THREAD

**Issue by ksatchit** [litmuschaos/litmus#1501]
**What happened**:

- The gcloud utils is an auxiliary requirement within ansible-runner and used for a limited set of tests. We need to push this to a separate container which can be used in these experiments -- over burning that into the ansible-runner. 

**What you expected to happen**:

- The ansible-runner should be of minimal size and also have only those dependencies common to all experiments. 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by rajdas98** [comment]
@ksatchit Where should we put the gcloud utils docker file? test-tools?

**Comment by ksatchit** [comment]
Ansible based experiments are more for illustrative purposes today. The experiments are rewritten in golang and the GCP APIs utilized to carry out the chaos.
