### ISSUE TITLE
Enhance pod-delete experiment to use the "helper pod" approach as with other experiments

### ISSUE THREAD

**Issue by ksatchit** [litmuschaos/litmus#1504]
Most chaos experiments in litmus allow chaos injection by "helper pods" launched by the chaoslib, with these chaos injectors removed/deleted upon completion of the total_chaos_duration. Pod-delete experiment is an exception to this approach, where the duration is enforced via timestamps comparison. This issue tracks conversion of this experiment to the "helper pod" idiom.

**Comment by uditgaurav** [comment]
I would like to take this up @ksatchit if it is not taken by anyone.
