### ISSUE TITLE
Can I run litmus chaos outside of my kubernetes clusters?

### ISSUE THREAD

**Issue by ravikumar2000** [litmuschaos/litmus#1516]

**Comment by rajdas98** [comment]
Hi @ravikumar2000 , You can run the ansible experiments which are dockerized under this image litmuschaos/ansible-runner:ci.

**Comment by rajdas98** [comment]
Other components such as chaos-operator, chaos-exporter and runner are kubernetes native. It requires k8s cluster to run on it.

**Comment by ksatchit** [comment]
Moving this issue to the chaos-backlog.

**Comment by ksatchit** [comment]
Based on maintainers consensus, Litmus will continue to itself remain a Kubernetes app (albeit one that can target/subject both k8s and non-k8s resources to chaos)
