### ISSUE TITLE
Basic Validations needed for litmuschaos/admission-controllers Release

### ISSUE THREAD

**Issue by rahulchheda** [litmuschaos/litmus#1517]

**Comment by rahulchheda** [comment]
Following Issues have to be closed before the 1.5 Release for Beta

**Comment by rahulchheda** [comment]
https://github.com/litmuschaos/admission-controllers/issues/7

**Comment by rahulchheda** [comment]
https://github.com/litmuschaos/admission-controllers/issues/6

**Comment by rahulchheda** [comment]
cc: @ksatchit

**Comment by ksatchit** [comment]
Both the referenced issues have been resolved
