### ISSUE TITLE
Do we have any other sample applications  r pods to test all chaos experiments using litmuschaos apart from nginx?

### ISSUE THREAD

**Issue by ravikumar2000** [litmuschaos/litmus#1518]

**Comment by ksatchit** [comment]
The sock-shop microservices demo app from weaveworks is a popular one amongst litmus practitioners: https://github.com/zebrium/zebrium-kubernetes-demo/blob/master/deploy/sock-shop.yaml

(picked this from a demo that the zebrium folks used to demonstrate litmus. While the instructions largely hold, note that the chaosengines are from a much older release. You may want to update them where necessary OR just use the app link shared above & run the latest experiments against them)

**Comment by ksatchit** [comment]
There is a sock-shop based demo within litmus itself, now: https://github.com/litmuschaos/litmus-demo
