### ISSUE TITLE
Infra & support for long-running staging clusters for Litmuschaos experiments (e2e) 

### ISSUE THREAD

**Issue by ksatchit** [litmuschaos/litmus#1520]
- We need to subject the chaos experiments to duration tests

**Comment by uditgaurav** [comment]
A long-duration BDD for every experiment?

**Comment by anshikavashistha** [comment]
@ksatchit Could you please elaborate a bit the given issue so that It would be easy for me what exactly I have to do as a beginner in this org?

**Comment by ksatchit** [comment]
This was an issue tracking the creation of infra (clusters) for doing the e2e tests in Litmus. This has since been made available.
