### ISSUE TITLE
Litmuschaos works only for default namespace  if we create other namespace and update service account yaml and chaosengine yaml it wont work

### ISSUE THREAD

**Issue by ravikumar2000** [litmuschaos/litmus#1524]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by ravikumar2000** [comment]
I removed the namespace default to nginx-litmus 

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-delete-sa
  namespace: default
  labels:
    name: pod-delete-sa
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: pod-delete-sa
  namespace: default
  labels:
    name: pod-delete-sa
rules:
- apiGroups: ["","litmuschaos.io","batch","apps"]
  resources: ["pods","deployments","pods/log","events","jobs","chaosengines","chaosexperiments","chaosresults"]
  verbs: ["create","list","get","patch","update","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: pod-delete-sa
  namespace: default
  labels:
    name: pod-delete-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-delete-sa
subjects:
- kind: ServiceAccount
  name: pod-delete-sa
  namespace: default

chaosengine file also updated as default instead of nginx-litmus
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: litmusnginx-pod-delete
  namespace: default
spec:
  appinfo:
    appns: 'default'
    applabel: 'app=litmusnginx'
    appkind: 'deployment'
  # It can be true/false
  annotationCheck: 'true'
  # It can be active/stop
  engineState: 'active'
  #ex. values: ns1:name=percona,ns2:run=nginx
  auxiliaryAppInfo: ''
  chaosServiceAccount: pod-delete-sa
  monitoring: true
  # It can be delete/retain
  jobCleanUpPolicy: 'delete'
  experiments:
    - name: pod-delete
      spec:
        components:
          env:
            # set chaos duration (in sec) as desired
            - name: TOTAL_CHAOS_DURATION
              value: '30'

            # set chaos interval (in sec) as desired
            - name: CHAOS_INTERVAL
              value: '10'

            # pod failures without '--force' & default terminationGracePeriodSeconds
            - name: FORCE
              value: 'false'

**Comment by ravikumar2000** [comment]
I delete the namespace and not getting nay experiments or chaosengine & chaos results

**Comment by ksatchit** [comment]
Ok, so you are saying you just replaced `default` to `nginx-litmus` in both the RBAC & chaosengine YAML. Here are a few questions: 

- Did you install the chaosexperiment CR in `nginx-litmus` namespace? Find out using `kubectl get chaosexperiments -n nginx-litmus`. Does it have pod-delete listed there? 

- Does the app with label `app=litmusnginx` exist in `nginx-litmus` namespace? Is is annotated for chaos?

**Comment by ravikumar2000** [comment]
yes i have installed experiment with nginx-litmus.
It didnot delete pod
Even applabel was also updated as app=litmusnginx

**Comment by ravikumar2000** [comment]
Appreciate your quick support on this.

**Comment by ravikumar2000** [comment]
we are planning to use litmus chaos and need your inputs on  scaling this to use chaos experiments with customization's and security perspective with respect to any issues with chaos libraries etc..

**Comment by ksatchit** [comment]
> yes i have installed experiment with nginx-litmus.
> It didnot delete pod
> Even applabel was also updated as app=litmusnginx

Would have to see the logs @ravikumar2000 . AFAIK, we have been supporting experiments across namespaces. Please share them when you have an opportunity to do so.

**Comment by ksatchit** [comment]
> we are planning to use litmus chaos and need your inputs on scaling this to use chaos experiments with customization's and security perspective with respect to any issues with chaos libraries etc..

Sure! Would be great to track these customizations as individual feature requests/issues? That way we can prioritize/deliver them better.

**Comment by ksatchit** [comment]
Closing this as Litmus supports chaos on non-default ns. Can be re-opened with logs if seen again.
