### ISSUE TITLE
Push a summary event into the chaosresult

### ISSUE THREAD

**Issue by ksatchit** [litmuschaos/litmus#1534]
(Based on a discussion with [Andreas](https://github.com/andreas131989)

Right now, only the chaosengine is fed with events during the chaos experiment execution. It is useful to push a summarization event to the chaosresult as well, to clearly state a failure or success in some detail. 

Also refer: https://github.com/litmuschaos/litmus/issues/1254

**Comment by rajdas98** [comment]
@ksatchit I want to work on this issue. Can I pick it?

**Comment by ksatchit** [comment]
Sure, thanks !

**Comment by ksatchit** [comment]
Available in litmuschaos/go-runner:1.6.0 images.
