### ISSUE TITLE
Containerd container-kill experiment fails to find necessary file

### ISSUE THREAD

**Issue by nicoekkart** [litmuschaos/litmus#1547]
**What happened**:
After building my own ansible-runner image on master, I tried the container-kill experiment. This fails with the error: `/bin/bash: ./experiments/container-kill: No such file or directory`. This is because of a commit 3 days ago, where this line was changed in containerd.j2. The container-kill file is copied nowhere (as far as I can see).

**What you expected to happen**:
Experiment should work with manual building.

**How to reproduce it (as minimally and precisely as possible)**:
`sudo docker build . -f build/ansible-runner/Dockerfile -t nicoekkart/ansible-runner:latest` and push.
Create a chaos experiment with this image.

**Anything else we need to know?**:
The change was in PR #1543.

**Comment by ispeakc0de** [comment]
Hi @nicoekkart ,
You are right there is some mismatch in the entry point & LIB_IMAGE.
We have two images (`LIB_IMAGE`) for the helper pod (both for the same purpose).
-  One is in bash `litmuschaos/container-killer:latest` which is using `crictl-kill.sh` as an entry point and another one is in golang `litmuschaos/container-kill-helper:latest` which is using `./experiments/container-kill` as an entry point. 
- This PR #1546 will fix your issue

**Comment by ksatchit** [comment]
@nicoekkart , on a side note: thanks for trying it out w/ a custom image 👍

**Comment by nicoekkart** [comment]
Great! I'll use that PR.
