### ISSUE TITLE
Add multi-arch images for Litmus components (ARM support) 

### ISSUE THREAD

**Issue by ksatchit** [litmuschaos/litmus#1550]
(On behalf of Michael Fornaro)

- The litmus component images are amd64. We need to add multi-arch support to enable LitmusChaos on ARM based kubernetes clusters (preferred over separate images/tags)

**Comment by rajdas98** [comment]
@ksatchit I will pick this issue

**Comment by odidev** [comment]
Hi Team,
I am also interested in adding arm64 support to this package. May I please know if there is any progress on this activity so far ?

**Comment by rajdas98** [comment]
Hi @odidev , we are working on it. Most probably litmus 1.6 will have this feature

**Comment by rajdas98** [comment]
Also, I would like to know, if you are interested to contribute to this issue.

**Comment by odidev** [comment]
@rajdas98,  yes we would really like to contribute , if you feel we can help in any part.

**Comment by rajdas98** [comment]
Thanks @odidev , I was exploring `docker buildx` , which is useful to create multi arch image. We have to do it for the following repos
- litmuschaos/litmus
- litmuschaos/chaos-operator
- litmuschaos/chaos-exporter
- litmuschaos/chaos-runner
- litmuschaos/litmus-go
- litmuschaos/litmus-ansible
- litmuschaos/admission-controller

**Comment by rajdas98** [comment]
It would be great, if you find any better approach for it.

**Comment by xUnholy** [comment]
Thank you @ksatchit for raising this issue on my behalf, it's greatly appreciated! 

@rajdas98 using `docker buildx` is a fantastic approach and can potentially make this quite easy. There are some great examples that I've been involved in the past that you can use as a reference on how you might do it. https://github.com/raspbernetes/multi-arch-images

Again, if you need help let me know.

**Comment by xUnholy** [comment]
@rajdas98 has there been any progress on this? If not can you point me to a repo and I'll assist.

**Comment by rajdas98** [comment]
Hi @xUnholy , This issue was lost due to some other priority issues. Here are the list of repos
- https://github.com/litmuschaos/chaos-operator
- https://github.com/litmuschaos/chaos-runner
- https://github.com/litmuschaos/litmus-go
- https://github.com/litmuschaos/chaos-runner (This is required when you want to monitor the chaos experiments)

**Comment by uditgaurav** [comment]
The multi-arch images support is now added for all the core litmus repositories:
1. chaos-runner
2. chaos-operator
3. litmus-go
4. chaos exporter

**Comment by rajdas98** [comment]
Following up on this issue. we need to add multi-arch support for litmus portal components also. Following are the components
1. https://github.com/litmuschaos/litmus/tree/master/litmus-portal/frontend
2. https://github.com/litmuschaos/litmus/tree/master/litmus-portal/graphql-server
3. https://github.com/litmuschaos/litmus/tree/master/litmus-portal/authentication
4. https://github.com/litmuschaos/litmus/tree/master/litmus-portal/cluster-agents/event-tracker
5. https://github.com/litmuschaos/litmus/tree/master/litmus-portal/cluster-agents/subscriber

cc: @ajeshbaby @ksatchit

**Comment by nlamirault** [comment]
Hi, any news on this feature ? I would like to deploy Limus 2.0.0 on my k8s arm64 cluster.

**Comment by rajdas98** [comment]
Yes @nlamirault, We added ARM64 for litmusportal components. We will make a release of Litmus-2.0.0-Beta8 tomorrow, after that you can use it.

**Comment by rajdas98** [comment]
Closing this issue-  Added the support of multi-arch(ARM64 & AMD4) image for all the litmus components.
