### ISSUE TITLE
[experiment/generic/kubelet-service-kill] error converting YAML to JSON

### ISSUE THREAD

**Issue by ToruMakabe** [litmuschaos/litmus#1582]
**What happened**:
"generic/kubelet-service-kill" experiment failed.

```
2020-06-19 07:11:48.002109 Step: [Inject]: Creating the chaos pod in default namespace
task path: /utils/common/create_chaos_pod.yml:3
fatal: [127.0.0.1]: FAILED! => {"changed": true, "cmd": "kubectl apply -f /tmp/kubelet-service-kill.yml -n default", "delta": "0:00:00.865666", "end": "2020-06-19 07:11:47.982637", "msg": "non-zero return code", "rc": 1, "start": "2020-06-19 07:11:47.116971", "stderr": "error: error parsing /tmp/kubelet-service-kill.yml: error converting YAML to JSON: yaml: line 8: mapping values are not allowed in this context", "stderr_lines": ["error: error parsing /tmp/kubelet-service-kill.yml: error converting YAML to JSON: yaml: line 8: mapping values are not allowed in this context"], "stdout": "", "stdout_lines": []}
```

[All log](https://gist.github.com/ToruMakabe/f5319e98df1c4a808ed3b56cca995bb8)

**What you expected to happen**:
Complete experiment with "Verdict:    Pass"

**How to reproduce it (as minimally and precisely as possible)**:
* Create ServiceAccount, ClusterRole and ClusterRoleBinding. followed [the manifest](https://raw.githubusercontent.com/litmuschaos/chaos-charts/master/charts/generic/kubelet-service-kill/rbac.yaml)
* Create ChaosExperiment. followed [the manifest](https://raw.githubusercontent.com/litmuschaos/chaos-charts/master/charts/generic/kubelet-service-kill/experiment.yaml)
* Create ChaosEngine. followed [the manifest](https://raw.githubusercontent.com/litmuschaos/chaos-charts/master/charts/generic/kubelet-service-kill/engine.yaml)
  * Changed chaosServiceAccount from chaosServiceAccount: kubelet-service-kill-sa to kubelet-service-kill due to inconsistency with ServiceAccount name created previously.

**Anything else we need to know?**:
Azure Kubernetes Service (1.18.2)

**Comment by uditgaurav** [comment]
Thanks again @ToruMakabe, the PR for this has already been raised. Ref: https://github.com/litmuschaos/litmus/pull/1581. We will be fixing this asap.

**Comment by ToruMakabe** [comment]
@uditgaurav Sorry for dup. Looking forward to it.

**Comment by uditgaurav** [comment]
We can keep it open for the track @ToruMakabe. Thanks!
