### ISSUE TITLE
Create Kubernetes CR's Chaos Chart

### ISSUE THREAD

**Issue by rahulchheda** [litmuschaos/litmus#1608]
As, many non native resources are now being created with the help of CR's and CRD's with their separate controllers. It would be good to have a CR delete chaos, with a time constraint, to see how your controller/Kubernetes cluster/ application behaves in those cases.

Example: What if someone want to delete an Ingress or an HPA. These components being critical to Kubernetes Cluster, and managed by separate controllers, might need to tested/ validated in a production environment.

**Comment by rahulchheda** [comment]
cc: @ksatchit

**Comment by ksatchit** [comment]
This is not being prioritized for the immediate future.
