### ISSUE TITLE
(Branch optimisation): Remove stale branches and move pipeline details into master branch

### ISSUE THREAD

**Issue by uditgaurav** [litmuschaos/litmus#1658]
_This issue is for:_

**Optimizing Litmus-e2e Branches:** 

This Includes:
- Moving the content of the baseline branch to the master branch only.
- Addition of a new branch that is litmus-portal for portal e2e which will be a separate pipeline. 
- Addition of master-plan.yaml which includes coverage per category-wise (generic/category/litmus-portal)  in the respective folder in the master branch.
- Removing generic-staging, openebs-staging, litmus-Onpem, baseline branch.

**Comment by ksatchit** [comment]
Fixed via https://github.com/litmuschaos/litmus-e2e/pull/155, https://github.com/litmuschaos/litmus-e2e/pull/154, https://github.com/litmuschaos/litmus-e2e/pull/156
