### ISSUE TITLE
Need to setup CI for the litmus portal

### ISSUE THREAD

**Issue by rajdas98** [litmuschaos/litmus#1684]
- [x] Need to setup circleCI for the Litmus Portal.
- [ ] Need to create a Makefile and Makefile.common
- CI checks
  - [ ] Lint
  - [x] Unused packages
  - [ ] Add go vet
  - [ ] trivy security check
  - [x] Add BDD and unit tests

**Comment by ksatchit** [comment]
@rajdas98 is this available?

**Comment by rajdas98** [comment]
Yes, we need to improve the CI for the litmus portal

**Comment by rajdas98** [comment]
closing by this PR- https://github.com/litmuschaos/litmus/pull/1601 and a few more
