### ISSUE TITLE
Documentation for the litmus portal

### ISSUE THREAD

**Issue by rajdas98** [litmuschaos/litmus#1686]
- Need to add the documentation for the litmus portal 1.6
- Contents
  - High Level Design
  - Architecture
  - Component definitions
  - Installation and un-installation steps

**Comment by ksatchit** [comment]
Basic install/uninstall documentation is available here: https://github.com/litmuschaos/litmus/tree/master/litmus-portal

Usage guide is here: https://docs.google.com/document/d/1fiN25BrZpvqg0UkBCuqQBE7Mx8BwDGC8ss2j2oXkZNA/edit#

Efforts are on to place this in git source and render on the docs website. This will be tracked separately.
