### ISSUE TITLE
Refactor all the experiments to make execution faster

### ISSUE THREAD

**Issue by ispeakc0de** [litmuschaos/litmus#1691]
**Description**

- Refactor all the experiments to make execution faster. we can remove all the unnecessary checks. This issue can be used to track all the approaches can be used to  reduce the execution time in both positive & negative cases.

**Comment by ksatchit** [comment]
- Removal of exp cleanup from within experiment logic. The operator cleanups up based on jobCleanupPolicy
- Fix container state checks to exit upon finding terminated containers over waiting for active state
