### ISSUE TITLE
Add docker static security checks in travis CI for test images

### ISSUE THREAD

**Issue by chandankumar4** [litmuschaos/litmus#1721]
## Is this a BUG REPORT or FEATURE REQUEST?
 FEATURE REQUEST

**What happened**:

- The test containers do not have any security checks implemented against them, which can be included in the Travis CI.

**What you expected to happen**:

- Include security checks in build process

**Anything else we need to know?**:

- Ref:  https://github.com/docker/docker-bench-security

**Comment by ksatchit** [comment]
The Trivy checks have been extended to all litmus infra components via Github Workflows
