### ISSUE TITLE
use a common label to select multiple experiment targets

### ISSUE THREAD

**Issue by steevi** [litmuschaos/litmus#1730]
it would be good to be able to select multiple targets for the experiments.

Tried adding a common label in 4 statefulsets (e.g. appkey: test). Would like all those 4 sts to be targets of the experiments, and have one selected at random during fault injection.

When that new label was added only to one sts, I could get the chaos experiment to run, but when I added that label to multiple sts, then the chaos experiment wasn't fired.

**Comment by ksatchit** [comment]
@steevi thanks for the issue. We will update this issue with the fixes and relevant spec.

**Comment by steevi** [comment]
Thanks for your reply. Waiting for it

**Comment by ksatchit** [comment]
This is supported currently with `.spec.annotationCheck` set to `false` in the chaosengine. Any sts/deploy/ds that carries this unique label will be picked randomly for chaos. 

**Note**: However, ensure that this label is present in the podTemplateSpec of these above resources.

**Comment by steevi** [comment]
Thanks a lot @ksatchit 
Changing `.spec.annotationCheck` to `false` made that work perfect!!!
