### ISSUE TITLE
Add coverage percentage in readme file and in ci website

### ISSUE THREAD

**Issue by uditgaurav** [litmuschaos/litmus#1748]
This issue is for:

- Add coverage percentage in the readme and also in ci website so that we could get all the pipeline info in one place.

**Comment by uditgaurav** [comment]
**How are we updating the coverage percentage in Readme table:**

- We will get the coverage percentage from`e2e-metrics` job, then we will save it in some file called `coverage.txt` then in the `pipeline status update` job we will use this file to get the coverage value and add it in the readme file with a new column.
- Clicking on the coverage value will take us to the `.master-plan.yml` which is used to calculate the coverage.

**Comment by ksatchit** [comment]
Fixed by https://github.com/litmuschaos/litmus-e2e/pull/174 https://github.com/litmuschaos/litmus-e2e/pull/176
