### ISSUE TITLE
tc-image for network chaos experiments is hardcoded

### ISSUE THREAD

**Issue by blencoff** [litmuschaos/litmus#1764]
[path to tc-image](https://github.com/litmuschaos/litmus/blob/master/chaoslib/pumba/network_chaos/pumba_netem_job.j2#L21) are currently hardcoded.

The current implementation blocks normal use of the network experiments on systems without internet access.
There is an ability to specify  location of pumba image on a local repository but in the current state it will still try to download `gaiadocker/iproute2` image from docker.io so that will cause an issue like following

**What happened**:

I've specified path to local artifactory in `LIB_IMAGE`
```yaml
- name: LIB_IMAGE
   value: 'artifactory:8080/chaos/litmuschaos/pumba:0.6.5'
```
created chaosengine and faced with issue with pumba pod
```bash
pumba-netem-bmndgx                                        0/1     Error     0          2s
```
further investigation led to the following error
```bash
kubectl logs pumba-netem-bmndgx -n test_ns
time="2020-07-20T11:11:42Z" level=error msg="failed to pull tc image" app=pumba error="Error response from daemon: Get https://registry-1.docker.io/v2/: read tcp x.x.x.x:x->x.x.x.x:x: read: connection reset by peer" function=github.com/sirupsen/logrus.WithError source="container/client.go:497"
time="2020-07-20T11:11:42Z" level=error msg="Error response from daemon: Get https://registry-1.docker.io/v2/: read tcp x.x.x.x:x->x.x.x.x:x: read: connection reset by peer" app=pumba function=github.com/alexei-led/pumba/pkg/container.dockerClient.NetemContainer source="container/client.go:240"
time="2020-07-20T11:11:42Z" level=error msg="failed to start netem for container" app=pumba error="Error response from daemon: Get https://registry-1.docker.io/v2/: read tcp x.x.x.x:x->x.x.x.x:x: read: connection reset by peer" function=github.com/sirupsen/logrus.WithError source="netem/netem.go:27"
```
**What you expected to happen**:

There should be an option for tc-image path.

**How to reproduce it (as minimally and precisely as possible)**:

Run network chaos experiments on environment with no internet access.

**Comment by ksatchit** [comment]
Indeed this is the case @blencoff !! Thank you for trying litmus and bringing this up. Fix underway!! 

cc: @ispeakc0de 

References: 

- https://github.com/litmuschaos/litmus-go/blob/master/chaoslib/pumba/network_chaos/network-chaos.go#L174) 
- https://github.com/litmuschaos/litmus-ansible/blob/master/chaoslib/pumba/network_chaos/pumba_netem_job.j2#L21)

**Comment by blencoff** [comment]
@ksatchit 
I've also created an [issue](https://github.com/litmuschaos/litmus-ansible/issues/12) in [litmus-ansible](https://github.com/litmuschaos/litmus-ansible) project related to one of the references mentioned above.
I'm not sure if it should be closed or linked.

**Comment by ksatchit** [comment]
@blencoff , yes, I suppose we can close it by referencing to the fixes. The fix is available in the `ci` tagged images for both litmuschaos/go-runner & litmuschaos/ansible-runner 

We will be doing a patch release 1.6.1 later this week (tentative 22/07/2020) that will include these fixes. Will keep you posted on the same/reply to this thread. Thanks !

**Comment by blencoff** [comment]
@ksatchit Thanks a lot!

**Comment by ksatchit** [comment]
@blencoff , here are the release artefacts: 

Operator manifest: https://github.com/litmuschaos/pages/blob/master/docs/litmus-operator-v1.6.1.yaml
Chaos experiment CR Bundle: https://hub.litmuschaos.io/generic (refer: https://github.com/litmuschaos/chaos-charts/blob/v1.6.x/charts/generic/pod-network-latency/experiment.yaml#L51)
