### ISSUE TITLE
experiments for more than one replica

### ISSUE THREAD

**Issue by blencoff** [litmuschaos/litmus#1780]
As far as I've got, currently there is an ability to perform experiments only for one random application replica in case if app has been scaled up to several instances.
It would be great if there would be ability to make experiments with more than one (several/all) of them.

**Comment by ksatchit** [comment]
Thanks for the requirement @blencoff !! Yes, this is in the short-term roadmap - i.e., define blast-radius % for the experiment - to select more than one replica. Will keep you posted on this.

There is a way to do this for pod-delete via the env "KILL_COUNT", for pod-cpu-hog & pod-memory-hog via the env POD_AFFECTED_PERC. The one for network chaos and some standardization around this is coming next.

**Comment by ksatchit** [comment]
Meanwhile, @blencoff just wanted to share here: please feel free to join our [slack](https://slack.litmuschaos.io/) community where there are some interesting discussions going on around topics such as these !!

**Comment by ksatchit** [comment]
@blencoff the capability to run parallel chaos on several/all replicas of a deployment  (or ds, sts) has been added in 1.8.0 release. You can specify the PODS_AFFECTED_PERC env variable in the ChaosEngine to specify the % of replicas you want to inject the chaos on - in a given experiment run. 

Refer experiment docs for more details: https://docs.litmuschaos.io/docs/pod-delete/#supported-experiment-tunables
