### ISSUE TITLE
Add instructions in litmus-docs to run litmus on Okteto 

### ISSUE THREAD

**Issue by ksatchit** [litmuschaos/litmus#1800]
[Okteto](https://github.com/okteto/okteto) is focused on giving users a development environment right on the cluster, with the Okteto [Cloud](https://okteto.com) providing namespaces for getting started w/ in-cluster development and simulate dev/ci/prod environments, with options to deploy pre-configured application templates. 

This issue will track the creation of the resources/docs to run litmus on okteto in namespace scope, with the chaos experiments pulled as helm charts.

**Comment by ksatchit** [comment]
- ns-scoped operator (openAPI schema validation needs to be updated as per latest changes!): https://github.com/litmuschaos/litmus/blob/master/docs/litmus-operator-namespaced-scope.yaml

- helm charts for chaos experiments (needs update as per 1.6.1 & removal of helper images): https://github.com/litmuschaos/litmus-helm/tree/master/charts/kubernetes-chaos

**Comment by ksatchit** [comment]
- The namespaced operator manifest & associated docs are available with 1.6.2 images 
- The chaos CRs have been updated with latest image tags & schema enhancements in both sources helm as well as chaoshub.

**Comment by rberrelleza** [comment]
This is an initial attempt from our side, leveraging the "develop on okteto" button to spin up litmus, an experiment, and the target application: https://github.com/okteto/litmus-on-okteto. Our goal is to make this into a tutorial or blog post for future reference.
