### ISSUE TITLE
List of refactors for the Graphql Server

### ISSUE THREAD

**Issue by rajdas98** [litmuschaos/litmus#1811]
- Need to make generic MongoDB operations. Currently, we have too many functions to make similar MongoDB operations.
- Need to refactor the directory structure to make the reusability
- Need to refactor the graphql schema for the subscriber.
- Need to change some environment variables to a meaningful name.

**Comment by rajdas98** [comment]
cc @gdsoumya

**Comment by oumkale** [comment]
@rajdas98 @gdsoumya  Please assigned it to me as well i will try to make some meaningful changes.

**Comment by gdsoumya** [comment]
@oumkale we are already looking into this, @rajdas98 has started the refactor I believe. You can surely reach out to him and check if he needs any help.

**Comment by oumkale** [comment]
@gdsoumya Ok thanks.
