### ISSUE TITLE
Need a function to get system's IP for the graphql Server

### ISSUE THREAD

**Issue by rajdas98** [litmuschaos/litmus#1816]
- Currently, we are passing external IP as an environment variable to graphql server. 
  - https://github.com/litmuschaos/litmus/blob/litmus-portal/litmus-portal/k8s-manifest.yml#L74
- Need a function to get the system's IP.

NOTE- We don't need external third party API to get the IP address

**Comment by rajdas98** [comment]
cc @oumkale

**Comment by rajdas98** [comment]
Or, Use client-go pkg to get the node IP.

**Comment by oumkale** [comment]
@rajdas98 Yes! Will do it.

**Comment by rajdas98** [comment]
Thanks @oumkale

**Comment by rajdas98** [comment]
Put the get Ip function inside pkg/cluster/util.go

**Comment by gdsoumya** [comment]
@rajdas98 the node ip might not be usable for external cluster-connects in case the user is using minikube/kind for testing.

**Comment by rajdas98** [comment]
In the absence of external IP, we can use InternalIP

**Comment by oumkale** [comment]
@rajdas98  yes thank you i was confussed with that point only.
