### ISSUE TITLE
Fix for Cypress coming as unused dependency and Refactoring of unit tests needed.

### ISSUE THREAD

**Issue by Jonsy13** [litmuschaos/litmus#1830]
**1. Right now, Cypress is coming as an unused dependency by depcheck, Needs to be fixed.**
**2. Some Unit Tests need to be refactored.**
**3. Typescript configuration for Cypress needed.**

**Comment by rajdas98** [comment]
closing in favor of https://github.com/litmuschaos/litmus/pull/1831 and https://github.com/litmuschaos/litmus/pull/1831
