### ISSUE TITLE
Unable to run the pod delete experiment in LinkerD (emojivoto)

### ISSUE THREAD

**Issue by Shreyangi** [litmuschaos/litmus#1838]
**What happened**: I tried running the generic chaos experiments in linkerd, specifically in emojivoto which the sample application provided by linkerd itself. Starting with pod-delete, the experiment is taking around 3 min for completion and still resulting in an unsuccessful run of the experiment. Tried deleting the exact pod (voting, which I am working on) to see if it is taking time to recreate but that's not the case too.

**What you expected to happen**: The experiment should be successful without any issue and in the specified time being.

**How to reproduce it (as minimally and precisely as possible)**: Logs for the experiment pod
> kubectl logs -f pod-delete-mvy8mn-9f2pz -n emojivoto
W0807 03:16:46.228093       1 client_config.go:541] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2020-08-07T03:16:46Z" level=info msg="[PreReq]: Getting the ENV for the  experiment"
time="2020-08-07T03:16:46Z" level=info msg="[PreReq]: Updating the chaos result of pod-delete experiment (SOT)"
time="2020-08-07T03:16:46Z" level=info msg="The application informations are as follows" Ramp Time=0 Namespace=emojivoto Label="name=voting"
time="2020-08-07T03:16:46Z" level=info msg="[Status]: Verify that the AUT (Application Under Test) is running (pre-chaos)"
time="2020-08-07T03:16:46Z" level=info msg="[Status]: Checking whether application pods are in running state"
time="2020-08-07T03:19:46Z" level=error msg="Application status check failed due to Unable to get the pod, err: <nil>\n"

Logs for runner pod
> kubectl logs -f chaos-runner -n emojivoto
W0807 03:16:37.874529       1 client_config.go:541] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0807 03:16:37.881911       1 runner.go:21] Experiments List:  [pod-delete]   Engine Name:  chaos   appLabels :  name=voting   appKind:     Service Account Name:  pod-delete-sa Engine Namespace:  emojivoto
I0807 03:16:38.686628       1 experimentHelpers.go:46] Getting the ENV Variables
I0807 03:16:39.089694       1 runner.go:50] Preparing to run Chaos Experiment: pod-delete
I0807 03:16:39.488341       1 configMapUtils.go:17] Validating configmaps specified in the ChaosExperiment & ChaosEngine
I0807 03:16:39.886848       1 secretsUtils.go:18] Validating secrets specified in the ChaosExperiment & ChaosEngine
I0807 03:16:40.088438       1 hostFileVolumeUtils.go:25] Validating HostFileVolumes details specified in the ChaosExperiment
I0807 03:16:50.103869       1 runner.go:66] Started Chaos Experiment Name: pod-delete, with Job Name: pod-delete-mvy8mn

**Comment by rajdas98** [comment]
cc @ispeakc0de @uditgaurav
