### ISSUE TITLE
Membership tracker: SIG-Observability

### ISSUE THREAD

**Issue by ksatchit** [litmuschaos/litmus#1846]

**Comment by rahulchheda** [comment]
Would like to a part of SIG-Observability.
Github ID: rchheda@infracloud.io

**Comment by arkajyotiMukherjee** [comment]
I would like to take part in SIG-Observability
Github ID: arkajyotiMukherjee
@ksatchit

**Comment by ishantanu** [comment]
Interested in sig-observability.

**Comment by rajdas98** [comment]
Hi @ksatchit, I am interested in sig-observability

**Comment by ishangupta-ds** [comment]
@ksatchit i am interested in SIG-Observability
GitHub ID: ishangupta-ds
Mail: ishan.gupta@mayadata.io

**Comment by chandankumar4** [comment]
Interested :+1:

**Comment by xkbarkar** [comment]
interested aswell

**Comment by just1900** [comment]
Interested
