### ISSUE TITLE
Need a microservice to check subscriber is running or not

### ISSUE THREAD

**Issue by rajdas98** [litmuschaos/litmus#1857]
- As the subscriber manifest is increasing with a number of deployment like argo, Prometheus. We need a small microservice to check the subscriber is running or not. 
- This microservice will go as an init container with argo and Prometheus.  
- If the subscriber is not running it will not install other resources

**Comment by gdsoumya** [comment]
We can let the subscriber itself handle the installation for the components, thus if it is not running the other components are also not installed?

**Comment by rajdas98** [comment]
It should be visible for user, what application is installed in the user's cluster. By having compoents in a manifest file is clearly visible and  to install components from subscriber requires cluster admin permission. 
Goal is to reduce rbac permission for the subscriber.

**Comment by rajdas98** [comment]
The same approach is taken by mayadata's kubera

**Comment by rajdas98** [comment]
Enhancement rejected
Closed PR- https://github.com/litmuschaos/litmus/pull/1946
