### ISSUE TITLE
Helm charts for Litmus-portal

### ISSUE THREAD

**Issue by rajdas98** [litmuschaos/litmus#1894]
Conditions:
- Self Cluster
  - Litmus components
  - Argo components
  - Litmus portal components
- External Cluster
    - Litmus components
    - Argo components

**Comment by rajdas98** [comment]
cc @ispeakc0de @ksatchit

**Comment by ksatchit** [comment]
This is available in the litmus-helm helm repo: https://github.com/litmuschaos/litmus-helm/tree/master/charts/litmus-portal
