### ISSUE TITLE
support for prometheus probes so that I can verify if the SLOs are breached during a chaos run

### ISSUE THREAD

**Issue by suhrud-kumar** [litmuschaos/litmus#1902]
It would be great if litmus has support for native prometheus probes. Idea is that, we can run promQL expression(s) against prometheus api so that we can verify if our applications SLOs are being breached during a chaos run.

**Comment by ksatchit** [comment]
The prometheusProbe is available since 1.11.0 release of litmus: https://docs.litmuschaos.io/docs/litmus-probe/#promprobe
