### ISSUE TITLE
chore(litmus-portal): Self-Deployer not able to create all resources

### ISSUE THREAD

**Issue by gdsoumya** [litmuschaos/litmus#1906]
**What happened**:

The `self-deployer` component is unable to create all the resources in the manifest provided. It is able to only create the 1st resource which in this case is the `subscriber`.

**What you expected to happen**:

All components/resources in the manifest to be installed by the `self-deployer`

**How to reproduce it (as minimally and precisely as possible)**:

This can be reproduced by running the self-deployer

**Comment by rajdas98** [comment]
closing because the `self deployer` is deprecated now.
