### ISSUE TITLE
Good directory structure for Litmus Portal

### ISSUE THREAD

**Issue by rajdas98** [litmuschaos/litmus#1908]
The current directory structure of litmus portal is not reusable and scalable. We need to refactor the directory structure before the codebase become too big.

**Comment by rajdas98** [comment]
cc @arkajyotiMukherjee

**Comment by arkajyotiMukherjee** [comment]
This is much needed change...
Also will be have a separate folder for database?
webui is a bit unconventional name...but I'm fine with it.
The front-end directory will change a bit too upon extracting the components

**Comment by Sanjay1611** [comment]
- graphql-server
  - build
     - Dockerfile (file)
  - graph
     - generated
     - model (We can write our custom models too)
       - model_gen.go
     - resolver.go (file)
     - schemas (all definitions, mutation/query/subscription go here)
       - user.go
       - project.go (schemas and subschemas of all resources will go inside `schemas` directory like this)
     - schema.resolvers.go (We should find a way to separate all the resolvers in their separate files.Will need to look up for this )
   - manifest
      - subscriber.yml (file)
    - pkg
       - helper (or util)
         - cluster
           - (different files for different types of actions mutations etc)
         - workflow
           - workflow.go
         - logs
           - logs.go
         - project
           - project.go
         - user
           - user.go
      - data-store
      - database
        - mongodb(if later we want to provide support for other DBs also)
          - init.go (mongo type-def and db conn. init etc.)
          - schemas (this schemas directory can later be put under database directly to support other frameworks too without much effort)
            - cluster.go
            - workflow.go
            - project.go
            - user.go
          - operations
            - cluster.go
            - project.go
            - user.go
            - workflow.go
       - other_handlers
         - file_handler.go
       - util
         - <util_category>.go
     - go.mod/go.sum (file)
     - server.go (file)
     - gqlgen.yml (file)

**Comment by rajdas98** [comment]
1. Separate graphql schema
    - global.graphqls
    - project.graphqls
    - ..... resources
2. manifests/{manifest.yaml.....}---- issue / skipped
3. database pkg needs to refactor later

**Comment by rajdas98** [comment]
closing by this PR https://github.com/litmuschaos/litmus/pull/1947 and a few more
