### ISSUE TITLE
Need a GraphQL query parser

### ISSUE THREAD

**Issue by imrajdas** [litmuschaos/litmus#1916]
Currently, the graphql queries are looking too ugly. It requires a graphql parser which will convert good readable string to GQL query string.

Ex- 	
```
 {"query":"subscription {\n    clusterConnect(clusterInfo: {cluster_id: \"` + clusterData["CID"] + `\", access_key: \"` + clusterData["KEY"] + `\"}) {\n   \t project_id,\n     action{\n      k8s_manifest,\n      external_data,\n      request_type\n     }\n  }\n}\n"}
```
Ref: https://github.com/shurcooL/graphql

**Comment by ksatchit** [comment]
The APIs have undergone significant refactor since the time of creation of this issue. 

Further enhancements will be tracked with dedicated tasks/issues.
