### ISSUE TITLE
Reduce go-runner image size by using single binary in place of creating different binaries for different experiments

### ISSUE THREAD

**Issue by uditgaurav** [litmuschaos/litmus#1920]
#### LITMUS VERSION
- 1.7.0

#### DETAILS 

- This issue is for _reducing the size of litmus go-runner image_  by using/creating less number of binaries for the experiment execution. Today our every experiment creates a binary in the image for the execution of the experiments, this is gradually increasing the size of the image as the number of experiments increases. This issue is to reduce the number of binaries created in the image and so the size of the image.

**Comment by ksatchit** [comment]
Fixed via https://github.com/litmuschaos/litmus-go/pull/155
