### ISSUE TITLE
add support aws ssm run commands

### ISSUE THREAD

**Issue by suhrud-kumar** [litmuschaos/litmus#1928]
Add support for running ssm commands/documents, specifically interested in blocking traffic to aws services mentioned here - https://github.com/adhorn/chaos-ssm-documents/tree/master/run-command

Also, I believe ssm run commands will be run at node level. It will be great if we can run at pod level so that other pods on that node will not be affected.

**Comment by suhrud-kumar** [comment]
@sumitnagal - FYI. I don't think I have access to add assignees to the issue

**Comment by sumitnagal** [comment]
Thanks Suhrud, will add in out roadmap.

**Comment by ksatchit** [comment]
This experiment category is now available: https://litmuschaos.github.io/litmus/experiments/categories/aws-ssm/aws-ssm-chaos-by-id/
