### ISSUE TITLE
Pod  Memory Hog  experiment fails on termination stage in containerd env

### ISSUE THREAD

**Issue by ajeshbaby** [litmuschaos/litmus#1930]
## STR
1. Run the node memory hog / node cpu hog experiment, it runs and fails on the termination stage.

## Issue
- The chaos is injected, it ran the stress commands as a process but unable to kill the process in the cleanup section As `-lname` command is not supported in some application/setup. We need to find an alternative of `-lname` or change the way to filter out the process_id.

```
time="2020-08-27T04:17:27Z" level=info msg="The running status of container to stress is as follows" container=nginx Pod=nginx-764c9b96cf-4hhs8 Status=Running
time="2020-08-27T04:17:27Z" level=info msg="[Chaos]:Stressing: 500 Megabytes"
time="2020-08-27T04:17:27Z" level=info msg="[Chaos]:Waiting for: 60s"
time="2020-08-27T04:17:27Z" level=info msg="The memory consumption is: 500"
time="2020-08-27T04:18:27Z" level=info msg="[Chaos]: Time is up for experiment: pod-memory-hog"
sh: invalid number 'find:'
sh: invalid number 'unrecognized:'
sh: invalid number '-lname'
time="2020-08-27T04:18:27Z" level=info msg="[Prepare]: Unable to run command inside container due to, err : command terminated with exit code 3"
time="2020-08-27T04:18:27Z" level=info msg="[Chaos]:Memory stress error: Unable to kill stress process inside target container, due to err: command terminated with exit code 3"
time="2020-08-27T04:18:27Z" level=error msg="[Error]: pod memory hog failed due to Unable to kill stress process inside target container, due to err: command terminated with exit code 3\n"
```

Note  - The stress command gets executed and it fails in the cleanup /terminate stage.

**Comment by ksatchit** [comment]
This is now handled via the CHAOS_KILL_COMMAND env var in the ChaosEngine which can provide a shell command mapped to the base image used in the target pod. 

Ref: https://docs.litmuschaos.io/docs/pod-memory-hog/#supported-experiment-tunables
