### ISSUE TITLE
Add a spell-checker to the litmus-docs CI 

### ISSUE THREAD

**Issue by ksatchit** [litmuschaos/litmus#1943]
Ref: 
- [PySpelling](https://github.com/marketplace/actions/run-pyspelling-as-a-github-action#:~:text=A%20Github%20Action%20that%20spell,provided%20by%20the%20repository%20owner)
- [rojopolis/spellcheck-github-actions](https://github.com/rojopolis/spellcheck-github-actions/issues)

**Comment by adarsh-k-tiwari** [comment]
@ksatchit Is this available? I would like to work on it.
