### ISSUE TITLE
Update apiVersion of the RBAC, CR and CRDs according to the latest k8s version

### ISSUE THREAD

**Issue by uditgaurav** [litmuschaos/litmus#1963]
**This issues is for:**

- This issue is for updating the apiVersion of the rbac, CR and CRDs according to the k8s latest version. 

```
Warning: rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
clusterrole.rbac.authorization.k8s.io/litmus unchanged
Warning: rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRoleBinding
clusterrolebinding.rbac.authorization.k8s.io/litmus unchanged
deployment.apps/chaos-operator-ce created
Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
```

This warning message is from k8s version `v1.19.0`

**Comment by WilliamHYZhang** [comment]
Taking this one on.

**Comment by uditgaurav** [comment]
Thanks, @WilliamHYZhang for the PR. There are other places also where we what to update the CRs. Please take a look if you are interested: 

- [Chaos-Charts](https://github.com/litmuschaos/chaos-charts/tree/master/charts) inside every folder check for `rbac.yaml` file and update the version. 

- [Litmus-Go](https://github.com/litmuschaos/litmus-go/tree/master/experiments) here also inside every folder check for `rbac.yaml` file and update the version.

**Comment by WilliamHYZhang** [comment]
@uditgaurav PRs are open :smile:

**Comment by uditgaurav** [comment]
Thanks, @WilliamHYZhang for the PRs. We will review it soon :)
