### ISSUE TITLE
Remove stale documentation from litmus-docs website

### ISSUE THREAD

**Issue by ksatchit** [litmuschaos/litmus#1986]
As a fast moving project with a monthly cadence, litmus ensures backward compatibility up to 2-3 releases (n-2). Considering the upgrades are very simple (a stateless app called chaos operator undergoes a rolling upgrade & a set of static custom resource bundles are pulled from the chaoshub), and the community experience thus far, the documentation for older versions need not be maintained for several previous releases. This issue tracks removal of older releases (based on where we are at the time of resolving this) and preferably automating this process.

**Comment by kapil-raj** [comment]
Hey guys, I can try to remove the old documentation for you. :)

**Comment by ksatchit** [comment]
Pre 1.0 documentation has been removed.
