### ISSUE TITLE
Automate embedmd update commands and document its usage as a pre-commit hook 

### ISSUE THREAD

**Issue by ksatchit** [litmuschaos/litmus#1989]
- Litmus-docs makes use of [embedmd](https://github.com/campoy/embedmd/) to pull changes to chaos snippets from the [chaos-charts](https://github.com/litmuschaos/chaos-charts) and other such repos
- This enables simpler update to snippets/manifests embedded into the docs. However, this is a user-action today, which may to may not be performed. Also, since it is per-file based, a bash script automating this would help. 
- Adding this to the build may be a good idea. Another approach is to use it as part of a pre-commit hook action. This needs to documented.

**Comment by uditgaurav** [comment]
This has been done with https://github.com/litmuschaos/litmus-docs/pull/360.

**Comment by ksatchit** [comment]
This is now automated and added as a as a github actions workflow triggered to push to master branch - https://github.com/litmuschaos/litmus-docs/blob/master/.github/workflows/main.yml
