### ISSUE TITLE
Update the resource page on litmus-docs with updated information

### ISSUE THREAD

**Issue by ksatchit** [litmuschaos/litmus#1992]
The [resources]( (https://docs.litmuschaos.io/docs/resources/)) page in litmus-docs consists of stale information. Restructure & provide references to latest resources available here: https://github.com/litmuschaos/litmus/wiki/Litmus-Architecture

**Comment by lumenCodes** [comment]
Hi. I am interested in this issue but please can I get more explanation on it. 

Am I supposed to add the resources in a table?

**Comment by ksatchit** [comment]
Fixed by https://github.com/litmuschaos/litmus-docs/pull/403
