### ISSUE TITLE
Update the chaos plugins page with type-1/2 integration mechanisms 

### ISSUE THREAD

**Issue by ksatchit** [litmuschaos/litmus#1993]
- This page describes the other opensource chaos tools Litmus can integrate with. 
- Restructure this doc with information on the types of integrations and examples to support the same. 

Ref: https://docs.google.com/presentation/d/1OGuSisuory7jE-LvrDyC6J9x1wdom2Bowc0Fso6F4Ps/edit#slide=id.g836279615b_0_56

**Comment by manavsiddharthgupta** [comment]
can you assign me?
i would like to work on this issue.
thank you

**Comment by ksatchit** [comment]
The advocated integration approach has been documented in the dev guide docs.
