### ISSUE TITLE
Include steady state , deviation state and elobrative experiment definitaion 

### ISSUE THREAD

**Issue by tejendrab** [litmuschaos/litmus#1998]
Hi Team,
We are running the experiments and also achieving the results.
For a non technical presentation i am seeking a way to define the steady state with purpose of experiment and actions taken defined in either a good reporting format or on the output of results section that can help in powerful impact on the audience and non tech usage.

**Comment by ksatchit** [comment]
The chaos center is equipped to generate reports for experiments with details on resilience
