### ISSUE TITLE
GQL Inetegration

### ISSUE THREAD

**Issue by oumkale** [litmuschaos/litmus#2008]

**Comment by Jonsy13** [comment]
Which GQL integration specifically are you referring to here??For scheduling it was already done there were only minor fixes.

**Comment by oumkale** [comment]
Ya, it is already done. I was just making the issues on which we have worked.

**Comment by Jonsy13** [comment]
Yes thats why I asked...because you already made one issue for integration, which was assigned to both of us.
So what this was about specifically assigned to you only?

**Comment by oumkale** [comment]
No @Jonsy13. Yaa I closed this issue.
