### ISSUE TITLE
Getting started fails at https://docs.litmuschaos.io/docs/next/getstarted.html#observe-chaos-results

### ISSUE THREAD

**Issue by yarcyarc** [litmuschaos/litmus#2020]
**What happened**:

Follow the getting started guide at https://docs.litmuschaos.io/docs/next/getstarted.html. 

With both clean installed Google GKE and local microk8s I find this fails at step https://docs.litmuschaos.io/docs/next/getstarted.html#run-chaos; 

```
$ kubectl describe chaosresult nginx-chaos-container-kill -n nginx
Error from server (NotFound): chaosresults.litmuschaos.io "nginx-chaos-container-kill" not found
```

If you switch to https://docs.litmuschaos.io/docs/next/rancher-litmus/ for a slightly different approach, then you get further, principally because the LIB_IMAGE value in `chaosengine.yaml` is newer; `gaiaadm/pumba:0.7.2`. Here you get to step https://docs.litmuschaos.io/docs/next/getstarted.html#observe-chaos-results. The transcript below is for `gaiaadm/pumba:0.7.4`, but it is the same for 0.7.2:   

```
$ kubectl describe chaosresult nginx-chaos-container-kill -n nginx
Name:         nginx-chaos-container-kill
Namespace:    nginx
Labels:       name=nginx-chaos-container-kill
Annotations:  <none>
API Version:  litmuschaos.io/v1alpha1
Kind:         ChaosResult
Metadata:
  Creation Timestamp:  2020-09-09T13:54:30Z
  Generation:          3
  Resource Version:    3979
  Self Link:           /apis/litmuschaos.io/v1alpha1/namespaces/nginx/chaosresults/nginx-chaos-container-kill
  UID:                 bae66f5d-ee3e-43c2-9339-6ee8047d3370
Spec:
  Engine:      nginx-chaos
  Experiment:  container-kill
Status:
  Experimentstatus:
    Fail Step:  Executing pumba lib for the container-kill
    Phase:      Completed
    Verdict:    Fail
Events:
  Type     Reason   Age   From                         Message
  ----     ------   ----  ----                         -------
  Warning  Summary  119s  container-kill-ml5o5y-cmkdg  container-kill experiment has been Failed
$ kubectl get pods -n nginx
NAME                          READY   STATUS               RESTARTS   AGE
container-kill-737du8-pjwhc   1/1     Running              0          20s
container-kill-omfulj         0/1     ContainerCannotRun   0          14s
nginx-554b9c67f9-vj28w        1/1     Running              0          13m
nginx-chaos-runner            1/1     Running              0          32s
```

with the failing container like this; 

```
$ kubectl describe pod container-kill-omfulj -n nginx
Name:               container-kill-omfulj
Namespace:          nginx
Priority:           0
PriorityClassName:  <none>
<..>
Events:
  Type     Reason   Age    From                                                       Message
  ----     ------   ----   ----                                                       -------
  Normal   Pulling  9m33s  kubelet, gke-mfo-litmus-200909-default-pool-6176e6ec-sqdn  Pulling image "gaiaadm/pumba:0.7.4"
  Normal   Pulled   9m29s  kubelet, gke-mfo-litmus-200909-default-pool-6176e6ec-sqdn  Successfully pulled image "gaiaadm/pumba:0.7.4"
  Normal   Created  9m29s  kubelet, gke-mfo-litmus-200909-default-pool-6176e6ec-sqdn  Created container container-kill
  Warning  Failed   9m29s  kubelet, gke-mfo-litmus-200909-default-pool-6176e6ec-sqdn  Error: failed to start container "container-kill": Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"pumba\": executable file not found in $PATH": unknown
```

**What you expected to happen**:

Cf. https://docs.litmuschaos.io/docs/next/rancher-litmus/#observe-chaos-results; 

```
Status:
  Experimentstatus:
    Fail Step:  N/A
    Phase:      Completed
    Verdict:    Pass
Events:         <none>
```
**How to reproduce it (as minimally and precisely as possible)**:

Follow https://docs.litmuschaos.io/docs/next/getstarted.html or https://docs.litmuschaos.io/docs/next/rancher-litmus but for a normal gke or microk8s cluster. Fails identically on both. 

**Anything else we need to know?**:

No. I'd like litmus to work so I might see if it fits into our SRE setup. :-)

**Comment by ksatchit** [comment]
cc: @ispeakc0de

**Comment by ispeakc0de** [comment]
Hi @yarcyarc,

Thanks for pointing out this issue. The value of `LIB_IMAGE` is older/depreciated(not update in getting started docs). Can you please change try it by setting the value of `LIB_IMAGE` env as `litmuschaos/go-runner:1.7.0`
you can also refer: https://docs.litmuschaos.io/docs/container-kill/#supported-experiment-tunables

**Comment by yarcyarc** [comment]
Thanks for a reply. Tried with 

```- name: LIB_IMAGE  
      value: 'litmuschaos/go-runner:1.7.0' 
```

in the chaosengine.yaml. 

That seems to possibly get me further but no cigar yet. 

It runs; 

```
$ kubectl get pods -n nginx
NAME                          READY   STATUS    RESTARTS   AGE
container-kill-km1p8h-sr8gp   1/1     Running   0          105s
nginx-chaos-runner            1/1     Running   0          2m1s
nginx-f89759699-w9wpm         1/1     Running   3          44h
```

Then finishes, apparently nicely; 

```
$ kubectl get pods -n nginx
NAME                    READY   STATUS    RESTARTS   AGE
nginx-f89759699-w9wpm   1/1     Running   3          44h
```

But the result is not satisfactory

```
$ kubectl describe chaosresult nginx-chaos-container-kill -n nginx
Name:         nginx-chaos-container-kill
Namespace:    nginx
Labels:       name=nginx-chaos-container-kill
Annotations:  <none>
API Version:  litmuschaos.io/v1alpha1
Kind:         ChaosResult
Metadata:
  Creation Timestamp:  2020-09-09T10:44:16Z
  Generation:          5
  Managed Fields:
    API Version:  litmuschaos.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .:
          f:name:
      f:spec:
        .:
        f:engine:
        f:experiment:
      f:status:
        .:
        f:experimentstatus:
          .:
          f:failStep:
          f:phase:
          f:verdict:
    Manager:         container-kill
    Operation:       Update
    Time:            2020-09-11T06:53:58Z
  Resource Version:  3416788
  Self Link:         /apis/litmuschaos.io/v1alpha1/namespaces/nginx/chaosresults/nginx-chaos-container-kill
  UID:               b9cae2e5-b90a-438b-b203-13e14d04f133
Spec:
  Engine:      nginx-chaos
  Experiment:  container-kill
Status:
  Experimentstatus:
    Fail Step:  Executing pumba lib for the container-kill
    Phase:      Completed
    Verdict:    Fail
Events:
  Type     Reason   Age   From                         Message
  ----     ------   ----  ----                         -------
  Warning  Summary  22s   container-kill-km1p8h-sr8gp  container-kill experiment has been Failed
```

The container-kill is gone, so I guess I'm not at liberty to look at the logs. Mind you, I have no insight into the project or how this is stitched together, I'm simply doing the "getting started" to make a preliminary assessment whether our team should look more closely at this. So I might be doing silly things or there might be really obvious remedies you @ispeakc0de see immediately. Bear over with me. :-)

**Comment by yarcyarc** [comment]
I had some more time this afternoon. I log tailed the container-kill; 

```
$ kubectl logs --follow container-kill-uh04tm-mw684 -n nginx
W0911 10:36:16.437914       1 client_config.go:541] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2020-09-11T10:36:16Z" level=info msg="[PreReq]: Getting the ENV for the  experiment"
time="2020-09-11T10:36:16Z" level=info msg="[PreReq]: Updating the chaos result of container-kill experiment (SOT)"
time="2020-09-11T10:36:16Z" level=info msg="The application information is as follows" Ramp Time=0 Namespace=nginx Label="app=nginx"
time="2020-09-11T10:36:16Z" level=info msg="[Status]: Verify that the AUT (Application Under Test) is running (pre-chaos)"
time="2020-09-11T10:36:16Z" level=info msg="[Status]: Checking whether application containers are in running state"
time="2020-09-11T10:36:16Z" level=info msg="The running status of container are as follows" Pod=nginx-f89759699-w9wpm Status=Running container=nginx
time="2020-09-11T10:36:18Z" level=info msg="[Status]: Checking whether application pods are in running state"
time="2020-09-11T10:36:18Z" level=info msg="The running status of Pods are as follows" Pod=nginx-f89759699-w9wpm Status=Running
time="2020-09-11T10:36:20Z" level=info msg="[Info]: Details of application under chaos injection" ContainerName=nginx PodName=nginx-f89759699-w9wpm NodeName=yarc-mainii
time="2020-09-11T10:36:20Z" level=info msg="restartCount of target container before chaos injection: 3"
time="2020-09-11T10:36:20Z" level=info msg="[Status]: Checking the status of the helper pod"
time="2020-09-11T10:36:20Z" level=info msg="[Status]: Checking whether application containers are in running state"
time="2020-09-11T10:36:22Z" level=info msg="[Status]: Checking whether application pods are in running state"
time="2020-09-11T10:36:24Z" level=info msg="The running status of Pods are as follows" Pod=container-kill-lppwhx Status=Running
time="2020-09-11T10:36:26Z" level=info msg="[Wait]: Waiting for the 20s chaos duration"
time="2020-09-11T10:36:46Z" level=info msg="[Cleanup]: Deleting the helper pod"
time="2020-09-11T10:38:34Z" level=info msg="restartCount of target container after chaos injection: 3"
time="2020-09-11T10:38:34Z" level=error msg="Chaos injection failed due to Target container is not restarted , err: Target container is not restarted\n"
```

**Comment by uditgaurav** [comment]
@yarcyarc You are getting this from micro-k8s or GKE?

**Comment by yarcyarc** [comment]
Good call. It was microk8s. Did it over gcp now, and that works; 

```
Status:
  Experimentstatus:
    Fail Step:  N/A
    Phase:      Completed
    Verdict:    Pass
Events:
  Type    Reason   Age   From                         Message
  ----    ------   ----  ----                         -------
  Normal  Summary  86s   container-kill-qhi2p9-z29zw  container-kill experiment has been Passed
```

So, it works in gcp. Doesn't in microk8s. That's weird I guess, but I'm happy. gcp suffices. :-) 

Thanks for your support and patience.

**Comment by uditgaurav** [comment]
cool @yarcyarc ...It should work with micro-k8s as well as microk8s have containerd run-time environment 
we just need to change the `CONTAINER_RUNTIME` to `containerd`(engine) `LIB` value to `litmus` if its `pumba`(experiment).

**Comment by yarcyarc** [comment]
Would've been nice if it worked on microk8s as well. Less scaffolding for experimental use. I looked for the `CONTAINER_RUNTIME` but couldn't really find that, on the github project or on litmuschaos.io. Is this something I can add in a yaml file or similar @uditgaurav or is this something deep under the hood? :-)

**Comment by sakshigupta-29** [comment]
Hello,
I am facing the same issue .

```
`root@master-node:~#` kubectl describe chaosresult nginx-chaos-container-kill
Error from server (NotFound): chaosresults.litmuschaos.io "nginx-chaos-container-kill" not found
```
Given below the commands which I followed :
#kubectl apply -f https://litmuschaos.github.io/litmus/litmus-operator-v1.7.0.yaml
#kubectl get pods -n litmus
#kubectl get crds | grep chaos

 Install Chaos Expermiment - container-kill
#kubectl apply -f https://hub.litmuschaos.io/api/chaos/1.7.0?file=charts/generic/container-kill/experiment.yaml
 
vim rbac.yaml
#kubectl apply -f rbac.yaml

vim chaosengine.yaml
#kubectl apply -f chaosengine.yaml

#watch -n 1 kubectl get pods -n litmus
#kubectl describe chaosresult nginx-chaos-container-kill -n nginx



Output which I got after describing chaos operator : 
Events:
  Type     Reason     Age                   From                 Message
  ----     ------     ----                  ----                 -------
  Normal   Pulled     12m                   kubelet, slave-node  Successfully pulled image "litmuschaos/chaos-operator:1.7.0" in 3.976277407s
  Normal   Pulled     12m                   kubelet, slave-node  Successfully pulled image "litmuschaos/chaos-operator:1.7.0" in 3.752989184s
  Normal   Pulled     11m                   kubelet, slave-node  Successfully pulled image "litmuschaos/chaos-operator:1.7.0" in 3.913858715s
  Normal   Scheduled  10m                   default-scheduler    Successfully assigned litmus/chaos-operator-ce-6996ddd78d-6ckjb to slave-node
  Normal   Pulled     10m                   kubelet, slave-node  Successfully pulled image "litmuschaos/chaos-operator:1.7.0" in 3.973767981s
  Normal   Started    10m (x4 over 12m)     kubelet, slave-node  Started container chaos-operator
  Normal   Created    10m (x4 over 12m)     kubelet, slave-node  Created container chaos-operator
  Normal   Pulling    9m2s (x5 over 12m)    kubelet, slave-node  Pulling image "litmuschaos/chaos-operator:1.7.0"
  Normal   Pulled     8m58s                 kubelet, slave-node  Successfully pulled image "litmuschaos/chaos-operator:1.7.0" in 3.998879853s
  Warning  BackOff    2m47s (x29 over 11m)  kubelet, slave-node  Back-off restarting failed container
``

**Comment by ksatchit** [comment]
@sakshigupta-29 can you please do a `kubectl describe chaosengine -n <ns>` & also share the logs of the chaos-operator/runner?

**Comment by sakshigupta-29** [comment]
@ksatchit 

`  root@master-node:~# kubectl logs chaos-operator-ce-6996ddd78d-phspf -n litmus
{"level":"info","ts":1600083943.25164,"logger":"cmd","msg":"Go Version: go1.10.3"}
{"level":"info","ts":1600083943.2516992,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1600083943.2517161,"logger":"cmd","msg":"Version of operator-sdk: v0.15.2"}
{"level":"info","ts":1600083943.2517338,"logger":"leader","msg":"Trying to become the leader."}
root@master-node:~# kubectl logs -f chaos-operator-ce-6996ddd78d-phspf -n litmus
{"level":"info","ts":1600083992.0587275,"logger":"cmd","msg":"Go Version: go1.10.3"}
{"level":"info","ts":1600083992.0587652,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1600083992.0587788,"logger":"cmd","msg":"Version of operator-sdk: v0.15.2"}
{"level":"info","ts":1600083992.0587957,"logger":"leader","msg":"Trying to become the leader."}
{"level":"error","ts":1600084022.0599606,"logger":"cmd","msg":"","error":"Get https://10.96.0.1:443/api?timeout=32s: dial tcp 10.96.0.1:443: i/o timeout","stacktrace":"github.com/litmuschaos/chaos-operator/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\tsrc/github.com/litmuschaos/chaos-operator/vendor/github.com/go-logr/zapr/zapr.go:128\nmain.main\n\tsrc/github.com/litmuschaos/chaos-operator/cmd/manager/main.go:65\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:198"} `

**Comment by sakshigupta-29** [comment]
@ksatchit 

` root@master-node:~# kubectl describe chaosengine -n litmus
Name:         nginx-network-chaos
Namespace:    litmus
Labels:       <none>
Annotations:  <none>
API Version:  litmuschaos.io/v1alpha1
Kind:         ChaosEngine
Metadata:
  Creation Timestamp:  2020-09-14T16:25:05Z
  Generation:          1
  Managed Fields:
    API Version:  litmuschaos.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:annotationCheck:
        f:appinfo:
          .:
          f:appkind:
          f:applabel:
          f:appns:
        f:auxiliaryAppInfo:
        f:chaosServiceAccount:
        f:engineState:
        f:experiments:
        f:jobCleanUpPolicy:
        f:monitoring:
    Manager:         kubectl-client-side-apply
    Operation:       Update
    Time:            2020-09-14T16:25:05Z
  Resource Version:  881244
  Self Link:         /apis/litmuschaos.io/v1alpha1/namespaces/litmus/chaosengines/nginx-network-chaos
  UID:               5b081df8-0dbc-4165-8096-879fba633403
Spec:
  Annotation Check:  true
  Appinfo:
    Appkind:              deployment
    Applabel:             app=nginx
    Appns:                default
  Auxiliary App Info:
  Chaos Service Account:  pod-network-loss-sa
  Engine State:           active
  Experiments:
    Name:  pod-network-loss
    Spec:
      Components:
        Env:
          Name:         TARGET_CONTAINER
          Value:        nginx
          Name:         LIB_IMAGE
          Value:        litmuschaos/go-runner:latest
          Name:         NETWORK_INTERFACE
          Value:        eth0
          Name:         NETWORK_PACKET_LOSS_PERCENTAGE
          Value:        100
          Name:         TOTAL_CHAOS_DURATION
          Value:        60
  Job Clean Up Policy:  delete
  Monitoring:           false
Events:                 <none>
`
