### ISSUE TITLE
Unable to install litmus 

### ISSUE THREAD

**Issue by aluwala** [litmuschaos/litmus#2026]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
 kubectl apply -f https://litmuschaos.github.io/litmus/litmus-operator-v1.7.0.yaml

ERROR :
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
Error from server (Forbidden): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"v1\",\"kind\":\"Namespace\",\"metadata\":{\"annotations\":{},\"name\":\"litmus\"}}\n"}}}
to:
Resource: "/v1, Resource=namespaces", GroupVersionKind: "/v1, Kind=Namespace"
Name: "litmus", Namespace: ""
Object: &{map["apiVersion":"v1" "kind":"Namespace" "metadata":map["creationTimestamp":"2020-09-07T10:58:26Z" "labels":map["askid":"***********" "dc":"CTC_NONPROD" "env":"Non-prod" "msid":"*********" "namespace":"litmus" "project":"litmus" "zone":"CORE"] "name":"litmus" "resourceVersion":"192540375" "selfLink":"/api/v1/namespaces/litmus" "uid":"cf691fda-1d99-42f8-a59d-e2b2bb67d30f"] "spec":map["finalizers":["kubernetes"]] "status":map["phase":"Active"]]}
for: "https://litmuschaos.github.io/litmus/litmus-operator-v1.7.0.yaml": namespaces "litmus" is forbidden: User "system:serviceaccount:*XXXX*:*YYYYY*" cannot patch resource "namespaces" in API group "" in the namespace "litmus"
Error from server (Forbidden): error when retrieving current configuration of:
Resource: "/v1, Resource=serviceaccounts", GroupVersionKind: "/v1, Kind=ServiceAccount"
Name: "litmus", Namespace: "litmus"
Object: &{map["apiVersion":"v1" "kind":"ServiceAccount" "metadata":map["annotations":map["kubectl.kubernetes.io/last-applied-configuration":""] "labels":map["name":"litmus"] "name":"litmus" "namespace":"litmus"]]}
from server for: "https://litmuschaos.github.io/litmus/litmus-operator-v1.7.0.yaml": serviceaccounts "litmus" is forbidden: User "system:serviceaccount:*XXXX*:*YYYYY*" cannot get resource "serviceaccounts" in API group "" in the namespace "litmus"
Error from server (Forbidden): error when retrieving current configuration of:
Resource: "rbac.authorization.k8s.io/v1beta1, Resource=clusterroles", GroupVersionKind: "rbac.authorization.k8s.io/v1beta1, Kind=ClusterRole"
Name: "litmus", Namespace: ""
Object: &{map["apiVersion":"rbac.authorization.k8s.io/v1beta1" "kind":"ClusterRole" "metadata":map["annotations":map["kubectl.kubernetes.io/last-applied-configuration":""] "labels":map["name":"litmus"] "name":"litmus"] "rules":[map["apiGroups":["" "apps" "batch" "litmuschaos.io" "apps.openshift.io"] "resources":["pods" "jobs" "deployments" "replicationcontrollers" "daemonsets" "replicasets" "statefulsets" "deploymentconfigs" "events" "configmaps" "services" "secrets" "chaosengines" "chaosexperiments" "chaosresults"] "verbs":["get" "create" "update" "patch" "delete" "list" "watch" "deletecollection"]] map["apiGroups":["admissionregistration.k8s.io"] "resources":["validatingwebhookconfigurations"] "verbs":["get" "create" "list" "delete" "update"]]]]}
from server for: "https://litmuschaos.github.io/litmus/litmus-operator-v1.7.0.yaml": clusterroles.rbac.authorization.k8s.io "litmus" is forbidden: User "system:serviceaccount:**resilency**(namespacename):serviceaccountname" cannot get resource "clusterroles" in API group "rbac.authorization.k8s.io" at the cluster scope
Error from server (Forbidden): error when retrieving current configuration of:
Resource: "rbac.authorization.k8s.io/v1beta1, Resource=clusterrolebindings", GroupVersionKind: "rbac.authorization.k8s.io/v1beta1, Kind=ClusterRoleBinding"

**Comment by xkbarkar** [comment]
Hi 
This looks like a permission issue on your cluster , the service account you are using to patch / install litmus does not have the proper privileges 
`clusterroles.rbac.authorization.k8s.io "litmus" is forbidden: User "system:serviceaccount:resilency(namespacename):serviceaccountname" cannot get resource "clusterroles" in API group "rbac.authorization.k8s.io" at the cluster scope`

**Comment by ksatchit** [comment]
@xkbarkar is right. For the default mode of installation, please ensure you have the right permissions - as suggested by the doc: 

![image](https://user-images.githubusercontent.com/21166217/94770527-707a2280-03d2-11eb-90e5-8aae8fc26277.png)

There is also a namespace-scoped operator you can use: https://docs.litmuschaos.io/docs/namespaced-mode/ in case you are operating in a strictly multi-tenant env. However, in this case you need to install the CRDs separately (which, still is an admin task - though a one-time activity) 

Closing this issue, please feel free to re-open if you feel there are other problems with install.
