### ISSUE TITLE
Facing an issue while Installing litmus. 

### ISSUE THREAD

**Issue by sakshigupta-29** [litmuschaos/litmus#2059]
`Warning: rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
clusterrole.rbac.authorization.k8s.io/litmus created
Warning: rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRoleBinding
clusterrolebinding.rbac.authorization.k8s.io/litmus created
deployment.apps/chaos-operator-ce created
Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition `
``

Above is the output which I face while installing litmus. 
What should be done???

**Comment by uditgaurav** [comment]
@sakshamkatiyar This should not harm as it is a `warning`, not an issue. You must have got this with the latest Kubernetes version `1.19.0`? 
Here is the `good-first-issue` for this (https://github.com/litmuschaos/litmus/issues/1963). Feel free to update the CRs and let us know if you need some help.

**Comment by rahulchheda** [comment]
https://github.com/projectcalico/calico/issues/2695
