### ISSUE TITLE
Create unit tests for the litmus godog framework 

### ISSUE THREAD

**Issue by ksatchit** [litmuschaos/litmus#206]
## Is this a BUG REPORT or FEATURE REQUEST?
FEATURE REQUEST

**What happened**:

- The litmus godog-framework, (source available here: https://github.com/openebs/litmus/tree/master/pkg) needs the unit-tests to be written. 

**What you expected to happen**:

- Create the unit-tests (along with refactoring of the source, where needed) for the litmus go-code.

**Anything else we need to know?**:

- References: Good starting points 
  -  https://blog.alexellis.io/golang-writing-unit-tests/
  -  https://jonathanmh.com/golang-unit-testing-for-absolute-beginners/

**Comment by ksatchit** [comment]
cc: @AmitKumarDas for thoughts & guidance!

**Comment by AmitKumarDas** [comment]
This is a good thought @ksatchit 
It might be good to import packages from `openebs/maya` while refactoring go code.

**Comment by ksatchit** [comment]
Created sub-issues #298 #299 #300 #301 #302 for this

**Comment by ksatchit** [comment]
The go-based executor has been deprecated for now, with plans for the same being developed independently in a separate repo. Closing this issue now. Will be created on the new repo once available.
