### ISSUE TITLE
Chaos Results reports and visualization

### ISSUE THREAD

**Issue by Randhir123** [litmuschaos/litmus#2095]
We plan to run Chaos Experiments that will be triggered either manually or from CD pipeline or using Chaos Scheduler. We would like to collect the Chaos Results whenever we want into a format that is easy to visualize and present to humans.

Please provide ability to generate and see reports in Litmus Portal for all the experiments triggered from Portal or otherwise.

**Comment by ksatchit** [comment]
cc: @ishangupta-ds

**Comment by ishangupta-ds** [comment]
Hi @Randhir123 we have added this feature to generate reports from chaos workflows scheduled via litmus portal. Cc: @ksatchit @ajeshbaby
