### ISSUE TITLE
Improve our documentation by adding explanations and examples

### ISSUE THREAD

**Issue by S-ayanide** [litmuschaos/litmus#2099]
#### SUMMARY

Litmus's current documentation and README could be improved further. If you find something lacking any form of good description about Litmus perhaps consider adding those details.

For Documentation related contribution take a look into this repository [https://github.com/litmuschaos/litmus-docs](https://github.com/litmuschaos/litmus-docs)

> **Suggestion:** To begin with you can contribute to the *getting started with litmus* docs [https://github.com/litmuschaos/litmus-docs/blob/master/docs/getstarted.md](https://github.com/litmuschaos/litmus-docs/blob/master/docs/getstarted.md)

You can choose to improve any README.md file by adding in examples in the form of screenshots or improving on the details.

#### EASY README FILES TO IMPROVE

* Litmus Portal Readme ([https://github.com/litmuschaos/litmus/blob/master/litmus-portal/README.md](https://github.com/litmuschaos/litmus/blob/master/litmus-portal/README.md))
* Litmus Portal Frontend Readme ([https://github.com/litmuschaos/litmus/blob/master/litmus-portal/frontend/README.md](https://github.com/litmuschaos/litmus/blob/master/litmus-portal/frontend/README.md))

#### ISSUE TYPE

* Documentation Improvement

#### CONTACT PERSON

* [Sayan Mondal](https://github.com/S-ayanide)
* [Prithvi Raj](https://github.com/prithvi1307)

Thanks for taking the time to read this issue. In order for Litmus to clarify your doubts effectively, provide us a few hours to reply back.

**Comment by ayushsatyam146** [comment]
I want to work on this issue S-ayanide

**Comment by ayushsatyam146** [comment]
I want to work on this issue @S-ayanide

**Comment by umangj28** [comment]
As I am a complete beginner, I would to start by contributing here.

**Comment by S-ayanide** [comment]
Thanks, @ayushsatyam146 for you PR, however, the change is comparatively minor and just adds a few badges that were present in our main repository. I wouldn't consider this issue resolved yet since we haven't got a contribution in terms of content/examples. Thus we would keep this issue open.

**Comment by S-ayanide** [comment]
@umangj28 I am assigning you with this issue, you can contact any of the *Contact Person* as well as join our slack community for better interaction and guidance if needed.
