### ISSUE TITLE
Replace RC-Progress Line with Material UI Progress Bar

### ISSUE THREAD

**Issue by S-ayanide** [litmuschaos/litmus#2100]
#### SUMMARY

Aiming to decrease the project's bundle size by replacing [RC Progress](https://www.npmjs.com/package/rc-progress) line to [Linear Progress Bar](https://material-ui.com/api/linear-progress/) since Material UI bundle is already present in the dependency list. Customize the MUI Progress Bar to change based on the weightage provided. The look and feel of the progress bar should remain the same and it should vary based on the weight provided.

#### COLOR VARIATION ON THE PROGRESS BAR

* If weight is less than equal to 30 then the color of the progress bar should be `theme.palette.error.dark` or `#CA2C2C`
* If weight is less than equal to 60 then the color of the progress bar should be `theme.palette.warning.main` or `#F6B92B`
* If weight is greater than 60 then the color of the progress bar should be `theme.palette.primary.dark` or `#109B67`

#### COMPONENTS WHICH REQUIRE CHANGE

* AnalyticsLinearProgressBar
* LinearProgressBar

#### ISSUE TYPE

* Code Refactor

#### CONTACT PERSON

* [Sayan Mondal](https://github.com/S-ayanide)

Thanks for taking the time to read this issue. In order for Litmus to clarify your doubts effectively, provide us a few hours to reply back.

**Comment by malakar-soham** [comment]
I could take up this issue @S-ayanide

**Comment by chang90** [comment]
let me have a try

**Comment by bansalsurya** [comment]
I would like to take this issue

**Comment by iamanishagarwal** [comment]
I would like to take this issue.

**Comment by schezfaz** [comment]
Hey, could I work on this issue?

**Comment by S-ayanide** [comment]
Hey guys! Thanks for showing interest in this issue, Although a lot of you requested to take this issue up I can only assign one person since this is a relatively easy issue but still would require a lot of getting into our project. Thus I think it would be better if @bansalsurya could take it up!

**Comment by bansalsurya** [comment]
@S-ayanide Hey do you mean theme.palette.success.dark and not theme.palette.primary.dark? Since the former is green and latter is blue?

**Comment by S-ayanide** [comment]
@bansalsurya No! We don't have a success palette altogether, we use `theme.palette.primary.dark` as the success color. Also it's not `blue` but its `#109B67` which is the color above (dark green)

**Comment by bansalsurya** [comment]
> theme.palette.primary.dark

Oh I visited https://material-ui.com/customization/palette/ and it shows theme.palette.primary.dark as #115293 
I'll make the change from theme.palette.success.dark #388e3c to theme.palette.primary.dark

**Comment by Sonichigo** [comment]
Can i work on this issue?

**Comment by Sonichigo** [comment]
@S-ayanide can i work on this ?

**Comment by S-ayanide** [comment]
@Sonichigo I had already assigned @bansalsurya with this issue, but seems like there are a few logic issues in the PR, although I've requested some changes, could you work on it as well? I will review them both and merge the better one.

Also, please ensure you have signed your commits before sending a PR. Sign all your commits.

**Comment by Jonsy13** [comment]
Closing this issue as Corresponding PR is merged.
