### ISSUE TITLE
Refactor the See More button on HomePage

### ISSUE THREAD

**Issue by amityt** [litmuschaos/litmus#2102]
**SUMMARY**
The See More button is a link that is wrapped inside a button. The button does not work when clicking outside the text. Instead of using the link, the `onCLick` event can be used to redirect to the community page.

**SCREENSHOT**
![Screenshot from 2020-09-22 14-59-12](https://user-images.githubusercontent.com/40661238/93866686-9e31de00-fce5-11ea-832f-c13bb6ceb0e4.png)

**ISSUE TYPE**
- Code Refactor

**CONTACT PERSON**
- [Amit Kumar Das](https://github.com/amityt)

Thanks for taking the time to read this issue. In order for Litmus to clarify your doubts effectively, provide us a few hours to reply back.

**Comment by sanskar-p** [comment]
@amityt,can I send a PR for this?

**Comment by sanskar-p** [comment]
Hi @amityt, I can't seem to find the mentioned button in the website anywhere. I've found the appropriate code but can't find it on the website.

**Comment by amityt** [comment]
Hi @sanskar-p , thanks for choosing this issue. You can find the button here `litmus-portal/frontend/src/pages/HomePage/index.tsx`

**Comment by sanskar-p** [comment]
Yes @amityt, I have made the necessary changes in this line: https://github.com/sanskar-p/litmus/blob/8c3bd228a5405c62fc9221de0e14c68c788b26e9/litmus-portal/frontend/src/pages/HomePage/index.tsx#L193
and I have also sent a PR. Please review and inform me if I have to do any changes. Thanks!

**Comment by SandeepGamot** [comment]
Is this solved?

**Comment by Sonichigo** [comment]
can i work on this issue?

**Comment by amityt** [comment]
Thanks for showing your interest for this issue @SandeepGamot  @Sonichigo  :rocket: :100:   This issue has been solved. There are more good-first-issues that are present that you can take a look into and raise PR for the same.
