### ISSUE TITLE
Improve the username input field of Create New User section(Settings Page)

### ISSUE THREAD

**Issue by Saranya-jena** [litmuschaos/litmus#2103]
**Summary**
Currently, the username field in the "Create New User" section can take any characters including spaces. Validation needs to be added in the username field so that it takes only alphanumeric characters and periods(.), similar to Gmail username validation.

**SCREENSHOT**
![Screenshot from 2020-09-24 00-19-31](https://user-images.githubusercontent.com/28081206/94056645-36ba8200-fdfc-11ea-823d-8a10f37476a4.png)

Reference can be taken from the above screenshot, a similar error message can be displayed if the format is wrong.

**ISSUE TYPE**
Code Refactor

**CONTACT PERSON**
[Saranya Jena](https://github.com/Saranya-jena)

Thanks for taking the time to read this issue. In order for Litmus to clarify your doubts effectively, provide us a few hours to reply back.

**Comment by jabhishek87** [comment]
can i take this ?

**Comment by jabhishek87** [comment]
Started working on this

**Comment by jabhishek87** [comment]
Just to update working on this will commit tomorrow

**Comment by S-ayanide** [comment]
We should also add - and @ username validation. My own username has a **-** in it. @Saranya-jena what do you think about this? Waiting for your approval.

**Comment by jabhishek87** [comment]
done added @ and dot as allowed special chars

**Comment by Sonichigo** [comment]
@jabhishek87 can i take this?

**Comment by jabhishek87** [comment]
@Sonichigo already commit is in place @S-ayanide @uditgaurav can ou Please review
