### ISSUE TITLE
good color combination in the litmus-docs

### ISSUE THREAD

**Issue by ispeakc0de** [litmuschaos/litmus#2117]
Litmus docs [website](https://docs.litmuschaos.io/docs/getstarted/) has only black & white colors. It can be changed to attractive color combinations. 

Note: It is recommended to use 2-3 color only

**Comment by sanskar-p** [comment]
@ispeakc0de what is your opinion on `#001959` for the header/footer and `#BBEEEE` for the code snippets?

**Comment by raiedkhan** [comment]
@ispeakc0de Making header and footer Background to `#303030`, main body background as `#DEDEDE` and Code snippet color as `#0079AD` would sound great. What do you say?

**Comment by ispeakc0de** [comment]
Thanks, @sanskar-p & @raiedkhan for your insights. The main idea is to change the color of the sidebars(you can refer [this](https://docs.openebs.io) ). You can also change the footer, header, code snippet as well if you find them more attractive.

**Comment by raiedkhan** [comment]
Ok according to the demand, changing the background color of the body and sidebar to `#23232a` and color to `#ffffff`, change the link color to `#D0D3D4` and color of active and hover links as `#B9770E`, change the blockquote background to `#ECF0F1` and it's left border color to `#626567` and Code snippet color to `#0079AD` would look great.
The above changes when encorporated, would look as such :
<img width="943" alt="newchanges" src="https://user-images.githubusercontent.com/42418263/94595719-d1a5d700-02a8-11eb-9815-f4c1523566ae.png">

**Comment by ispeakc0de** [comment]
Looks good @raiedkhan. It is more of a dark mode. You can raise a separate PR for this. One for a dark mode similar to the ^^ above screenshot. Another for the normal mode (white & blue) color would be good.

You can take a reference from this: https://docs.docker.com/get-docker/ It would be very useful if you will update the documentation in a similar way.

**Comment by raiedkhan** [comment]
Ok @ispeakc0de , will surely get back with PR once I am all done.😊

**Comment by adarsh-k-tiwari** [comment]
@ispeakc0de I would like to give it a try. Is this available?

**Comment by raiedkhan** [comment]
OK @ispeakc0de , I have made some changes:
- [x] Make dark theme of current docs.
- [ ] Make a switch theme button

I have raised a separate PR in litmus-docs #367, please review the changes

**Comment by raiedkhan** [comment]
@ispeakc0de , please review the PR in Litmus Docs.

**Comment by raiedkhan** [comment]
@ispeakc0de Please check https://github.com/litmuschaos/litmus-docs/pull/374

**Comment by ispeakc0de** [comment]
Thanks for the PR @raiedkhan. Can you please make the changes in the master branch so that I can view the changes via netlify link? 

I saw you closed multiple PRs. Please raise the PR only if you are sure about changes. You can try to modify the same PR instead of raising new PRs.

**Comment by raiedkhan** [comment]
@ispeakc0de sorry for the inconvenience caused, earlier I updated changes to the master branch only, but there were some issues which I wasn't able to solve, so I did go for a staging branch, I have updated the changes to master branch, but still the error persists . You can view here https://github.com/litmuschaos/litmus-docs/pull/375

**Comment by Abhinandan-Purkait** [comment]
> Thanks for the PR @raiedkhan. Can you please make the changes in the master branch so that I can view the changes via netlify link?
> 
> I saw you closed multiple PRs. Please raise the PR only if you are sure about changes. You can try to modify the same PR instead of raising new PRs.

@ispeakc0de There was some issue with the CI, the build were failing and on rebase improper singed-off commits were pulled in this branch. He would supposedly redo this. PTAL

**Comment by divya-mohan0209** [comment]
@ispeakc0de @ksatchit @k8s-dev : I would like to weigh upon this in tomorrow's meeting. Docusaurus v2 seems to have Dark Mode support with minimal changes to the css. If we're planning to migrate to v2, dark mode shouldn't be something we're targetting on a PR.

**Comment by raiedkhan** [comment]
> @ispeakc0de @ksatchit @k8s-dev : I would like to weigh upon this in tomorrow's meeting. Docusaurus v2 seems to have Dark Mode support with minimal changes to the css. If we're planning to migrate to v2, dark mode shouldn't be something we're targetting on a PR.

That's really a good idea @divya-mohan0209 , but Docuhaurus v2 is in alpha release so I think Mayadata might not prefer it.
Still, it's a good to go option😊.

**Comment by Sonichigo** [comment]
can i take this?

**Comment by ksatchit** [comment]
Yes, we have begun beta trials with Docusaurus v2 and might go ahead with it as part of Litmus 2.0 efforts. 

Thanks for the contribution @raiedkhan , though we don't take this PR, we would love to work with you in the future.

**Comment by Othniel-dell** [comment]
Thank you too
