### ISSUE TITLE
Architectural/Activity Diagram of litmus-go repository

### ISSUE THREAD

**Issue by ispeakc0de** [litmuschaos/litmus#2118]
- Architectural/Activity diagram of the litmus-go repository which can cover/explain all the components of `litmus-go` repository and their connections. It can be used inside README.md. As Diagram can summarise things better.

**Comment by malakar-soham** [comment]
I could take up this issue

**Comment by malakar-soham** [comment]
I'm a bit confused from where to start. Could you please guide me a bit?
