### ISSUE TITLE
Validate litmus experiment for a larger set of platforms available

### ISSUE THREAD

**Issue by uditgaurav** [litmuschaos/litmus#2124]
## Details:

- We try to support the chaos experiments (which are not so much of platform-dependent) in as many platforms as we can for which we test the experiments and mention the initial set of the tested platform in [charts CSV](https://github.com/litmuschaos/chaos-charts/blob/39e7cbd19f191b9396fcfeae4d3dd6827589810f/charts/generic/node-drain/node-drain.chartserviceversion.yaml#L20). It will be great to test these experiments and add more numbers of platfom on which the experiment is validated. This will help in increasing the stability of the experiments across the platforms.

### Steps:

- Perform the experiments in a new platform that is not mentioned in the CSV already.
- Once the experiment is passed for all test scenarios raise a PR in [chaos-charts](https://github.com/litmuschaos/chaos-charts) repo
- Along with the PR don't forget to add the describe of chaos result and chaos engine. 
  - `kubectl describe chaosengine <engine-name> -n <namespace>`
  - `kubectl describe chaosresult <chaosresult-name> -n  <namespace>`

And That's all!

Even if the experiment doesn't work in any of the platforms feel free to comment here or create an issue for further discussion. 
Refer [Get Started Docs](https://docs.litmuschaos.io/docs/getstarted/) to know how to run an experiment.

**Comment by ari-hacks** [comment]
Hey @uditgaurav, I'd like to try this out 🙂

**Comment by uditgaurav** [comment]
Thanks, @ari-hacks. You can start working on this. Let me know if you need some help :)

**Comment by ari-hacks** [comment]
Hey @uditgaurav, I have a few questions:

1. When you say **perform the experiments in a new platform that is not mentioned in the CSV** already should that list include the platforms already listed in the [charts directory](https://github.com/litmuschaos/chaos-charts/tree/master/charts)?
2. For the PR submission should this include updates to the [charts directory](https://github.com/litmuschaos/chaos-charts/tree/master/charts) or just an update to the platform list in each generic experiment like the [one listed above](https://github.com/litmuschaos/chaos-charts/blob/39e7cbd19f191b9396fcfeae4d3dd6827589810f/charts/generic/node-drain/node-drain.chartserviceversion.yaml#L20)?
3. Should the describe outputs go directly in the PR description?

**Comment by uditgaurav** [comment]
@ari-hacks 
- There is an `<experiment-name>.chartserviceversion.yaml` file for every experiment which contains the list of platforms like [this](https://github.com/litmuschaos/chaos-charts/blob/39e7cbd19f191b9396fcfeae4d3dd6827589810f/charts/generic/node-drain/node-drain.chartserviceversion.yaml#L20) we need to test the experiment for the platform which is **NOT** listed there. Once we confirm that the experiment supports that platform raise a PR to add it to the list. (this answers Q2. as well that is it should include updating the platform list in each dir, not the dir itself).

- Describe output can go into the PR Comment :)

**Comment by csor-dev** [comment]
I see that major cloud providers are listed already.
Does any of these come under platforms which should be tested:
- kind
- minikube
- openshift
- k3s
- microk8s
- rancher

**Comment by ari-hacks** [comment]
Hey @csor-dev, I plan to test with a couple of these this week. Some have already been validated with minikube.

**Comment by csor-dev** [comment]
cool @ari-hacks , let me know which ones you're testing on so that i can try others

**Comment by ari-hacks** [comment]
hey @csor-dev, I'm testing with kind, openshift, and rancher

**Comment by ari-hacks** [comment]
Hey, @uditgaurav should each experiment have its own PR? Or should I include each `describe` result for all experiments that pertain to a specific platform in one PR?

**Comment by uditgaurav** [comment]
Thanks, @ari-hacks Can you update the PR with all the platforms on which you have tested like openshift and rancher.

**Comment by ari-hacks** [comment]
@uditgaurav yea will do! Does the PR require a name and email sign off to merge?

**Comment by ari-hacks** [comment]
Hey @uditgaurav, can this ticket stay open? I'd like to run some more tests on platforms with HA clusters.

**Comment by uditgaurav** [comment]
Thanks, @ari-hacks for the PR. Feel free to open a new issue for testing and adding more platform support in litmus.
