### ISSUE TITLE
Include K8s manifest validation check in litmus travis CI

### ISSUE THREAD

**Issue by ksatchit** [litmuschaos/litmus#213]
## Is this a BUG REPORT or FEATURE REQUEST?
FEATURE REQUEST

**What happened**:

- Litmus consists of several types of kubernetes manifests (deployments, pods, statefulsets, jobs) as part of the test framework. Currently, there is no K8s yaml validation performed as part of the CI

**What you expected to happen**:

- Include static checks for K8s YAMLs 

**How to fix it**:

- There are native/kubectl flags that achieve this to certain extent with (`--validate` & `--dry-run`). Also,
there are tools available for the same (refer: https://github.com/garethr/kubeval & https://github.com/garethr/kubernetes-json-schema) 

**Anything else we need to know?**:

- The approach would be to identify K8s YAMLs in the repo & subject them to these checks. The script that does this needs to be invoked as part of the Travis CI (makefile addition)

**Comment by ksatchit** [comment]
cc: @kmova @AmitKumarDas for guidance !

**Comment by AmitKumarDas** [comment]
Can Litmus validate the specs/yamls as part of a test scenario execution process?

**Comment by mathagician** [comment]
@ksatchit I would like to work on this issue.

**Comment by ajeshbaby** [comment]
Closing the old issues.

**Comment by ksatchit** [comment]
Helm lint is being used for the experiment CR and deployment manifests in litmus-helm repo
