### ISSUE TITLE
Enable option to chose executor before setting up argo | Litmus Portal

### ISSUE THREAD

**Issue by hmsvigle** [litmuschaos/litmus#2130]
Hi Team,

Through Litmus-Portal, while triggering any experiment, argo availability check is performed & deployed in case of unavailability. 

Before deploying argo-components, if we could enable option to chose type of **Executor** (docker/k8sapi), that would be helpful. 

Thanks

**Comment by ksatchit** [comment]
This has been moved to k8sAPI by default in order to work with different run times and avoid host mounts
