### ISSUE TITLE
Litmus Portal : Add sort feature to the columns of the table(Settings section)

### ISSUE THREAD

**Issue by Saranya-jena** [litmuschaos/litmus#2132]
Sort functionality can be added to the following tables:
-  "Name"  and "Username" columns in the User management tab.

![Screenshot from 2020-09-30 10-05-10](https://user-images.githubusercontent.com/28081206/94700331-f3f72d80-0358-11eb-81bf-e625a573b716.png)

-  "Name", "Role" and "joined to team"  columns in the Team tab.

![Screenshot from 2020-09-30 20-03-56](https://user-images.githubusercontent.com/28081206/94700375-03767680-0359-11eb-8034-fb2486e28ed7.png)

 Users should be able to click on the sort button in the header and details will be displayed in a sorted manner. Reference can be taken from the browse workflows section.

**ISSUE TYPE**
Feature addition

**CONTACT PERSON**
[Saranya Jena](https://github.com/Saranya-jena)

Thanks for taking the time to read this issue. In order for Litmus to clarify your doubts effectively, provide us a few hours to reply back.

**Comment by imrishabh18** [comment]
Hey @Saranya-jena

I would like to take up this issue. Would be helpful if you can give me some directions on resolving this issue.

**Comment by Saranya-jena** [comment]
Hi @imrishabh18 !
You can take a reference from the Browse workflow section, similar implementation is done there. Here is the link: https://github.com/litmuschaos/litmus/blob/master/litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/index.tsx

It might be helpful, let me know if you face any problem.

**Comment by rajdas98** [comment]
@Saranya-jena Is this feature added to litmus portal?
