### ISSUE TITLE
Hitting Enter key does not work in the Welcome Modal.

### ISSUE THREAD

**Issue by A4k9** [litmuschaos/litmus#2133]
**What happened**:
As visible in the below screenshot, upon entering the details in the welcome modal, hitting the enter key does not work and a user has to manually click on the "Continue" Button to submit the details and move to the next screen.

![Screenshot from 2020-09-30 20-37-49](https://user-images.githubusercontent.com/40641427/94704408-813c8100-035d-11eb-91f1-386bffd99405.png)

**What you expected to happen**:

Ideally, After the user has filled the information, they should be able to hit the enter key and move on to the next screen.

**How to reproduce it (as minimally and precisely as possible)**:

Launch the portal and login as a first time user or create a new user in the Setting/User Management/ section to access the welcome modal component.

**Comment by kala2** [comment]
Hello, is this available?

**Comment by JitendraDhakar** [comment]
Help wanted

**Comment by kala2** [comment]
> Hello, is this available?

Could you assign it to me please?

**Comment by Cryptonex7** [comment]
Hello I would Like to contribute to this issue. @A4k9

**Comment by kala2** [comment]
@A4k9 Submitted PR fixing also the last stepper enter key issue see #2163

**Comment by Cryptonex7** [comment]
#2170
