### ISSUE TITLE
Add pod affected percentage test for pod level chaos in litmus e2e

### ISSUE THREAD

**Issue by uditgaurav** [litmuschaos/litmus#2134]
## Details:

_Test - pod affected percentage_ 

- Litmus recently introduced a feature to run the pod level chaos parallelly that is running chaos on multiple app replicas at a time. So we need a proper test case for this feature in our e2e pipeline. The test could be similar to the [pod delete](https://github.com/litmuschaos/litmus-e2e/blob/generic/tests/pod-delete_test.go) test, the only change would be it should test it for multiple [chaos candidate](https://github.com/litmuschaos/chaos-charts/blob/d045169ac87e32098c20af4d98821a3b0277f4c4/charts/generic/pod-delete/experiment.yaml#L58).

- The test case could be something like - Running an experiment say pod delete should execute successfully for multiple pods with [PODS_AFFECTED_PERC](https://github.com/litmuschaos/chaos-charts/blob/d045169ac87e32098c20af4d98821a3b0277f4c4/charts/generic/pod-delete/experiment.yaml#L58) not nil.

### Language
- Go Test

### Steps:

You may need to follow the following steps to add a test:

- Fork [litmus-e2e](https://github.com/litmuschaos/litmus-e2e/tree/generic) repo and clone it. Use the generic branch for writing a new test. 
  - Eg. `git clone https://github.com/litmuschaos/litmus-e2e.git -b generic`

  - Write your go test like pod-delete test under `tests` dir.

- Once the experiment is passed for the test scenario raise a PR in litmus-e2e

- Along with the PR don't forget to add the test logs. 
  - _output of_ `go test <test-name>_test.go -v `

For any doubt/confusion feel free to comment on the issue we are here for the help.

**Comment by imrishabh18** [comment]
@uditgaurav I would like to take up this issue.

**Comment by uditgaurav** [comment]
Thanks, @imrishabh18. Let me know if you need any help! :)

**Comment by uditgaurav** [comment]
The test has been added in [litmus-e2e](https://github.com/litmuschaos/litmus-e2e/) and in GitHub Actions CI in Litmus GO repo using this PR https://github.com/litmuschaos/litmus-e2e/pull/235 and  https://github.com/litmuschaos/litmus-go/pull/282.Closing it.
