### ISSUE TITLE
Step-bar not responding on click

### ISSUE THREAD

**Issue by SarthakJain26** [litmuschaos/litmus#2141]
**What happened**:
The stepbar in welcome modals does not respond to clicks.

![Screenshot from 2020-10-01 11-41-32](https://user-images.githubusercontent.com/45846277/94774662-fe0e4000-03db-11eb-90de-d4936aec34c9.png)

**What you expected to happen**:
A user should be able to navigate through the modals using the stepbar and only those modals should be accessible that are previously visited atleast once. 

**How to reproduce it (as minimally and precisely as possible)**:
Launch the portal and login as a first time user or create a new user in the Setting/User Management/ section to access the welcome modal component.

**Comment by khushijindal** [comment]
Can I work on this issue ? @SarthakJain26

**Comment by ShubhamSood1406** [comment]
@SarthakJain26 Can I contribute to this issue?

**Comment by ShubhamSood1406** [comment]
@SarthakJain26 Do you want to make modal respond by clicking the bottom Stepbar?

**Comment by SarthakJain26** [comment]
> @SarthakJain26 Do you want to make modal respond by clicking the bottom Stepbar? And can you in which file this Modal is in.

The user should be able to switch between welcome modals by clicking on the stepbar.
* Only those modals should be accessible that are previously visited at least once.

**Comment by ShubhamSood1406** [comment]
@SarthakJain26 Can you tell in which file the modal is present?

**Comment by SarthakJain26** [comment]
litmus-portal/frontend/src/components/WelcomeModal/Stepper.tsx

**Comment by SarthakJain26** [comment]
change the working directory to frontend and then try to run the commands

**Comment by SarthakJain26** [comment]
Try this:
https://stackoverflow.com/questions/47928735/react-scripts-is-not-recognized-as-an-internal-or-external-command
