### ISSUE TITLE
[Readme]: Add general readme for chaos-observability repository

### ISSUE THREAD

**Issue by ispeakc0de** [litmuschaos/litmus#2142]
- Add general readme for [chaos-observability](https://github.com/litmuschaos/chaos-observability) repository. 
- Added some keypoints [here](https://docs.google.com/document/d/1yzETBZIb99F9rlw-N7UciSXmzHqltEgodQpcLD1FaeI/edit). You can take a reference for this while writing Readme.

**Comment by i-Pix** [comment]
Can you assign me this issue?

**Comment by Badkul77** [comment]
Please Assign it to me , i have a optimal solution

**Comment by frbio** [comment]
Hey, If you brief the details, I can work on this? You can assign it to me.

**Comment by jabhishek87** [comment]
No proper Information , Read me is already there what you want to add ?

**Comment by ispeakc0de** [comment]
updated the description! You can raise the PR [here](https://github.com/litmuschaos/chaos-observability).

**Comment by manpreetrathore** [comment]
I would like to take up this issue. Could you please assign it to me.

**Comment by RanadeepPolavarapu** [comment]
I can work this.

**Comment by prithvi1307** [comment]
@shaonkabir8 Please go ahead!

**Comment by shaonkabir8** [comment]
Sure. Thanks mate 😍

**Comment by shaonkabir8** [comment]
> @shaonkabir8 Please go ahead!

Hi :wave:
Would you please check this [PR](https://github.com/litmuschaos/chaos-observability/pull/21) ? 

Feel free to ping me anytime even for changing a single word, I'll be there :raised_hand_with_fingers_splayed: 

Thanks mate :heart:

**Comment by ksatchit** [comment]
This PR has been accepted (albeit very late)! @prithvi1307 please consider for hacktoberfest !
