### ISSUE TITLE
Make the annotation check as optional, if applabel is empty

### ISSUE THREAD

**Issue by ispeakc0de** [litmuschaos/litmus#2144]
- If the `.spec.appinfo` is empty (not provided inside the chaosengine) then ensure that the annotation checks won't be executed even if the `spec.annotationCheck` is true

**Comment by sccalabr** [comment]
Id like to give this a try. Where in the code would this be done at?

**Comment by ispeakc0de** [comment]
Thanks, @sccalabr for showing your interest. You can find the code [here](https://github.com/litmuschaos/chaos-operator/blob/master/pkg/controller/chaosengine/chaosengine_controller.go)

**Comment by sccalabr** [comment]
Can you have an AppInfo that is an Empty String or nil? Or one without an AppLabel? It looks to me like all the checks are done on the app label and not the app info. I'll post a pr, it might be easier to understand if you see what I am thinking.

**Comment by ispeakc0de** [comment]
Hi @sccalabr ,

If annotationCheck is true and appinfo is not provided inside chaosengine then the operator will error it out as appinfo is mandatory if the annotationCheck is provided as true.

But for the cases where annotationCheck field is not provided inside chaosengine then the operator is considering it as true by default(https://github.com/litmuschaos/chaos-operator/blob/master/pkg/controller/resource/resource.go#L31). We need to make this value to false. Because if no annotationCheck is provided inside engine then we can't mandate the appinfo.

**Comment by Nageshbansal** [comment]
cc @imrajdas @gdsoumya

**Comment by ispeakc0de** [comment]
We no longer support annotation checks
