### ISSUE TITLE
Litmus Go: Enhance pod-autoscaler experiment by adding abort chaos

### ISSUE THREAD

**Issue by uditgaurav** [litmuschaos/litmus#2145]
## Details 

- The pod autoscaler chaos experiment today does not support the abort chaos we need to add the abort functionality in for this experiment.

The abort chaos is supported by almost all other go experiments. We need to have the abort support for this.

**Comment by adhaamehab** [comment]
Hey @uditgaurav I made a PR for this :)

**Comment by uditgaurav** [comment]
Thanks for the PR @adhaamehab! We will review it soon :)

**Comment by uditgaurav** [comment]
fixed with https://github.com/litmuschaos/litmus-go/pull/185
