### ISSUE TITLE
Litmus Go: Enhance pod-autoscaler experiment by adding support for sts and ds along with deployments

### ISSUE THREAD

**Issue by uditgaurav** [litmuschaos/litmus#2146]
## Details:

- Enhance pod-autoscaler experiment by adding support for sts, ds currently it only supports deployment kind of application.

The details of the experiments can be found [here](https://docs.litmuschaos.io/docs/pod-autoscaler/) and the source code [here](https://github.com/litmuschaos/litmus-go/tree/master/experiments/generic/pod-autoscaler).

**Comment by fillerInk** [comment]
Is this issue about improving the documentation [here](https://docs.litmuschaos.io/docs/pod-autoscaler/)?

**Comment by uditgaurav** [comment]
It is a feature enhancement for pod autoscaler experiment. Currently, it
scales deployment kind of application only. We need to add the support of
StatefulSet and DaemonSet as well. The changes will be mostly [here](
https://github.com/litmuschaos/litmus-go/blob/1492379fe24f247929656f6223ae59051a183178/chaoslib/litmus/pod-autoscaler/lib/pod-autoscaler.go#L74)
once this feature is added we can update the docs as well.

**Comment by SrishtyC13** [comment]
can you @uditgaurav help me in solving this issue,?

**Comment by uditgaurav** [comment]
Yed sure @SrishtyC13 feel free to start with this.

**Comment by uditgaurav** [comment]
Fixed by https://github.com/litmuschaos/litmus-go/pull/187
