### ISSUE TITLE
Ability to run serial/parallel run in pod level chaos, tuned by an ENV

### ISSUE THREAD

**Issue by ispeakc0de** [litmuschaos/litmus#2147]
- Add an ability to run serial/parallel run in pod level chaos, tuned by an ENV called `SEQUENCE`. 
- It will execute the chaos in serial mode if `SEQUENCE` is set to `serial` otherwise it will run the chaos in the parallel mode, provided that the target pods are more than one.

**Comment by daniel-shuy** [comment]
Doesn't a pod level chaos target only a single pod?

**Comment by ispeakc0de** [comment]
fixed by #litmuschaos/litmus-go#167
