### ISSUE TITLE
Litmus Go: Add support for non root user in Dockerfile of litmus-go

### ISSUE THREAD

**Issue by uditgaurav** [litmuschaos/litmus#2148]
## Details

- Add support for non root user in litmus-go. Currently, the `litmuschaos/go-runner` image runs as root. This is to add the support for a non root user in this image. Once we change the user to non root. We need to perform certain tests by running some experiments:
- network experiments (pod network loss/latency/corruption/duplication)
- resource chaos(node-cpu/memory and pod-cpu/memory)

And check if the chaos is actually inducing.

The [Dockerfile](https://github.com/litmuschaos/litmus-go/blob/master/build/litmus-go/Dockerfile) for `litmuschaos/go-runner` image can be found in the [litmus-go](https://github.com/litmuschaos/litmus-go) repo.

**Comment by divyavit** [comment]
Hi, I am up for this task. Please let me know if I can begin

**Comment by uditgaurav** [comment]
Thanks, @divyavit. You can start working on this. Feel free to comment in
case you need any help :)
repo - https://github.com/litmuschaos/litmus-go
Once you make the user non root please verify that some experiments like
pod-network-loss and node-cpu-hog are working fine with the non root user.

**Comment by divyavit** [comment]
Okay sure

**Comment by uditgaurav** [comment]
The litmus go-runner image has become a non-root image in this PR https://github.com/litmuschaos/litmus-go/pull/266
