### ISSUE TITLE
Litmus demo: Add support for EKS platform in litmus-demo 

### ISSUE THREAD

**Issue by uditgaurav** [litmuschaos/litmus#2151]
## Details

- Litmus demo is a complete demo experience of a chaos experiment in a system. If we don't have a cluster it can deploy a KinD (Kubernetes in Docker) cluster and perform the experiments. Additionally it supports GKE but not the EKS cluster. We should have the support for the EKS cluster as well.

**Comment by kashish2909** [comment]
What additional things are required to support eks cluster?

**Comment by pranavbaitule** [comment]
Can you assign this to me? I have a working version. Thanks.

**Comment by uditgaurav** [comment]
Hey guys, this is about updating the `manage.py` python script in the repo - (https://github.com/litmuschaos/litmus-demo). 
If you'll go through the script you can see that it supports GKE and KinD. You can refer GKE, we have to add the support for AWS, in the same way, please let me know if you're interested!

**Comment by pranavbaitule** [comment]
Please see PR #9 in (https://github.com/litmuschaos/litmus-demo)

**Comment by uditgaurav** [comment]
Thanks, @pranavbaitule for the PR. We will review it soon :)

**Comment by uditgaurav** [comment]
The issue is resolved with https://github.com/litmuschaos/litmus-demo/pull/9!
