### ISSUE TITLE
Litmus docs: Add gif for installing litmus in docs

### ISSUE THREAD

**Issue by uditgaurav** [litmuschaos/litmus#2154]
## Details 

- Litmus installation is a very simple and easy task. We can install litmus by just applying a YAML manifest and we mention this is our [get started](https://github.com/litmuschaos/litmus-docs/blob/master/docs/getstarted.md) page of litmus docs. To make even simpler for a new user we can create a gif of this process which will include installation steps and showing the list of resources that are created as part of the installation.

The target repo for this is [litmus-docs](https://github.com/litmuschaos/litmus-docs).

**Comment by wassimbj** [comment]
i'll do it !

**Comment by panos** [comment]
Hey, I'm interested in taking this;
- Should the GIF be compressed before I push a PR?
- Am I only expected to run the command `kubectl apply -f https://litmuschaos.github.io/litmus/litmus-operator-v1.8.2.yaml`? (If not, should I also add `kubectl get pods -n litmus` to the batch, or is there something more that needs to be done?)

Thanks!

**Comment by uditgaurav** [comment]
Thanks, @panos. It will be good if you show the GIF in the comment here if possible!  otherwise, you can directly raise a PR and we can review it from there only. GIF should contain.
- `kubectl apply -f https://litmuschaos.github.io/litmus/litmus-operator-v1.8.2.yaml`
- `kubectl get ns` (and show that litmus ns comes up)
- `kubectl get crds | grep litmus` (and show that the crds are created)
- `kubectl get pods -n litmus` (and show that the operator pod comes up)

**Comment by panos** [comment]
Any color scheme-related or length preferences?

**Comment by uditgaurav** [comment]
@panos For size, it should not be too much large (equivalent to a paragraph of some 6-7lines in [docs](https://docs.litmuschaos.io/docs/getstarted/#install-litmus)) and the color should be neat & clean in visibility, something which suites in [docs](https://docs.litmuschaos.io/docs/getstarted/#install-litmus). I like [this one](https://github.com/litmuschaos/litmus/issues/2117#issuecomment-700538606) but feel free to pick a better one if possible.

**Comment by panos** [comment]
Just to confirm before recording (for quality reasons), is this alright, visually speaking?

![image](https://user-images.githubusercontent.com/30193966/94988677-92081500-055e-11eb-87ca-066b3e964c9a.png)

![image](https://user-images.githubusercontent.com/30193966/94988679-9af8e680-055e-11eb-8c4e-aabf5234226d.png)

**Comment by panos** [comment]
CC: @uditgaurav

**Comment by uditgaurav** [comment]
It looks good @panos 👍🏻

**Comment by uditgaurav** [comment]
The litmus docs are now migrating to docusaurus-2 and the gif changes can be added to the newer version. Closing it now. Feel free to reopen it whenever you want to work on it @panos. Thanks!
