### ISSUE TITLE
[BDD]: Add test for targetPod and applicationNode

### ISSUE THREAD

**Issue by ispeakc0de** [litmuschaos/litmus#2155]
- Addition of BDD test in the litmus-e2e for the following use cases:
    - when `TARGET_POD` is defined on which we have to inject the chaos - applicable for pod-level chaos.
    - when `APP_NODE` is defined on which we have to inject the chaos - applicable for node-level chaos

**Comment by uditgaurav** [comment]
Fixed with https://github.com/litmuschaos/litmus-e2e/pull/199. For some pod level experiment, it is done along with the validation step only where we choose the target pod/node for testing the experiment.
