### ISSUE TITLE
Litmus E2E: Auxiliary app test in litmus-e2e

### ISSUE THREAD

**Issue by uditgaurav** [litmuschaos/litmus#2156]
## Details

- Litmus E2E has a number of chaos component tests like `annotationCheck`, `engineState`, and other tests. We can also add an auxiliary app info test which includes the addition of auxiliary app as part of node level chaos and the experiment will check for the status of auxiliary apps after chaos completion. We just need to check is the experiment runs fine along with the provided auxiliary app info.

### Language
- Go Test

_Key points:_

- We can add the test in [litmus-e2e]()https://github.com/litmuschaos/litmus-e2e repo under generic branch. Just fork the repo and clone it and switch to generic branch for writing this test. Eg: `git clone https://github.com/litmuschaos/litmus-e2e.git -b generic`.

- Start writing the test under [tests](https://github.com/litmuschaos/litmus-e2e/tree/generic/tests) dir. You can refer [pod-delete](https://github.com/litmuschaos/litmus-e2e/blob/generic/tests/pod-delete_test.go) test. The only change will be in the step of creating the chaosengine, we need to provide the auxiliary app info value here.

_Once the test has been created:_ 

- Raise a PR in [litmus-e2e](https://github.com/litmuschaos/litmus-e2e) on generic branch. And don't forget to add the logs of `go test <test-name>_test.go -v`.
 
Litmus E2E website - https://litmuschaos.github.io/litmus-e2e/

**Comment by MexsonFernandes** [comment]
Can I try this to solve this issue? it would be great to learn something out of it. @uditgaurav

**Comment by uditgaurav** [comment]
Thanks, @MexsonFernandes for showing your interest! please let me know if you need any help! :)

**Comment by MexsonFernandes** [comment]
@uditgauravi any medium to have better communication?

**Comment by uditgaurav** [comment]
@MexsonFernandes you can join our [slack community](https://kubernetes.slack.com/archives/CNXNB0ZTN) if not already joined!

**Comment by MexsonFernandes** [comment]
@uditgaurav how to get the invite link? email -> robomex2020[at]gmail[dot]com

**Comment by Nageshbansal** [comment]
@uditgaurav , can i take this issue?

**Comment by jignyasamishra** [comment]
Hello @uditgaurav I went through the mentioned links also through the pod_delete_test file . Just wanted little more context on auxiliary app info test on what exactly we are running the tests on , some more hints on how to approach this issue . Thank you!

**Comment by uditgaurav** [comment]
The auxiliary app test was initially introduced to perform health checks on dependent components. However, we now have the concept of probes, which offer a better and more customizable way to perform these checks. Therefore, we plan to deprecate the auxiliary app check in the future. With this in mind, I am closing this issue.
