### ISSUE TITLE
Litmus Go: Add support to use go-runner(exp image) as kubelet kill helper image  (in place of pulling a seperate image) 

### ISSUE THREAD

**Issue by uditgaurav** [litmuschaos/litmus#2158]
## Details: 

- Kubelet kill experiment pulls `ubuntu:16.04` image as part of the helper image. This can be done with the go-runner image only we may not need to pull a different image for this as go-ruuner image has a base image of `ubuntu:bionic. We need to have systemd installed for running kubelet kill experiment

_Some Key Points:_

- The [Dockerfile](https://github.com/litmuschaos/litmus-go/blob/master/Dockerfile) for go runner experiment image is in litmuschaos/litmus-go repo.

- The kubelet kill experiment is [here](https://github.com/litmuschaos/litmus-go/tree/master/experiments/generic/kubelet-service-kill) in litmus-go which uses [chaoslib](https://github.com/litmuschaos/litmus-go/tree/master/chaoslib/litmus/kubelet-service-kill/lib) to create helper pod.

- We need to make the experiment working for the go-runner [helper image](https://github.com/litmuschaos/litmus-go/blob/1492379fe24f247929656f6223ae59051a183178/chaoslib/litmus/kubelet-service-kill/lib/kubelet-service-kill.go#L146).

_Once it is resolved:_

- Raise a PR in [litmus-go](https://github.com/litmuschaos/litmus-go) repository and don't forget to add the logs of the chaos pod and helper pod. For any help feel free to comment here.

**Comment by avats-dev** [comment]
@uditgaurav I want to contribute, I know a little bit docker. Can you guide me a bit in implementing this? Thanks.

**Comment by uditgaurav** [comment]
sure @avats-dev feel free to try on this.
You can also join our slack community to know more about chaos engineering and litmus:

To join our slack please follow the following steps!
Step 1: Join the Kubernetes slack using the following link: https://slack.k8s.io/
Step 2: Join the #litmus channel on the Kubernetes slack or use this link after joining the Kubernetes slack: https://slack.litmuschaos.io/

**Comment by jabhishek87** [comment]
i wanted to work can you assign it to me

**Comment by jabhishek87** [comment]
any guide to set up litmus on okteto?

**Comment by uditgaurav** [comment]
Please feel free to take this @jabhishek87  Oketo guide is [here](https://dev.to/ksatchit/litmus-sdk-devtest-your-chaos-experiments-with-okteto-4dkj).

**Comment by uditgaurav** [comment]
The go-runner requires systemd capabilities, which will increase its size. To address this, we can maintain a Ubuntu image in litmuschaos with reduced vulnerabilities by conducting a thorough scan.
