### ISSUE TITLE
Litmus Ansible: Add support for docker service kill experiment for more number of platforms than GKE alone.

### ISSUE THREAD

**Issue by uditgaurav** [litmuschaos/litmus#2160]
## Details

- The docker service kill experiment is in [litmus ansible repo](https://github.com/litmuschaos/litmus-ansible/tree/master/experiments/generic/docker_service_kill) which supports only `GKE` platform as of now, we need to increase the support for multiple platforms.

**Comment by pipaliyajaydip** [comment]
Yes, above The docker service kill experiment in which supports only one platform but my choice increase lots of places and platform
