### ISSUE TITLE
Add a Unit Test for litmus ansible plugin actionable.py

### ISSUE THREAD

**Issue by dargasudarshan** [litmuschaos/litmus#217]
FEATURE REQUEST

What happened:

The litmus ansible plugin actionable.py needs the unit-tests to be written. (https://github.com/litmuschaos/litmus/blob/master/tools/plugins/actionable.py)

What you expected to happen:

Create the unit-tests (along with refactoring of the source, where needed) for the litmus.

Anything else we need to know?:

References :
https://stackoverflow.com/questions/652292/what-is-unit-testing-and-how-do-you-do-it
http://pythontesting.net/framework/unittest/unittest-introduction/

**Comment by Skchoudhary** [comment]
Hi @dargasudarshan , I would like to work on this issue.

**Comment by princerachit** [comment]
@Skchoudhary you can work on this issue. In case of any query reach us at our slack channel.

**Comment by Skchoudhary** [comment]
@dargasudarshan  @princerachit  I have created a Test class structure in this [commit](https://github.com/Skchoudhary/litmus/commit/07edced1594fecdea2177c6bd90766be31b330aa). Just want a confirmation that I am doing it in right way ?

**Comment by ksatchit** [comment]
@Skchoudhary , you can continue with the approach taken. Here are some good references on writing unit tests for ansible: 

- References: https://docs.ansible.com/ansible/2.5/dev_guide/testing_units_modules.html
- Ansible Unit test for callback : https://github.com/ansible/ansible/blob/devel/test/units/plugins/callback/test_callback.py

**Comment by Skchoudhary** [comment]
@ksatchit Can you help me from here?
I haven't right test case before. So I am confused on what value assertion should check.

**Comment by ksatchit** [comment]
OpenEBS specific ansible plugins will be maintained at https://github.com/mayadata-io/litmus
