### ISSUE TITLE
Dockerize the Litmus demo repository to reduce the prerequisites for running a demo experiment

### ISSUE THREAD

**Issue by uditgaurav** [litmuschaos/litmus#2189]
This issue is to dockerize the litmus demo repository to run a demo experiment with the minimal prerequisites. Currently, there are certain numbers of [prerequisites](https://github.com/litmuschaos/litmus-demo#requirements) to run the litmus demo env, this can be reduced by containerizing the dependencies and running the script from it.

**Comment by jabhishek87** [comment]
i want to work on this

**Comment by uditgaurav** [comment]
Thanks for taking this @jabhishek87 you can start working on this!

**Comment by jabhishek87** [comment]
since it uses kind , kind requires Docker , so there will be problem in doing Docker in Docker

**Comment by uditgaurav** [comment]
@jabhishek87 You are right we can try:

1. Using some [dind](https://hub.docker.com/layers/docker/library/docker/stable-dind/images/sha256-ddb293bed8dd980233c2b61773d07deb84c485571d565101cb77d101c11fd8a2?context=explore)  image as the base image. Like [this](https://github.com/litmuschaos/test-tools/blob/master/resource_stress/app-cpu-stress/Dockerfile)
2. We can also use an image with kind preinstalled in it as a base image.
3. Use binaries to build the image.

ref: https://github.com/actions/virtual-environments/search?q=kind&unscoped_q=kind

**Comment by jabhishek87** [comment]
https://app.circleci.com/pipelines/github/jabhishek87/litmus-demo/1/workflows/71f9782a-528e-4819-924f-7ee6f3633945/jobs/1

**Comment by ksatchit** [comment]
Fixed by https://github.com/litmuschaos/litmus-demo/pull/11
