### ISSUE TITLE
Take Agent Namespace and Scope as user Input

### ISSUE THREAD

**Issue by gdsoumya** [litmuschaos/litmus#2200]
Currently the agent ns and scope is hardcoded into the portal manifest. Changes needed:
- Take user choice for ns and scope while cluster-registration
- Each agent can have a different ns and scope
- Manifest ns and scope will be used only in self-deployer

**Comment by gdsoumya** [comment]
@rajdas98

**Comment by rajdas98** [comment]
closing by this PR- https://github.com/litmuschaos/litmus/pull/2187
