### ISSUE TITLE
Add docs for dockerize litmus-demo

### ISSUE THREAD

**Issue by uditgaurav** [litmuschaos/litmus#2236]
## Details

- Once the litmus demo is dockerized we need proper documentation covering the steps to run litmus-demo within a container. This is in accordance with (https://github.com/litmuschaos/litmus-demo/pull/10).

**Comment by uditgaurav** [comment]
@jabhishek87  Thanks for showing interest in this you can start working on it.

**Comment by RanadeepPolavarapu** [comment]
May I work on this?

**Comment by uditgaurav** [comment]
Hey, @RanadeepPolavarapu this issue is already [taken](https://github.com/litmuschaos/litmus-demo/pull/10#issuecomment-705364560) by @jabhishek87. You can select an issue from https://mayadata.io/hacktoberfest-2020 which doesn't have a label `issue-taken`. If you're interested in some docs enhancement you should checkout issues like this https://github.com/litmuschaos/litmus/issues/2142

**Comment by RanadeepPolavarapu** [comment]
> Hey, @RanadeepPolavarapu this issue is already [taken](https://github.com/litmuschaos/litmus-demo/pull/10#issuecomment-705364560) by @jabhishek87. You can select an issue from https://mayadata.io/hacktoberfest-2020 which doesn't have a label `issue-taken`. If you're interested in some docs enhancement you should checkout issues like this #2142

@uditgaurav Sure, thank you. Can you please assign #2142 to me?

**Comment by uditgaurav** [comment]
This is fixed by https://github.com/litmuschaos/litmus-demo/pull/12
