### ISSUE TITLE
Translate README.md to Spanish language 

### ISSUE THREAD

**Issue by prithvi1307** [litmuschaos/litmus#2259]

**Comment by AlexandreInsua** [comment]
Can you asign me this issue?

**Comment by prithvi1307** [comment]
Sure @AlexandreInsua. Assigned

**Comment by AlexandreInsua** [comment]
Done.

**Comment by AlexandreInsua** [comment]
@prithvi1307 , I apologize, I forget sign the commit.

**Comment by Vinamra2009** [comment]
Hey, can I take over this issue if it is not been completed yet?

**Comment by AlexandreInsua** [comment]
Hi, Can you see this PR #2283 ?
