### ISSUE TITLE
Translate README.md to German language

### ISSUE THREAD

**Issue by prithvi1307** [litmuschaos/litmus#2260]

**Comment by glumand** [comment]
Hello @prithvi1307 may I grab this one? It's my first issue so I probably have some questions, but translating to German seems like something I can do well. Thank you and greetings!

**Comment by prithvi1307** [comment]
Sure @glumand . Feel free to ask!

**Comment by glumand** [comment]
I have just read through the English README and compared the structure to the other languages so I will just do the same thing but in German.
Is there like any rule what to name the branch I create? I have not found anything in the Steps to Contribute.

**Comment by prithvi1307** [comment]
@glumand Are you well versed with German or will use google translate?

**Comment by glumand** [comment]
@prithvi1307 it is my mother tongue. So I guess that counts as well versed.

**Comment by prithvi1307** [comment]
Awesome @glumand. Assigned. Please go ahead. No rule as such. You can create a file named README-de.md

**Comment by glumand** [comment]
Alright, thank you @prithvi1307 . I will do my best and ask if I have more questions.

**Comment by glumand** [comment]
In German there are like two options for saying "you". One really polite one for people you do not know, so it is quite distanced and the second one more personal. I am finished with the translation apart from a few lines where I'd like to know which kind of "you" seems more appropriate to you @prithvi1307 .

**Comment by ksatchit** [comment]
cc: @LaumiH

**Comment by LaumiH** [comment]
Hey @glumand , I may help, I'm from Germany :D 
Personally, looking at docs from google, I would prefer "Sie", just because it sounds more professional. Imagine looking into Litmus as some senior of whatever, and then there is "Du" ... just my two cents :D

**Comment by glumand** [comment]
@LaumiH thats what I thought but I wanted to be sure. Thank you. :)

**Comment by ksatchit** [comment]
Fixed by https://github.com/litmuschaos/litmus/pull/2281
