### ISSUE TITLE
Translate README.md to Portuguese language

### ISSUE THREAD

**Issue by prithvi1307** [litmuschaos/litmus#2263]

**Comment by adarsh-k-tiwari** [comment]
@prithvi1307 I would like to take this

**Comment by prithvi1307** [comment]
@adarsh-k-tiwari extremely sorry but we are actually looking up to country native people translating these instead of google translate. In case this isn't being taken by someone versed with Portuguese, I will assign it to you.

**Comment by rafaeelaudibert** [comment]
Hello @prithvi1307, I'm Brazilian, and I'd like to take this!

**Comment by rafaeelaudibert** [comment]
I've actually already opened the PR! Thanks
