### ISSUE TITLE
what is th possibility of imagePullPolicy for the node-cpu-hog which is default set to Always ?

### ISSUE THREAD

**Issue by ipsita2192** [litmuschaos/litmus#2315]
while executing node-cpu-hog experiment , resources are getting created :
NAME                        READY   STATUS         RESTARTS   AGE
nginx-6bbd77d656-pvzjl      1/1     Running        0          11m
nginx-chaos-runner          1/1     Running        0          84s
node-cpu-hog-bl7m80-bszhs   1/1     Running        0          46s
node-cpu-hog-dghdgu         0/1     ErrImagePull   0          39s 

The problem is , when `node-cpu-hog-xxxxx` pod is being created is goes to `ErrImagePull` as my lab doesn't have Internet connection to pull the image dynamically , with the below specification
spec:
  containers:
  - args:
    - --cpu
    - "8"
    - --timeout
    - "60"
    command:
    - stress-ng
    image: litmuschaos/go-runner:1.9.0
    **imagePullPolicy: Always**
    name: node-cpu-hog 

Is there any possibility to change the ImagePullPolicy in the node-cpu-hog pod that is created by go-runner image with ./experiments -name node-cpu-hog 

Images are used :
litmuschaos/go-runner:1.9.0
litmuschaos/chaos-operator:1.9.0
litmuschaos/chaos-runner:1.9.0

**Comment by ksatchit** [comment]
Being tracked via the duplicate issue on this: https://github.com/litmuschaos/litmus/issues/2335
