### ISSUE TITLE
uploading our own yaml files on litmus portal.

### ISSUE THREAD

**Issue by asibece** [litmuschaos/litmus#2323]
Request to provide a new feature of uploading our own yaml files on litmus portal.

**Comment by ajeshbaby** [comment]
Thanks for this feedback Ashik, It's a good feature to have. 

We will be adding as part of a new workflow definition. With 1.10 Litmus Portal would be having MyHub feature. As part of this you can define your own custom Github repo from which experiments can be picked. 

In new workflow creation, there would be an option either to select/upload a yaml or construct your own by adding experiments from your personal hub or hub.litmuschaos.io

**Comment by ajeshbaby** [comment]
Closing this issue. It's addressed with 1.10 feature PR #2325
