### ISSUE TITLE
imagePullPolicy for the node-cpu-hog set to "Always" , unable to change it to "IfnotPresent" or "Never"

### ISSUE THREAD

**Issue by ipsita2192** [litmuschaos/litmus#2335]
while executing node-cpu-hog experiment , resources are getting created :
NAME READY STATUS RESTARTS AGE
nginx-6bbd77d656-pvzjl 1/1 Running 0 11m
nginx-chaos-runner 1/1 Running 0 84s
node-cpu-hog-bl7m80-bszhs 1/1 Running 0 46s
node-cpu-hog-dghdgu 0/1 ErrImagePull 0 39s

The problem is , when node-cpu-hog-xxxxx pod is being created is goes to ErrImagePull as my lab doesn't have Internet connection to pull the image dynamically , with the below specification
spec:
containers:

args:
--cpu
"8"
--timeout
"60"
command:
stress-ng
image: litmuschaos/go-runner:1.9.0
imagePullPolicy: Always
name: node-cpu-hog
Is there any possibility to change the ImagePullPolicy in the node-cpu-hog pod that is created by go-runner image with ./experiments -name node-cpu-hog

Images are used :
litmuschaos/go-runner:1.9.0
litmuschaos/chaos-operator:1.9.0
litmuschaos/chaos-runner:1.9.0

**Comment by ksatchit** [comment]
Hi @ipsita2192 The runner supports imagePullPolicy to IfNotPresent via a setting/flag on the ChaosEngine

**Comment by ksatchit** [comment]
@ipsita2192 we welcome you to the [#litmus](slack.litmuschaos.io) slack channel to get a faster response to the issue and also to participate/benefit from several other conversations around chaos!

**Comment by ipsita2192** [comment]
The place that you mentioned I already changed but the image from where it creates stress-ng container getting failed due to unavailability of internet connectivity :

https://github.com/litmuschaos/chaos-charts/blob/3651278b1b87bcd6de22db3fd5bfec92c7d0b647/charts/generic/node-cpu-hog/experiment.yaml#L74-L76

The problem is , when node-cpu-hog-xxxxx pod is being created is goes to ErrImagePull as my lab doesn't have Internet connection to pull the image dynamically , with the below specification
spec:
containers:

args:
--cpu
"8"
--timeout
"60"
command:
stress-ng
image: litmuschaos/go-runner:1.9.0
imagePullPolicy: Always
name: node-cpu-hog

**Comment by ksatchit** [comment]
Cool. Fixing this @ipsita2192

**Comment by ipsita2192** [comment]
Yes sure @ksatchit  why not!
I will do the changes and test on environment, and let you know.
Thanks for your support.

**Comment by ipsita2192** [comment]
Hi @ksatchit  , could you please add me on slack channel as one of my colleague has tried to add me the slack channel and request has been declined by the slack channel admin

**Comment by ksatchit** [comment]
@ipsita2192 could you please share your slack userid?

**Comment by ipsita2192** [comment]
Thanks @ksatchit , I am able to join the slack channel :)

**Comment by ksatchit** [comment]
This is fixed via https://github.com/litmuschaos/litmus-go/pull/214
