### ISSUE TITLE
/var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory

### ISSUE THREAD

**Issue by niebomin** [litmuschaos/litmus#2357]
The chaos runner pod can't get up and running.  Here's the log I see

```
time="2020-11-19T15:16:53Z" level=fatal msg="Unable to create ClientSets, error: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory"
```

I checked the code a little.  Looks like it's using the kubeconfig to get the service account.  My local kubeconfig does not have the access to list service account.  Is this the reason?

**Comment by ksatchit** [comment]
Hey @niebomin , in cases where kubeconfig is not provided explicitly, it uses the inClusterConfig. So shouldn't be an issue ideally. We will get back on this.

**Comment by niebomin** [comment]
Sorry, I should've updated it.  It's because k8s auto mount is disabled.  Now, it's fixed.

**Comment by niebomin** [comment]
User error
