### ISSUE TITLE
my hub feature in litmus portal 1.10.0 should allow to use tokens to use the private github repositores.

### ISSUE THREAD

**Issue by asibece** [litmuschaos/litmus#2358]
Hello, my hub feature in litmus portal 1.10.0 should allow to use tokens to use the private github repositories. Please implement this to proceed further.

**Comment by rajdas98** [comment]
cc: @ajeshbaby

**Comment by rajdas98** [comment]
Hi @asibece, we have added private myhub in the litmusportal. Closing this issue in favour of https://github.com/litmuschaos/litmus/pull/2402 and https://github.com/litmuschaos/litmus/pull/2393
