### ISSUE TITLE
Appkind limitations

### ISSUE THREAD

**Issue by gouyang** [litmuschaos/litmus#2369]
Try to run pod-delete experiment on an custom object get hit below error:
```
The ChaosEngine "vm-chaos" is invalid: spec.appinfo.appkind: Invalid value: "": spec.appinfo.appkind in body should match '^(^$|deployment|statefulset|daemonset|deploymentconfig|rollout)$'
```

Why does it limit to these objects? Is it possible to remove the limitations?

**Comment by ksatchit** [comment]
@gouyang thanks for trying litmus. Can you please provide the ChaosEngine spec you are using ?

**Comment by ksatchit** [comment]
Litmus allows for blast radius control via filtering the parent resource (deploy/ds/sts/rollouts) for a chaos annotation (litmuschaos.io/chaos="true") before injecting chaos on pods owned by these. 

But this is an optional feature. If you would directly like to inject chaos on pods w/o limiting to these resources - you can do so. You just need to set the `.spec.annotationCheck` to `false` in the chaosengine. And can skip appkind, i.e., provide only `appns `& `applabel `in the` spec.appinfo` section. The `appkind `is needed only if `annotationCheck `is set to `true `(which is the default).

**Comment by gouyang** [comment]
@ksatchit thanks for the tips, I'll try it now and will report back asap.

**Comment by gouyang** [comment]
Set `.spec.annotationCheck` to `false` and remove `appkind` works for me.

**Comment by ksatchit** [comment]
Great, thanks for the confirmation!!

**Comment by ksatchit** [comment]
@gouyang  let me welcome you to the litmus slack channel - we live in the Kubernetes Slack workspace and will be happy to see you there. You might get faster responses from community folks & also participate in other interesting discussions around chaos engineering.

You can use this self-service link https://slack.kubernetes.io to register & join the workspace. Once done, you can search and join the #litmus channel.
