### ISSUE TITLE
create chaos experiment with other ServiceAccount not belong to me

### ISSUE THREAD

**Issue by WangXiangUSTC** [litmuschaos/litmus#2457]
## Question

I see the document, before creating a chaos experiment, I need to prepare `chaosServiceAccount`, and then create the ChaosEngine Resource with the ServiceAccount. 

I understand this is used for security, but I have a question: the `ServiceAccount` maybe not belong to me, I can use any `ServiceAccount` I can see in the K8s cluster, how to make sure the security?

**Comment by ksatchit** [comment]
Hi @WangXiangUSTC ! Thats a great question. Will try to elaborate the philosophy behind this: 

Litmus supports different modes of operations - the most used ones are the standard/regular modes & [admin ](https://docs.litmuschaos.io/docs/admin-mode/ ) mode. Latter is used when users have autonomy over the cluster and generally have cluster-wide permissions (say, either devtest purposes on small/transient clusters or SREs with singular access to protected environments). Here there is an all-encompassing svcAccount that can run all experiments (which is shipped with admin mode installation via helm OR can be installed via kubectl using a public manifest) w/o the need to create a chaosServiceAccount or select one for each experiment. So, if you opt for this mode, you need not bother about creating a svcAccount before you run each exp :) 

In the case of the regular/standard mode (also what is explained as default in the get-started/experiment documentation - for illustrative purposes), the litmus infra or control plane is expected to be setup by an admin persona - post which developers **_can_** run chaos experiments in their respective namespaces by using (creating/selecting) a ChaosServiceAccount that has just enough permissions necessary for their exp. Each experiment in the chaoshub/docs is accompanied by such a reference/example RBAC.  

Now, in this std mode, the emphasis is on what kind of permissions the developer/user is entrusted with within your self-service environment. If the persona has visibility to other serviceaccounts that [do not belong to] / [have not been created by] him/her, OR has permissions to impact beyond one/more namespaces - then that is a conscious choice. They _will_  be able to use these other SA. The constraint being, the SA has enough permissions to run the chosen experiment, the lack of which can cause failure. 

On *how to make sure security*, part - it is expected that these environments are set up in such a way as to allow restricted visibility and actions for the individual users. **_What litmus provides is an option to still enable them to run experiments in such environments_** by clearly defining what min. permissions are needed to run a given experiment - so they can end up with a catalog that works for them. We have seen various use-cases around this model in the litmuschaos community. 

In truly multi-tenant environments that have very strict boundaries & role enforcements, litmus also allows a wholly [namespaced](https://docs.litmuschaos.io/docs/namespaced-mode/) mode of execution - where not only the experiment resources but the entire control plane can be created inside a particular namespace (for ex: [Okteto Cloud](https://okteto.com/)) to ease management and visibility. Here too a single serviceaccount is sufficient to run most pod-level chaos experiments, there being a natural/inherent deterrent for running experiments with cluster-wide/multi-service blast radius. 

This is a brief on how litmus enables execution for security practices. This philosophy is being carried over to the upcoming Litmus Portal as well.

**Comment by WangXiangUSTC** [comment]
Thanks for your reply! @ksatchit

**Comment by ksatchit** [comment]
Closing this issue based on user response. We could update this issue as and when there are changes to the policies adopted.
