### ISSUE TITLE
Pod Network Latency: If specified TARGET_HOST is invalid (?) all traffic has injected latency

### ISSUE THREAD

**Issue by damalamp** [litmuschaos/litmus#2461]
**What happened**:
If I specify an invalid DESTINATION_HOSTS ~~TARGET_HOST~~ (ie a host which cannot be resolved to an IP) for a pod-network-latency scenario, it seems all egress traffic from the pod is impacted. 

**What you expected to happen**:
I would expect if there is no traffic going to the target host specified (or if the target host cannot be resolved) then no traffic would be impacted with latency or maybe an error would throw indicated a failure to resolve the specified DESTINATION_HOSTS values.

**How to reproduce it (as minimally and precisely as possible)**:
Specify a DESTINATION_HOSTS ~~TARGET_HOST~~ which will not resolve to an ip when injecting network latency against a pod and verify if there is latency for ALL traffic leaving the pod.

**Anything else we need to know?**:
[Comment from Karthik](https://kubernetes.slack.com/archives/CNXNB0ZTN/p1614129889066700?thread_ts=1614036862.064000&cid=CNXNB0ZTN) (and I've been able to verify this behavior) indicates that if the host cannot be resolved to an IP then the chaos behaves as though no targets were passed to the chaos experiment.

**Comment by ksatchit** [comment]
Fixed via: https://github.com/litmuschaos/litmus-go/pull/302

The changes will be available on the 1.13.2 patch release expected before March 15th (current: 1.13.1)
