### ISSUE TITLE
Provision to restart the workflow without creating a new one every time

### ISSUE THREAD

**Issue by ajeshbaby** [litmuschaos/litmus#2467]
Question -  Is there a way to restart the workflow without creating a new one every time?

Answer -  For now, you could do the following 
- Create a recurring schedule that repeats the workflow execution with a defined interval. 
-  Import/uploading the YAML is another way to run workflows w/o constructing it every time - but still doesn’t meet the req fully. 
 
A possible solution - Have a feature where we can re-run the workflow again by allowing Edit and `Schedule Now` workflow with a re-run option.

**Comment by gdsoumya** [comment]
Currently a version of this is available with the event-tracker, whenever the event tracker sends a request for workflow run even a one-time workflow can be triggered again automatically. The same thing can be done for this feature but instead of event-trigger it shall be a user action.

**Comment by rajdas98** [comment]
Technically it possible because we are storing workflow YAML in the DB. We
need a restart API that will pick the workflow manifest from the DB and
change the workflow name then schedule it to the target cluster
