### ISSUE TITLE
Remove vendor directory from chaos {operator, exporter}, upgrade {k8s deps, operator-sdk} and improve CI/CD

### ISSUE THREAD

**Issue by imrajdas** [litmuschaos/litmus#2481]
1. Currently, we have a vendor directory in chaos operator and exporter, there is no need to have a vendor directory. we can build both modules from the docker file. Vendor directory creates the repo too bulky and overhead to manage this directory

2. Due to having a lower `operator-SDK` version, we are bound to use a lower k8s version(Almost 2 years old) in both the repo and if we import any pkg from these repos then we need to downgrade the client-go version in that repo. Recently, we need to downgrade some k8s deps in `graphql-server` because we import a pkg from chaos-operator
 
3. Instead of using this base image `registry.access.redhat.com/ubi8/ubi-minimal:8.3`, we can have a multi-stage build with `golang` and `scratch` image and we need to simplify the CI/CD scripts.

**Comment by rajdas98** [comment]
cc: @ksatchit

**Comment by rajdas98** [comment]
Also, in chaos runner repo.

**Comment by rajdas98** [comment]
**Status:**
I have removed the vendor directory and refactored the CI/CD scripts for chaos exporter https://github.com/litmuschaos/litmus/issues/2481

**Comment by imrajdas** [comment]
Required changes have been already merged.
