### ISSUE TITLE
Workflow not starting when the manifest is uploaded from Litmus-Portal

### ISSUE THREAD

**Issue by amityt** [litmuschaos/litmus#2496]
## Details

**What happened**: While uploading the manifest from Litmus Portal, the workflow is not getting started.

**What you expected to happen**: While uploading the manifest, the workflow name should be updated in the manifest.

**Anything else we need to know?**:  While uploading the manifest from Litmus Portal, there was no provision to update the workflow name. 

![Screenshot from 2021-03-04 11-18-40](https://user-images.githubusercontent.com/40661238/109917500-7bb3e000-7cdb-11eb-90d8-4d7f9fe80ce2.png)

## Workaround 

Current work-around is to update the name manually using the YAML editor provided in the Tune Workflow screen. 

With the fix, the workflow name will be updated in the manifest while uploading:

![Screenshot from 2021-03-04 11-35-38](https://user-images.githubusercontent.com/40661238/109918915-ca627980-7cdd-11eb-81f1-b83ece58a91f.png)

**The workflow name provided by the user will be updated in the manifest.**

![Screenshot from 2021-03-04 11-21-18](https://user-images.githubusercontent.com/40661238/109917700-c3d30280-7cdb-11eb-837c-e35097d1a719.png)

## Workaround until release
_Click on the gif for Full Screen._

![2021-03-04 13-38-52 (online-video-cutter com)](https://user-images.githubusercontent.com/40661238/109932180-dc4d1800-7cef-11eb-9e52-a13f8ccc82dc.gif)

**Comment by amityt** [comment]
This issue has been resolved and added to master branch with PR: https://github.com/litmuschaos/litmus/pull/2487

**Comment by rajdas98** [comment]
@AmitKumarDas Can we close this issue?

**Comment by amityt** [comment]
Yes @rajdas98 . Closing this issue.
