### ISSUE TITLE
Workflow not starting when scheduled with multiple number of same experiments.

### ISSUE THREAD

**Issue by Jonsy13** [litmuschaos/litmus#2500]
**What happened**: When we try to schedule a custom workflow with multiple numbers of the same experiments on Litmus-Portal, It doesn't run and gets in a failed state. It can also be the case with the upload YAML option. The workflow graph comes as blank.

`Warning  WorkflowFailed   22m   workflow-controller  invalid spec: spec.templates[3].name 'container-kill' is not unique`

![Screenshot from 2021-03-05 11-15-23](https://user-images.githubusercontent.com/40681425/110072663-24c60d80-7da4-11eb-9a42-3d79a79d46b1.png)

**What you expected to happen**: It should run successfully with the same multiple experiments. 

**How to reproduce it (as minimally and precisely as possible)**: Try to schedule a custom workflow with two same experiments.

**Anything else we need to know?**: 

Sample Configuration

> steps:
>         - - name: install-chaos-experiments
>             template: install-chaos-experiments
>             arguments: {}
>         - - name: container-kill
>             template: container-kill
>             arguments: {}
>         - - name: container-kill
>             template: container-kill
>             arguments: {}
>         - - name: revert-chaos
>             template: revert-chaos
>             arguments: {}

**Workaround** - Check the experiment names and show a warning message `this experiment is already used in the workflow. More on documentation..`. if they are repeated.

**Comment by jinjiaw** [comment]
I have similar situation when i tried to add two serial pod-delete experiment in one workflow. The workflow creation was ok, but when i clicked the finish button to schedule the workflow, it just failed silently and left the error  **"Please check the configuration, the workflow was not able to start".** I could not see any workflow/runner/experiment pods created.  I have tried to tune some settings in the manifest mainly to distinguish each pod-delete with different names, but it still failed. May i ask if there is any restriction, or any extra setups need to be done to make it work?  I think the issue can be reproduced easily by create a workflow with two pod-delete.
However I could successfully create and execute a workflow with multiple different type of experiments.
thanks much

**Comment by ksatchit** [comment]
cc: @amityt @Jonsy13 any updates on this ?

**Comment by Jonsy13** [comment]
Hi @gbuirel @bipinkm This issue is currently in planning phase & may take some more time, we will get back here with some more updates once we are good with planning of changes needed for implementation. Thanks!! cc: @amityt

**Comment by amityt** [comment]
This issue has been fixed with https://github.com/litmuschaos/litmus/pull/3540
