### ISSUE TITLE
litmus-portal doesn't work with latest helm chart

### ISSUE THREAD

**Issue by Jasstkn** [litmuschaos/litmus#2510]
**What happened**:
litmus-portal was deployed via helm-chart (1.13.2) with release name: litmus-portal. It doesn't work. I assume that it could be becaus of hardcoded name of services in `nginx.conf` (see links below)
<img width="1399" alt="Screenshot 2021-03-06 at 19 06 16" src="https://user-images.githubusercontent.com/20466436/110212974-08fb5e00-7eaf-11eb-93c8-24be03c790bb.png">

**What you expected to happen**:
It should work.

**How to reproduce it (as minimally and precisely as possible)**:
helm upgrade --install litmus-portal litmus/litmus-portal --version=1.13.2

Try to login via UI, check error in the console output

**Anything else we need to know?**:
List of hardcoded values:
https://github.com/litmuschaos/litmus/blob/aa475a1002e2a4fdd72a2be54813b860433e739a/litmus-portal/frontend/nginx/nginx.conf#L34
https://github.com/litmuschaos/litmus/blob/aa475a1002e2a4fdd72a2be54813b860433e739a/litmus-portal/frontend/nginx/nginx.conf#L42
https://github.com/litmuschaos/litmus/blob/aa475a1002e2a4fdd72a2be54813b860433e739a/litmus-portal/frontend/nginx/nginx.conf#L52

Could be an issues too:
https://github.com/litmuschaos/litmus/blob/aa475a1002e2a4fdd72a2be54813b860433e739a/litmus-portal/graphql-server/pkg/k8s/cluster.go#L88
https://github.com/litmuschaos/litmus/blob/aa475a1002e2a4fdd72a2be54813b860433e739a/litmus-portal/graphql-server/pkg/k8s/cluster.go#L91

**Comment by imrajdas** [comment]
This is an old issue. @Jasstkn feel free to re-open this issue if it's not fixed.
