### ISSUE TITLE
litmus-portal subscriber crashloopbackoff

### ISSUE THREAD

**Issue by Jasstkn** [litmuschaos/litmus#2511]
**What happened**:
Deployed litmus-portal using 1.3.1 helm chart. And subscriber goes to `CrashLoopBackOff` state.
In logs:
```
k logs -f -n chaos subscriber-6fcdd7fd76-9m9ng2021/03/06 19:04:18 Post "http://34.70.245.189:31822/query": dial tcp 34.70.245.189:31822: i/o timeout
```

**What you expected to happen**:
All pods are up and running. Subscriber always should use internal service name instead of external IP address of node.

**How to reproduce it (as minimally and precisely as possible)**:
`helm upgrade --install litmus-portal litmus/litmus-portal --version=1.13.1`

**Anything else we need to know?**:
Related to:
- https://github.com/litmuschaos/litmus/blob/aa475a1002e2a4fdd72a2be54813b860433e739a/litmus-portal/graphql-server/pkg/k8s/cluster.go#L88
- https://github.com/litmuschaos/litmus/blob/aa475a1002e2a4fdd72a2be54813b860433e739a/litmus-portal/graphql-server/pkg/k8s/cluster.go#L91

It works fine when use `litmusportal-server-service:9002/query` as a `GQL_SERVER` variable

**Comment by ksatchit** [comment]
Closing this as there have been improvements since, please feel free to reopen if this issue is still seen in 2.1.0
