### ISSUE TITLE
litmus-portal subscriber crashloopbackoff due to CLUSTER ID MISMATCH

### ISSUE THREAD

**Issue by jinjiaw** [litmuschaos/litmus#2512]
**What happened**:

Deployed litmus-portal 1.13.0 using helm chart in a very fresh installed Kubernetes cluster, basic workflow worked well. 
But the following error occurred against subscriber when i removed and reinstalled the same portal chart on the same cluster again. it was CrashLoopBackOff and complained "CLUSTER ID MISMATCH", meanwhile the self-cluster is not available on the portal.

```
kubectl logs pod/subscriber-5f7bb775d7-2skwr -n litmus
2021/03/07 09:09:02 connecting to ws://1.2.3.4:30478/query
2021/03/07 09:09:03 Cluster Connect Established, Listening....
time="2021-03-07T09:09:03Z" level=fatal msg="gql error : {\"payload\":{\"errors\":[{\"message\":\"ERROR:  CLUSTER ID MISMATCH\",\"path\":[\"clusterConnect\"]}],\"data\":null},\"type\":\"data\"}\n"
```

**What you expected to happen**:

all related resources are up and running. self-cluster can be correctly identified and confirmed.
The litmus-portal helm chart can be successfully removed and redeployed. 

**How to reproduce it (as minimally and precisely as possible)**:
1. install litmus-portal using helm chart 1.13.0
2. execute some workflow on the self-cluster
3. helm uninstall the chart and clean up all left-over resources (e.g. argo workflow controller ) 
4. reinstall the same chart again
5. login and trigger workflow on the portal and see if the self-cluster is available.

**Anything else we need to know?**:

**Comment by gdsoumya** [comment]
When you uninstalled the portal it was not properly cleaned maybe. Can you try redoing it, but make sure to delete the litmus namespace all together before reinstalling. There are some configmaps which if not removed properly can cause this error after a reinstall.

**Comment by gdsoumya** [comment]
> When you uninstalled the portal it was not properly cleaned maybe. Can you try redoing it, but make sure to delete the litmus namespace all together before reinstalling. There are some configmaps which if not removed properly can cause this error after a reinstall.

This is the configmap that might be causing this issue `litmus-portal-config`

**Comment by jinjiaw** [comment]
you are right. i forgot to clean the cm. the litmus-portal was successfully reinstalled after everything is cleaned up in litmus namespace.  thanks much.

**Comment by jinjiaw** [comment]
closed this issue. thanks
