### ISSUE TITLE
Infra chaos experiments should not have any dependency on application pods

### ISSUE THREAD

**Issue by asibece** [litmuschaos/litmus#2517]
Infra chaos experiments should not have any dependency on application pods.

For EBS Disk attach or AWS Terminate experiments no need to have spec definition w.r.t app kind like deployment label selection etc.

**Comment by ispeakc0de** [comment]
https://github.com/litmuschaos/litmus-go/pull/304

**Comment by ispeakc0de** [comment]
The requested changes are already available in the `ci` tag. Refer: https://github.com/litmuschaos/litmus-go/pull/304

**Comment by ajeshbaby** [comment]
Addressed part of litmuschaos/litmus-go#304
