### ISSUE TITLE
Add litmusctl binaries for MacOSX (darwin/amd64)

### ISSUE THREAD

**Issue by GrzegorzWild** [litmuschaos/litmus#2575]
New version of Litmus 2.0.0 requires usage of litmusctl to install agents on cluster. Users of MacOSX are unable to do it without binaries compiled for that architecture.

**Comment by ajeshbaby** [comment]
@arkajyotiMukherjee  @rajdas98 Is there an easy workaround till you support this?

**Comment by arkajyotiMukherjee** [comment]
Looking into the matter... @GrzegorzWild @ajeshbaby

**Comment by rajdas98** [comment]
Hi @GrzegorzWild, we just built the binaries for mac. Please take a look here- https://github.com/litmuschaos/litmusctl

**Comment by GrzegorzWild** [comment]
@rajdas98 Thank you very much for quick resolution of this issue.

**Comment by rajdas98** [comment]
> @rajdas98 Thank you very much for quick resolution of this issue.

Thanks @arkajyotiMukherjee

**Comment by rajdas98** [comment]
closing this issue in favour of https://github.com/litmuschaos/litmusctl/pull/7
