### ISSUE TITLE
Experiment: Network policies

### ISSUE THREAD

**Issue by carolili** [litmuschaos/litmus#2586]
**Feature request**
It would be nice to have Litmus experiments to verify [Kubernetes Network Policies](https://kubernetes.io/docs/concepts/services-networking/network-policies/). Since there are network drivers, it could also be useful to support specific drivers as their policies may bring extra features or work in a different way.

Examples of network drivers are e.g.:
- [Cilium](https://docs.cilium.io/en/v1.8/policy/)
- [Calico](https://docs.projectcalico.org/security/calico-network-policy)
- [Weave](https://www.weave.works/docs/net/latest/kubernetes/kube-addon/#npc)

**How should it work**
The experiment could apply the given network policies and use HTTP or command probes to test if they work.

Examples of experiments:
- Test blocked or allowed access to pods in different namespaces.
- Test blocked or allowed access to services/ports from specific pods and namespaces.

**Comment by ksatchit** [comment]
This experiment is now available here: https://litmuschaos.github.io/litmus/experiments/categories/pods/pod-network-partition/
