### ISSUE TITLE
litmus-portal failing workflow if not able to connect to google analytics

### ISSUE THREAD

**Issue by johnqa** [litmuschaos/litmus#2587]
Hi,

I have manually created a workflow using a yaml file and executed it.

The workflow fails, but when looking at the logs the only error I see is that it cannot connect to google analytics. My installation is air-gapped so this is expected.

I would expect that not being able to connect to google analytics would be in worse case scenario a warning and not an error.

Thanks,
John

**Comment by rajdas98** [comment]
Hi @johnqa, We are using google analytics to count the operator and experiment installation. You can disable it by an env called `ANALYTICS` in the chaos engine manifest. 
https://docs.litmuschaos.io/docs/faq-general/#does-litmus-track-any-usage-metrics-on-the-test-clusters

Can you try again after disabling it?

**Comment by johnqa** [comment]
By disabling it, the workflow is passing, but the point is that connectivity to google analytics should not mark a workflow as failed.

**Comment by ispeakc0de** [comment]
Hi @johnqa ,

Yes, you are right. The chaos-operator is working in the same way. It will just log the error if analytics fails and continue the execution. The experiment should not fail even if the google anaytics are unreachable. There might be another reason for failure in the earlier run.

Would you like to retry it and share the operator logs if it will fail again?.

**Comment by ajeshbaby** [comment]
Marking it closed, as no response. Please feel free to reopen in case if you are able to reproduce this issue.
