### ISSUE TITLE
Unable to connet the target cluster for Namesapced scope installation of litmus portal

### ISSUE THREAD

**Issue by uditgaurav** [litmuschaos/litmus#2599]
**What happened**:
- When trying to connect an external agent from a cluster the installation failed.

- When the target cluster installation mode is `namespace`
```
Error from server (NotFound): error when creating "http://54.245.208.59:32549/api/file/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbHVzdGVyX2lkIjoiYzgyNmVjOGQtNzI4YS00MzNlLTlhMjItM2I1Yjg1NTVkZGNkIn0.NdFs4UXRONU3iQ_F6RtG9DzIS7jDv8IiwW74cA4h7_k.yaml": namespaces "litmus" not found
```

- When the target cluster installation mode is `cluster`.
```
The CustomResourceDefinition "chaosexperiments.litmuschaos.io" is invalid: 
* spec.validation.openAPIV3Schema.properties[spec].properties[definition].properties[labels].additionalProperties: Forbidden: additionalProperties and properties are mutual exclusive
* spec.validation.openAPIV3Schema.properties[spec].properties[definition].properties[env].items.properties[valueFrom].properties[resourceFieldRef].properties[divisor].type: Required value: must not be empty for specified object fields
*

```

**What you expected to happen**:

- Installation for both the mode should work.

**How to reproduce it (as minimally and precisely as possible)**:

- Deploy namespace mode of installation of the portal and try to connect an agent. 

**Anything else we need to know?**:

**Comment by ajeshbaby** [comment]
@uditgaurav This has been fixed in master can you check and close it.
