### ISSUE TITLE
Github workflow should run on particular file change

### ISSUE THREAD

**Issue by rajdas98** [litmuschaos/litmus#2604]
We are using GH workflows to build the litmus portal's components. But, the workflows got triggered on any file change, the requirement is the job should run on a particular file change in the respective directory.

| GH workflow jobs  | Code Directory |
| ------------- | ------------- |
| docker-build-frontend, docker-build-and-push-frontend  | https://github.com/litmuschaos/litmus/tree/master/litmus-portal/frontend  |
| docker-build-graphql-server, docker-build-and-push-graphql-server  | https://github.com/litmuschaos/litmus/tree/master/litmus-portal/graphql-server  |
| docker-build-authentication-server, docker-build-and-push-authentication-server  | https://github.com/litmuschaos/litmus/tree/master/litmus-portal/authentication  |
| docker-build-subscriber, docker-build-and-push-subcriber  | https://github.com/litmuschaos/litmus/tree/master/litmus-portal/cluster-agents/subscriber  |
| docker-build-event-tracker, docker-build-and-push-event-tracker  | https://github.com/litmuschaos/litmus/tree/master/litmus-portal/cluster-agents/event-tracker  |

Ref to GH-workflows
- https://github.com/litmuschaos/litmus/blob/master/.github/workflows/build.yml
- https://github.com/litmuschaos/litmus/blob/master/.github/workflows/push.yml

**Comment by Jasstkn** [comment]
@rajdas98 Hi! Just to clarify: github actions doesn't support templating or define specific paths on the jobs level. 
So the only one solution is to divide build / push workflows to be specific for each part of litmus. Is it ok?

**Comment by rajdas98** [comment]
@Jasstkn Currently, our workflows are divided into multiple jobs and each job is mapped to particular components. so, I am thinking, if we can write a script to check the file change for the current and previous commit and based on the that we will trigger or cancel the job

@Jonsy13 has implemented a similar thing for the e2e workflow. Here is the script- https://github.com/litmuschaos/litmus/blob/master/.github/filter_and_build.sh. Not sure if it will work with the other workflow.
