### ISSUE TITLE
Unable to read the secrets from ENV

### ISSUE THREAD

**Issue by DelphineJoyneer** [litmuschaos/litmus#2613]
What happened:
Its unable to read the secrets from ENV

What you expected to happen:
It should show <set to the key 'KEYNAME' of secret 'secret'>  Optional: false. Instead its showing empty against the ENV variable

How to reproduce it (as minimally and precisely as possible):
You can run any experiment which uses secrets as ENV in pod.

Workaround:
Its working fine with older crds

**Comment by uditgaurav** [comment]
Thanks, @DelphineJoyneer for bringing this up. Can I know the Kubernetes version you're using?

**Comment by DelphineJoyneer** [comment]
Its v1.20.4 @uditgaurav

**Comment by uditgaurav** [comment]
The updated CRDs are here - https://github.com/litmuschaos/litmus-helm/tree/master/charts/litmus/crds. The one which is used by you is an older one.
