### ISSUE TITLE
Kubelet Service Kill / Node Drain - Wrong Node-Selector

### ISSUE THREAD

**Issue by ozgunakalin** [litmuschaos/litmus#2642]
**What happened**: Creating kubelet-service-kill or node-drain workflow assigns nodeselector as node02 or node03

**What you expected to happen**: Nodename for pod to be deployed should be input or valid

**How to reproduce it (as minimally and precisely as possible)**: Create workflow -> kubelet-service-kill -> Enter NodeName -> Add Experiment -> Finish adding experiment -> Construct workflow -> Check yaml -> nodeselector has kubernetes.io/hostname: node02

**Anything else we need to know?**: Version: Litmus 2.0

Kubelet-service-kill pod event:
Warning  FailedScheduling  44s (x5 over 5m13s)  default-scheduler  0/3 nodes are available: 3 node(s) didn't match node selector.

**Comment by ispeakc0de** [comment]
Closing this issue as it is not reproducible with the latest litmus version. You can re-open it, if you are still facing this issue with latest version
