### ISSUE TITLE
Use kelseyhightower/envconfig pkg to validate the environment variables.

### ISSUE THREAD

**Issue by rajdas98** [litmuschaos/litmus#2659]
Currently, we have a lot of env vars in the litmusportal, so we need to use `envconfig` pkg to validate and process the env vars.
PKG- https://github.com/kelseyhightower/envconfig

Need to add in:
- graphql-server
- event-tracker
- subscriber
- authentication-server

**Comment by srisatya1197** [comment]
I want to work on this issue.

**Comment by rajdas98** [comment]
Thanks, @srisatya1197. Assigning to you

**Comment by srisatya1197** [comment]
Ok Sir. Thank you.

**Comment by srisatya1197** [comment]
I'm trying to login in slack channel but it's not working like :
![Sign up for a new account _ Slack - Google Chrome 14-04-2021 09_25_14](https://user-images.githubusercontent.com/78905067/114652380-63d07280-9d03-11eb-9584-726c28b91d90.png)

**Comment by sayantani11** [comment]
Hey, is the issue solved? I mean if I get some leads, may be even I could help

**Comment by rajdas98** [comment]
@sayantani11 , It's still a open issue. I am assigning this issue to you.

**Comment by sayantani11** [comment]
@rajdas98 could you guide me a bit through the issue?

**Comment by 123vivekr** [comment]
Hi, I'd like to take up this issue. Can I be assigned?

**Comment by gdsoumya** [comment]
Hi @123vivekr, I have assigned the issue to you. If you have any questions you can ask them here or in the slack channel.

**Comment by 123vivekr** [comment]
Hey, I've added the validation for three modules in separate commits [here](https://github.com/123vivekr/litmus/commits/env_var_validation)

For the `authentication-server` module, where should I add validation? 
Is [configs.go](https://github.com/litmuschaos/litmus/blob/master/litmus-portal/authentication/pkg/utils/configs.go) the right file?
