### ISSUE TITLE
Minikube script (minikube.sh ) optimization 

### ISSUE THREAD

**Issue by doruboyina** [litmuschaos/litmus#269]
## Script Optimization ?
 

**What happened**:
CURDIR=`pwd`  ( instead of back ticks , its always better to keep variable in $(pwd) )

Also there multiple exports commands where we can export all variable in single line

**What you expected to happen**:

The POSIX standard defines the $() form of command substitution. $() allows nested commands and looks better (legibility).

Reducing lines of code by removing multiple export commands

**How to reproduce it (as minimally and precisely as possible)**:

CURDIR=$(pwd)

export  MINIKUBE_WANTUPDATENOTIFICATION=false MINIKUBE_WANTREPORTERRORPROMPT=false
MINIKUBE_HOME=$HOME CHANGE_MINIKUBE_NONE_USER=true  KUBECONFIG=$HOME/.kube/config

**Comment by doruboyina** [comment]
I would like to work on this request

**Comment by dargasudarshan** [comment]
@doruboyina Yeah you can work on this issue. Looking forward to your PR.

**Comment by ksatchit** [comment]
The minikube bringup scripts will no longer be maintained in litmuschaos/litmus
