### ISSUE TITLE
Content changes 

### ISSUE THREAD

**Issue by mallick370** [litmuschaos/litmus#2699]
May be we need to think to show some other info or we can remove it if we are not showing or fetching any description of the workflow.

![image](https://user-images.githubusercontent.com/43519140/114615694-9b1f2f00-9cc3-11eb-9e5c-9d3ae4c75eca.png)

**Comment by Jonsy13** [comment]
The is fixed, as the description phrase is removed now. Addressed here - https://github.com/litmuschaos/litmus/pull/2698
Images are attached in the given PR, also can be validated in the ci tag as well.
