### ISSUE TITLE
Experiment based on iteration

### ISSUE THREAD

**Issue by Ckathiravan** [litmuschaos/litmus#2727]
If possible can we do the experiment based on the iteration inside of duration

**Comment by ksatchit** [comment]
To repeat/iterate a fault over a period of time (duration) with a specific interval, refer to the chaosScheduler:

- https://litmuschaos.github.io/litmus/chaos-scheduler-v2.1.0.yaml
- https://litmuschaos.github.io/litmus/experiments/concepts/chaos-resources/chaos-scheduler/contents/
