### ISSUE TITLE
Tests are started twice if there is another argo-server

### ISSUE THREAD

**Issue by devfaz** [litmuschaos/litmus#2735]
**What happened**:
**How to reproduce it (as minimally and precisely as possible)**:

* I installed 2.0.0-Beta4
* I created a scheduled job with generic/delete-pod against a nginx-deployment as mentioned in the docs.
* Every schedule-time I got 2 workflows created. One will fail, the second one will succeed.

after some help from nice guys in slack => https://kubernetes.slack.com/archives/CNXNB0ZTN/p1619017820349400

It seems the *other* argo-server installed in the cluster is causing this issue.

**What you expected to happen**:

I create a shedule and only one workflow is sheduled which succeeds.

**Anything else we need to know?**:

There is another argo-server running in this k8s cluster.

**Comment by ajeshbaby** [comment]
More details on this [thread](https://kubernetes.slack.com/archives/CNXNB0ZTN/p1619017820349400)
As a workaround for now
Adding an instance id to your custom argo setup and see if that prevents the duplicate workflow runs?
ref: https://argoproj.github.io/argo-workflows/scaling/#instance-id
You have to restart the controller after edits

**Comment by gdsoumya** [comment]
The fix has been merged, this should solve this issue without having to manually add the instance-id.
