### ISSUE TITLE
Not able to connect to Litmus Chaos Control Plane

### ISSUE THREAD

**Issue by saradocasar** [litmuschaos/litmus#2739]
Hi! I'm starting to using this tool and I'm having an issue accessing the Litmus Chaos Control Plane.
I'm working with Google GKE and I've followed the instructions to access the Litmus Chaos Control Plane. 
When I enter kubectl get svc -n litmus I got this:
chaos-operator-metrics          ClusterIP   10.88.1.90    <none>        8383/TCP                        46h
litmusportal-frontend-service   NodePort    10.88.3.103   <none>        9091:32651/TCP                  45h
litmusportal-server-service     NodePort    10.88.2.84    <none>        9002:31402/TCP,9003:32252/TCP   45h
mongo-service                   ClusterIP   10.88.3.196   <none>        27017/TCP                       45h

which is the expected output, but when I try to access the portal by my nodeip:port, I constantly getting the  Not able to connect to this web site error. 

I have this nodes in my Kubernetes Cluster:
gk3-cluter-tfg-default-pool-18acfb0d-bx50   Ready    <none>   47h   v1.18.16-gke.502
gk3-cluter-tfg-default-pool-18acfb0d-j09l   Ready    <none>   45h   v1.18.16-gke.502
gk3-cluter-tfg-default-pool-18acfb0d-rskc   Ready    <none>   47h   v1.18.16-gke.502
gk3-cluter-tfg-default-pool-6dd3c0a9-p7rs   Ready    <none>   47h   v1.18.16-gke.502
gk3-cluter-tfg-default-pool-6dd3c0a9-rcpj   Ready    <none>   47h   v1.18.16-gke.502
gk3-cluter-tfg-nap-ap7izk07-af5be935-g0lm   Ready    <none>   21h   v1.18.16-gke.502

and by making a kubectl describe node gk3-cluter-tfg-default-pool-18acfb0d-bx50 it seems that the litmusportal-frontend is located there, but I'm sill having no access. 
Any idea what might be happening?
Thank you!

**Comment by ishangupta-ds** [comment]
Hi @saradocasar have you setup a firewall rule to allow TCP traffic on the node port? If not you may use this command:

gcloud compute firewall-rules create test-node-port --allow tcp:32651

**Comment by saradocasar** [comment]
Hi! 
Its seems it was that!! Thank you so much for your help.

**Comment by ajeshbaby** [comment]
Please do add this in documentation / FAQ and close the same. The next step would be to do a connection check and give this error in litmusctl as part of the pre-check.

**Comment by ksatchit** [comment]
Covered by this FAQ item: https://docs.litmuschaos.io/docs/troubleshooting#not-able-to-connect-to-the-litmus-chaos-control-plane-hosted-on-gke-cluster
