### ISSUE TITLE
LitmusChaos pod not showing up at all in 'litmus' namepsace in a MicroK8S ubuntu cluster

### ISSUE THREAD

**Issue by jnsrikanth** [litmuschaos/litmus#2750]
**What happened**:

I am able to find the CRDs and the deployment for the namespace "litmus" while installing the litmuschaos operator as with the below command.

kubectl apply -f https://litmuschaos.github.io/litmus/litmus-operator-v1.13.3.yaml

**What you expected to happen**:
However I am unable to see any pods in the namespace "litmus" in this cluster. What could be going wrong?

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by uditgaurav** [comment]
Hi @jnsrikanth `https://litmuschaos.github.io/litmus/litmus-operator-v1.13.3.yaml` spec have litmus operator deployment. What happens when you apply the deployment? Do you get the output telling that the deployment is created or not? You can check the pods in litmus ns `kubectl get pods -n litmus`

**Comment by ksatchit** [comment]
Closing for lack of response/presuming issue is not seen at present. Feel free to re-open if you encounter this
