### ISSUE TITLE
ChaosSchedule is creating infinite ChaosEngines and Results in repeat mode 

### ISSUE THREAD

**Issue by RenePinnow** [litmuschaos/litmus#2765]
**What happened**:
Using Chaos Scheduler in repeat mode is creating infinite ChaosEngine and ChaosResult ressources.

**What you expected to happen**:
Why is the Chaos Scheduler not adding the Result of a run everytime in the same result?
Else there should be a automatic cleanup of the ressources by the operator.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy a ChaosSchedule in a namespace in repeat mode

**Anything else we need to know?**:

**Comment by ispeakc0de** [comment]
Closing this issue as it is inactive
