### ISSUE TITLE
Litmus portal giving error: Failed to unmarshal ChaosEngine

### ISSUE THREAD

**Issue by lalitkr90** [litmuschaos/litmus#2767]
I am trying to schedule a workflow using Litmus Portal and I am importing the workflow.yaml from my desktop.
Below is the my workflow.yaml file.
While I am selecting the file, its showing the YAML is good to go but as soon as I am at the last step, its giving me the below error.
![image](https://user-images.githubusercontent.com/47416276/117197227-3019d180-ae05-11eb-9431-7a089d24bc9e.png)
[workflow.txt](https://github.com/litmuschaos/litmus/files/6429754/workflow.txt)

Can you please look into the same, I am using the litmus images with the tag ci.
Below are the pods and services configured.
![image](https://user-images.githubusercontent.com/47416276/117197904-fbf2e080-ae05-11eb-8437-31776b36998a.png)

Please suggest on how to rectify this.

**Comment by lalitkr90** [comment]
I have attached the workflo.txt which I am using for the experiment.
The same is working fine when I am using the argo-server.
![image](https://user-images.githubusercontent.com/47416276/117201722-98b77d00-ae0a-11eb-9474-d3a8428903ba.png)

Below is the litmus portal final step after which I am getting the error.
![image](https://user-images.githubusercontent.com/47416276/117201861-c69cc180-ae0a-11eb-9745-e2334a4f4040.png)

**Comment by lalitkr90** [comment]
Any update on the mentioned error ?

**Comment by amityt** [comment]
Hi @lalitkr90 , we have identified the issue. It is due to some parsing issue in the workflow manifest. Will notify you once the fix is available.

**Comment by S-ayanide** [comment]
Hey @lalitkr90, this issue has been fixed, you can try the latest master ci to test the same. Thanks for letting us know about this and making Litmus better. Cheers 🙌🏻

**Comment by ksatchit** [comment]
Closing this as the issue has been fixed in recent Litmus versions. Please feel free to re-open if you encounter this again!
