### ISSUE TITLE
agent registration successful when chaos-operator is not actually running/ready on agent

### ISSUE THREAD

**Issue by jinjiaw** [litmuschaos/litmus#2798]
**What happened**:
Hi, I am trying out the litmus portal with litmus-2-0-0-beta-2.0.18-Beta6. I happened to find that the agent registration showed successful both on portal->Agent (Active) view and in litmusctl output (Agent Registration Successful) even if chaos-exporter, chaos-operator-ce, event-tracker on the agent side somehow failed to pull their images. i am guessing it is by design that the Subscriber interacts with server and is considered as a successful registration as long as Subscriber is up and running properly?

**What you expected to happen**:
chaos-operator is critical for experiment execution on agent and should be counted for a successful agent registration?

**How to reproduce it (as minimally and precisely as possible)**:
simulate chaos-operator failure during agent registration.

**Anything else we need to know?**:

**Comment by ksatchit** [comment]
Thanks @jinjiaw for this issue. This indeed makes sense and is a good requirement. We need to validate the success of the infra components before marking an agent active. cc: @rajdas98 @gdsoumya
