### ISSUE TITLE
Litmus portal not working in arm64 graviton2 instance

### ISSUE THREAD

**Issue by manee2k6** [litmuschaos/litmus#2847]
**What happened**:
I am trying to setup litmus portal beta7 stable version on graviton2(arm64) instance, but not supported.

**What you expected to happen**:
Litmus portal setup on arm64 will help to target all the services running graviton2(arm64) at different namespace scoped.
Docker images for pod-delete and any experiments being used are not supported in graviton2(arm64). Is there any other way to explore this and make it work?

**How to reproduce it (as minimally and precisely as possible)**:
Setting up the limtus portal on graviton2(arm64) is not supported and all pods are crashing.

**Anything else we need to know?**:

**Comment by rajdas98** [comment]
Thanks, @manee2k6, We'll add the ARM support for Litmus Portal components soon.

**Comment by rajdas98** [comment]
Hi @manee2k6, We have added support for ARM64. Please check and let us know. Here is the PR- https://github.com/litmuschaos/litmus/pull/2858

cc: @uditgaurav
