### ISSUE TITLE
Can't terminal a workflow in Litmus dashboard while the workflow was pending 

### ISSUE THREAD

**Issue by kyonasa** [litmuschaos/litmus#2848]
When I try workflow 'sock-shop-chaos', I got stuck in 'install-chaos-experiments' and 'load-test' and didn't find any place to terminal that workflow.

**Comment by amityt** [comment]
Hi @kyonasa, thanks for trying out litmus. I presume that the sock-shop-chaos workflow was scheduled properly, but the experiment got stuck in `install-chaos-experiment` and `load-test` and the workflow didn't complete. Currently, we dont support workflow termination directly from the dashboard. 
We can surely add this feature in the coming releases.
