### ISSUE TITLE
ImagePullPolicy change to IfNotPresent

### ISSUE THREAD

**Issue by TidalPoo** [litmuschaos/litmus#2850]
After I was able to solve the problem:
https://github.com/litmuschaos/litmus/issues/2846

There is a new problem
I tried to deploy an litmus agent, and again got into the problem of download limits from docker hub

```
litmus        argo-server-58cb64db7f-5xv9q          0/1     ImagePullBackOff   0          72m
litmus        chaos-exporter-547b59d887-wfdvs       0/1     ImagePullBackOff   0          72m
litmus        chaos-operator-ce-84ddc8f5d7-g4brz    0/1     ImagePullBackOff   0          72m
litmus        event-tracker-5bc478cbd7-wz4rq        0/1     ImagePullBackOff   0          72m
litmus        subscriber-958948965-zplbt            0/1     ImagePullBackOff   0          72m
litmus        workflow-controller-78fc7b6c6-kx2hg   0/1     ImagePullBackOff   0          72m
```

But i can't edit litmusctl yaml files to change ImagePullPolicy: Always to IfNotPresent

**Comment by rajdas98** [comment]
Hi @TidalPoo , It's a good requirement to add `pull policy` environment variable in the `litmusportal-server` deployment. so that all agents can be installed with a user-defined `pull policy`.

@ksatchit @ajeshbaby Any other thoughts on this?

**Comment by neelanjan00** [comment]
Hi @imrajdas, is this issue still valid?

**Comment by imrajdas** [comment]
Closing this issue. We decided to use ImagePullPolicy as "Always". And now we are part of the docker hub sponsor OSS project, so the pull limit issue won't be possible.
