### ISSUE TITLE
Wrong command shown to register Litmus Agent 

### ISSUE THREAD

**Issue by k8s-dev** [litmuschaos/litmus#2884]
**What happened**:
Portal shows the command to connect/register the agent is : 
`litmusctl agent connect` whereas litmusctl does not support this command.

**What you expected to happen**:
Replace it with correct command. ie. `litmusctl agent register`

**How to reproduce it (as minimally and precisely as possible)**:
Litmus Portal -> left hand pane -> Agent shows this.

**Anything else we need to know?**:

https://github.com/litmuschaos/litmus/blob/master/litmus-portal/frontend/src/views/Targets/TargetCopy/index.tsx#L32 and https://github.com/litmuschaos/litmus/blob/master/litmus-portal/frontend/src/views/Home/AgentDeployModal/index.tsx#L70 

The PR was : https://github.com/litmuschaos/litmus/pull/2616

**Comment by rajdas98** [comment]
Hi @k8s-dev , `litmusctl agent register` is used in  `litmuctl v0.2.0` and `litmusctl agent register` is used in the master version of `litmusctl`

**Comment by k8s-dev** [comment]
I see two different version of commands in same Portal deployment 
<img width="1150" alt="Screenshot 2021-06-11 at 1 51 21 PM" src="https://user-images.githubusercontent.com/57744184/121655634-627db500-cabc-11eb-83ce-7ab3d4a0f13b.png">
<img width="910" alt="Screenshot 2021-06-11 at 1 51 10 PM" src="https://user-images.githubusercontent.com/57744184/121655664-66a9d280-cabc-11eb-8a18-d211d424b12d.png">

**Comment by Jonsy13** [comment]
Hi @k8s-dev , thanks for trying out Litmus-portal.
Yes, this is a known typo. This is fixed now in master. This will get updated in next release.

**Comment by rajdas98** [comment]
Closing this issue-
We have made the release of LitmusCtl v0.2.0, where `litmusctl agent connect` command is available and also updated the docs for the same.
cc: @k8s-dev
