### ISSUE TITLE
API endpoints for the chaos services

### ISSUE THREAD

**Issue by cookbook87** [litmuschaos/litmus#2888]
litmus Experiments are the most attractive part of litmuschaos, but the most inconvenient part is that it doesn't inherently open an api endpoint to trigger chao scenarios.
 it often makes the life of the developer difficult to test the workflows from a development environment where you need to run the scenarios from CI. Unless the service is exposable from the cluster it is not possible to call it from outside to do some operation.

Also, the litmusportal is in a nascent stage where it is deployed primarily over nodeport where it becomes local, and in an environment of multitenancy it is not feasible to use it as exposing the portal is merely impossible.

While the former part about the api endpoint is very much relevant for a multitenant organizational usage.

## Question
Feel free to get your queries resolved.

**Please make sure you have,**

- Reviewed the [Questions](https://github.com/litmuschaos/litmus/labels/question) asked by our community members and contributers.
- Searched opened and closed [GitHub issues](https://github.com/litmuschaos/litmus/issues)

**We primarily use GitHub as an issue tracker; for usage and support questions, please check out these resources below. Thanks!**

  - [LitmusChaos Readme](https://github.com/litmuschaos/litmus)
  - [LitmusChaos Docs](https://docs.litmuschaos.io/docs/next/getstarted.html)

**Comment by ksatchit** [comment]
cc: @rajdas98 @gdsoumya would you like take this question

**Comment by gdsoumya** [comment]
Litmus portal itself has it's own apis that can be directly called, you would still have to expose the portal either using nodeport or loadbalancer svc. This is the link to the api doc https://litmuschaos.github.io/litmus/api.html, you can also directly see the graphql apis and run queries from the graphql playground that is exposed by the litmusportal server service

**Comment by cookbook87** [comment]
There are lot of constraints in exposing services via nodeport/load balancers in some kube platforms especially when its a closed one and an on premise cluster application, ClusterIP is the ideal way to do that, I had tried to do it and services always fails to spawn up.

**Comment by cookbook87** [comment]
Also what if someone doesn't deploy limusportal, and still wants to get chaosresults via APIs or run experiments via apis?

**Comment by ksatchit** [comment]
@cookbook87 in case you'd like to directly consume/manipulate the chaos resources (i.e., chaosexperiment, chaosengine or chaosresults) via API - you can directly use the kube API. The CRDs by default us with an API endpoint. You can use any generic client implementation (go/python are most used ones) to access them. In case you use go, there is a clientset available as well: https://github.com/litmuschaos/chaos-operator/tree/master/pkg/client/clientset/versioned/typed/litmuschaos/v1alpha1

Here are some simple CRUD ops against chaosresources you could construct with curl (I have used kubectl proxy, one could use an auth token instead)- just for illustration purposes. 

- Create ChaosEngine: 

  For example, assume this is the engine spec: https://gist.github.com/ksatchit/7426f2c24a48e3aedbe79b5547d817b3

  ```bash
  curl -s http://localhost:8001/apis/litmuschaos.io/v1alpha1/namespaces/default/chaosengines -XPOST -H 'Content-Type: application/json' -d@pod-delete-chaosengine-trigger.json
  ```

- Read ChaosEngine status: 

   ```bash
   curl -s http://localhost:8001/apis/litmuschaos.io/v1alpha1/namespaces/default/chaosengines/nginx-chaos | jq '.status.engineStatus, .status.experiments[].verdict'
   ```

- Update ChaosEngine Spec: (say, this is the patch: https://gist.github.com/ksatchit/be54955a1f4231314797f25361ac488d) 

   ```bash
   curl --header "Content-Type: application/json-patch+json" --request PATCH --data '[{"op": "replace", "path": "/spec/engineState", "value": "stop"}]' http://localhost:8001/apis/litmuschaos.io/v1alpha1/namespaces/default/chaosengines/nginx-chaos
   ```

- Delete the ChaosEngine resource: 
 
  ```bash
   curl -X DELETE localhost:8001/apis/litmuschaos.io/v1alpha1/namespaces/default/chaosengines/nginx-chaos \
  -d '{"kind":"DeleteOptions","apiVersion":"v1","propagationPolicy":"Foreground"}' \
  -H "Content-Type: application/json"
  ```

Similarly, to check the results/verdict of the experiment from ChaosResult, you could use: 

```bash
curl -s http://localhost:8001/apis/litmuschaos.io/v1alpha1/namespaces/default/chaosresults/nginx-chaos-pod-delete | jq '.status.experimentStatus.verdict, .status.experimentStatus.probeSuccessPercentage'
```

**Comment by cookbook87** [comment]
Thanks @ksatchit  This helps. so I need to create all the specs in json. 
By any chance is there any python clients which are equivalent to those go clients?


Also, the API opens up via localhost and port 8001, Is there a way that I could expose it as a microservice endpoint and also customize this port to a port of my choice? It will definitely need a change in the manifest. Do you have any suggestion in that aspect?

Also one small input. In most of the hybrid cloud it is mandatory to have resource definition to deploy. I think it is better that manifests has the following, I learnt it in the hard way but wanted to share.

`resources:
            requests:
              memory: 128Mi
              cpu: 50m
            limits:
              memory: 128Mi
              cpu: 50m`

**Comment by cookbook87** [comment]
After deployment, I have tried as directed.
the localhost itself is not reachable.

it clearly says connection refused.

bash-4.4$ curl http://localhost:8001/apis/litmuschaos.io/v1alpha1/namespaces/default/
curl: (7) Failed to connect to localhost port 8001: Connection refused

**Comment by ksatchit** [comment]
This was also discussed on slack: the apiserver access has been enabled in this [comment](https://github.com/litmuschaos/litmus/issues/2888#issuecomment-859766605) using kubectl proxy and is more for illustration purposes.
