### ISSUE TITLE
Generating Test Reports from ChaosSchedule or ChaosResult

### ISSUE THREAD

**Issue by jnsrikanth** [litmuschaos/litmus#2896]
## Question

Hi, Is there a provision in LitmusChaos Tool for us to generate a Test Report (from the Kubectl CLI) or from the Litmus Portal for all the individual Chaos Experiments conducted in a sequence or in a workflow?

Please let me know, what are all the options available and what custom methods can we use to generate reports of our own in CSV or in JSON format etc.?

Please let me know.

Thanks,
Srikanth

**Please make sure you have,**

- Reviewed the [Questions](https://github.com/litmuschaos/litmus/labels/question) asked by our community members and contributers.
- Searched opened and closed [GitHub issues](https://github.com/litmuschaos/litmus/issues)

**We primarily use GitHub as an issue tracker; for usage and support questions, please check out these resources below. Thanks!**

  - [LitmusChaos Readme](https://github.com/litmuschaos/litmus)
  - [LitmusChaos Docs](https://docs.litmuschaos.io/docs/next/getstarted.html)

**Comment by ksatchit** [comment]
The litmus portal consists of an "Analytics" section that has an option to compare workflows and download reports - available as html/pdf.

**Comment by ksatchit** [comment]
ChaosResults in xUnit format is being tracked via this issue: https://github.com/litmuschaos/litmus/issues/2839, in case that is what is being requested. 

In case you'd like the results in JSON format using kubectl - please use the `-o json` flag in the command
