### ISSUE TITLE
Add NodeSelector/Tolerations feature to control-plane

### ISSUE THREAD

**Issue by devfaz** [litmuschaos/litmus#2911]
It would be nice if there would be a way to add some NodeSelector and Tolerations to pods used by litmus "control-plane". This would allow us to place litmus on separate nodes we normally use for this kind of services (monitoring, logging, ...)

**Comment by ksatchit** [comment]
Thanks @devfaz for the suggestion - this is definitely useful and is already being worked by @rajdas98 !
