### ISSUE TITLE
Generic pod-delete failed in chaos injection phase

### ISSUE THREAD

**Issue by TajaneSwapnil** [litmuschaos/litmus#2922]
**What happened**:
I have a kubernetes cluster consisting on 9 pods (3 applications*3 instances).
I tried to execute delete pod on one of the instance which has unique label.

I cannot see any detailed information about why it happened.

below is the chaos engine describe result
 `Events:
  Type     Reason                         Age                  From                     Message
  ----     ------                         ----                 ----                     -------
  Normal   ExperimentJobCreate            9m50s                delete-chaos-runner      `Experiment` Job pod-delete-txw5yw for Chaos Experiment: pod-delete
  Normal   ExperimentDependencyCheck      9m50s                delete-chaos-runner      Experiment resources validated for Chaos Experiment: pod-delete
  Normal   PreChaosCheck                  9m42s                pod-delete-txw5yw-2f7wv  AUT: Running
  Warning  Summary                        9m42s                pod-delete-txw5yw-2f7wv  experiment: pod-delete, Result: Fail
  Normal   ExperimentJobCleanUp           9m28s                delete-chaos-runner      Experiment Job: pod-delete-txw5yw will be deleted
  Normal   ChaosEngineCompleted           9m27s (x8 over 12h)  chaos-operator           ChaosEngine completed, will delete or retain the resources according to jobCleanUpPolicy
[root@ipxxxxx~]#`

Below is the describe chaos result 
`Status:
  Experiment Status:
    Fail Step:                 failed in chaos injection phase
    Phase:                     Completed
    Probe Success Percentage:  0
    Verdict:                   Fail
  History:
    Failed Runs:   8
    Passed Runs:   0
    Stopped Runs:  0
Events:
  Type     Reason   Age   From                     Message
  ----     ------   ----  ----                     -------
  Normal   Awaited  14m   pod-delete-txw5yw-2f7wv  experiment: pod-delete, Result: Awaited
  Warning  Fail     14m   pod-delete-txw5yw-2f7wv  experiment: pod-delete, Result: Fail`

**What you expected to happen**:
Delete pod successfully

**How to reproduce it (as minimally and precisely as possible)**:
1. Demo application(Micronaut, Gradle) deployed on a kubernetes with 3 nodes 
2. Try running it from AWS CLI with root user
3. Rest just follow the guide of get started in Litmus documentation 

**Anything else we need to know?**:
Applications are deployed in Default namespace

**Comment by ispeakc0de** [comment]
HI @TajaneSwapnil,

Can you please share logs of the `pod-delete-txw5yw-2f7wv` pod?

**Comment by TajaneSwapnil** [comment]
Unfortunately with current architecture I cannot get logs for terminated pods
