### ISSUE TITLE
Litmus webapp should be able to load from "/litmus" path inaddition to "/" path

### ISSUE THREAD

**Issue by asibece** [litmuschaos/litmus#2942]
We are not able to access litmus portal from /litmus path when we setup an ingress path for litmus portal within an enterprise, we need litmus app to be loaded from customized paths inaddition to root path "/". Hence request to configure litmus to load from "/litmus" path inaddition to "/" path.

Thanks.

**Comment by prithvi1307** [comment]
Hi, @asibece Could you ask the same question by joining the Litmus slack channel as well? 
Assigning @ksatchit this but just in case you don't get an immediate response here you surely will in our slack community for this as well as further questions!
To join the slack please follow the following steps!
Step 1: Join the Kubernetes slack using the following link: https://slack.k8s.io/
Step 2: Join the #litmus channel on the Kubernetes slack or use this link after joining the Kubernetes slack: https://slack.litmuschaos.io/

Thanks
