### ISSUE TITLE
Add Support for SSL/TLS in Kafka Chaos Experiments

### ISSUE THREAD

**Issue by jnsrikanth** [litmuschaos/litmus#2959]
Need to add SSL/TLS support for (Confluent) Kafka Experiments in LitmusChaos. 

A typical set of SSL params that needs to be provisioned/configured for any client trying to communicate with an SSL enabled Kafka Brokers or a StatefulSet Deployment. An example set of parameters are given below for a client to connect to a Kafka Broker/Server.

listeners=PLAINTEXT://:9092,SSL://:9093
ssl.keystore.location=/opt/kafka/config/kafka01.keystore.jks
ssl.keystore.password=vertica
ssl.key.password=vertica
ssl.truststore.location=/opt/kafka/config/kafka.truststore.jks
ssl.truststore.password=vertica
ssl.enabled.protocols=TLSv1.2,TLSv1.1,TLSv1
ssl.client.auth=required

A detailed overview for supporting SSL/TLS enabled Kafka configuration is given in the below link...

https://docs.confluent.io/platform/current/kafka/authentication_ssl.html

Will be happy to answer any follow up questions.

Thanks,
Srikanth

**Comment by jnsrikanth** [comment]
@ksatchit - PR has been raised - is there any additional steps for implementing TLS/SSL in Kafka LitmusChaos experiments?
Please let me know.

-Srikanth

**Comment by jnsrikanth** [comment]
@ksatchit any updates on this PR? Does the latest version of Litmuschaos have support for TLS in Kafka?

**Comment by ksatchit** [comment]
This is an issue @jnsrikanth , not a PR! This is in our backlog for sure - just that it is not an immediate term item. We will update the status on the duplicate issue https://github.com/litmuschaos/litmus/issues/2957
