### ISSUE TITLE
Create unit test for /pkg/exec/exec.go

### ISSUE THREAD

**Issue by ksatchit** [litmuschaos/litmus#298]
## Is this a BUG REPORT or FEATURE REQUEST?
FEATURE REQUEST

**What happened**:

- Create unit test for https://github.com/openebs/litmus/blob/master/pkg/exec/exec.go

**Anything else we need to know?**:

- Refer tests at https://github.com/openebs/maya/tree/master/pkg/task/v1alpha1

**Comment by kaustumbh7** [comment]
I would like to take this issue.

**Comment by ksatchit** [comment]
Sure @kaustumbh7 !

**Comment by ksatchit** [comment]
The go-based executor has been deprecated for now, with plans for the same being developed independently in a separate repo. Closing this issue now. Will be created on the new repo once available.
