### ISSUE TITLE
Litmus chaos pod cpu hog experiment showing failed verdict sometimes

### ISSUE THREAD

**Issue by rini2208** [litmuschaos/litmus#2990]
While running pod cpu hog experiment , sometimes experiment is failing with below logs.
Kill command used is kill $(find /proc -name exe -lname '*/md5sum' 2>&1 | grep -v 'Permission denied' | awk -F/ '{print $(NF-1)}').
Command is working at pod level fine.

W0712 07:30:12.374586       1 client_config.go:541] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2021-07-12T07:30:12Z" level=info msg="Experiment Name: pod-cpu-hog"
time="2021-07-12T07:30:12Z" level=info msg="[PreReq]: Getting the ENV for the  experiment"
time="2021-07-12T07:30:12Z" level=info msg="[PreReq]: Updating the chaos result of pod-cpu-hog experiment (SOT)"
time="2021-07-12T07:30:12Z" level=info msg="The application information is as follows" Ramp Time=0 Namespace=atom Label="app=atom-core" Chaos Duration=60
time="2021-07-12T07:30:12Z" level=info msg="[Status]: Verify that the AUT (Application Under Test) is running (pre-chaos)"
time="2021-07-12T07:30:12Z" level=info msg="[Status]: Checking whether application containers are in ready state"
time="2021-07-12T07:30:12Z" level=info msg="[Status]: The Container status are as follows" Readiness=true container=atom-core Pod=atom-core-57f9c5ffd6-66d2s
time="2021-07-12T07:30:12Z" level=info msg="[Status]: The Container status are as follows" Pod=atom-core-57f9c5ffd6-947vb Readiness=true container=atom-core
time="2021-07-12T07:30:14Z" level=info msg="[Status]: Checking whether application pods are in running state"
time="2021-07-12T07:30:14Z" level=info msg="[Status]: The status of Pods are as follows" Pod=atom-core-57f9c5ffd6-66d2s Status=Running
time="2021-07-12T07:30:14Z" level=info msg="[Status]: The status of Pods are as follows" Status=Running Pod=atom-core-57f9c5ffd6-947vb
time="2021-07-12T07:30:16Z" level=info msg="[Info]: chaos candidate of kind: deployment, name: atom-core, namespace: atom"
time="2021-07-12T07:30:16Z" level=info msg="[Info]: chaos candidate of kind: deployment, name: atom-core, namespace: atom"
time="2021-07-12T07:30:16Z" level=info msg="[Chaos]:Number of pods targeted: 1"
time="2021-07-12T07:30:16Z" level=info msg="Target pods list for chaos, [atom-core-57f9c5ffd6-947vb]"
time="2021-07-12T07:30:16Z" level=info msg="[Chaos]: The Target application details" Target Pod=atom-core-57f9c5ffd6-947vb CPU CORE=2 Target Container=atom-core
time="2021-07-12T07:30:16Z" level=info msg="[Chaos]:Waiting for: 60s"
time="2021-07-12T07:31:16Z" level=info msg="[Chaos]: Time is up for experiment: pod-cpu-hog"
/bin/sh: 1: kill: Illegal number: task
time="2021-07-12T07:31:24Z" level=error msg="[Error]: CPU hog failed, err: Unable to kill the stress process in atom-core-57f9c5ffd6-947vb pod, err: command terminated with exit code 2"

**Comment by uditgaurav** [comment]
We need to derive the right command to kill the stress process after chaos injection. This issue should be resolved from litmus 1.13.8.

**Comment by uditgaurav** [comment]
This issue should be resolved by using the updated pod cpu hog experiment. The older approach is also retained with a different name called pod-cpu-hog-exec. Refer to this for more details - https://litmuschaos.github.io/litmus/experiments/faq/experiments/#whats-the-difference-between-pod-memorycpu-hog-vs-pod-memorycpu-hog-exec.

Feel free to reopen it in case of any difficulty. Thanks!
