### ISSUE TITLE
md5sum process issue for pod cpu hog experiment

### ISSUE THREAD

**Issue by rini2208** [litmuschaos/litmus#2991]
While running pod cpu hog experiment at given time we are seeing 2 md5sum processes running instead of one. We are litmus operator , experiment and rbac version 13.6 .
As seen in image in given minute , 2 md5sum processes running.

![image](https://user-images.githubusercontent.com/83286730/125251415-e7a2f680-e314-11eb-8a7a-87010b64249e.png)

**Comment by uditgaurav** [comment]
Hi, @rini2208 each `md5sum` process hog 1 Core of `CPU` so if you've provided 2 `CPU_CORES` in the engine as an input then the two parallel threads will combine to consume the two cores for cpu.

**NOTE:** From litmus 1.13.8 this experiment is renamed as `pod-cpu-hog-exec` and you can also use the non-exec mode of chaos injection with the new pod-cpu-hog experiment.

**Comment by uditgaurav** [comment]
The non-exec mode use stress-ng in place of md5sum feel free to give it a try. please refer this for more details https://litmuschaos.github.io/litmus/experiments/faq/experiments/#whats-the-difference-between-pod-memorycpu-hog-vs-pod-memorycpu-hog-exec. Thanks!
