### ISSUE TITLE
Store agent manifest(YAML) in the database during cluster register mutation.

### ISSUE THREAD

**Issue by rajdas98** [litmuschaos/litmus#3003]
Currently, we are dynamically generating the agent manifest. Request for storing the manifest(yaml) during the cluster register mutation.

**Comment by rajdas98** [comment]
cc: @gdsoumya

**Comment by 123vivekr** [comment]
Hi, I'd like to work on this. Can you give me a brief idea on how to go about implementing this?

**Comment by gdsoumya** [comment]
@rajdas98 I don't think this is needed anymore

**Comment by rajdas98** [comment]
Okay
