### ISSUE TITLE
Create unit test for pkg/verify/verify.go

### ISSUE THREAD

**Issue by ksatchit** [litmuschaos/litmus#302]
## Is this a BUG REPORT or FEATURE REQUEST?
FEATURE REQUEST

**What happened**:

- Create unit test for https://github.com/openebs/litmus/blob/master/pkg/verify/verify.go

**Anything else we need to know?**:

- Refer the tests at https://github.com/openebs/maya/tree/master/pkg/task/v1alpha1

**Comment by egurnov** [comment]
taking this one

**Comment by James-N-M** [comment]
Assign this issue to me please !

**Comment by ksatchit** [comment]
The go-based executor has been deprecated for now, with plans for the same being developed independently in a separate repo. Closing this issue now. Will be created on the new repo once available.
