### ISSUE TITLE
Update TestType fields in result custom resource spec in the litmus tests

### ISSUE THREAD

**Issue by nsathyaseelan** [litmuschaos/litmus#303]
Is this a BUG REPORT or FEATURE REQUEST?
FEATURE REQUEST

**What happened:**

Litmus result custom resource jinja template: https://github.com/openebs/litmus/blob/master/hack/litmus-result.j2)

Currently, the result custom resource updates (which are done at the beginning of a test's execution, i.e., before proceeding to the business logic (SoT) - and - upon completion of test business logic (EoT)) which are performed in a litmus test playbooks (refer test.yml of any given litmus test) only update the test name, test phase, app, chasotype & test result fields of the CR.

It is desirable to update the Testype field of the CR in order to facilitate filtering of results for a given type  test.

**Comment by ksatchit** [comment]
The standard litmusbooks now solely perform chaos.
