### ISSUE TITLE
does litmus demo support aks platform?

### ISSUE THREAD

**Issue by nitinkansal1984** [litmuschaos/litmus#3042]
## Question
Feel free to get your queries resolved.

**Please make sure you have,**

- Reviewed the [Questions](https://github.com/litmuschaos/litmus/labels/question) asked by our community members and contributers.
- Searched opened and closed [GitHub issues](https://github.com/litmuschaos/litmus/issues)

**We primarily use GitHub as an issue tracker; for usage and support questions, please check out these resources below. Thanks!**

  - [LitmusChaos Readme](https://github.com/litmuschaos/litmus)
  - [LitmusChaos Docs](https://docs.litmuschaos.io/docs/next/getstarted.html)

**Comment by ksatchit** [comment]
Duplicate of #3043
