### ISSUE TITLE
Docker image build workflow

### ISSUE THREAD

**Issue by Vr00mm** [litmuschaos/litmus#3048]
## Question
Hello guys,

I need to understand something about the docker build / push workflow.
Some commits goes merged yesterday in the master branch but the docker image on docker hub 
have a creation date 8days ago.
![image](https://user-images.githubusercontent.com/87191932/126767867-5ddabc24-b00c-4595-b42b-427bfa665f31.png)

Can you push the latest docker image please ? I excepted the new API route available in graphql ( it make fail my helm pull request )

See you later,
Best regards,
Rémi
**Please make sure you have,**

- Reviewed the [Questions](https://github.com/litmuschaos/litmus/labels/question) asked by our community members and contributers.
- Searched opened and closed [GitHub issues](https://github.com/litmuschaos/litmus/issues)

**We primarily use GitHub as an issue tracker; for usage and support questions, please check out these resources below. Thanks!**

  - [LitmusChaos Readme](https://github.com/litmuschaos/litmus)
  - [LitmusChaos Docs](https://docs.litmuschaos.io/docs/next/getstarted.html)

**Comment by rajdas98** [comment]
Hi @Vr00mm, We have a `ci` tag which have the latest changes. 

Here- https://hub.docker.com/layers/litmuschaos/litmusportal-server/ci/images/sha256-9fd945595733220400db9de173b97be96f7ffa1c598a748bf605b17db23f13a9

**Comment by Vr00mm** [comment]
Hello @rajdas98,
Ok, thanx !
