### ISSUE TITLE
Logic flaw in pkg/verify/verify.go

### ISSUE THREAD

**Issue by egurnov** [litmuschaos/litmus#305]
## Is this a BUG REPORT or FEATURE REQUEST?
 
BUG REPORT

**What happened**: 
Looks like a potential logic flaw. Results from individual components need to be ANDed together to produce the result for all components, yet only the most recent value is stored, making the result for the last component to be presented as an overall result for all of them.

https://github.com/openebs/litmus/blob/2d1152a1d708dbf7005274e9adf78cb14a48fbff/pkg/verify/verify.go#L232-L237
https://github.com/openebs/litmus/blob/2d1152a1d708dbf7005274e9adf78cb14a48fbff/pkg/verify/verify.go#L249-L254
https://github.com/openebs/litmus/blob/2d1152a1d708dbf7005274e9adf78cb14a48fbff/pkg/verify/verify.go#L266-L275

**Comment by AmitKumarDas** [comment]
@egurnov While I agree there is a potential to improve the logic, however I still did not understand the comments clearly.  The predicate (i.e. conditional) logic fails if all the components do not satisfy the condition.

**Comment by AmitKumarDas** [comment]
@egurnov Thanks. Understood the problem. The concerns raised should be addressed.

**Comment by codegagan** [comment]
looking at it.

**Comment by ksatchit** [comment]
The go-based executor has been deprecated for now, with plans for the same being developed independently in a separate repo. Closing this issue now. Will be created on the new repo once available.
