### ISSUE TITLE
"Edit Sequence" and "Edit Yaml" option is not working in Firefox browser

### ISSUE THREAD

**Issue by vamsiammineni** [litmuschaos/litmus#3067]
**What happened**:
Blank page appears in Litmus Portal (Only in Firefox browser) when I try to "Edit the sequene" or "Edit Yaml" of a workflow.

**What you expected to happen**:
Expected to proceed further to submit the workflow with changes

**How to reproduce it (as minimally and precisely as possible)**:
1. Schedule a workflow
2. Choose Agent
3. Create a new workflow using the experiments form MyHub
4. Workflow settings (name change)
5. Tune the selected workflow
6. Add a new experiment (added two experiments)
7. Edit Yaml to make the two experiments run in parallel
8. Save changes(After clicking on the save changes, I got the blank page.)
9. Same problem appears with the "Edit Sequence" or clicking on the added experiment

**Anything else we need to know?**:
Problem did not appear on Chrome browser.
Litmus 2.0.0-Beta9 version is being used

**Comment by Montatip16** [comment]
> 
> 
> **What happened**:
> Blank page appears in Litmus Portal (Only in Firefox browser) when I try to "Edit the sequene" or "Edit Yaml" of a workflow.
> 
> **What you expected to happen**:
> Expected to proceed further to submit the workflow with changes
> 
> **How to reproduce it (as minimally and precisely as possible)**:
> 1. Schedule a workflow
> 2. Choose Agent
> 3. Create a new workflow using the experiments form MyHub
> 4. Workflow settings (name change)
> 5. Tune the selected workflow
> 6. Add a new experiment (added two experiments)
> 7. Edit Yaml to make the two experiments run in parallel
> 8. Save changes(After clicking on the save changes, I got the blank page.)
> 9. Same problem appears with the "Edit Sequence" or clicking on the added experiment
> 
> **Anything else we need to know?**:
> Problem did not appear on Chrome browser.
> Litmus 2.0.0-Beta9 version is being used

[]()montatip16

**Comment by ksatchit** [comment]
cc: @AmitKumarDas @S-ayanide

**Comment by amityt** [comment]
Hi @vamsiammineni. I tried to replicate the above issue on Firefox, looks like the changes are already fixed with newer releases.

![Screenshot (17)](https://user-images.githubusercontent.com/40661238/146804643-1098e6df-0774-4821-90c0-029724cbfc41.png)
![Screenshot (18)](https://user-images.githubusercontent.com/40661238/146804647-608a0919-0310-4ad0-bea4-1692148fbf6b.png)

**Closing the issues, since it is already fixed**
