### ISSUE TITLE
Run Chaos Runner and Operator with a Non-Root User Group

### ISSUE THREAD

**Issue by chirangaalwis** [litmuschaos/litmus#3075]
### Description:
Run the Chaos Operator and Runner container deployments with a non-root user group.

According to the [discussion](https://kubernetes.slack.com/archives/CNXNB0ZTN/p1627906262089500), these components do not need any root user/group privileges during execution.

**Comment by uditgaurav** [comment]
The Dockerfile includes a line that changes the group of the application directories to group ID 0, which is the root group:

```
# change to 0(root) group because openshift will run container with arbitrary uid as a member of root group
&& chgrp -R 0 "$APP_DIR" "$DATA_DIR" "$CONF_DIR" \
&& chmod -R g=u "$APP_DIR" "$DATA_DIR" "$CONF_DIR"
```

This means that while the container's processes run as the non-root litmus user, the application directories are owned by the root group to accommodate running on OpenShift, which assigns arbitrary user IDs to containers but always includes the root group. The permissions are also set to allow group access to these directories.

Refer base image dockerfile: https://github.com/litmuschaos/test-tools/blob/master/custom/hardened-alpine/infra/Dockerfile
