### ISSUE TITLE
Prepare E2E dashboard with pipeline details and enhance litmus e2e website

### ISSUE THREAD

**Issue by uditgaurav** [litmuschaos/litmus#3112]
## Feature Request Details

This is the feature request to add an e2e dashboard that represents the pipeline details of the [scheduled](https://litmuschaos.github.io/litmus-e2e/generic-pipeline/pipeline-runs/pod-level-run.html) and [manual](https://github.com/litmuschaos/litmus-e2e/tree/master/.github/workflows) runs. This dashboard will contain details like:

- ## Difference between two consecutive scheduled pipeline runs
  The difference can be the "_new PR numbers_/_commits_" that are added in the repository and are running in the pipeline.

- ## Pass and Fail test counts
  Represent the number of passed, failed, canceled tests in the pipeline 
  
![image](https://user-images.githubusercontent.com/35391335/128865988-b95259f5-505a-4444-832b-5c50b4733e3e.png)

-  ## Current pipeline status and final verdict
  The current status of the pipeline whether it is running or completed. If completed what is the verdict, is it passed/failed/skipped
  
 ![image](https://user-images.githubusercontent.com/35391335/128866168-8869a418-a2d9-42f1-b333-10ccd80f4b54.png)
 
- ## Capture and display the failed step in the test
  We need to capture the failed step for a test and display it.
  
- ## Multiple pipelines in the sidebar
  The dashboard should contain all the litmus backend and portal pipelines and it should be easy to switch or add more pipelines. Currently, [these](https://github.com/litmuschaos/litmus-e2e/tree/master/.github/workflows) are the pipeline present in the e2e.

 **NOTE: The above points are for the illustration purpose to give you an idea. We can add more details to make a complete useful dashboard. We can refer to the following dashboards to get an idea.**
 
 - https://openebs.ci/home
 - https://prow.k8s.io/?repo=kubernetes%2Fkubernetes

**Comment by aribalam** [comment]
Hi @uditgaurav, I am a final year student from IIT Kharagpur, and willing to work under this organization under LFX Mentorship programme. Could you give me idea what do you expect me to do for my application? Any previous knowledge needed for it?

**Comment by BhargaviChada** [comment]
Hello @uditgaurav , I am new to Litmus project, could you tell me how can beginners start contributing to the project. Also is there any Slack channel that we can join to ask queries regarding any issues that we run into while working on good first issues?

**Comment by wisdomekpotu** [comment]
Hi @uditgaurav , My name is Wisdom Ekpotu, I am a Third Year Computer Engineering Student from University of Uyo, Nigeria. I saw this project in the LFX mentorship fall 2021 and I thought this project had some parallels with my skills. I would love to contribute to this project and I'm open to learning any new technologies required for the project.
Also does this project have an official Slack channel that we can join to get more information about the project.I am really looking forward to contributing to this project!

**Comment by ShivamTyagi12345** [comment]
hello @uditgaurav  .Myself Shivam Tyagi . I come here with an interest to work on this Upstream Issue as a part of the LFX mentorship Fall 2021. I have made past contributions to [CNCF / glossary](https://github.com/cncf/glossary/pull/204) and am looking forward to learn further .

**Comment by rukundob451** [comment]
Hello there @uditgaurav, My name is Benjamin Rukundo. I am a Software Engineering student from Makerere University Kampala, Uganda. I came across this project in the LFX mentorship fall 2021 and I would surely like to contribute to this project as I am open to using my open source skills to contribute more and more.

**Comment by uditgaurav** [comment]
Hi everyone, please feel free to apply from your portal we'll reach out to everyone for discussing the use case in detail.
Thanks.

**Comment by uditgaurav** [comment]
Hi @BhargaviChada, you can join our litmus slack channel. 

To join our slack please follow the following steps!
Step 1: Join the Kubernetes slack using the following link: https://slack.k8s.io/
Step 2: Join the #litmus channel on the Kubernetes slack or use this link after joining the Kubernetes slack: https://slack.litmuschaos.io/

**Comment by rajdas98** [comment]
Hi Everyone, Thanks for showing interest in this project. Feel free to submit your proposal before the deadline(22nd Aug).
Here- https://mentorship.lfx.linuxfoundation.org/project/6f1497c6-f583-462e-bd67-b3f0bb3df5cb

Regards,
Raj

**Comment by wisdomekpotu** [comment]
hi @rajdas98 @uditgaurav, I just submitted my application for this project on the LFX mentorship Platform

**Comment by notrealanurag** [comment]
Hello there @uditgaurav & @rajdas98 , at the last moment, but I submitted my resume and cover letter on the LFX Portal to become a mentee on this Litmus Project.
I ve started going through the Code Base and understood the scope of the project. Looking forward to discuss more about the Project.

Thanks
