### ISSUE TITLE
Develop/Enhance E2E test-cases for ChaosCenter 

### ISSUE THREAD

**Issue by Jonsy13** [litmuschaos/litmus#3114]
This is a feature request for enhancing the ChaosCenter-E2E test suite.

### Details
Currently, The ChaosCenter Pipeline consists of tests for Installation, Workflow Scheduling, Hub CRUD operations, Teaming, Settings & Cleanup, which tests the basic functionality of ChasoCenter.

Additional Scenarios or improvements which can be added for different features are as follows - 

- **Workflow Scheduling** - 
  - Tests for workflow schedules can be made more optimized & robust as they are a bit flaky due to delays in the mounting of frontend components sometimes.
  - Tests for validation of scheduled workflow, when it is running (Dagre graph nodes & workflow details) in different scenarios.
  - Tests for validation of the Final verdict & resilience score have to be added.

- **Observability** - 
  - Workflow Analytics
    - Tests for validating details shown on Schedule Analytics screen (Recurring & non-Recurring)
    - Tests for validating workflows comparison.
    - Tests for workflows & schedules statistics.

  - Datasource & Dashboard configuration
    - Tests for Validating Successful Datasource configuration & Other scenarios (Negative cases also)
    - Tests for validating Successful Dashboards configuration & Other scenarios (Negative cases also)
   
- Performance testing of Portal is also one of the requirements now.

> Note: Above scenarios are for starting with e2e-cases for different features. Other test suites can also be consolidated.

**To accomplish this, one should try using ChaosCenter to know the functionalities.**

Check the contributing [guide](https://github.com/litmuschaos/litmus-e2e/blob/master/Cypress/Readme.md)

**Comment by anonymousr007** [comment]
Hi @rajdas98 , I am final year Computer Engineering at Delhi Technological University. I am a javascript developer and i know basics of golang and I want to work in this project but new in this type of project.Can you please guide me  and how to select for this project ? 

Thanks & Regards
Rishabh

**Comment by DhananjayPurohit** [comment]
Hey @rajdas98, I just completed my Google Summer of Code 2021 with Orcasound and looking forward to exploring more in my journey. I am experienced with JavaScript and have some hands-on experience with Kubernetes too. I am looking forward to submitting a proposal for this project under LFX-Mentorship, It would be great if there is any guide or template that can help me draft my proposal.

**Comment by rajdas98** [comment]
Hi Everyone, Thanks for showing interest in this project. Feel free to submit your proposal before the deadline(22nd Aug). 
Here- https://mentorship.lfx.linuxfoundation.org/project/8e9537fe-fdea-4f92-941d-e86d2fcb48ba

Regards,
Raj

**Comment by Zain-Muiz** [comment]
Heyy @rajdas98 @Jonsy13 , Can you suggest some resources which might specifically help in understanding how to effectively write E2E tests in regards with Litmus, that we can go through in the mean time ?

**Comment by Jonsy13** [comment]
Closing this issue,since the tasks have been completed.
