### ISSUE TITLE
Unable to run chaos Experiments in default namespace

### ISSUE THREAD

**Issue by ShinyAnnie** [litmuschaos/litmus#3132]
Hi Chaos Support,

We are using litmus chaos toolkit to run experiments.
We are unable to run any experiment in the default namespace.
Error is :
Warning ChaosResourcesOperationFailed 47m (x25 over 6d19h) chaos-operator (chaos start) Unable to get chaos resources
Could you please help us at the earliest as we are completely stuck?

Thanks.

**Comment by ShinyAnnie** [comment]
Could you please help at the earliest?

**Comment by prithvi1307** [comment]
Tagging @ispeakc0de @ajeshbaby for assistance.
@ShinyAnnie would urge you to ask the same question in the slack community for quick assistance.
To join our slack please follow the following steps!
Step 1: Join the Kubernetes slack using the following link: https://slack.k8s.io/
Step 2: Join the #litmus channel on the Kubernetes slack or use this link after joining the Kubernetes slack: https://slack.litmuschaos.io/

**Comment by ShinyAnnie** [comment]
> Tagging @ispeakc0de @ajeshbaby for assistance.
> @ShinyAnnie would urge you to ask the same question in the slack community for quick assistance.
> To join our slack please follow the following steps!
> Step 1: Join the Kubernetes slack using the following link: https://slack.k8s.io/
> Step 2: Join the #litmus channel on the Kubernetes slack or use this link after joining the Kubernetes slack: https://slack.litmuschaos.io/

Sure Thanks. Posted it.

**Comment by ksatchit** [comment]
The discussions are tracked here: 

-  https://kubernetes.slack.com/archives/CNXNB0ZTN/p1629102881015000
- https://kubernetes.slack.com/archives/CNXNB0ZTN/p1629187177059600

The issues was resolved by preventing istio sidecar proxy injection in the chaos pods
