### ISSUE TITLE
Link "Install Litmux Operator" is not working

### ISSUE THREAD

**Issue by brsvpr** [litmuschaos/litmus#3143]
I am trying to install litmux and experiments for K8s PODs in AWS

1) Link "Install Litmux Operator" is not working
2) This yaml is not working
kubectl apply -f https://hub.litmuschaos.io/api/chaos/2.0.0?file=charts/generic/experiments.yaml
kubectl apply -f https://hub.litmuschaos.io/api/chaos/2.0.0?file=charts/kube-aws/experiments.yaml

![image](https://user-images.githubusercontent.com/16670189/129767448-6cc999d5-9e1f-4885-97fb-92c39cdff8a0.png)

>> kubectl apply -f experiments.yaml
unable to recognize "experiments.yaml": no matches for kind "ChaosExperiment" in version "litmuschaos.io/v1alpha1"
unable to recognize "experiments.yaml": no matches for kind "ChaosExperiment" in version "litmuschaos.io/v1alpha1"
unable to recognize "experiments.yaml": no matches for kind "ChaosExperiment" in version "litmuschaos.io/v1alpha1"
unable to recognize "experiments.yaml": no matches for kind "ChaosExperiment" in version "litmuschaos.io/v1alpha1"
unable to recognize "experiments.yaml": no matches for kind "ChaosExperiment" in version "litmuschaos.io/v1alpha1"
unable to recognize "experiments.yaml": no matches for kind "ChaosExperiment" in version "litmuschaos.io/v1alpha1"

Can you please help to find why this error and help to resolve it ?

Thanks,
Sai

**Comment by prithvi1307** [comment]
Hi, @brsvpr  have added @uditgaurav  for some comments on this, meanwhile feel free to join the LitmusChaos slack and ask the same to the community! Cheers!
To join the slack please follow the following steps!
Step 1: Join the Kubernetes slack using the following link: https://slack.k8s.io/
Step 2: Join the #litmus channel on the Kubernetes slack or use this link after joining the Kubernetes slack: https://slack.litmuschaos.io/

**Comment by ispeakc0de** [comment]
Closing this inactive issue. Hoping @uditgaurav's suggestion solved your issue
