### ISSUE TITLE
Present at the Argo Workflows community meeting

### ISSUE THREAD

**Issue by alexec** [litmuschaos/litmus#3144]
It would be cool to have you come and talk at our community meeting!

**Comment by ksatchit** [comment]
We would love to @alexec ! Interestingly, litmus too has its community sync up on 3rd Wednesdays every month between 9.30 AM  - 10.30 AM PST. However, we can probably present in the latter half of the meet. 

I see that the items for Aug-18th are populated & we also have a small celebratory meeting in today's litmus sync upon the release of 2.0. We will be happy to present in the next month's meet!

**Comment by alexec** [comment]
What a coincidence! Would September work for you?

**Comment by neelanjan00** [comment]
Prithvi's CNCF Slack username is `Prithvi Raj` in case you haven't already figured it out. Closing this issue! :)
