### ISSUE TITLE
Analytics sent without consent

### ISSUE THREAD

**Issue by Vr00mm** [litmuschaos/litmus#3148]
**What happened**:
ChaosEngine and litmus-portal send analytics to google without consent or any enable/disable feature

**What you expected to happen**:
I wont being tracked

**How to reproduce it (as minimally and precisely as possible)**:
Install litmus

**Anything else we need to know?**:
GDPR ?

**Comment by ksatchit** [comment]
You can add an ENV on the operator manifest to stop the call-home metrics

![image](https://user-images.githubusercontent.com/21166217/129881768-e70d88ac-6b2a-403a-bd04-bdea1908519f.png)

**Comment by Vr00mm** [comment]
mybad then!
