### ISSUE TITLE
Getting started page is returning 404 on 25-Aug-2021

### ISSUE THREAD

**Issue by mffiedler** [litmuschaos/litmus#3174]
**What happened**:  https://docs.litmuschaos.io/docs/getstarted/ gives a 404 (on 25-Aug-2021)

**What you expected to happen**:  To see the getting started doc.

**Comment by S-ayanide** [comment]
With the 2.0 release we have updated the documentation for the same and you can find all the relevant details about getting started here: https://docs.litmuschaos.io/docs/getting-started/installation

If you are trying to revisit the old docs! You can find the version 1 getting started document here: https://v1-docs.litmuschaos.io/docs/getstarted/
