### ISSUE TITLE
SSO integration

### ISSUE THREAD

**Issue by reggie-k** [litmuschaos/litmus#3192]
Enabling SSO integration for the Chaos Center will be beneficial.

Perhaps a bundled Dex like in ArgoCD?
Or/and a SAML integration?

**Comment by ksatchit** [comment]
Hi @reggie-k ! Thanks for creating this issue. Feature development to this effect is in progress.

**Comment by apetheriotis** [comment]
Hi @ksatchit, are there any updates on the development of this feature?

**Comment by imrajdas** [comment]
Hi @reggie-k, we have added DEX support for the chaos center. Please take a look at this doc- https://docs.litmuschaos.io/docs/user-guides/chaoscenter-oauth-dex-installation/
