### ISSUE TITLE
What tool do you use in experiments with pod_network_*?

### ISSUE THREAD

**Issue by TidalPoo** [litmuschaos/litmus#3207]
## Question
What tool do you use in experiments with pod_network_*?

tc - trafic control?

what about SCH_NETEM module in Linux kernel, is this module needed for the experiment?

in most conteiners SCH_NETEM is not installed and trafic control not work.

**Comment by ksatchit** [comment]
Hello @TidalPoo , the pod-network-latency/loss/corruption/duplication experiments do use tc (which is installed within the litmus containers -- not needed on the apps) & need SCH_NETEM kernel module on the host where the pods run.

In case you don't have SCH_NETEM kernel module, feel free to use the [pod-network-partition](https://hub.litmuschaos.io/generic/pod-network-partition experiment) for blocking traffic to specific pods/microservices. This experiment needs CNI plugins that support network policies on your kubernetes cluster.
