### ISSUE TITLE
Create unit test for /executor/ansible/plugins/callback/openebs.py

### ISSUE THREAD

**Issue by chirag200666** [litmuschaos/litmus#321]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 Choose one: FEATURE REQUEST

  - we need test cases for functions defined in openebs.py file

**Comment by Anil1331** [comment]
Hi I would like to work on this

**Comment by ksatchit** [comment]
The OpenEBS specific ansible plugins will be maintained at https://github.com/mayadata-io/litmus
