### ISSUE TITLE
What Should I Contribute as Beginner ?

### ISSUE THREAD

**Issue by Rahul7171** [litmuschaos/litmus#3211]
help me im knew here where should i Contribute

**Comment by ksatchit** [comment]
Please take a look at https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md & https://github.com/litmuschaos/litmus/tree/master/resources sections for a better idea on this.

Please feel free to reach out on slack on specific areas you are interested in OR join the community sync up meetings for more questions!
