### ISSUE TITLE
Add docker static security checks in travis CI for ansible, godog runner tools

### ISSUE THREAD

**Issue by chandankumar4** [litmuschaos/litmus#322]
## Is this a BUG REPORT or FEATURE REQUEST?
FEATURE REQUEST

**What happened**:

- The litmus runner containers do not have any security checks implemented against them, which can be included in the Travis CI.

**What you expected to happen**:

- Include security checks in build process

**Anything else we need to know?**:

- Reference: https://github.com/docker/docker-bench-security

**Comment by debojitkakoti** [comment]
@chandankumar4 If this is still open , I would like to work on it.

**Comment by mathagician** [comment]
@chandankumar4 @ksatchit There are tools available in the github market place. You can visit [Github Marketplace](https://github.com/marketplace) and select the tools

1. Snyk
2. Code Climate Coverage Action
3. Code Cov
4. Better Code Hub

**Comment by mathagician** [comment]
@chandankumar4 @ksatchit Any update?

**Comment by ksatchit** [comment]
Ref: Synk & [Trivy](https://github.com/aquasecurity/trivy) seems to be good options to add to travis builds. We should gt to this in the 1.3 milestone!

**Comment by ksatchit** [comment]
We already have the trivy scans added by @rajdas98 for the following repos: 

- litmuschaos/litmus
- litmuschaos/chaos-exporter

It will be added to other repos soon. 

- litmuschaos/chaos-runner
- litmuschaos/test-tools

**Comment by ksatchit** [comment]
The scan has been added for chaos-operator and chaos-runner repos as well. The test-tools repo has multiple image housed in it, unlike the other repos and the trivy integration for those will be tracked by individual issues in the litmuschaos/test-tools repo.
