### ISSUE TITLE
The experiment-pod and helper-pod having same ip address

### ISSUE THREAD

**Issue by balajisoundar22** [litmuschaos/litmus#3223]
When I try executing the container-kill experiment, the container-kill-<hash>-<hash> pod and the container-kill-helper-<hash> pod are having the same ip address. 
And the helper pod not able to connect to target 
time="2021-09-28T03:46:41Z" level=fatal msg="helper pod failed, err: Get \"https://. . .\": dial tcp <ipaddress>: connect: no route to host"

**Comment by MarouaneTn** [comment]
Hello, 

We have the same issue when running the container-kill experiment on openshift, 
The error on the helper pod:
level=fatal msg="helper pod failed, err: Get \"https://<apiserver>:443/api/v1/namespaces/<namespace>/pods/<podname>\": dial tcp <apiserver>:443: connect: no route to host"

**Comment by vivekdsr** [comment]
Same issue for us.

**Comment by BK-STAR77** [comment]
Any news about this issue ? I'm having the same problem. Openshift 4.6

**Comment by uditgaurav** [comment]
The fix is available from litmus 2.9.0

**Comment by uditgaurav** [comment]
We need to add it as an ENV before running the experiment @BK-STAR77 like we have other env `TOTAL_CHAOS_DURATION`.

**Comment by BK-STAR77** [comment]
@uditgaurav  OK I see thank you
