### ISSUE TITLE
Updation of Litmus README

### ISSUE THREAD

**Issue by neelanjan00** [litmuschaos/litmus#3231]
The Mandarin, Korean, Brazillian Portuguese, and Hindi README sections need to be updated according to the current English version of the README.

**Comment by Pockerman20** [comment]
I will like to do the update hindi language to the current English version.

**Comment by Pockerman20** [comment]
@ispeakc0de and @neelanjan00 please review my pull request.

**Comment by Pockerman20** [comment]
@ispeakc0de and @neelanjan00 Please anyone review my pull request.....

**Comment by imrajdas** [comment]
Closing this issue. It's hard to main multi lang readme rn. Will think about this soon.
