### ISSUE TITLE
Subscriber pod restarts when workflow is created with invalid manifest

### ISSUE THREAD

**Issue by vamsiammineni** [litmuschaos/litmus#3245]
**What happened**:

- Fetched the workflow manifest for pod-delete experiment with the help of getPredefinedExperimentYAML Query 
-  Received manifest seems faulty at  this line **->** labels:\n    subject: \" 
   {{workflow.parameters.appNamespace}}_kube-proxy\". Which I have realized later 
- Converted the received manifest yaml string to json string 
- Created a workflow with the with manfiest(json string) with the mutation createChaosWorkflow. cronSyntax was set to run the 
   chaosworkflow immediately
- Chaos Workflow was created. But, the subscriber crashes as soon as the server tries to run the workflow. 

**What you expected to happen**:

- GetPredefinedExperimentYAML query should return a valid manifest 
- There should be validation at server side to reject the requests which does not conform to a valid schema
- Subscriber should not crash in such cases. It should be handled properly

**How to reproduce it (as minimally and precisely as possible)**:

- Fetch the pod-delete workflow manifest from the chaoshub with gepPredefinedExperimentYAML query
- convert it to valid json string 
- create a workflow using the json manifest string with createChaosWorkflow

subscriber pod crashing can be noticed at this point with the following log event in the subscriber

`time="2021-10-01T07:07:01Z" level=fatal msg="error on processing request" error="error performing cluster operation: Workflow.argoproj.io \"some-name-6\" is invalid: metadata.labels: Invalid value: \"{{workflow.parameters.appNamespace}}_kube-proxy\": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')"`

**Anything else we need to know?**:

**Comment by ksatchit** [comment]
cc: @rajdas98

**Comment by rajdas98** [comment]
Hi @vamsiammineni, This is not a bug. this is a generic query (getPredefinedExperimentYAML) which is taking experiment name, hub name as input and searches in my hub repository (Default- [Myhub Repository](http://github.com/litmuschaos/chaos-charts))

So, you need to change this in your myHub repository and reclone/update the myHub repository from the chaoscenter. In this case, this configuration is present at this place- [pod-delete-workflow](https://github.com/litmuschaos/chaos-charts/blob/aef7d97c23dc0b5d1a0e8b61e021bb598b547e0f/workflows/pod-delete/workflow.yaml#L7)

**Comment by vamsiammineni** [comment]
@rajdas98 My concern is not about the chaoshub. In any case, subscriber pod should be restarted.  I see subscriber pod going for restart whenever there is a wrong manifest submitted

**Comment by rajdas98** [comment]
@vamsiammineni, Currently, we are panic the error, that's why it into crashing. Will change the panic to a normal error log.

**Comment by vamsiammineni** [comment]
@rajdas98 Thanks. Please let me know when it is fixed.

**Comment by rajdas98** [comment]
Hi @vamsiammineni, the fix is available now in the `ci` version of the subscriber.

**Comment by vamsiammineni** [comment]
@rajdas98 Thanks :)
