### ISSUE TITLE
Not able to access litmus document from litmus home page

### ISSUE THREAD

**Issue by andrewhu0209** [litmuschaos/litmus#3247]
**What happened**:
Access the litmus official website(https://litmuschaos.io/) and click the get started button. It redirects to the 404 not found page.

**What you expected to happen**:
It should redirect to the litmus get started document page.

**How to reproduce it (as minimally and precisely as possible)**:
1. Access the litmus official website(https://litmuschaos.io/)
2. Click the get started button

**Comment by fsbaraglia** [comment]
I can confirm, the problem is the Get_Started button, it should be https://docs.litmuschaos.io/docs/introduction/what-is-litmus/# instead of https://docs.litmuschaos.io/docs/getstarted/ .

**Comment by mehabhalodiya** [comment]
So now @andrewhu0209 can you please close this issue, since all's working fine?
