### ISSUE TITLE
Add test to run the experiments with disabled pre and post chaos checks

### ISSUE THREAD

**Issue by uditgaurav** [litmuschaos/litmus#3250]
## Description

-  With the latest release [2.1.0](https://github.com/litmuschaos/litmus/releases/2.1.0) , we have the capability to tune the checks (both pre and post chaos) as enabled or disabled for a pod-level experiment. We need to add the e2e test for the same.

- The test will verify the execution of the experiment with pre and post chaos check disabled as by default it is enabled.

**Comment by neelanjan00** [comment]
@uditgaurav, is this functionality already implemented?

**Comment by uditgaurav** [comment]
The experiment can be now tuned to run in such mode so this will not be required as the priority test cases
