### ISSUE TITLE
Add command to upgrade/downgrade litmusctl binary

### ISSUE THREAD

**Issue by imrajdas** [litmuschaos/litmus#3307]
We can add an upgrade/downgrade command for litmusctl binary, it can look at the matrix of versions in a file and upgrade/downgrade according to the user's choice.

example
* litmusctl upgrade v0.5.0
* litmusctl downgrade v0.4.0

**Comment by mehabhalodiya** [comment]
Hey, I would like to work on this!
Can you please help me how to approach this?
Thank you.

**Comment by Swathi-L** [comment]
Hi @imrajdas, is this done or yet to be done?

**Comment by mridul549** [comment]
@imrajdas I'm trying to set the env variable by using this code `os.Setenv("CLIVersion", CLIVersion)` in some test file, but if I try to reaccess the same env variable in some other file say `version.go`, I'm not getting the updated value. On further digging, I found out that the environment variables are bound to the process in which they are set. If this is the case, how can I tackle this? What should I do to make it accessible everywhere?

This is the directory structure
<img width="255" alt="Screenshot 2023-08-02 at 7 19 26 PM" src="https://github.com/litmuschaos/litmus/assets/94969636/44d9b16e-2d77-4918-b352-9fb7efcfeb4c">

Setting the env in test.go and trying to access the same in version.go.
