### ISSUE TITLE
the subscriber pod fails to start (EKS setup)

### ISSUE THREAD

**Issue by aangoulvant** [litmuschaos/litmus#3321]
**What happened**:
Deployed litmus on an EKS cluster - setup the frontend as a LoadBalancer

The subscriber pod fails to start it displays this error:
$ kubectl logs subscriber-6cb89f4d97-j2dl9 -n litmus
time="2021-10-28T21:23:24Z" level=info msg="Go Version: go1.16.9"
time="2021-10-28T21:23:24Z" level=info msg="Go OS/Arch: linux/amd64"
time="2021-10-28T21:23:24Z" level=info msg="all deployments up"
time="2021-10-28T21:23:24Z" level=info msg="all components live...starting up subscriber"
time="2021-10-28T21:23:54Z" level=fatal msg="failed to confirm cluster" data= error="Post \"http://13.56.x.y:32250/query\": dial tcp 13.56.x.y:32250: i/o timeout"

**What you expected to happen**:
the subscriber pod fails to start - it seems to use the node public IP to confirm the cluster

**How to reproduce it (as minimally and precisely as possible)**:
- install litmus with kubectl (kubectl apply -f https://raw.githubusercontent.com/litmuschaos/litmus/master/mkdocs/docs/2.2.0/litmus-2.2.0.yaml)
- make the frontend svc a LoadBalancer
- connect with the UI => the status of the agent remains "Pending"

**Anything else we need to know?**:

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:16:05Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-0389ca3", GitCommit:"8a4e27b9d88142bbdd21b997b532eb6d493df6d2", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}

$ kubectl get pods -n litmus
NAME                                     READY   STATUS             RESTARTS   AGE
chaos-exporter-bf7787458-8vpkf           1/1     Running            0          28m
chaos-operator-ce-5cfd656fdd-mw4fk       1/1     Running            0          28m
event-tracker-6bbdd9454c-r9qpx           1/1     Running            0          28m
litmusportal-frontend-859fcc5f9c-z8m8v   1/1     Running            0          40m
litmusportal-server-5c599f4b7d-fk2gb     2/2     Running            0          40m
mongo-0                                  1/1     Running            0          40m
subscriber-6cb89f4d97-j2dl9              0/1     CrashLoopBackOff   9          28m
workflow-controller-78dbff5b5d-hj9cw     1/1     Running            0          28m

$ kubectl get svc -n litmus
NAME                            TYPE           CLUSTER-IP      EXTERNAL-IP                                                              PORT(S)                         AGE
chaos-exporter                  ClusterIP      10.100.85.89    <none>                                                                   8080/TCP                        39m
chaos-operator-metrics          ClusterIP      10.100.187.35   <none>                                                                   8383/TCP                        38m
litmusportal-frontend-service   LoadBalancer   10.100.141.83   aeb3b7a86e15941a0ad03a828349032b-491950590.region.elb.amazonaws.com   9091:31158/TCP                  50m
litmusportal-server-service     NodePort       10.100.42.66    <none>                                                                   9002:32250/TCP,9003:31926/TCP   50m
mongo-service                   ClusterIP      10.100.213.71   <none>                                                                   27017/TCP                       50m
workflow-controller-metrics     ClusterIP      10.100.254.15   <none>                                                                   9090/TCP                        39m

$ kubectl logs subscriber-6cb89f4d97-j2dl9 -n litmus
time="2021-10-28T21:23:24Z" level=info msg="Go Version: go1.16.9"
time="2021-10-28T21:23:24Z" level=info msg="Go OS/Arch: linux/amd64"
time="2021-10-28T21:23:24Z" level=info msg="all deployments up"
time="2021-10-28T21:23:24Z" level=info msg="all components live...starting up subscriber"
time="2021-10-28T21:23:54Z" level=fatal msg="failed to confirm cluster" data= error="Post \"http://13.56.x.y:32250/query\": dial tcp 13.56.x.y:32250: i/o timeout"

**Comment by rajdas98** [comment]
Hi, Looks like the subscriber is not able to communicate to the server. You have to open your "32250" port in the security group and restart the subscriber pod.

Or, set up ingress for the communication between subscriber and server. Follow this- https://docs.litmuschaos.io/docs/user-guides/setup-with-ingress

**Comment by aangoulvant** [comment]
I ended up opening the litmus-server port just for the node IP and it enabled the communication between subscriber and server.
