### ISSUE TITLE
Litmus gitops not working on some kubernetes clusters

### ISSUE THREAD

**Issue by asibece** [litmuschaos/litmus#3324]
I feel solution for gitops should be universal accross all k8s clusters or version. Looks like gitops is looking for last applied configuration annotation and some of k8s clusters are not populating it and gitops is not working on our clusters.

**Comment by uditgaurav** [comment]
Can you share your cluster information?
cc: @rajdas98

**Comment by Vr00mm** [comment]
Hello, I did not found anything about last applied configuration annnotation into source code.
What is the error message you get ?

**Comment by rajdas98** [comment]
Hi, We have removed the dependency from last applied configuration annotation in Litmus 2.4.0. Please upgrade this component with 2.4.0.
