### ISSUE TITLE
Pod memory hog experiment installation failed

### ISSUE THREAD

**Issue by shankarramesh16** [litmuschaos/litmus#3353]
**Pod memory hog experiment install failed**

Hi All, I am running pod memory hog experiment on simple nginx deployment on my local machine. I could run pod delete and cpu memory hog experiment but this one is failing with below error.

**Helper pod failed**:
Err : an empty namespace may not be set when a resource name is provided 

litmus version - 2.0.0
K8s - v1.21.5

**Comment by uditgaurav** [comment]
Hi @shankarramesh16 can you please provide the complete logs of the experiment and helper pods?

**Comment by shankarramesh16** [comment]
Hi @uditgaurav , we can close this issue, as there was version mismatch in experiment pod and helper pod. Thank you.
