### ISSUE TITLE
Create Prom Datasource Basic Auth

### ISSUE THREAD

**Issue by lamc** [litmuschaos/litmus#3373]
## Question: 

In the following picture, I have LitmusChaos v2.2.0 installed and have been running workflows with Self Agent and 2 other agents successfully.  I'm trying to create prom datasource so I can utilize chaos interleaved monitoring on our services/ targets. However, when I try creating a datasource, Basic Auth is not an option and only No Auth.  

LitmusChaos Center:
<img width="1628" alt="Screen Shot 2021-11-30 at 3 59 09 PM" src="https://user-images.githubusercontent.com/4719549/144128303-e05f1572-1b11-401f-b8ec-b371a75a9b6f.png">

**Comment by lamc** [comment]
@rajdas98 following up on this issue, do you have any pointers or suggestions as to why I'm seeing this behavior?

I successfully upgraded the chaos control plane to v2.3.0 as well

**Comment by rajdas98** [comment]
Hi @lamc, we aren't planning to have this feature in our coming release(15th Dec). Most probably, it will come in our subsequent releases. 

Let me know, If you want to contribute to this feature, I will also send you some references.

**Comment by lamc** [comment]
@rajdas98 ah okay understood. Sure if you can send me some references that would be great 😄

**Comment by lamc** [comment]
@rajdas98 is there any traction for this feature request?

**Comment by neelanjan00** [comment]
We are currently moving away from implementing this feature. If you still have questions, please feel free to reach out at the Litmus Slack channel in k8s Slack (https://k8s.slack.com).
