### ISSUE TITLE
Automation of assigning issues

### ISSUE THREAD

**Issue by mehabhalodiya** [litmuschaos/litmus#3382]
## Feature:
I have an idea to implement the automation of assigning issues with the `/assign` command in this project.

## Objective:
I think it's much needed because the assigning process doesn't always seem to happen quickly.  As neither the maintainer nor the other member of the organization has the time to do so.

I have gone through `Open` and `Closed` issues as well. As per my observation, assigning process is not going regularly.

### Why it is important to have:
`Assignees` field clarifies who is working on specific issues.

## How to approach:
I want some suggestions from the team as well regarding, 
- what to use: Github action or bot for the same

I request @uditgaurav @rajdas98 and @Jonsy13 to add some comments on this.
Other maintainers & reviewers are also requested to add their opinions. I would highly appreciate it.

Thank you!

**Comment by mehabhalodiya** [comment]
I would like to work. Kindly assign it to me.

> `Note`: Currently, I may not move forward with working on this as I have my semester exams between 12th - 25th Dec 2021. But sure enough that I will solve with the help of mentors whenever I find a moment to look into this.

**Comment by Akshit42-hue** [comment]
Hey @mehabhalodiya, are you still working on it?

**Comment by mehabhalodiya** [comment]
No @Akshit42-hue, thank you for pinging me. I have unassigned myself, you can take it up if you want 🙂

**Comment by Akshit42-hue** [comment]
I have seen there is no github action for this automation. I have seen you have work with Kubernetes org do you have any leads(ideas) on how I can proceed further.
// @mehabhalodiya
