### ISSUE TITLE
What should the litmus container image contain

### ISSUE THREAD

**Issue by AmitKumarDas** [litmuschaos/litmus#34]
litmus should provide some guidelines with regards to the binaries that goes into its container.
Should the litmus container have following:
- godog
- ansible
- go runtime

Should there be different litmus containers, one each for godog & ansible?

**Comment by AmitKumarDas** [comment]
As per last discussions, each test case should have flexibility to be packaged as a unique docker image e.g. openebs/litmus-test-case-name

**Comment by umamukkara** [comment]
Cleaning/scrubbing the issues. 

Closing this one as we moved to the hub, chart and operator framework
