### ISSUE TITLE
Diskfill Experiment on pod not able to access the CONTAINER_PATH

### ISSUE THREAD

**Issue by GopiChandra25** [litmuschaos/litmus#3404]
**What happened:**
While we running the Diskfill experiment  it's getting failed due to error,
Error: failed to start container "disk-fill": Error response from daemon: linux mounts: Path /var/lib/docker/containers is mounted on /var/lib/docker/containers but it is not a shared or slave mount.
**What you expected to happen**:
The FILE_PERCENTAGE specified value amount will be diskfill happen on target pod, result pod may evict if it exceeds its storage limit. 

**Where can this issue be corrected? (optional)**
The helper pod is failing because it not able to access the specified default container path
![image](https://user-images.githubusercontent.com/95012010/146871215-058fc0cb-1fb4-4598-906a-b1a64f5ac34c.png)

**How to reproduce it (as minimally and precisely as possible)**:
Creating DIskfill experiment on any of the pod as mentioned in below screenshot.
![image](https://user-images.githubusercontent.com/95012010/146871315-d91cbf20-4091-46a9-9240-e23b9f5500a1.png)

**Anything else we need to know?**:
Below are the environment where we are trying to execute:
![image](https://user-images.githubusercontent.com/95012010/147722072-cb5402ce-761e-47fc-9830-831f54790a2a.png)

Litmus:
Litmus Version: 2.0.0
Build Time: 11 Aug 2021 17:08:00

**Reached Openshift admin, after seeing the error they mentioned below points:**
By default OCP would not allow pods to have access to these directories. That would be a very big security risk.
The litmus side may have any config change or work around to resolve this permission issue.

**Comment by mbecca** [comment]
Hi, any workaround or solution for it?

**Comment by neelanjan00** [comment]
Expecting this issue to have been resolved. If you still have questions, please feel free to reach out at the Litmus Slack channel in k8s Slack (https://k8s.slack.com).
