### ISSUE TITLE
mongodb service fails to return workflowrun documents if there are many documents to return

### ISSUE THREAD

**Issue by vamsiammineni** [litmuschaos/litmus#3405]
**What happened**:
getWorkflowRuns query failed with following error when it had to parse and return many documents from the database

```
**Query**
{
  getWorkflowRuns(workflowRunsInput:{project_id:"e16d134a-64aa-4950-9e21-0a09efb72c34"})
  {
    total_no_of_workflow_runs
    workflow_runs{workflow_run_id phase}
  }
}
```

```
**Response:**
{
  "errors": [
    {
      "message": "(BSONObjectTooLarge) BSONObj size: 16837750 (0x100EC76) is invalid. Size must be between 0 and 16793600(16MB) First element: total_filtered_workflow_runs: [ { count: 3374 } ]",
      "path": [
        "getWorkflowRuns"
      ]
    }
  ],
  "data": null
}
```
**What you expected to happen**:
Query should be executed without errors and return the list of workflowrun objects

**Where can this issue be corrected? (optional)**

In Mongodb service 

**How to reproduce it (as minimally and precisely as possible)**:
When more than 3400 workflows are present in the database for a particular project and if we try to get some information from all of these documents with one query, then we encounter this issue.

**Anything else we need to know?**:
Log from the mongodb container
`2021-12-22T14:07:24.958+0000 I  COMMAND  [conn56484] command litmus.workflow-collection command: aggregate { aggregate: "workflow-collection", pipeline: [ { $match: { project_id: "e16d134a-64aa-4950-9e21-0a09efb72c34" } }, { $match: { isRemoved: { $eq: false } } }, { $project: { workflow_id: 1, workflow_name: 1, cronSyntax: 1, weightages: 1, isCustomWorkflow: 1, updated_at: 1, created_at: 1, project_id: 1, cluster_id: 1, cluster_name: 1, cluster_type: 1, isRemoved: 1, workflow_runs: { $filter: { input: "$workflow_runs", as: "wfRun", cond: { $eq: [ "$$wfRun.isRemoved", false ] } } } } }, { $unwind: { path: "$workflow_runs" } }, { $facet: { total_filtered_workflow_runs: [ { $count: "count" } ], flattened_workflow_runs: [ { $sort: { workflow_runs.last_updated: -1 } } ] } } ], cursor: {}, lsid: { id: UUID("24b20376-030c-40b4-8228-e6538612e26b") }, $db: "litmus" } planSummary: COLLSCAN numYields:26 queryHash:FB872943 planCacheKey:FB872943 ok:0 errMsg:"BSONObj size: 16837750 (0x100EC76) is invalid. Size must be between 0 and 16793600(16MB) First element: total_filtered_workflow_runs: [ { count: 3374 } ]" errName:BSONObjectTooLarge errCode:10334 reslen:247 locks:{ ReplicationStateTransition: { acquireCount: { w: 33 } }, Global: { acquireCount: { r: 33 } }, Database: { acquireCount: { r: 33 } }, Collection: { acquireCount: { r: 33 } }, Mutex: { acquireCount: { r: 7 } } } storage:{} protocol:op_msg 216ms`

**Comment by arkajyotiMukherjee** [comment]
Hey @vamsiammineni mongo has a document limit of 16MB that is why we have built this `getWorkflowRuns` query to take pagination requests so that you can fetch the data in parts. We are doing the same in our portal. Please refer to our API documentation for more details.
Do let me know if your issue is solved so that I can close this later. Hope this helps.

**Comment by vamsiammineni** [comment]
Hi @arkajyotiMukherjee 

Pagination is optional as per the API documentation

**Comment by arkajyotiMukherjee** [comment]
Yes @vamsiammineni you are correct but since the limitation is from mongo itself there is not much we can do.
Are you suggesting to make it mandatory field in the API docs? That we can do after discussing with the team if required by the community.

**Comment by vamsiammineni** [comment]
@arkajyotiMukherjee does the pagination always give the latest documents from the collection ?

**Comment by arkajyotiMukherjee** [comment]
That depends on the sorting order...but yes the default sorting order is latest/last modified by time. @vamsiammineni

**Comment by vamsiammineni** [comment]
@arkajyotiMukherjee 

I tried with pagination. I see the default order is not the latest/last modified by time. 

```
{
  getWorkflowRuns(workflowRunsInput:{project_id:"e16d134a-64aa-4950-9e21-0a09efb72c34", pagination:{page:1, limit:5}})
  {
    total_no_of_workflow_runs
    workflow_runs
    {
      workflow_run_id 
      workflow_name
    }
  }
}

{
  "data": {
    "getWorkflowRuns": {
      "total_no_of_workflow_runs": 1644,
      "workflow_runs": [
        {
          "workflow_run_id": "c33cf108-4cf4-49e4-ac0a-fddcc6563efc",
          "workflow_name": "chaos-custom-workflow-7913269493"
        },
        {
          "workflow_run_id": "d12f0081-31ab-4afa-95c8-148fcde70d37",
          "workflow_name": "chaos-custom-workflow-6244372210"
        },
        {
          "workflow_run_id": "4b39f22c-652d-491d-bc25-f2ab91841896",
          "workflow_name": "chaos-custom-workflow-8927417785"
        },
        {
          "workflow_run_id": "57671a2c-2ca5-4241-b6a6-509703e97d26",
          "workflow_name": "chaos-custom-workflow-0140277234"
        },
        {
          "workflow_run_id": "ea4cea38-5866-4a58-8a84-bd7e300591bd",
          "workflow_name": "chaos-custom-workflow-9449639847"
        }
      ]
    }
  }
}
```
This is not the order what I see if query for workflowruns without pagination

```
{
  getWorkflowRuns(workflowRunsInput:{project_id:"e16d134a-64aa-4950-9e21-0a09efb72c34"})
  {
    total_no_of_workflow_runs
    workflow_runs
    {
      workflow_run_id
      workflow_name
    }
  }
}

{
  "data": {
    "getWorkflowRuns": {
      "total_no_of_workflow_runs": 1644,
      "workflow_runs": [
        {
          "workflow_run_id": "a4e6611a-740e-46c2-b5b5-b6f9bc71dfd6",
          "workflow_name": "chaos-custom-workflow-7917697265"
        },
        {
          "workflow_run_id": "657a6859-aa9e-4633-8259-7ae535130ba5",
          "workflow_name": "chaos-custom-workflow-6762502269"
        }
      }
   }
 }    
```

**Comment by arkajyotiMukherjee** [comment]
In that case, you can sort if by Time or Name in ascending or descending order. We have provisions for all these sorting. Please refer to the docs. @vamsiammineni

**Comment by vamsiammineni** [comment]
@arkajyotiMukherjee It would be nice to have documentation about what is the default sort order. I cant find this information anywhere.

**Comment by arkajyotiMukherjee** [comment]
Sure @vamsiammineni.
Tagging @amityt for changes in the documentation.
