### ISSUE TITLE
Update the ChaosCenter API document

### ISSUE THREAD

**Issue by rajdas98** [litmuschaos/litmus#3411]
As, we have moved project related graphql APIs to REST, so we need to update our API docs with these changes.

PR- https://github.com/litmuschaos/litmus/pull/3377

**Comment by vamsiammineni** [comment]
@rajdas98 Is graphql API moved into REST API ? :(

We have implemented a wrapper library around the graphql library and spent a lot of time on it 

We did not expect this change coming

**Comment by rajdas98** [comment]
@vamsiammineni not all APIs, only 2-3 project-related API.

**Comment by SarthakJain26** [comment]
@vamsiammineni only the project related APIs are converted to REST APIs, to optimise performance and eliminate chances of DB inconsistencies

**Comment by vamsiammineni** [comment]
@rajdas98 @SarthakJain26  Thanks for the update. I am just looking into your  PR- 3377

Is there any changes planning in graphql API in near future ?

**Comment by rajdas98** [comment]
No, we are not migrating any APIs to REST from now-onwards. But we will add a few fields to some existing APIs.

**Comment by vamsiammineni** [comment]
@rajdas98 Thank you. Thats okay.

**Comment by vamsiammineni** [comment]
@rajdas98 Shouldn't this page also be updated ?

**Comment by rajdas98** [comment]
Yes @vamsiammineni

**Comment by rajdas98** [comment]
Updated API doc- https://github.com/litmuschaos/litmus/issues/3411#issuecomment-1002063282
