### ISSUE TITLE
Record username for every workflowrun

### ISSUE THREAD

**Issue by bbarin** [litmuschaos/litmus#3418]
It's very important for all users to know who has triggered the experiments for audit purposes.

**Comment by bbarin** [comment]
Hi! Is there any plan to add it?

**Comment by ksatchit** [comment]
Hi @bbarin , yes: this is an important feature. We are still in the planning stages, but that is the intention definitely.

**Comment by bbarin** [comment]
Great! Just to let you know that we are working on this and a PR will arrive soon ;)

**Comment by ksatchit** [comment]
Awesome 👍
