### ISSUE TITLE
Litmus chaos as an API

### ISSUE THREAD

**Issue by Thisisprasad007** [litmuschaos/litmus#3423]
Hi Team,

We would like to trigger the chaos workflow from our performance test scripts so looking for a an API.

so far, we are launching/scheduling the experiments from chaos center web portal in our k8 cluster (using Self agent).
We also saw Litmus portal API docs, but unable to configure it, does this fulfil our requirement? if so, please guide us to configure it, the below documentation provided the API endpoints but doesn't discuss about configuring it.

https://litmuschaos.github.io/litmus/graphql/v2.0.0/api.html

Your help is much appriciated.

**Comment by rajdas98** [comment]
HI @Thisisprasad007, you can look at this video for the reference: https://youtu.be/J8nlPhJuCuY?t=2884
