### ISSUE TITLE
Make a copy button for commands on Litmus docs

### ISSUE THREAD

**Issue by kitarp29** [litmuschaos/litmus#3437]
Hi, I was installing Litmus on my cluster locally.
It's a small fix, but would be helpful.
Can We have a copy button for the commands on this page and others?
- https://litmuschaos.github.io/tutorials/tutorial-getting-started/index.html#1

Proposed place for the **copy** button:

![image](https://user-images.githubusercontent.com/56778773/150680623-c7c9c0e6-839c-4679-bb65-fd8f846908ab.png)

I can get it done when directed to the correct files in the code.
cc: @rajdas98

**Comment by rajdas98** [comment]
This is code directory for tutorials- https://github.com/litmuschaos/tutorials
