### ISSUE TITLE
LitmusCTL feature requests

### ISSUE THREAD

**Issue by rajdas66** [litmuschaos/litmus#3440]
- Add self-upgrade and self-downgrade commands to switch between different versions of litmusctl.
- Add commands for create, get and delete workflows:
    -  `litmusctl create workflow -f <workflow-file.yaml>` command to create a workflow from a file.
    -  `litmusctl delete workflow <workflow-name/workflow-id>` command to delete schedule workflow.
    -  `litmusctl get workflows` command to list all workflows scheduled from the chaoscenter.
        -  Flags:
            - --agent-id="" (List workflows by a specific agent )
            - -A --all-agents (List all workflows associated to the users)
* Write integration tests for litmusctl

Repository- http://github.com/litmuschaos/litmusctl

**Comment by iharshit009** [comment]
Hi Raj, My name is Harshit. I am interested in working on this project and I have a good understanding of Kubernetes, CLI and basic knowledge of Golang.

**Comment by ggold7046** [comment]
Hi, I am new to open source project.  Could anyone guide me how to contribute to this project.

**Comment by rajdas66** [comment]
Closing wrt-
https://github.com/litmuschaos/litmusctl/pull/64
https://github.com/litmuschaos/litmusctl/pull/73
https://github.com/litmuschaos/litmusctl/pull/75
https://github.com/litmuschaos/litmusctl/pull/76
https://github.com/litmuschaos/litmusctl/pull/77
https://github.com/litmuschaos/litmusctl/pull/78
