### ISSUE TITLE
Create a terraform provider/scripts for litmus 

### ISSUE THREAD

**Issue by imrajdas** [litmuschaos/litmus#3456]
Develop a terraform provider on top of helm provider to provision litmus with the following operations
1. Install chaoscenter on k8s 
2. Install chaos agent via helm
3. Add chaoshub to ChaosCenter via API provider
4. Run chaos workflows via API provider

Along with the documentation of the provider/script

**Comment by iamrajiv** [comment]
Hi, @Adarshkumar14 @rajdas98 @Jonsy13 I want to work on this issue in GSoC 2022. Also, wanted to know is there a document or proposal available on this issue that gives me more context.

**Comment by Mostafa-wael** [comment]
How can I apply for this idea for GSOC? is there any communication channel with the mentors?

**Comment by kitarp29** [comment]
Hi @Mostafa-wael 
You can join the open community here: https://join.slack.com/t/chaosnative/shared_invite/zt-tff9qr0z-cgahgNmux5rSDFl1yac90w
:)

**Comment by MimicTester1307** [comment]
Hi all. I am Excel, and I im interested in contributing to this project for GSoC '22. I have joined the community,  and have been looking into ChaosEngineering too. I am thinking of attending the event that was posted on the community to get up to speed with LitmusChaos and Chaos Engineering in general. 

Is this alright?  And are there any prerequisites I need to complete to increase my chances,  or to write a good proposal?  Thank you!

**Comment by ahmedihabb2** [comment]
Is there is a specific channel on slack for GSoC?

**Comment by akshat5302** [comment]
Hii I'm akshat jain and I'm interested in this project . I have intermediate knowledge of kubernetes and basic knowledge of terraform and golang . I never applied to gsoc previously but have some prior experience of open source . 
I don't have any idea on how to write a proposal please can u help me out with that .
Is I'm late to apply ??

**Comment by neelanjan00** [comment]
Closing this due to being descoped.
