### ISSUE TITLE
Missing Dex Deployment in docs

### ISSUE THREAD

**Issue by lamc** [litmuschaos/litmus#3463]
Where can this issue be corrected? https://raw.githubusercontent.com/litmuschaos/litmus/8d025a2f3101990a1acc002612fbe7281dcbfb4d/litmus-portal/dex-server/dex-deployment.yaml

**How to reproduce it (as minimally and precisely as possible)**: While following documentation [here] (https://docs.litmuschaos.io/docs/user-guides/chaoscenter-oauth-dex-installation/), pod will not come up as the dex-deployment.yaml file doesn't include deployment config yaml

I see dex deployment in main/ release-2.6.0 branch: https://github.com/litmuschaos/litmus/blob/release-2.6.0/litmus-portal/dex-server/dex-deployment.yaml#L87-L122

**Comment by gdsoumya** [comment]
@DarthBenro008 @SarthakJain26 @Saranya-jena

**Comment by DarthBenro008** [comment]
A PR has already been raised for this issue and will be fixed by https://github.com/litmuschaos/litmus-docs/pull/169 !

**Comment by rajdas98** [comment]
PR has been merged
