### ISSUE TITLE
Can create more then one admin users via the API

### ISSUE THREAD

**Issue by haroon9** [litmuschaos/litmus#3464]
**What happened**:
Using an API call from Postman I was able to create more than one account with an admin role.

**What you expected to happen**:
I should not have been allowed to create more than admin or I should have the option to delete admins if I am allowed to create more than one admin.

**Where can this issue be corrected? (optional)**

**How to reproduce it (as minimally and precisely as possible)**:
A POST call to this endpoint ``auth/create`` with the following body:
```
{
  "username": "test2",
  "password": "test2",
  "role": "admin",
  "email": "test2@litmus.com",
  "name": "Test Account"
}
```

**Anything else we need to know?**:

**Comment by gdsoumya** [comment]
The ability to create more admins is known we just don't expose it in UI yet, only admins can create accounts so it's safe. You are correct about the ability to delete an admin, we should have the feature if we don't already. @DarthBenro008 can you see if we can add deletion for admins, let's keep the default admin the one created at initialization as unremovable. cc: @ajeshbaby @SarthakJain26 @Saranya-jena

**Comment by haroon9** [comment]
One more thing if I try to create a user with a different role the API is not allowing me. I can only create a user with the role: admin. Is this also the expected behaviour?

**Comment by DarthBenro008** [comment]
@gdsoumya i agree, we should definitely provide a more user-management options. Will make a PR for the same soon.
@haroon9 yes, the fact that only admin can create more users is an intended behaviour. The user is supposed to reset their password in the first login.

**Comment by haroon9** [comment]
@DarthBenro008 I am referring to the user role. What if as an admin I want to create a new user with a different role. As currently if I try this POST call it does not work:
```
{
  "username": "test3",
  "password": "test3",
  "role": "viewer",
  "email": "test3@litmus.com",
  "name": "Test Account"
}
```

Returns the following:
```
{
    "error": "invalid_request",
    "error_description": "The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed"
}
```

**Comment by DarthBenro008** [comment]
@haroon9 , role `viewer` is invalid hence the backend functions as intended, if you'd like to create a user as an admin, do pass the "user" role in parameter `role`

All types of roles can be found at:

https://github.com/litmuschaos/litmus/blob/8fa5334c29db76b5caa2f2af8a32a5bdfc212f2c/litmus-portal/authentication/pkg/entities/user.go#L14-L20

**Comment by gdsoumya** [comment]
> @DarthBenro008 I am referring to the user role. What if as an admin I want to create a new user with a different role. As currently if I try this POST call it does not work:
> 
> ```
> {
>   "username": "test3",
>   "password": "test3",
>   "role": "viewer",
>   "email": "test3@litmus.com",
>   "name": "Test Account"
> }
> ```
> 
> Returns the following:
> 
> ```
> {
>     "error": "invalid_request",
>     "error_description": "The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed"
> }
> ```

`viewer`, `owner`, `editor` these are project level access not portal, all users created from the user by admin are just users and each one is a owner of their own project can add others into the project as either a viewer or editor

**Comment by haroon9** [comment]
Yes, @DarthBenro008 @gdsoumya Thank you for the clarification. Also, the admin should be able to delete a portal user I checked the API but this functionality is also missing. Are you going to add something like this too?

https://litmuschaos.github.io/litmus/auth/v2.0.0/api.html

**Comment by gdsoumya** [comment]
> Yes, @DarthBenro008 @gdsoumya Thank you for the clarification. Also, the admin should be able to delete a portal user I checked the API but this functionality is also missing. Are you going to add something like this too?
> 
> https://litmuschaos.github.io/litmus/auth/v2.0.0/api.html

I think the admin can disable users, deletion is not allowed for keeping audit trails.
