### ISSUE TITLE
Add support for redis

### ISSUE THREAD

**Issue by DarrenJiang13** [litmuschaos/litmus#3465]
Hi guys, 

I am trying to test redis cluster with litmus. However I have no ideas about writing redis part in workflow.yaml. Do you have any tutorials or document for reference? Thank you so much.

**Comment by gdsoumya** [comment]
We do not have any redis specific experiments as of now, but you can perform generic experiments like pod delete, network loss, disk fill, etc. on your redis cluster. You do not need to write any specific redis parts in the workflows you just need to provide pod/deployment labels and experiment specific details which you can see from the experiment doc https://litmuschaos.github.io/litmus/experiments/categories/contents/
