### ISSUE TITLE
Don't believe PersistentVolumeClaim mongo-0

### ISSUE THREAD

**Issue by Poswark** [litmuschaos/litmus#3480]
Mongo pod won't start

[root@k8s-master1 ~]# kubectl get pods -n litmus
NAME                                     READY   STATUS     RESTARTS   AGE
litmusportal-frontend-74f699bc65-xj6mg   1/1     Running    0          4m21s
litmusportal-server-5b79b6577c-qstlz     0/2     Init:0/1   0          4m21s
mongo-0                                  0/1     Pending    0          4m20s
[root@k8s-master1 ~]# 

Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  mongo-persistent-storage:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  mongo-persistent-storage-mongo-0
    ReadOnly:   false
  kube-api-access-fx6vx:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  43s (x4 over 3m49s)  default-scheduler  0/2 nodes are available: 2 pod has unbound immediate PersistentVolumeClaims.

### solution ############
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-persistent-storage-mongo-0
  namespace: litmus
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongo-0
  namespace: litmus
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/db"

**Comment by ksatchit** [comment]
cc: @rajdas98

**Comment by rajdas98** [comment]
Hi @Poswark, Mongo is an STS and it will create PVC and PV in the background. The attachment of PVC with pod depends on your storage provisioner.

**Comment by Poswark** [comment]
ok
