### ISSUE TITLE
URL manipulation in ChaosCenter

### ISSUE THREAD

**Issue by SarthakJain26** [litmuschaos/litmus#3485]
**What happened**:
- User is able to access UI of project user is not part of by manipulating the URL.
- User is able to update the project role from URL

**What you expected to happen**:
User should not be allowed to access projects that user is not part of and URL manipulation should not be possible.

**Where can this issue be corrected? (optional)**

**How to reproduce it (as minimally and precisely as possible)**: 
Run chaoscenter and change the projectID query param in URL, or update the role in URL

**Anything else we need to know?**:

**Comment by vanshBhatia-A4k9** [comment]
API level RBAC validation: https://github.com/litmuschaos/litmus/pull/3486 @SarthakJain26

**Comment by vanshBhatia-A4k9** [comment]
RBAC based frontend validations: https://github.com/litmuschaos/litmus/pull/3501 @arkajyotiMukherjee @SarthakJain26 @Saranya-jena

**Comment by SarthakJain26** [comment]
Issue fixed with this PR: https://github.com/litmuschaos/litmus/pull/3501

**Comment by SarthakJain26** [comment]
Fix:
- On manipulating the project role manually in the URL, an API call will be made to validate the user's role in the project and the correct role will be set in the URL again as per the response from API.
- On manipulating the project ID with an incorrect project ID in URL, user will be redirected back to the default project where user has an `Owner` role.

**Comment by SarthakJain26** [comment]
Demo describing updated RBAC flow
https://user-images.githubusercontent.com/45846277/158531698-5e074ca3-9e50-45b8-95a7-57555250f227.mp4
