### ISSUE TITLE
Litmus Portal: parallel or serial wf including the same experiment for different microservices fails

### ISSUE THREAD

**Issue by serape** [litmuschaos/litmus#3511]
If the workflow includes the same experiment (e.g. pod-delete) twice, the workflow is created but it fails. See output below.
This applies for parallel and serial wf.

When looking into the manifest file created we noticed that the same experiment with the same name and templates is included everywhere. So litmus probably tries to install the same experiment (e.g pod-delete) twice and fails.

We should be able to add the same experiment (ex: with different services ) multiple times in same workflow

as a workaround 
we manually modify the manifest file in order to have the experiment running:

In the install experiment part the experiment to be installed is set twice and it has the same name.
Remove one and keep only one.
Update the experiment name in all applicable places: step session, template name and experiment name, engine session, etc.
Original manifest includes everywhere experiment e.g pod-delete. Update the name accordingly with the service name: e.g.: pod-delete-yyy and pod-delete-yyy

**Comment by amityt** [comment]
This issue has been fixed with https://github.com/litmuschaos/litmus/pull/3540
