### ISSUE TITLE
[Experiment] Introduce CPU_LOAD tunable for Pod CPU hog via exec experiment

### ISSUE THREAD

**Issue by chirangaalwis** [litmuschaos/litmus#3514]
**Description:**
It would be ideal if the $subject could be introduced to `pod-cpu-hog-exec` as in the case of https://github.com/litmuschaos/chaos-charts/blob/2.6.0/charts/generic/pod-cpu-hog/experiment.yaml#L76-L79.

This will provide users more control over the level of chaos injection.

**Comment by uditgaurav** [comment]
Hi @chirangaalwis , Thanks for opening this issue.  We use `CPU_LOAD` as stress-ng flag in the pod-cpu-hog experiment which helps us to consume the CPU resources in percentage. The exec-chaos (pod-cpu-hog-exec) don't use stress-ng so we might need to have some alternative approach for consuming CPU in percentage for md5sum.
Do you have any specific reason for using exec mode over non-exec for the CPU hog experiment?

**Comment by chirangaalwis** [comment]
> Hi @chirangaalwis , Thanks for opening this issue. We use `CPU_LOAD` as stress-ng flag in the pod-cpu-hog experiment which helps us to consume the CPU resources in percentage. The exec-chaos (pod-cpu-hog-exec) don't use stress-ng so we might need to have some alternative approach for consuming CPU in percentage for md5sum. Do you have any specific reason for using exec mode over non-exec for the CPU hog experiment?

@uditgaurav yes. Security teams are concerned about the use of privileged containers in the non-exec approach. Using privileged containers in a production grade deployment is not recommended. As per the recommendation of the LitmusChaos team (https://kubernetes.slack.com/archives/CNXNB0ZTN/p1644888327469729?thread_ts=1644869928.562819&cid=CNXNB0ZTN), we decided to use the non-exec appraoch.

**Comment by avaakash** [comment]
Hi @chirangaalwis, thank you for raising this request but currently, there are no plans to support `CPU_LOAD` for `pod-cpu-hog-exec` experiment as `md5sum` doesn't support this.
