### ISSUE TITLE
Litmus API returns 500 when accessing SSO users project

### ISSUE THREAD

**Issue by haroon9** [litmuschaos/litmus#3516]
**What happened**:
After adding the dex configuration I try to access a user project information via the API endpoint ``GET /get_user_with_project/{username}`` but I got 500 errors for every SSO user.

**What you expected to happen**:
The API should have returned the projects that the user is currently part of. It is possible to get the project information for the other users that are created via the litmus chaos centre but not for the SSO users. Also, the API returns an empty 500 error without any message. So better error handling should also be implemented.

**Where can this issue be corrected? (optional)**

**How to reproduce it (as minimally and precisely as possible)**:
Login using SSO and then using the API try to access this endpoint ``GET /get_user_with_project/{username}`` you will get 500 error.

**Anything else we need to know?**:

**Comment by SarthakJain26** [comment]
Fix: https://github.com/litmuschaos/litmus/pull/3529
