### ISSUE TITLE
Overflowing content in user management tab if the username is a little long 

### ISSUE THREAD

**Issue by haroon9** [litmuschaos/litmus#3517]
**What happened**:
The username text is overflowing if the username is a little longer in the user management tab. The current litmus version 2.7.0
![see](https://user-images.githubusercontent.com/7084240/159457350-3d92822d-a84f-40b3-ab55-a35a39abf95d.PNG)

**What you expected to happen**:
The text should not overflow.

**Where can this issue be corrected? (optional)**

**How to reproduce it (as minimally and precisely as possible)**:
Try to create a user with a longer username such as an email.

**Anything else we need to know?**:

**Comment by vanshBhatia-A4k9** [comment]
the Issue has been fixed: https://github.com/litmuschaos/litmus/pull/3534/commits/65e49408e5560fea08a9e665f2dbebed9d13c961

tagging @Saranya-jena & @SarthakJain26 for closing the issue
