### ISSUE TITLE
agent: new ACCESS_KEY not updated in secret

### ISSUE THREAD

**Issue by gdsoumya** [litmuschaos/litmus#3531]
**What happened**:

After the initial cluster registration operation, the agent updates the config with the new access key. This PR https://github.com/litmuschaos/litmus/pull/3492 broke the config update by moving the ACESS_KEY env var to a secret, the agent is still updating the access key in the configmap instead of the secret 

Might be a critical bug depending on which env is prioritized(secret or the cm) when the agent restarts, because if the secret is prioritized the agent will be using the old access key causing the authentication to fail.

**What you expected to happen**:

Agent updates the new ACCESS_KEY in the `agent-secret instead of configmap

**Where can this issue be corrected? (optional)**

Ref: https://github.com/litmuschaos/litmus/blob/master/litmus-portal/cluster-agents/subscriber/pkg/k8s/operations.go#L155-L173

In the above function, we need to remove the access key and cluster id env var from the configmap and update it in the secret instead

**How to reproduce it (as minimally and precisely as possible)**:

Install litmus and let the agent perform the registration, once active check the secret and config maps for the agent

**Comment by gdsoumya** [comment]
might be a critical bug depending on which env is prioritized(secret or the cm) when the agent restarts, because if the secret is prioritized the agent will be using the load access key and the auth will fail.

**Comment by imrajdas** [comment]
The requested changes have been implemented.

https://github.com/litmuschaos/litmus/blob/b010cc3e67d3e0dbffe3a4c6602e488079550066/litmus-portal/cluster-agents/subscriber/pkg/k8s/operations.go#L193
