### ISSUE TITLE
User attribute in Chaos results

### ISSUE THREAD

**Issue by haroon9** [litmuschaos/litmus#3548]
Currently, when someone starts a workflow using the portal we can observe who started the experiment but if we check the logs there is currently no attribute to verify who started the experiment. According to the setup if someone has log exporters deployed on clusters there won't be any logs related to who started the experiment.

**Comment by avaakash** [comment]
Hi, @haroon9 thank you for raising this request but currently, there are no plans to support audit logging on the experiments.
