### ISSUE TITLE
Failed in applying connection yaml

### ISSUE THREAD

**Issue by GopiKannanJP** [litmuschaos/litmus#3582]
Installed litmus 2.7.0 using helm, self agent is active, trying to test out adding external chaos agent feature, not able to add the new external agent  throws below error while executing litmusctl create agent

❌ Failed in applying connection yaml:

not sure how to debug this further as the error is null. Sharing the command below.

litmusctl create agent
Project list:
1.  admin's project

Select a project [Range: 1-1]: 1

Installation Modes:
1. Cluster
2. Namespace

Select Mode [Default: cluster] [Range: 1-2]: 1

🏃 Running prerequisites check....
🔑 clusterrole ✅
🔑 clusterrolebinding ✅
🌟 Sufficient permissions. Installing the Agent...

Enter the details of the agent

Agent Name: qa

Agent Description: qa

Do you want Agent to skip SSL/TLS check (Y/N) (Default: N): Y

Do you want NodeSelector to be added in the agent deployments (Y/N) (Default: N): N

Do you want Tolerations to be added in the agent deployments? (Y/N) (Default: N): N

Platform List:
1. AWS
2. GKE
3. Openshift
4. Rancher
5. Others

Select a platform [Default: AWS] [Range: 1-5]: 1

Enter the namespace (new or existing namespace) [Default: litmus]: litmusv2

Enter service account [Default: litmus]: litmus

📌 Summary
Agent Name: qa
Agent Description: qa
Agent SSL/TLS Skip: true
Platform Name: AWS
Namespace:  litmusv2 (new)
Service Account:  litmus (new)

Installation Mode: cluster

🤷 Do you want to continue with the above details? [Y/N]: Y
👍 Continuing agent connection!!
Applying YAML:
https://xxxxxxxxxxx/api/file/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbHVzdGVyX2lkIjoiZDcwMDgwMjMtMWFiNy00MWFlLWFiMGQtMzMwYmFiM2RiNWYzIn0.V8s5j7KDWmPmIU4Cmw4KyGUY-OwCm6b0ktPGTwOb7Gg.yaml
❌ Failed in applying connection yaml:

**Comment by shwetahgithub** [comment]
Hi @GopiKannanJP  Can you help with the fix for above issue?
