### ISSUE TITLE
Add a provision to de-register an agent from the litmusctl

### ISSUE THREAD

**Issue by hkgopal** [litmuschaos/litmus#3604]
Currently,  litmusctl has an option to register an agent but not to de-register and agent.
It would be great if litmusctl provides an option to deregister an existing agent

**Comment by Jonsy13** [comment]
Hi @hkgopal , Thanks for this feature request.
This functionality was added in v0.11.0 version of litmusctl. 
Closing this issue. Feel free to open this if you face any issues with same.
