### ISSUE TITLE
Litmus mongo-db creation failed

### ISSUE THREAD

**Issue by santhoshissa** [litmuschaos/litmus#3609]
When I try to install Litmus using helm command 

helm repo add litmuschaos https://litmuschaos.github.io/litmus-helm/
helm install chaos litmuschaos/litmus --namespace=litmus

Facing pod issue 

![image](https://user-images.githubusercontent.com/34296918/168655602-d31e9616-2bb8-4448-a0d6-fde67078aad1.png)

kubectl describe pod chaos-litmus-mongo-0

![image](https://user-images.githubusercontent.com/34296918/168655853-975d6c8e-b2ef-4014-b7de-ff4eb10a0227.png)

any solution for this issue

**Comment by imrajdas** [comment]
It's not a mongo db issue. As per the log, the mongo STS needs more resources to start. But it's not getting it, that's why it fails to start.

And auth server and litmus-server depend on MongoDB, that's why they are init state.
