### ISSUE TITLE
AWS IAM Integration Docs Fix

### ISSUE THREAD

**Issue by QAInsights** [litmuschaos/litmus#3611]
**What happened**:
There is a typo in the EKS command in [AWS IAM Integration doc](https://litmuschaos.github.io/litmus/experiments/concepts/IAM/awsIamIntegration/).

**What you expected to happen**:
The command will fail if the user follows as-is.

**Where can this issue be corrected? (optional)**
NA

**How to reproduce it (as minimally and precisely as possible)**:
In this [instructions](https://litmuschaos.github.io/litmus/experiments/concepts/IAM/awsIamIntegration/) doc, if the user follows the `Step 2` command, it will fail due to typo.

```
eksctl create iamserviceaccount \
    --name <service_account_name> \
    --namespace <service_account_namespace> \
    --cluster <cluster_name> \
    --attach-policy-arn <IAM_policy_ARN> \
    --approve \
    --override-existing-serviceaccont
```
**Anything else we need to know?**:
I will submit a PR with a corrected command.

**Comment by QAInsights** [comment]
https://github.com/litmuschaos/litmus/pull/3612

**Comment by uditgaurav** [comment]
Thanks @QAInsights for the PR!
