### ISSUE TITLE
Re-run schedule does not work if user is an email address

### ISSUE THREAD

**Issue by brnck** [litmuschaos/litmus#3634]
**What happened**:

I am using the DEX server so all users are authenticated/created using information from the 3rd party providers

I log in as an editor to the project, go to Workflows > Schedules, and click Rerun schedule, but nothing happens. UI just redirects me to the Runs tab, but the new Run is not created.

Backend ACKs the request:
```
{"data":{"reRunChaosWorkFlow":"Request for re-run acknowledged, workflowID: dae6de43-13e0-475f-9ea8-8e4ad71d9980"}}
```

Subscriber has an error:

```
time="2022-05-27T06:56:50Z" level=error msg="Error on processing request" error="error performing cluster operation: Workflow.argoproj.io \"custom-chaos-workflow-1653598244-1653634610\" is invalid: metadata.labels: Invalid value: \"a_surname@my.domain\": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')"
```

**What you expected to happen**:

I expect that the workflow will be executed

**Where can this issue be corrected? (optional)**

N/A

**How to reproduce it (as minimally and precisely as possible)**:

1. Have a user with an editor role that has a username that is an email (foo.bar@domain.com).
2. Try to re-run workflow
3. Check subscriber logs

**Anything else we need to know?**:

The manifest consists of a label named executed_by which is the username. Since the username came from 3rd party and is an email, it is not valid according to the label regex. Maybe it makes sense to sanitize the username before submitting it to the Workflow

**Comment by amityt** [comment]
PR for the fix https://github.com/litmuschaos/litmus/pull/3648
Thanks @brnck for reporting this issue!

**Comment by deividMatos** [comment]
Hi @amityt,
I proposed a different solution for this problem, without breaking the audit.
#3705
