### ISSUE TITLE
Chaos Center Edit Schedule Cached?

### ISSUE THREAD

**Issue by lamc** [litmuschaos/litmus#3646]
**What happened**: When I edit a workflow schedule, I always get presented the same workflow I had modified a few days ago

**What you expected to happen**: When I choose a workflow to edit schedule, the YAML and workflow details should match the one I chose.

**How to reproduce it (as minimally and precisely as possible)**: I'm not sure how to reproduce this

**Anything else we need to know?**: The only workaround I have is to login to chaos center in incognito window, but can only change schedule to one workflow otherwise, the same behavior occurs as described above.

In the photo below, you see the workflow details shows `djin-platform-app-dns-chaos` not matching up to the workflow I chose `djin-shared-app-dns-chaos`

![Screen Shot 2022-06-07 at 5 01 08 PM](https://user-images.githubusercontent.com/4719549/172481901-9e55fed9-7d73-4426-82a8-a4a92084e143.png)

**Comment by mehak-sha** [comment]
I am also working with Crystal on this. We notice the same behavior if we change "Schedule". 
eg. The schedule has been modified to "every Tuesday at 9 AM". It shows fine when we "Edit Schedule", but when we see "Show Schedule", it shows a different one.

Edit Schedule:
![image](https://user-images.githubusercontent.com/68915118/173875758-c4372e91-da2c-4c56-b098-cee20536b960.png)

Show Schedule:
![image](https://user-images.githubusercontent.com/68915118/173876250-017e97d4-2e40-489a-b271-d600f9339b24.png)
