### ISSUE TITLE
Client ID is left empty when trying to login via dex / oauth2

### ISSUE THREAD

**Issue by Xangliev** [litmuschaos/litmus#3652]
**What happened**:
I followed the documentation at: https://docs.litmuschaos.io/docs/user-guides/chaoscenter-oauth-dex-installation/
and setup everything accordingly. After navigating to /auth/dex/login and attempting to login via github I get the following error: 
`Not Found
Invalid client_id ("").`.

It seems that the clientid in the call (or url) is left empty, despite it being defined in the configuration file: https://github.com/litmuschaos/litmus/blob/master/litmus-portal/dex-server/dex-deployment.yaml#L21

When the clientid from the configuration is added to the url it works.

**What you expected to happen**:
Navigating to /auth/dex/login and selecting a login method should redirect users to the appropriate ouath2 approval/login step.

**How to reproduce it**:
Setup a fresh helm install of litmus version 2.8.0+  and follow the documentation at https://docs.litmuschaos.io/docs/user-guides/chaoscenter-oauth-dex-installation/ to setup a dex server. Navigate to /auth/dex/login on the frontend server and attempt to login.

**Comment by Xangliev** [comment]
On a somewhat related note,  even when I authenticate succesfully on github I am still unable to access the chaos center.

**Comment by rajdas66** [comment]
cc: @DarthBenro008

**Comment by ruchi1803** [comment]
+1

**Comment by DarthBenro008** [comment]
Hey @Xangliev , you have to change the ClientID in this specific line:

https://github.com/litmuschaos/litmus/blob/7f1e279043f16962dbeffb6268d1f10da34fea92/litmus-portal/dex-server/dex-deployment.yaml#L44

instead of:

https://github.com/litmuschaos/litmus/blob/7f1e279043f16962dbeffb6268d1f10da34fea92/litmus-portal/dex-server/dex-deployment.yaml#L21

I had created a video walkthrough of integrating Dex with Litmus, you can find the same at https://dex.benro.dev , please do look from the timestamp 12:17 with relevance to this issue

**Comment by Xangliev** [comment]
@DarthBenro008 I have added the clientID for my connectors and I can see in the auth server logs that authentication works correctly (eg. I get the Oauth authentication screen). The problem is that the static client ID defined on line 21 is not preserved in the url headers. So when you navigate to /auth/dex/login initially I get an error which states that the client id is empty. Also when you add the static client id manually to the url you can see the oauth screen and after authentication with github or google it will still fail to log you in to the litmus portal as it will once again complain in the logs about the client id being empty.

**Comment by DarthBenro008** [comment]
@Xangliev , upon looking into the code, i figured that you have to add the ClientID in env params of the authentication service, exactly here:

https://github.com/litmuschaos/litmus/blob/7f1e279043f16962dbeffb6268d1f10da34fea92/litmus-portal/authentication/pkg/utils/configs.go#L21

This means, we need to add more variables under [this](https://docs.litmuschaos.io/docs/user-guides/chaoscenter-oauth-dex-installation/#configuring-litmusportal-server-to-enable-dex-features) section of the docs. I'll soon send a PR to update the docs! 

for now, you can use the following command to bypass this issue:
```bash
kubectl set env deployment/litmusportal-server -n litmus --containers="auth-server" DEX_ENABLED=true OIDC_ISSUER=<REPLACE_NODE_IP>:32000 DEX_OAUTH_CALLBACK_URL=https://<REPLACE_FRONTEND_URL>/auth/dex/callback DEX_OAUTH_CLIENT_ID=LitmusPortalAuthBackend DEX_OAUTH_CLIENT_SECRET=ZXhhbXBsZS1hcHAtc2VjcmV0
```

this should hopefully fix the issue!

**Comment by Xangliev** [comment]
@DarthBenro008 Thanks for the quick response, I will test it out soon and will get back to you!

**Comment by ruchi1803** [comment]
adding clientId and client secret in auth-server manually worked for me. its not showing empty client ID and login is successful.
Thanks @Xangliev

**Comment by Xangliev** [comment]
Also works for me, thanks @DarthBenro008
