### ISSUE TITLE
Litmus Portal not getting connected to Litmus Chaos Hub and not importing generic pod delete engine YAML file

### ISSUE THREAD

**Issue by PoojaS4444** [litmuschaos/litmus#3681]
<img width="951" alt="litmus_choasHub_error02" src="https://user-images.githubusercontent.com/69305654/178657310-b3721803-20fe-4868-8280-5bb7da3fca02.png">
<img width="960" alt="litmus_file_import_error02" src="https://user-images.githubusercontent.com/69305654/178657377-fa46e976-fb99-4b28-bd15-7cdb30d46eec.png">

**What happened**:

1.  In the Litmus Portal/UI, under ChaosHubs section, I am unable to connect to Litmus ChaosHub/v2.9.x and use predefined workflows. Its showing -> [Error: could not connect]
2. I am unable to upload the generic-pod-delete-engine.yaml file downloaded from here: https://hub.litmuschaos.io/generic/pod-delete. Its showing -> Error while uploading YAML : Cannot read properties of undefined (reading 'templates')

**What you expected to happen**: 
1. I expected it to connect to Litmus ChaosHub/v2.9x so that i can execute chaos tests using pre-defined workflows.
2. I expected to upload engine.yaml successfully as i have neither edited the file or changed the format

**Where can this issue be corrected? (optional)**
Litmus Portal

**How to reproduce it (as minimally and precisely as possible)**:
1. Install Litmus 2.10.0 with Helm on a machine running in lab
2. SSH to the machine that has litmus from PC
3. Access Litmus Portal/frontend service
Next

**Related to Chaos Hub error**
a. Click ChaosHubs
b. Select Litmus ChaosHub/v2.9.x
c. Click 3 dots option. Select Refresh Hub

**Related to File import error**
a. Login and click schedule a workflow
b. Select the Self agent and click Next
c. Under choose a workflow, click Import a workflow using YAML and try to upload generic-pod-delete-engine.yaml file by selecting file from device

**Anything else we need to know?**:

**Comment by amityt** [comment]
Hi @PoojaS4444  Regarding ChaosHub, it is a know issues and it will be fixed in the next release.
For the upload issue, we don't support the upload of engine YAML as of now. Please try to upload a manifest of kind : Workflow.
You can use this manifest for the same: https://github.com/litmuschaos/chaos-charts/blob/master/workflows/pod-delete/workflow.yaml

**Comment by PoojaS4444** [comment]
Hi @amityt, Thanks for looking into the issue. Yes i will try uploading workflow manifest and execute tests
