### ISSUE TITLE
agent installation error

### ISSUE THREAD

**Issue by santhoshissa** [litmuschaos/litmus#3693]
Hi Team,
 When I trying to install litmus on my k8s clusters facing an agent installation issue 
 
  `Kubectl logs -f subscriber-55cbccdd65-bjknm  -n litmus`

`root@k8server:~# kubectl logs -f subscriber-55cbccdd65-bjknm -n litmus
time="2022-07-15T11:37:18Z" level=info msg="Go Version: go1.16.15"
time="2022-07-15T11:37:18Z" level=info msg="Go OS/Arch: linux/amd64"
time="2022-07-15T11:37:18Z" level=info msg="All agent deployments are up"
time="2022-07-15T11:37:18Z" level=info msg="Starting the subscriber"
time="2022-07-15T11:37:18Z" level=fatal msg="Failed to check cluster confirmed status" error="secrets \"agent-secret\" is forbidden: User \"system:serviceaccount:litmus:litmus\" cannot get resource \"secrets\" in API group \"\" in the namespace \"litmus\"" `

after this issue deleted all cluster clusterrolebinding and clusterrole even same issue 

![image](https://user-images.githubusercontent.com/34296918/179216620-7acd22aa-636b-4082-9b31-04be7302d5ce.png)

![image](https://user-images.githubusercontent.com/34296918/179216371-52c91dcb-a31f-4691-996b-89e9a80fa3c0.png)

**Comment by ashmilhussain** [comment]
Same issue for me with V 2.11.0

**Comment by dyegowermelinger** [comment]
Could you try to run it?

`kubectl create clusterrolebinding litmus-cluster-admin --clusterrole=litmus-admin --serviceaccount=litmus:litmus`

**Comment by neelanjan00** [comment]
Hi @santhoshissa, will you join the Litmus community Slack channel in k8s Slack? We usually help each other troubleshoot problems there. https://k8s.slack.com/

**Comment by avaakash** [comment]
Closing this issue due to no response, if the problem is still not resolved, feel free to re-open this.
