### ISSUE TITLE
Pod cpu hog and Pod memory hog experiments expecting privileged scc for litmus-admin sa 

### ISSUE THREAD

**Issue by GopiChandra25** [litmuschaos/litmus#3696]
**What happened**: While executing Pod cpu hog and Pod Memory hog experiments in below environment
**OpenShift Master**: v3.11.439
**Kubernetes Master**: v1.11.0+d4cacc0
**Litmus Version**: 2.9.0
1. Using namespace level agent, scc is applied as mentioned in https://litmuschaos.github.io/litmus/experiments/concepts/security/openshift-scc/
  a. oc create -f litmus-scc.yaml
  b. oc adm policy add-scc-to-user litmus-scc -z litmus-admin --as system:admin -n litmus

2.  Pod cpu hog and Pod memory hog experiment is created and helper pod is failed with below errors
    
time="2022-07-18T11:49:03Z" level=error msg="[Error]: CPU hog failed, err: unable to create the helper pod, err: pods \"pod-cpu-hog-helper-ppbohu\" is forbidden: unable to validate against any security context constraint: [provider restricted: .spec.securityContext.hostPID: Invalid value: true: Host PID is not allowed to be used spec.volumes[0]: Invalid value: \"hostPath\": hostPath volumes are not allowed to be used spec.volumes[1]: Invalid value: \"hostPath\": hostPath volumes are not allowed to be used spec.containers[0].securityContext.securityContext.runAsUser: Invalid value: 0: must be in the ranges: [1000520000, 1000529999] spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed capabilities.add: Invalid value: \"KILL\": capability may not be added capabilities.add: Invalid value: \"MKNOD\": capability may not be added capabilities.add: Invalid value: \"SYS_ADMIN\": capability may not be added capabilities.add: Invalid value: \"SYS_CHROOT\": capability may not be added capabilities.add: Invalid value: \"SYS_PTRACE\": capability may not be added spec.containers[0].securityContext.hostPID: Invalid value: true: Host PID is not allowed to be used]"

3. once giving "privileged " scc to litmus-admin service account, experiment is ran successfully.
    ( oc adm policy add-scc-to-user privileged -z litmus-admin --as system:admin -n gopi-litmus )

**What you expected to happen**:
Pod Cpu hod and Pod Memery Hog experiments expecting to be run without "privileged" access.

**Where can this issue be corrected? (optional)**

We digged into it little bit and found that CPU hod and Memory 

**How to reproduce it (as minimally and precisely as possible)**:
1. created namespace level agent
2. added litmus-scc to litmus-admin service account
3. created Pod cpu hog and Pod Memory hog experiments 

**Anything else we need to know?**:

[pod-memory-hog-Without-Privileged-scc.log](https://github.com/litmuschaos/litmus/files/9137507/pod-memory-hog-Without-Privileged-scc.log)
[pod-memory-hog-helper-With-privileged-scc.log](https://github.com/litmuschaos/litmus/files/9137509/pod-memory-hog-helper-With-privileged-scc.log)
[pod-cpu-hog-ej27h6-Without-privileged-scc.log](https://github.com/litmuschaos/litmus/files/9137510/pod-cpu-hog-ej27h6-Without-privileged-scc.log)

[litmus-scc.yaml.txt](https://github.com/litmuschaos/litmus/files/9137528/litmus-scc.yaml.txt)

@neelanjan00 @uditgaurav @Skchoudhary @ksatchit

**Comment by erekgit** [comment]
@GopiChandra25  Does is make sense/help?

"Anderson, Erik6/28 11:45 AM

[karthik.s_active_acc](https://urldefense.com/v3/__https:/app.slack.com/team/U029L6WJHQQ__;!!INViTUAdUeDF!0ECanToO5ObYvKTotdZ0AVvfBrOOul9wF8tgqkj28PYNukt04bXoxAPQmtzXEISD4v5Ao7T5GCehKxSBaHnsFMI$)  [25 minutes ago](https://urldefense.com/v3/__https:/kubernetes.slack.com/archives/CNXNB0ZTN/p1656429454194359?thread_ts=1656425545.815969&cid=CNXNB0ZTN__;!!INViTUAdUeDF!0ECanToO5ObYvKTotdZ0AVvfBrOOul9wF8tgqkj28PYNukt04bXoxAPQmtzXEISD4v5Ao7T5GCehKxSBOkNntsU$)

The experiment that uses md5sum is the older pod-cpu-hog-exec [@Erik Anderson](https://urldefense.com/v3/__https:/kubernetes.slack.com/team/UHPM8FG1Y__;!!INViTUAdUeDF!0ECanToO5ObYvKTotdZ0AVvfBrOOul9wF8tgqkj28PYNukt04bXoxAPQmtzXEISD4v5Ao7T5GCehKxSBxMrAZyQ$).  This doesn't need the above privileges - as there are no container-runtime APIs involved (though you would need to support exec into target pods. Also while this works with most base images, it may not work on all.)These are being used for the newer pod-cpu-hog experiment that remotely injects a stress-ng process into the target container. (edited) 

 

https://litmuschaos.github.io/litmus/experiments/categories/pods/pod-cpu-hog-exec/"

**Comment by neelanjan00** [comment]
Closing this issue, based on the resolution in this Slack thread: https://kubernetes.slack.com/archives/CNXNB0ZTN/p1654569314744489
