### ISSUE TITLE
PlatformTests fail when auxiliaryAppInfo is passed in the workflow

### ISSUE THREAD

**Issue by vamsiammineni** [litmuschaos/litmus#3730]
**What happened**:
While running Platform level tests, I have passed the "auxiliaryAppInfo" details in order to check the status of a particular application before and after the chaos.

But, the workflow failed in pre-chaos step when it tries to check the containerstatus for the auxiliaryAPP with following error message.

```
time="2022-08-08T14:02:15Z" level=info msg="[Status]: Verify that the AUT (Application Under Test) is running (pre-chaos)"
time="2022-08-08T14:02:15Z" level=info msg="[Status]: No appLabels provided, skipping the application status checks"
time="2022-08-08T14:02:15Z" level=info msg="[Status]: Verify that the Auxiliary Applications are running (pre-chaos)"
time="2022-08-08T14:02:15Z" level=info msg="[Status]: Checking whether application containers are in ready state"
time="2022-08-08T14:05:17Z" level=error msg="Auxiliary Application status check failed, err: Unable to find the pods
with matching labels, err: invalid namespace \"app.kubernetes.io/name=<label>\": [may not contain '/']" 
```

**What you expected to happen**:

Workflow should not fail in pre-chaos step. auxiliaryAppInfo status check should be succeeded

**Where can this issue be corrected? (optional)**
// CheckAuxiliaryApplicationStatus checks the status of the Auxiliary applications

https://github.com/litmuschaos/litmus-go/blob/535c1e7d05ff61caff79a93beb0b2dd176c1f94f/pkg/status/application.go

```
func CheckAuxiliaryApplicationStatus(AuxiliaryAppDetails string, timeout, delay int, clients clients.ClientSets) error {

	AuxiliaryAppInfo := strings.Split(AuxiliaryAppDetails, ",")

	for _, val := range AuxiliaryAppInfo {
		AppInfo := strings.Split(val, ":")
		if err := CheckApplicationStatus(AppInfo[0], AppInfo[1], timeout, delay, clients); err != nil {
			return err
		}
	}
	return nil
}
```
In the above code, AppInfo[0] is label and AppInfo[1] is namespace after splitting the auxiliaryAppInfo string.

checkApplicationStatus method accepts appNs as first argument and appLabel as second argument. Here we are passing these in reverse order which is causing the failure.

**How to reproduce it (as minimally and precisely as possible)**:
Issue is reproduced when the auxiliaryAppInfo has a label that contain '/' 

**Anything else we need to know?**:
This is a very basic and important functionality. Needs to be fixed with high prio.

**Comment by avaakash** [comment]
Fixed with this PR: https://github.com/litmuschaos/litmus/pull/3823
