### ISSUE TITLE
auxialiaryAppInfo support is removed for pod-level tests. But, documentation still says it is supported

### ISSUE THREAD

**Issue by vamsiammineni** [litmuschaos/litmus#3740]
**What happened**:
As per the existing documentation, auxiliaryAppInfo feature is still supported by litmus even for pod-level tests. But, community has confirmed that this feature is removed for pod-level tests and the documentation needs an update.

https://litmuschaos.github.io/litmus/experiments/concepts/chaos-resources/chaos-engine/application-details/#auxiliary-application-info

**What you expected to happen**:
Update this document 
https://litmuschaos.github.io/litmus/experiments/concepts/chaos-resources/chaos-engine/application-details/#auxiliary-application-info

**Where can this issue be corrected? (optional)**
Update this document:
https://litmuschaos.github.io/litmus/experiments/concepts/chaos-resources/chaos-engine/application-details/#auxiliary-application-info

**How to reproduce it (as minimally and precisely as possible)**:
Add auxiliaryAppInfo in the pod-level tests see there are no logs for verifying the auxiliary applications in pre-chaos and post-chaos steps.

Nothing is implemented related to auxiliaryAppInfo verification in the code for all pod-level tests.

**Anything else we need to know?**:
No

**Comment by avaakash** [comment]
Since auxiliaryAppCheck is still applicable for node-level experiments, we will be adding a note in the documentation to highlight this.
