### ISSUE TITLE
Pod memory hog chaosschedule not working in istio enabled namespace.

### ISSUE THREAD

**Issue by pawanphalak** [litmuschaos/litmus#3741]
Hi team, While running the pod memory hog with chaosscheduler, the helper pods created by the litmus are running into the error state. We noticed this happening for namespace with istio injection enabled. There are option to add annotations to runner pod such that we can disable the istio proxy for chaos runner pods , however I can not find any configuration such that I can add annotations to helper pods as well, can you please help if we can configure the annotations for helper pods created by litmus chaos test as well?
Or if there is any other way we can make the pod memory hog chaosschedule work with istio side car containers.

Following is my chaosschedule configurations:
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosSchedule
metadata:
  name: schedule-pod-memory-hog
  namespace: default
spec:
  engineTemplateSpec:
    annotationCheck: "false"
    appinfo:
      appkind: deployment
      applabel: app=productpage
      appns: default
    chaosServiceAccount: pod-memory-hog-sa
    engineState: active
    experiments:
    - name: pod-memory-hog
      spec:
        components:
          env:
          - name: STRESS_IMAGE
            value: alexeiled/stress-ng:latest-ubuntu
          - name: MEMORY_CONSUMPTION
            value: "500"
          - name: TOTAL_CHAOS_DURATION
            value: "60"
    jobCleanUpPolicy: delete
  schedule:
    repeat:
      properties:
        minChaosInterval:
          minute:
            everyNthMinute: 2
  scheduleState: active

Following is the error log seen in the litmus chaos helper pods:
level=fatal msg="helper pod failed, err: Get \"https://10.108.0.1:443/api/v1/namespaces/default/pods/productpage-v1-5fcf699874-rc4kp\": dial tcp 10.108.0.1:443: connect: connection refused"

Here productpage-v1-5fcf699874-rc4kp is the application under test for chaos.

**Comment by ispeakc0de** [comment]
Hi @pawanphalak ,
Please follow this FAQ, it should solve your issue - https://litmuschaos.github.io/litmus/experiments/troubleshooting/experiments/#experiment-failed-for-the-istio-enabled-namespaces
