### ISSUE TITLE
StatusChecktimeouts values don't take effect in the workflow manifest

### ISSUE THREAD

**Issue by vamsiammineni** [litmuschaos/litmus#3744]
**What happened**:
statusCheckTimeout custom values don't take effect and default values 180s override the custom values.

**What you expected to happen**:
statusCheckTimeout values should override the default values.

**How to reproduce it (as minimally and precisely as possible)**:
Update the workflow with the following values and can see that workflow still waits 180s(default) before it fails.

statusCheckTimeouts:
   delay: 2
   timeout: 600

**Anything else we need to know?**:

**Comment by ispeakc0de** [comment]
Hi @vamsiammineni ,
It should work as expected. Can you please follow this https://litmuschaos.github.io/litmus/experiments/concepts/chaos-resources/chaos-engine/experiment-components/#experiment-status-check-timeout ? If it is still not working then please share the following info:
1. litmus version
2. Describe output of the ChaosEngine

**Comment by neelanjan00** [comment]
@vamsiammineni were you able to figure this out?
