### ISSUE TITLE
Update in the Front End 

### ISSUE THREAD

**Issue by lavakush07** [litmuschaos/litmus#3751]
![Screenshot 2022-08-30 220804](https://user-images.githubusercontent.com/70131581/187492772-bd4300b5-38a0-4ae1-b524-754aa559cc27.png)

- As Litmus Chaos is an incubating project it's need to be get update it on the website.

Can you assign me this issue to work upon.

**Comment by divaspathak** [comment]
I also want to work on this issue. Can you please assign me this?

**Comment by ksatchit** [comment]
@divaspathak the website code is maintained here: https://github.com/litmuschaos/litmus-website-2

**Comment by avaakash** [comment]
Hi, @divaspathak and @lavakush07  any updates on this issue? If you have made the changes, feel free to raise a PR in the[ Litmus Website Repo](https://github.com/litmuschaos/litmus-website-2).

**Comment by 0xSaksham** [comment]
Hi I can update the message. Please assign me this issue.

**Comment by avaakash** [comment]
Hi @0xSaksham you can raise a PR linking this issue, we can get it merged at the earliest.

**Comment by 0xSaksham** [comment]
Okay sir @avaakash I will do it early in the day.

Thank you

**Comment by 0xSaksham** [comment]
![image](https://user-images.githubusercontent.com/90046016/199509032-cb8124f7-f4d4-40e6-9f2d-335426329bc5.png)
@avaakash How does this look?

**Comment by 0xSaksham** [comment]
@avaakash Yes sure.

**Comment by avaakash** [comment]
Thank you @0xSaksham for the PR, this issue has been fixed.

**Comment by 0xSaksham** [comment]
**Thank you everyone for help.**
