### ISSUE TITLE
Unable to pull litmuschaos/upgrade-agent-cp from dockerhub

### ISSUE THREAD

**Issue by Gaethje** [litmuschaos/litmus#3779]
I am trying to install in a private on-prem k8 cluster. What we usually do is we pull all the images needed locally and push it to our internal artifactory. Then we route images to the helm chart.
i was able to pull all the images except one.
` sksabit.faisal@P87111  ~  docker pull litmuschaos/upgrade-agent-cp`
`Using default tag: latest`
`Error response from daemon: manifest for litmuschaos/upgrade-agent-cp:latest not found: manifest unknown: manifest unknown
`
FYI i was able to pull litmusportal-frontend, litmusportal-server, curl, litmusportal-auth-server. mongodb-bitnami images also was no issue.
is there any other registry that i can use to pull this image? 
Thanks. Great project! appreciate your work.

**Comment by neelanjan00** [comment]
Thanks for creating this issue, @Gaethje! 🙏 Can you PTAL @Jonsy13?

**Comment by avaakash** [comment]
Hi @Gaethje, the `latest` tag is not available for `litmuschaos/upgrade-agent-cp` image, you can use `ci` for the master branch or `2.13.0` for the latest release version. It is advised to use the versioned tag for all the images (or `ci` tag for development).
Ref: https://hub.docker.com/r/litmuschaos/upgrade-agent-cp/tags

**Comment by bingwei-hong-partior** [comment]
Hi, i believe the issue is not due to the image not available on dockerhub, but rather, imagePullSecrets is missing from the job manifest created when using private image registry. is there any fix on this? as we can't even modify the job created.
