### ISSUE TITLE
Create Litmus Plugin for Backstage

### ISSUE THREAD

**Issue by ksatchit** [litmuschaos/litmus#3813]
Backstage is a popular CNCF project that acts as an aggregator to bring together multiple aspects of development-to-deploy for app (where the code lives, where/how is the service defined, where/how it is being built, where the docs reside) into a single view for the cloud native developer (backstage calls this the "developer portal"). There is immense value in viewing chaos tests associated with an app in this developer portal. For example, each app can be associated with its own hub, that can be visualized and leveraged within a given developer portal. Going further, this can be leveraged to view experiment execution status, not very different from how the CI/CD pipeline runs are viewed today in backstage. 

This issue has been created to track the implementation of a chaos plugin for backstage, to provide the aforementioned functionality - based on a discussion between Backstage maintainers and @umamukkara , @ksatchit during the Kubecon NA 22.

**Comment by money8203** [comment]
Hey, I am a beginner and I want to contribute to this project so could you please tell me form where to get started ?

**Comment by Saranya-jena** [comment]
Closing it as this has been added.
