### ISSUE TITLE
External dex support

### ISSUE THREAD

**Issue by ksponomarev** [litmuschaos/litmus#3821]
Hello, Team. 
Could you please implement support for external dex?
We have own dex instance and want to connect litmus to it
Thank you

**Comment by imrajdas** [comment]
Hey @ksponomarev - We do support dex

Refer the following
- https://docs.litmuschaos.io/docs/concepts/oauth-dex-concept/
- https://docs.litmuschaos.io/docs/user-guides/chaoscenter-oauth-dex-installation/

**Comment by ksponomarev** [comment]
Ok
I've edited my auth-server with
```
DEX_ENABLED:               true
DEX_OAUTH_CALLBACK_URL:    https://litmus.example.com
DEX_OAUTH_CLIENT_ID:       litmus
DEX_OAUTH_CLIENT_SECRET:   11111111
OIDC_ISSUER:               https://dex.esb-d-dmz5-msk34-c01.compute.raiffeisen.ru/dex
```
But dex still isn't enabled
What I am doing wrong?

**Comment by ksponomarev** [comment]
@imrajdas FYI
