### ISSUE TITLE
Add custom tests

### ISSUE THREAD

**Issue by KurtSchenk** [litmuschaos/litmus#3824]
Is it possible to add custom tests? For example, I would like more control over storage tests to include capabilities that FIO provides.

**Comment by avaakash** [comment]
Hi @KurtSchenk, if you are talking about custom experiments, you can use the litmus-go SDK or litmus-python SDK to write custom business logic for experiments.
For docs:
[litmus-go SDK](https://github.com/litmuschaos/litmus-go/tree/master/contribute/developer-guide)
[litmus-python SDK](https://github.com/litmuschaos/litmus-python/tree/master/contribute/developer-guide)
