### ISSUE TITLE
GraphQL APIs not working 

### ISSUE THREAD

**Issue by avimalakar** [litmuschaos/litmus#3841]
I have deployed Litmus chaos on AWS EKS but when I am trying to run graphql queries on graphql server , it gives me this error for all your APIs on official documentation. Below is the response of getCluster request
{
    "errors": [
        {
            "message": "Cannot query field \"getCluster\" on type \"Query\". Did you mean \"listClusters\"?",
            "locations": [
                {
                    "line": 2,
                    "column": 4
                }
            ],
            "extensions": {
                "code": "GRAPHQL_VALIDATION_FAILED"
            }
        }
    ],
    "data": null
}

**Comment by avimalakar** [comment]
![Screenshot 2022-11-23 175015](https://user-images.githubusercontent.com/100187318/203545853-e992123f-475d-4104-8eb3-dacc1566acb1.jpg)

**Comment by imrajdas** [comment]
Please follow this API doc- https://litmuschaos.github.io/litmus/graphql/v2.0.0/api.html#tag-Cluster

It's a syntax issue. Not an API/code issue.
