### ISSUE TITLE
Litmus on GKE Autopilot cluster

### ISSUE THREAD

**Issue by btprocorp** [litmuschaos/litmus#3842]
I was exploring Litmus 2.14.0 for GKE Autopilot cluster. however, I came to know that Since we're no longer provisioning or managing the nodes in GKE Autopilot cluster, there's no SSH access to nodes. not even the nodes are displayed in the console. is there any way to get a chaos experiment like node restart in autopilot cluster nodes? Does commercial tools like Gremlin support GKE Autopilot cluster chaos testing?

**Comment by neelanjan00** [comment]
Hi @btprocorp, you can still do a `node-restart` kind of experiment for the GKE cluster using the [GCP VM Instance Stop](https://hub.litmuschaos.io/gcp/gcp-vm-instance-stop) experiment. It will cause a GCP VM, which in this case is your GKE node, to stop for a specified duration and then re-start.
