### ISSUE TITLE
what's the most number of agents that a litmus server can support

### ISSUE THREAD

**Issue by serlina** [litmuschaos/litmus#3853]
## Question
I'm trying to use litmus, it is a great tool with a powerful ability.  I noticed litmus server can be connected by a remote agent. So I want to confirm, how many agents can be connected by a litmus server? is there some description of this?
and if there is a limitation of the agent's number, which factors limit it

My limitus server is 2.14.0

**Please make sure you have,**

- Reviewed the [Questions](https://github.com/litmuschaos/litmus/labels/question) asked by our community members and contributers.
- Searched opened and closed [GitHub issues](https://github.com/litmuschaos/litmus/issues)

**We primarily use GitHub as an issue tracker; for usage and support questions, please check out these resources below. Thanks!**

  - [LitmusChaos Readme](https://github.com/litmuschaos/litmus)
  - [LitmusChaos Docs](https://docs.litmuschaos.io/docs/next/getstarted.html)

**Comment by neelanjan00** [comment]
During a stress test, we scaled up to 1.1K agents and 11K workflow runs with no issues 😄 
Check this tweet: https://twitter.com/Uma_Mukkara/status/1408024334845710337?s=20&t=O7UsoiyU_Y0PB4lRnPB3Cg

Coming back to your question, we don't have exact benchmark numbers for your reference, but the scalability will depend on your Kubernetes cluster's configuration.
