### ISSUE TITLE
How to modify the "CHAOS LIB" ENV of the chaos experiment via the CHAOSCENTER 

### ISSUE THREAD

**Issue by xidian237** [litmuschaos/litmus#3858]
## Question
How to modify the "**CHAOS LIB**" ENV of the chaos experiment via the **CHAOSCENTER**?

**Comment by swarna1101** [comment]
1. Install the `chaoslib` module: You can install the chaoslib module using `pip`. Open a terminal and run the following command:

```python
pip install chaoslib
```

2. Import the `chaoslib` module: In your Python script, you can import the `chaoslib` module using the `import `statement. For example:

```python
import chaoslib
```

```python
chaoslib.set_env(key1='value1', key2='value2', ...)
```

```python
chaoslib.run_experiment(experiment_function, **kwargs)
```

**Comment by neelanjan00** [comment]
As part of this PR, the `LIB` env was removed. Now only `litmus` LIB is supported.
