### ISSUE TITLE
Container kill experiment failing

### ISSUE THREAD

**Issue by rini2208** [litmuschaos/litmus#3876]
**What happened**: Container kill experiment failed with error  err: application container is not in running state, unable to find the pod with name <pod-name>-776cb96ff6-gktkk, err: pods \"<pod-name>-776cb96ff6-gktkk\" not found" as pod suffix will change once pod got killed and new pod has been created.

**What you expected to happen**: Experiment should pick newly created pod of set by ignoring pod suffix

**Where can this issue be corrected? (optional)**

**How to reproduce it (as minimally and precisely as possible)**: By passing pod with suffix which changes when you kill the container into container kill experiment chaos engine

**Anything else we need to know?**:

**Comment by neelanjan00** [comment]
This is bound to happen if you're providing the pod names as the target. To avoid this from happening, you can either choose the target as the pod parent resource (i.e. deployment/statefulset/replicaset/daemonset) or restrict the experiment to a single iteration of chaos per run i.e. `TOTAL_CHAOS_DURATION` == `CHAOS_INTERVAL`.
