### ISSUE TITLE
gitops function -- when multiple files are deleted in one commit only one file is sync to chaosCenter

### ISSUE THREAD

**Issue by bingwei-hong-partior** [litmuschaos/litmus#3888]
**What happened**:
When chaosCenter is sync to a github repo via gitops, and there are multiple scenario files deleted in one git commit to the repo, only one file is deleted from chaosCenter. The other files remain in chaosCenter. Subsequently when manually delete the file from chaosCenter, the log will shows an File not found in git error.

**What you expected to happen**:
When multiple scenario files are deleted from github repo, all the files be deleted from chaosCenter as well.

**Where can this issue be corrected? (optional)**

**How to reproduce it (as minimally and precisely as possible)**:
Create multiple scenario files via chaosCenter, it will be sync to gitops repository in github. Use git to do multiple scenario files delete from the repo and commit the changes. Observe only one file is actually deleted from chaosCenter, even though multiple files already deleted from the repo.

**Anything else we need to know?**:
<img width="729" alt="image" src="https://user-images.githubusercontent.com/114902409/212596746-24aafffe-29b2-4648-a5a9-868f6efc04c4.png">

**Comment by neelanjan00** [comment]
CC: @AmitKumarDas PTAL

**Comment by neelanjan00** [comment]
@bingwei-hong-partior thanks for reporting this! We will take a look into this.
