### ISSUE TITLE
MongoDB upgrade

### ISSUE THREAD

**Issue by mtcolman** [litmuschaos/litmus#3918]
## Question
Hi, apologies if this should have been a bug report or feature request.

As per the issue I've raised here: https://github.com/litmuschaos/test-tools/issues/336, 

The image `litmuschaos/mongo:4.2.8` is being used in litmus 3.0.0 (e.g. here: https://github.com/litmuschaos/litmus/blob/master/mkdocs/docs/3.0.0-beta4/litmus-3.0.0-beta4.yaml#L823), it is very old (2 years) and comes from (I believe) [here](https://github.com/litmuschaos/test-tools/tree/master/custom/mongo/Dockerfile).

It has a lot of vulnerabilities:
```
litmuschaos/mongo:4.2.8 (ubuntu 18.04)

Total: 374 (UNKNOWN: 0, LOW: 144, MEDIUM: 215, HIGH: 15, CRITICAL: 0)
```

It uses upstream `mongo:4.2.8` and the latest version (11 days old) is `mongo:6.0.4`.

What I'd like to know is how the upgrade should be performed/correlated given it is cross-repo and if there is a reason why such an old image is still in use etc? And how can we go about getting this resolved?

Thanks!

**Comment by imrajdas** [comment]
Hi @mtcolman , we will take this mongo upgrade in LitmusChaos 3.0. Thanks for reminding this.

**Comment by Chan9390** [comment]
The base image Ubuntu 18.04 has attained [End of Standard Support](https://wiki.ubuntu.com/Releases) and will not receive security updates.

**Comment by mtcolman** [comment]
FYI - 

- mongo:4.2.8 = ubuntu 18.04
- mongo:6.0.8 = ubuntu 22.04

**Comment by ksatchit** [comment]
Mongo has been upgraded as part of 3.0 GA: https://github.com/litmuschaos/test-tools/commit/8b624a7867ae495a320e8a5a618664e9797ca02a
