### ISSUE TITLE
Migrate graphql-server from Gorilla mux to Gin

### ISSUE THREAD

**Issue by S-ayanide** [litmuschaos/litmus#3919]
Currently, our codebase uses Gorilla Mux as well as Gin as router frameworks for our backend application. However, Gorilla Mux is no longer actively maintained. To ensure the stability and long-term viability of our codebase, we have decided to migrate completely to Gin, since its more actively maintained and supported.

The goal of this issue is to migrate from Gorilla Mux to Gin and unify the router framework used in our backend application to only use a single framework. This will involve:

1. Updating the codebase to use Gin for all routing functionality.
2. Removing all dependencies on Gorilla Mux from the codebase.
3. Updating any related tests and documentation to reflect the changes made.

Additionally, we need to ensure that the migration process is smooth and does not impact the functionality or stability of the application. We will need to thoroughly test the new router framework to ensure that it meets our performance and stability requirements.

**Comment by c0d33ngr** [comment]
Hi @S-ayanide I'd love to apply for this LFX-MENTORSHIP so I can work on it as a mentee but can't find this issue open in CNCF website.

**Comment by S-ayanide** [comment]
Hey @c0d33ngr 

I'm sorry to inform you that we are not taking LFX mentee applications this year anymore. The application process has been closed, and we are no longer accepting any new submissions at this time. Please keep an eye out for future opportunities that may arise in the future.

**Comment by namkyu1999** [comment]
As an LFX mentee, I'll catch up on this issue :)

**Comment by S-ayanide** [comment]
A PR for this issue has been raised

https://github.com/litmuschaos/litmus/pull/3923

**Comment by imrajdas** [comment]
closed by https://github.com/litmuschaos/litmus/pull/3923
