### ISSUE TITLE
Move to using interfaces for better mocking, abstraction and decoupling

### ISSUE THREAD

**Issue by S-ayanide** [litmuschaos/litmus#3931]
Currently, our Golang codebase heavily relies on concrete types for implementing functionality. While this approach has its benefits, it can lead to tight coupling between modules and make our codebase less modular and harder to maintain in the long run.

To address this, we propose that we start using interfaces in our codebase. Interfaces provide a way to define a set of behaviors that a type must implement, without specifying the implementation details. This allows us to achieve better abstraction and decoupling, making our code more modular and easier to test.

An example template on how we can move forward with this -
https://gist.github.com/S-ayanide/94654714b9f1a7f5da3a7cdf38396427

**Comment by namkyu1999** [comment]
As an LFX mentee, I can handle this issue!
