### ISSUE TITLE
Add better logging for backend components

### ISSUE THREAD

**Issue by S-ayanide** [litmuschaos/litmus#3932]
# Description

Currently, our server logs provide limited information, making it difficult to diagnose issues and track user activity. To address this, I propose that we enhance our server logs with additional fields that provide more context and insights.

Here are some suggested fields that we can add to our server logs:

* Request metadata: Adding request metadata fields like request ID, request URL, and request method can help us identify and trace specific requests, making it easier to diagnose issues and track user activity.
* User metadata: Adding user metadata fields like user ID, user IP address, and user agent can help us identify and track user activity, making it easier to monitor and analyze user behavior.
* Server metadata: Adding server metadata fields like server hostname, server IP address, and server time can help us identify and diagnose issues related to server performance and availability.
* Custom fields: Adding custom fields like application-specific metadata can help us track and analyze application-specific events and behaviors.

# Implementation specifications

```golang
        logFields := logrus.Fields{
		"projectId": identifiers.ProjectIdentifier,
		"user": identifiers.User,
		"component": "GraphQL server"
	}

	logrus.WithFields(logFields).Info("request received to create a new delegate")
```

By adding these fields, we can significantly improve the quality and usefulness of our server logs, making it easier to diagnose issues, track user activity, and monitor server performance.

**Comment by S-ayanide** [comment]
@namkyu1999 assigning this task to you, based on the server logging discussion as a part of LFX.

**Comment by namkyu1999** [comment]
Good! I can handle it!

**Comment by JAYESHBATRA** [comment]
Is this issue still available ? If yes then please assign it to me.

**Comment by imrajdas** [comment]
Hi @JAYESHBATRA , these issues are part of LFX and our current mentee(@namkyu1999 ) is working on this. Please feel free to take any other open issue. Or apply for the next LFX term.

**Comment by imrajdas** [comment]
Hey @JAYESHBATRA, Please take up these issues if you're interested. 
1. https://github.com/litmuschaos/litmus/issues/3943
2. https://github.com/litmuschaos/litmus/issues/3944

**Comment by JAYESHBATRA** [comment]
Hi @imrajdas ,

Sure, I'd be happy to take up the issues you've raised.

**Comment by S-ayanide** [comment]
The updated logging setup has been merged, as an improvement we added parameters like `method`, `URI`, `status`, `latency` and `clientIP` with requests to structure as well as identify the logs better.

PR for reference: https://github.com/litmuschaos/litmus/pull/3939

Closing this issue since the task has been resolved.
