### ISSUE TITLE
Integration of Codecov to Compare Unit Test Code Coverage Metrics in Go

### ISSUE THREAD

**Issue by S-ayanide** [litmuschaos/litmus#3976]
# Description:
I would like to propose the integration of Codecov into our Go project to compare unit test code coverage metrics generated by the regular Go tool. This integration will provide us with valuable insights into the code coverage of our tests, enabling us to identify areas that require more thorough testing.

## Current Situation:
Currently, we are using the regular Go tool to generate code coverage metrics for our unit tests. While this provides us with basic coverage information, it lacks the ability to compare coverage across different branches, pull requests, and commits. It also lacks visual representation and easy-to-understand reports, making it difficult to track the progress of our code coverage over time.

## Proposed Solution:
Integrating Codecov into our Go project will address the limitations mentioned above and provide us with comprehensive code coverage reports. Codecov offers a range of features, including visual coverage reports, branch comparison, and pull request integration. By integrating Codecov, we will have access to the following benefits:

* Detailed Reports: Codecov generates detailed reports that provide insights into which lines of code are covered by tests and which ones are not. These reports can help us identify areas of our codebase that require additional testing.
* Visual Representation: Codecov presents code coverage metrics in an easily understandable and visually appealing format. This makes it simpler for team members to track the progress of code coverage and identify areas that need attention.
* Branch Comparison: Codecov allows us to compare code coverage across different branches, enabling us to assess the impact of changes on our test coverage. This feature is particularly useful when working on feature branches or when evaluating the impact of a specific change.
* Pull Request Integration: By integrating Codecov with our pull request workflow, we can automatically analyze the code coverage impact of proposed changes. This ensures that new code contributions maintain or improve our overall coverage.

## Steps to Implement:
To integrate Codecov into our Go project, we will need to perform the following steps:

* Sign up for a Codecov account at https://codecov.io/ if we don't have one already.
* Add the necessary configuration to our project's CI/CD pipeline to collect and upload coverage data to Codecov. This may involve updating our existing test command or adding a separate coverage command.
* Configure our CI/CD pipeline to send coverage data to Codecov after running the tests. This can be achieved by leveraging Codecov's command-line interface or using dedicated integrations available for common CI/CD systems like Jenkins, Travis CI, or GitHub Actions.
* Set up branch comparison and pull request integration within Codecov to enable comparison and analysis of coverage metrics across different branches and pull requests.

Review the generated reports and use the insights to improve our test coverage and identify areas for further testing.

Integrating Codecov will significantly enhance our ability to track and improve the code coverage of our Go project. By visualizing and comparing coverage metrics, we can make data-driven decisions to ensure that our codebase is well-tested and maintainable.

**Comment by Nageshbansal** [comment]
@S-ayanide i would like to work on this. Please assign it to me. thanks

**Comment by namkyu1999** [comment]
Here's a Demo

https://app.codecov.io/gh/namkyu1999/litmus

**Comment by namkyu1999** [comment]
Are there any updates about the security issue @S-ayanide ?

**Comment by mridul549** [comment]
Can I work on this issue?

**Comment by jignyasamishra** [comment]
@S-ayanide @namkyu1999 Hello! I have raised a PR. Please review it.Thank you!!

**Comment by S-ayanide** [comment]
After thorough consideration and in light of the recent security breach issue reported by Codecov (referenced here: [Codecov Security Update](https://about.codecov.io/security-update/)), we have decided not to move forward with Codecov as our unit test coverage metrics collection tool.

The security of our code and data is of utmost importance, and the mentioned security incident raises concerns about the overall integrity and safety of using Codecov at this time.

In exploring alternatives, we are open to considering tools that prioritize security and align with our use case. Two options we are interested in exploring are SonarQube and GuardRails. It's worth noting that we have previously tried Codeacy and DeepScan, but found them unsuitable for our use case. Codeacy did not meet our requirements, and DeepScan, while effective for frontend issues, does not align with our current needs.

Let's initiate the exploration of SonarQube and GuardRails, and please feel free to share any insights or concerns regarding these alternatives. Additionally, if anyone has other suggestions, please bring them to the discussion.
