### ISSUE TITLE
Incorrect function name in file_handler test

### ISSUE THREAD

**Issue by SohamRatnaparkhi** [litmuschaos/litmus#4012]
**What happened**:
When we try to run the file_handler test file in rest_handlers ([link](https://github.com/litmuschaos/litmus/blob/master/litmus-portal/graphql-server/pkg/rest_handlers/file_handler_test.go#L39)), the build of this test(test in the link) fails because there is no function named `ClusterCreateJWT`.

**What you expected to happen**:
The test should succeed.

**Where can this issue be corrected? (optional)**

The correct function name should be `CreateClusterJWT` as seen in file  [graphql-server/pkg/cluster/cluster_jwt.go](https://github.com/litmuschaos/litmus/blob/master/litmus-portal/graphql-server/pkg/cluster/cluster_jwt.go#L12)

**How to reproduce it (as minimally and precisely as possible)**:
From the root directory, run the command - `go test ./litmus-portal/graphql-server/pkg/rest_handlers/file_handler_test.go`

**Comment by amityt** [comment]
The fix will be taken as part of this PR: https://github.com/litmuschaos/litmus/pull/4009
