### ISSUE TITLE
Testcases for choas_experiment handler

### ISSUE THREAD

**Issue by SohamRatnaparkhi** [litmuschaos/litmus#4050]
Inside the [/chaos_experiment/](https://github.com/litmuschaos/litmus/tree/master/chaoscenter/graphql/server/pkg/chaos_experiment/) at location `choascenter/graphql/server/pkg`, the handler.go file does not have any testcases.

**Comment by punithnayak** [comment]
Hey @SohamRatnaparkhi can work on this is this issue open

**Comment by SohamRatnaparkhi** [comment]
> @sohamRatnaparkhi please let me know if you are working gon it

I am working on this issue currently.
