### ISSUE TITLE
Testcases for services in chaos_experiment directory

### ISSUE THREAD

**Issue by SohamRatnaparkhi** [litmuschaos/litmus#4051]
Inside the [/chaos_experiment/](https://github.com/litmuschaos/litmus/tree/master/chaoscenter/graphql/server/pkg/chaos_experiment/) at location `choascenter/graphql/server/pkg`, the service.go file does not have any testcases.

Testcases can be added for this file

**Comment by Freedisch** [comment]
Hello @SohamRatnaparkhi , I'm looking to participate in the LFX mentorship this fall, I would like to work on this issue to get familiar with the project 🙂

**Comment by SohamRatnaparkhi** [comment]
Welcome @Freedisch ,
This issue is a part of current LFX mentorship program (i.e. term - 2) and I am working on it. Feel free to pick some other issue. If you have started working on it then sorry for the inconvenience.
