### ISSUE TITLE
Compilation errors in choas_hub/handler tests 

### ISSUE THREAD

**Issue by SohamRatnaparkhi** [litmuschaos/litmus#4052]
**What happened**:
 The tests - [TestGetChartsPath](https://github.com/litmuschaos/litmus/blob/master/chaoscenter/graphql/server/pkg/chaoshub/handler/handler_test.go#L28) and [TestGetChartsData](https://github.com/litmuschaos/litmus/blob/master/chaoscenter/graphql/server/pkg/chaoshub/handler/handler_test.go#L259) fail due to compilation errors.

**What you expected to happen**:
The tests shouldn't have compilation errors

**Where can this issue be corrected?**

In [choascenter/graphql/server/pkg/chaoshub/handler/handler_test.go](https://github.com/litmuschaos/litmus/blob/master/chaoscenter/graphql/server/pkg/chaoshub/handler/handler_test.go), on lines 36, 292, and 303 - `GetChartsPath(_, _, _) is called which takes three arguments. But while calling this function, at all three instances, only 2 parameters are provided and the third boolean parameter is not provided.

**How to reproduce it (as minimally and precisely as possible)**:
Run any of the above mentioned testcases.

**Comment by punithnayak** [comment]
hey @SohamRatnaparkhi  are you working on this

**Comment by SohamRatnaparkhi** [comment]
> hey @SohamRatnaparkhi  are you working on this

No

**Comment by punithnayak** [comment]
can I raise pr for it

**Comment by ksatchit** [comment]
Fixed by https://github.com/litmuschaos/litmus/pull/4113
