### ISSUE TITLE
Contain Kill failing - Cannot connect to the Docker daemon

### ISSUE THREAD

**Issue by awalmsley** [litmuschaos/litmus#4066]
**What happened**:
Container Kill scenario failed, and the helper pod logs indicates could not connect to Docker daemon
```bash
kubectl logs container-kill-helper-bfxrpi
time="2023-07-03T16:55:05Z" level=info msg="Helper Name: container-kill"
time="2023-07-03T16:55:05Z" level=info msg="[PreReq]: Getting the ENV variables"
...
time="2023-07-03T16:55:05Z" level=fatal msg="helper pod failed, err: Unable to run command, err: exit status 1; error output: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\n"
```

**What you expected to happen**:
Expected the container kill scenario to succeed.

**Where can this issue be corrected? (optional)**

**How to reproduce it (as minimally and precisely as possible)**:
Deploy Litmus Chaos to an AWS EKS 1.25 cluster
Run a container kill

**Anything else we need to know?**:
This was working in AWS EKS 1.23, and I'm guessing it is related to the container runtime changing from Docker to containerd in EKS 1.24 https://repost.aws/questions/QU338cvx7RTCCh5tk54WOXqw/aws-eks-supported-container-runtimes

**Comment by oumkale** [comment]
Hi @awalmsley,
Thank you for trying out container kill experiment, 

Earlier versions of Kubernetes use Docker as the default runtime, but after 1.24 and later clusters, the only container runtime included in the officially published EKS is containerd

Please update chaosengine with `CONTAINER_RUNTIME` and `SOCKET_PATH` with `containerd` and `/run/containerd/containerd.sock` respectively in workflow manifest and try again.

**Comment by ksatchit** [comment]
Please re-open this issue if you are still unable the container-kill fault post the env changes recommended by @oumkale
