### ISSUE TITLE
[LFX-23-Term-3]: Improve Chaoscenter Web and Authentication Server: Add Unit Test Cases, Enhance GQL APIs, Update API Documentation

### ISSUE THREAD

**Issue by Saranya-jena** [litmuschaos/litmus#4102]
Tasks:

- Add unit test cases in chaoscenter web.
- Add test cases in the authentication server.
- Make changes in GQL and Auth servers to generate swagger API docs for latest release.
- Improve APIs and handler functions in graphql server to reduce code duplicacy.
- Add documentation/video tutorial for local development setup.

**Comment by RohanSasne** [comment]
Hello team :wave:, Rohan this side :)

I am a Google Summer of Code Mentee and an active Open Source contributor with strong belief in the power of community and the impact it can have on our world.

I have solid experience in Cloud Native technologies ranging from Kubernetes, Helms, Docker and many more (The list would be never ending :) ). I am interested in contributing to this project for this fall and would love to get more involved with the community.

I would spend the coming days exploring the codebase and would surely come up with a solid proposal 

Looking forward to have an amazing time with you all :smile:

**Comment by Freedisch** [comment]
This project looks interesting, I will definitely apply for it

**Comment by AHB102** [comment]
Hello team, Archit this side .
This project aligns with my interest and my skills and I would love to contribute to this project during LFX Fall 2023.
Pls let me know if there is any slack community to join for further communication.
Help will be highly appreciated.

**Comment by aashi-ihsaa** [comment]
hey @Saranya-jena this project looks really interesting. I have got experience with graphQL and typescript. would be great if i could get some open issues to learn more about the project. also any slack and discord channel link?

**Comment by omsurase** [comment]
hey @Saranya-jena , Could you please clarify a doubt regarding the addition of unit tests for chaoscenter web?

I went through the codebase of chaoscenter web and inside the controllers folder (https://github.com/litmuschaos/litmus/tree/master/chaoscenter/web/src/controllers) there are various controllers that are handling incoming requests and returning responses to the client.

one such Controller is for login, in which there is a handleLogin function(https://github.com/litmuschaos/litmus/blob/master/chaoscenter/web/src/controllers/Login/LoginPage.tsx) which is used for authentication. 

So will the unit test be written to mock this login controller by passing mock props to handlelogin function?

Thank you for your support.

**Comment by Pranjal7852** [comment]
This project looks really interesting and match with my current skills set. Definitely going to give it a shot

**Comment by kartikaysaxena** [comment]
Hello @Saranya-jena, I have got the codebase running locally and I am interested in this project as it suits my tech stack, I have been working with Go for a months now and am eager to apply to it.

**Comment by hirentimbadiya** [comment]
Greetings Litmus community! I'm eager to participate in the upcoming LFX mentorship for Fall 2023. As an open-source contributor and member at Layer5, I possess expertise in JavaScript, React.js, and Next.js. Additionally, I am well-versed in Golang and TypeScript, and I have familiarity with Docker and Kubernetes. Furthermore, I have a strong understanding of essential computer science topics such as object-oriented programming, data structures, and more. I look forward to contributing my skills and knowledge to this exciting project.

**Comment by Saranya-jena** [comment]
The applications for next term are now open please apply here: 
https://mentorship.lfx.linuxfoundation.org/project/237b7300-d749-4f14-bd4c-9375e5ec39b6
https://mentorship.lfx.linuxfoundation.org/project/fde90e7f-0410-4b84-ad9c-99f7139267ed

**Comment by imrajdas** [comment]
Hi All, Please apply here at https://mentorship.lfx.linuxfoundation.org/project/237b7300-d749-4f14-bd4c-9375e5ec39b6 before the deadline.

We will review all of your applications.

**Comment by alwinsDen** [comment]
I am Alwin T Varghese, an XR Open Source fellow, one among only 100 individuals selected for the program throughout India. During the fellowship, I built an editor introducing AR experiences for fashion designers, enabling them to upload 3D fashion models, edit various parts according to their preferences, alter designs using custom materials, add annotations directly to the model, and easily share their work with peers (also implemented an HD render feature). All of this was developed using **React Three Fiber, TypeScript, and styled-components**. Throughout the project's development from scratch, I have contributed nearly 170+ commits and also took the lead in developing the majority of the backend code using Node.js. I established a pipeline for the automatic deployment of the frontend to an S3 bucket and set up the backend on an EC2 instance. I am known for my determination to accomplish tasks without requiring extensive guidance, and I don't consider the work complete until I've achieved a state of perfection.

Check out my work at XR Open Source here: [https://github.com/alwinsDen/XROS-Fellowship-Contrib-2023.git](url)

**Comment by imrajdas** [comment]
Hi All, We have selected the candidate for this issue. Please visit the LFX mentorship website to learn about the mentee's details.

We regularly participate in LFX mentorship every quarter. Please feel free to apply next quarter.

Meanwhile, you can join our Litmus Community or Contributors calls to learn about projects for contributions.

Again, Thank you, everyone, for applying to this project.
