### ISSUE TITLE
Remove unused RBACs in GraphQL server

### ISSUE THREAD

**Issue by Saranya-jena** [litmuschaos/litmus#4120]
There are a lot of deprecated/unused RBACs present in `graphql/server/pkg/authorization/roles.go`, check the usages and remove them.

**Comment by punithnayak** [comment]
hey @saranya-jena I am able to find the deprecated/unused RBACs will raise pr soon

**Comment by samyakjain10** [comment]
Hey @Saranya-jena, I am interested to work on this issue. Can you assign it to me?

**Comment by RipulHandoo** [comment]
Hi @Saranya-jena @namkyu1999, is this issue still open? I'd like to raise a PR , if it is.
Can you also guide me which variable are to be removed from [this](https://github.com/litmuschaos/litmus/blob/master/chaoscenter/graphql/server/pkg/authorization/roles.go)

**Comment by SohamRatnaparkhi** [comment]
Hi @RipulHandoo 
I think the issue still persists.

In the roles.go ([link](https://github.com/litmuschaos/litmus/blob/master/chaoscenter/graphql/server/pkg/authorization/roles.go)), you might need to check if that particular role query and its corresponding RBAC-rule are being used somewhere.

If you are using VS Code, you can `ctrl+click` on that particular role-query. If VS-Code doesn't show any occurrence/use of that rule in some other file, then you can remove it. Alternatively, you can use the global search too.

For example:
1. If you `ctrl+click` on `UserInfrastructureReg`, you will find its occurrence in the `resolver` of `chaos-infra`. Hence, you will not remove it.
2. If you `ctrl+click` on `TerminateChaosWorkflow` or `SendInvitation`, then you won't find its occurrence anywhere else. Hence, you can remove it. Similarly, you will find many RBACs which are not being used any where.

**Comment by RipulHandoo** [comment]
> Hi @RipulHandoo I think the issue still persists.
> 
> In the roles.go ([link](https://github.com/litmuschaos/litmus/blob/master/chaoscenter/graphql/server/pkg/authorization/roles.go)), you might need to check if that particular role query and its corresponding RBAC-rule are being used somewhere.
> 
> If you are using VS Code, you can `ctrl+click` on that particular role-query. If VS-Code doesn't show any occurrence/use of that rule in some other file, then you can remove it. Alternatively, you can use the global search too.
> 
> For example:
> 
> 1. If you `ctrl+click` on `UserInfrastructureReg`, you will find its occurrence in the `resolver` of `chaos-infra`. Hence, you will not remove it.
> 2. If you `ctrl+click` on `TerminateChaosWorkflow` or `SendInvitation`, then you won't find its occurrence anywhere else. Hence, you can remove it. Similarly, you will find many rules which are not being used anywhere.

@SohamRatnaparkhi 
Thanks for guidance. I'll start working on it ASAP.
