### ISSUE TITLE
Change code architecture in Environment handler to use interface

### ISSUE THREAD

**Issue by Saranya-jena** [litmuschaos/litmus#4121]
Currently, all the resources are having interface architecture except environments. Update the Environment handler functions directory to use the interface structure.

**Comment by punithnayak** [comment]
Hey,@saranya-jena in this https://github.com/litmuschaos/litmus/tree/master/chaoscenter/web/src/views/Environments directory right?
can you please elaborate a bit?

**Comment by RohanSasne** [comment]
cool, will surely come up with a PR on this issue.

**Comment by punithnayak** [comment]
@RohanSasne  I am working in this issue please fell free to work on other issue

**Comment by RohanSasne** [comment]
oh cool, no worries, best luck with this :)

**Comment by srikanth-iyengar** [comment]
Hi @Saranya-jena @namkyu1999, is this issue still open, I'd like to work on this issue.

**Comment by Saranya-jena** [comment]
This has been done. Closing it
