### ISSUE TITLE
Environment listing page is not performing refetch after creating a new environment

### ISSUE THREAD

**Issue by Saranya-jena** [litmuschaos/litmus#4124]
**What happened**:
After creating a new environment, the listing page is not showing the latest environment. Have to refresh the page to get the latest data.
**What you expected to happen**:
After environment is created listEnvironments API to get prefetched and update the page automatically upon successful creation of the env.

**Where can this issue be corrected? (optional)**

**How to reproduce it (as minimally and precisely as possible)**:
Create a new environment and check after closing the modal, the latest is not listed, will have to refresh the page.
**Anything else we need to know?**:

**Comment by RohanSasne** [comment]
just curious! Would putting the API call in a `useEffect` hook solve this bug?
