### ISSUE TITLE
Documentation: Missing Documentation for Environments

### ISSUE THREAD

**Issue by smitthakkar96** [litmuschaos/litmus#4218]
First of all, configurations on `v3.0.0` release. I was going through the [release notes](https://github.com/litmuschaos/litmus/releases/tag/3.0.0), and it mentions `Introducing Environments, a powerful tool that helps users effectively handle their Chaos Infrastructures and keep things organized.` however I don't see any [docs](https://docs.litmuschaos.io/docs/getting-started/installation) on what environments are. Is this something WIP?

**Comment by Saranya-jena** [comment]
Hi @smitthakkar96 [Environment](https://docs.litmuschaos.io/docs/concepts/chaos-infrastructure) is an extra level for abstraction to organize the chaos infrastructures in a better way. You don't need to install anything for environments. An environment can be created using the Chaoscenter UI and the Chaos infrastructure needs to be created under a given environment. We are working on adding the user guide for the same shortly!

**Comment by vanshBhatia-A4k9** [comment]
Hi @smitthakkar96, you can now view the user-guides for Environments [here](https://docs.litmuschaos.io/docs/user-guides/create-environment). cc: @Saranya-jena

**Comment by smitthakkar96** [comment]
Thanks @vanshBhatia-A4k9 @Saranya-jena closing this
