### ISSUE TITLE
Unable to set `Stop On Failure` when editing a resilience probe

### ISSUE THREAD

**Issue by smitthakkar96** [litmuschaos/litmus#4251]
**What happened**:

When trying to edit a probe if you click on switch to toggle `Stop On Failure` nothing happens

**What you expected to happen**:

Being able to toggle `Stop On Failure` on probes during edit

**How to reproduce it (as minimally and precisely as possible)**:

- Create a Resilience Probe without `Stop On Failure` set to `true`
- Edit Probe
- Try to toggle `Stop On Failure` switch

**Comment by Saranya-jena** [comment]
Thanks for reporting this issue!

**Comment by S-ayanide** [comment]
Hey @smitthakkar96 thanks for reporting this issue, we've taken a look at this and this issue has been fixed in version 3.4.0 and above. Feel free to reopen this issue if you feel otherwise. Thanks.
