### ISSUE TITLE
Editing existing promprobe gives a k8sprobe error in 3.2.0 - Prom probes fail in PreChaos

### ISSUE THREAD

**Issue by nwinstel-insight** [litmuschaos/litmus#4306]
**What happened**: I created a promprobe, then tried to edit it and the panels give me a k8sprobe error when saving
![Screenshot 2023-11-27 at 12 42 59 PM](https://github.com/litmuschaos/litmus/assets/105605527/a83fde73-66ee-4162-a481-6aadcf658f59)

**What you expected to happen**: I can save my updated promprobe

**Where can this issue be corrected? (optional)**

**How to reproduce it (as minimally and precisely as possible)**:
Create a promprobe and then edit it. Try to save it after

**Anything else we need to know?**:

**Comment by nwinstel-insight** [comment]
I'm also seeing promprobes failing with label matching errors. I'm not using label matching. It almost looks like it thinks promprobes are k8sprobes no matter what.

**Comment by nwinstel-insight** [comment]
PromProbes appear to be broken.

**Comment by nwinstel-insight** [comment]
The mutator for creation looks good:

```json
{
    "operationName": "addPROMProbe",
    "variables": {
        "projectID": "unimportant",
        "request": {
            "name": "test-prom",
            "description": "",
            "tags": [],
            "type": "promProbe",
            "infrastructureType": "Kubernetes",
            "promProperties": {
                "probeTimeout": "10s",
                "interval": "5s",
                "retry": 3,
                "attempt": 3,
                "endpoint": "http://test.probe.creation",
                "query": "up{cluster=\"test-cluster\",job=\"kube-state-metrics\",instance=\"this-is-a-test}",
                "comparator": {
                    "type": "int",
                    "criteria": "==",
                    "value": "1"
                }
            }
        }
    },
    "query": "mutation addPROMProbe($projectID: ID!, $request: ProbeRequest!) {\n  addProbe(projectID: $projectID, request: $request) {\n    name\n    description\n    type\n    promProperties {\n      probeTimeout\n      interval\n      retry\n      comparator {\n        type\n        value\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}"
}
```

However when pulling the definition to edit it I see this:

```json
{
    "data": {
        "getProbe": {
            "name": "test-prom",
            "description": "",
            "type": "promProbe",
            "tags": [],
            "infrastructureType": "Kubernetes",
            "kubernetesHTTPProperties": null,
            "promProperties": {
                "probeTimeout": "10s",
                "interval": "5s",
                "retry": 3,
                "attempt": 3,
                "evaluationTimeout": null,
                "probePollingInterval": null,
                "initialDelay": null,
                "stopOnFailure": null,
                "endpoint": "http://test.probe.creation",
                "query": "up{cluster=\"test-cluster\",job=\"kube-state-metrics\",instance=\"this-is-a-test}",
                "queryPath": null,
                "comparator": {
                    "type": "int",
                    "value": "1",
                    "criteria": "==",
                    "__typename": "Comparator"
                },
                "__typename": "PROMProbe"
            },
            "k8sProperties": null,
            "kubernetesCMDProperties": null,
            "__typename": "Probe"
        }
    }
}
```

as what comes back when I pull it up to edit it. Then when I save it I get this:

```json
{
    "errors": [
        {
            "message": "k8s probe type's properties are empty",
            "path": [
                "updateProbe"
            ]
        }
    ],
    "data": null
}
```

Could the issue be that k8sProperties should just be ignored?

**Comment by nwinstel-insight** [comment]
Hello @S-ayanide any update on this? I know it's only been 5 days since you wrote back, but the ticket is 3 weeks old and had all promprobes broken?with previous versions of litmus chaos not working with k8s v1.27+ there are no functioning prom probes for anyone on k8s 1.27+.

**Comment by nwinstel-insight** [comment]
@S-ayanide - At this point promprobes are completely broken and I use them _a lot_. Is there a plan to update this anytime soon?

**Comment by nwinstel-insight** [comment]
To be clear, the execution of Promprobes also fails with a label matching error as if it's a k8sprobe, not just updating them in the UI

**Comment by nwinstel-insight** [comment]
@Saranya-jena @S-ayanide

**Comment by nwinstel-insight** [comment]
This is still broken in 3.2.0

**Comment by S-ayanide** [comment]
A PR has been raised to address this bug
https://github.com/litmuschaos/litmus/pull/4356

**Comment by nwinstel-insight** [comment]
Thanks @S-ayanide - I'm really looking forward to these probes working!

**Comment by nwinstel-insight** [comment]
The latest fix I stalled to main seems to have fixed it!
