### ISSUE TITLE
ListInfras GraphQL query return infras.projectID field empty

### ISSUE THREAD

**Issue by williamokano-dh** [litmuschaos/litmus#4337]
**What happened**:
When executing the following GraphQL query against the server, the field `infras.projectID` return an empty string `""`.

**What you expected to happen**:
The field should be populated.

**Where can this issue be corrected? (optional)**
Probably here https://github.com/litmuschaos/litmus/blob/master/chaoscenter/graphql/server/pkg/chaos_infrastructure/service.go#L665-L683

**How to reproduce it (as minimally and precisely as possible)**:
1. Install Litmus Chaos Center
2. Create an environment
3. Create an infra
4. Execute the following query against the graphql server
```graphql
query ListInfras($projectID: ID!, $request: ListInfraRequest!) {
    listInfras(projectID: $projectID, request: $request) {
        totalNoOfInfras
        infras {
            projectID,
            infraID
        }
    }
}
```
5. Observe that the response comes empty for the aforementioned field
```json
{
  "data": {
    "listInfras": {
      "totalNoOfInfras": 3,
      "infras": [
        {
          "projectID": "",
          "infraID": "bb976ecb-8f27-400c-8952-93cce038b864"
        },
        {
          "projectID": "",
          "infraID": "c5d1fa64-4032-459c-9115-71d9dc0ac39e"
        },
        {
          "projectID": "",
          "infraID": "b4cafc2c-d8e5-438e-82db-7779cef9a45c"
        }
      ]
    }
  }
}
```

**Anything else we need to know?**:
It's a minor bug as it's easily fixable from the client side as `projectID` is a mandatory field, but I would rather not have to have any post-query fixing.

**Comment by Saranya-jena** [comment]
Hi @williamokano-dh , thanks for reporting this issue, would you like to contribute to this, or else we can take it up?

**Comment by williamokano-dh** [comment]
I can work on it this weekend or the next one, but if you have someone from Litmus project to work on this already, it's fine by me.

**Comment by Nageshbansal** [comment]
@Saranya-jena I'll take this one
