### ISSUE TITLE
litmusctl connect chaos-infra: failed to get the Infra registration token:

### ISSUE THREAD

**Issue by CindyLizi** [litmuschaos/litmus#4343]
**What happened**:
Litmusctl version:  1.0.0

$litmusctl config set-account
Host endpoint where litmus is installed: <myURL>
Username [Default: admin]: admin
Password: ******

account.username/admin configured
Error:  internal system error

$litmusctl connect chaos-infra
...

❌ failed to get the Infra registration token:

there is issue https://github.com/litmuschaos/litmusctl/issues/169  on "litmusctl config set-account" error, i have the same issue before use "litmusctl connect chaos-infra" 

not sure if the fix of issue 169 will resolve this issue or not.

**Comment by SarthakJain26** [comment]
@Nageshbansal will this issue be fixed with your fix you raised in litmusctl 1.2.0 ?

**Comment by Nageshbansal** [comment]
Yes @SarthakJain26 , this issue has been resolved in the release-1.2.0
