### ISSUE TITLE
are the GraphQL EnvironmentFilterInput types wrong?

### ISSUE THREAD

**Issue by williamokano** [litmuschaos/litmus#4354]
## Question
Looking through the GraphQL definitions I found the following

https://github.com/litmuschaos/litmus/blob/master/chaoscenter/graphql/definitions/shared/environment.graphqls#L50-L57

Aren't these definitions inverted? Shouldn't `tags` be `[String!]` and `type` be `EnvironmentType`?

Looks swapped for me as they don't make much sense.

**Comment by Saranya-jena** [comment]
Thanks for reporting this issue!
