### ISSUE TITLE
Unifying Chaos Experiment Runs status to enum

### ISSUE THREAD

**Issue by namkyu1999** [litmuschaos/litmus#4400]
We already have the `ChaosExperimentRunStatus` enum like below.

https://github.com/litmuschaos/litmus/blob/399af62ca877c265160ea9edc6a2b8ee1b7f5f9d/chaoscenter/graphql/definitions/shared/chaos_experiment.graphqls#L23-L33

But our code base uses plain string, not an enum. That makes it difficult to make changes to the code.

e.g.

1. There's no `Queued` state in our enum.
https://github.com/litmuschaos/litmus/blob/399af62ca877c265160ea9edc6a2b8ee1b7f5f9d/chaoscenter/graphql/server/pkg/chaos_experiment_run/handler/handler.go#L856-L859

2. There's a difference between our enum and other code
https://github.com/litmuschaos/litmus/blob/399af62ca877c265160ea9edc6a2b8ee1b7f5f9d/chaoscenter/graphql/server/pkg/chaos_experiment_run/handler/handler.go#L1045-L1051

Also, I cannot find docs about `Chaos Experiment status & Chaos Experiment Run status`.

So, We need to implement two things.
1. Unifying Chaos Experiment Runs status to enum
2. Add docs about `Chaos Experiment status & Chaos Experiment Run status`

Let me know if I'm misinterpreting. If I'm on the right track, I'll get started or assign the task to the LFX mentee.

**Comment by Saranya-jena** [comment]
@amityt  Can you take a look at this?

**Comment by amityt** [comment]
Sure @Saranya-jena I will take this up! Thanks for pointing this out @namkyu1999
