### ISSUE TITLE
Enhancing Chaos Center: Implementing E2E Test Cases and Addressing CVE Issues

### ISSUE THREAD

**Issue by imrajdas** [litmuschaos/litmus#4406]
* Currently, we don't have many E2E test cases for the chaos centre, making testing difficult during the release. We have add the E2E critical test cases in the chaos center
* We have CVEs in the chaos centre, we need to fix those CVEs

**Comment by tilaksolunke** [comment]
are the CVEs already identified? if yes, could you please tell where to find those? or do we need to identify CVEs and solve them? I have checked https://cve.mitre.org/cve/search_cve_list.html and didn't find any public CVEs of chaos center

**Comment by KrishAryan** [comment]
Hello everyone,

I have basic knowledge of Linux, Docker, Helm, Kubernetes, IaC, Go, version control, GitHub Actions, and Argo CD. I was a part of GSoC 2023 in OpenSUSE and have cleared certifications such as CKA, CKAD, and Terraform Associate.

This issue caught my eye as it aligns with my skills and provides an excellent opportunity to gain hands-on experience with real-world open-source codebases. I'm excited about the prospect of making meaningful contributions.

I look forward to learning from the Litmus community and contributing to this valuable project.

**Comment by Dhanush0369** [comment]
Applied in this project for lfx mentorship. Looking forward to results.
