### ISSUE TITLE
tests: add tests for `chaoscenter/authentication/api/middleware/jwt_middlware.go`

### ISSUE THREAD

**Issue by EshaanAgg** [litmuschaos/litmus#4410]
Currently, there are no tests present in the repository for `chaoscenter/authentication/api/middleware/jwt_middlware.go`. I would like to add the tests for the same.

**Comment by prithvi1307** [comment]
Hey @EshaanAgg please go ahead taking this issue. Let us know if you need any help

**Comment by EshaanAgg** [comment]
I see that @nikzayn has already added a test suite in #4411. Perhaps we can try reviewing that to avoid duplicate efforts. If you would like me to raise a PR, I would be more than happy to. Thanks for the response!
