### ISSUE TITLE
Add `dashboard` button in side menu in the chaoscenter

### ISSUE THREAD

**Issue by milinddethe15** [litmuschaos/litmus#4419]
In account settings page, there is no button to go to `dashboard`.
User has to manually navigate to '/' path.
We can add a `dashboard` button in side menu shown below.
![image](https://github.com/litmuschaos/litmus/assets/99114125/2d2afd50-2af2-4b45-aa32-acf17fea063d)
I am willing to make PR regarding this.

**Comment by Saranya-jena** [comment]
Hey @milinddethe15 User should be able to go to the dashboard by clicking on the Litmus icon.

**Comment by hrishavjha** [comment]
Hey @milinddethe15
Thanks for finding this. This is a UI issue with screen sizes, I'm attaching a video that shows what is happening and assigning this to you. You can reach out for any help if needed.
Thanks.

https://github.com/litmuschaos/litmus/assets/13471333/a989a17e-b157-4993-bd9a-f25a778b43f7

**Comment by aryan-bhokare** [comment]
@hrishavjha  is this what we want? 

https://github.com/litmuschaos/litmus/assets/92683836/9cf603a6-8df2-4d13-b4f7-3de948bbc0cf

**Comment by hrishavjha** [comment]
> @hrishavjha is this correct?
> 
>  litmusicon.mp4

Yes this looks good, thanks @aryan-bhokare

**Comment by hrishavjha** [comment]
> Hi @hrishavjha @Saranya-jena, When I commit my changes it shows this error:
> 
> ```shell
> $ git commit -s -m "fixed main-nav height"
> chaoscenter/web/.husky/pre-commit: 4: declare: not found
> husky - pre-commit hook exited with code 127 (error)
> ```
> 
> I'm using `/bin/bash` I think `chaoscenter/web/.husky/pre-commit` needs bash shell support. Should I open issue regarding this?

Try running `yarn prepare` once and see if this fixes this issue.

**Comment by aryan-bhokare** [comment]
> > Hi @hrishavjha @Saranya-jena, When I commit my changes it shows this error:
> > ```shell
> > $ git commit -s -m "fixed main-nav height"
> > chaoscenter/web/.husky/pre-commit: 4: declare: not found
> > husky - pre-commit hook exited with code 127 (error)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I'm using `/bin/bash` I think `chaoscenter/web/.husky/pre-commit` needs bash shell support. Should I open issue regarding this?
> 
> Try running `yarn prepare` once and check if this fixes the issue. you don't have Husky installed for the web.

@hrishavjha  I have mentioned this issue with detail in the slack [here](https://kubernetes.slack.com/archives/CNXNB0ZTN/p1708497767008549).

As you said I ran `yarn prepare` and it gave me this issue
![image](https://github.com/litmuschaos/litmus/assets/92683836/3ae1aeb6-a50b-4e2f-bfd0-ed0816a8c3f7)

I think the issue lies in scripts and If you say so I can create and issue for it. Also I have researched about the issue so I can get started with it.

**Comment by aryan-bhokare** [comment]
> Try running `yarn prepare` once and check if this fixes the issue. you don't have Husky installed for the web.

![image](https://github.com/litmuschaos/litmus/assets/92683836/2ab89c9d-ed5a-4149-98be-158bdb609c0e)

it still persist. I have mentioned the issue in detail [here](https://kubernetes.slack.com/archives/CNXNB0ZTN/p1708497767008549).
