### ISSUE TITLE
In Project details 'Last modified' field showing incorrect date

### ISSUE THREAD

**Issue by Saranya-jena** [litmuschaos/litmus#4448]
**What happened**:
![image](https://github.com/litmuschaos/litmus/assets/28081206/bf006362-262e-420a-b59d-a35f849af58f)

**What you expected to happen**:

**Where can this issue be corrected? (optional)**

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by KrishAryan** [comment]
./assign

**Comment by milinddethe15** [comment]
Hi @KrishAryan, Are you working on this? or I would like to fix this.

**Comment by KrishAryan** [comment]
If you know the solution then please go ahead
