### ISSUE TITLE
Add loader in all the confirm buttons of Modals under User Management

### ISSUE THREAD

**Issue by Saranya-jena** [litmuschaos/litmus#4449]
**What happened**:

Currently upon selecting the confirm button, the API takes some time to get resolved however there is no loader for this state which makes it a bit confusing. 

**What you expected to happen**:

Add loader in all the confirm buttons of Modals under User Management

**Where can this issue be corrected? (optional)**

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by aryan-bhokare** [comment]
[Screencast from 19-02-24 04:20:11 PM IST.webm](https://github.com/litmuschaos/litmus/assets/92683836/bb2f2d74-8485-4cb5-8463-4639734735b6)

Hi @Saranya-jena  will this work.
I yes I can quicky make a pr for it.

**Comment by Saranya-jena** [comment]
@SahilKr24 @hrishavjha Can you confirm?

**Comment by SahilKr24** [comment]
> @SahilKr24 @hrishavjha Can you confirm?
Seems good to me, just a minor detail, we can also have the confirm button to be disabled when the modal opens i.e. the form is empty or not touched.

**Comment by aryan-bhokare** [comment]
> > @SahilKr24 @hrishavjha Can you confirm?
> 
> Seems good to me, just a minor detail, we can also have the confirm button to be disabled when the modal opens i.e. the form is empty or not touched.

@SahilKr24 ok sure let me take a look once.

**Comment by aryan-bhokare** [comment]
@SahilKr24 

![image](https://github.com/litmuschaos/litmus/assets/92683836/2a147f83-b6ee-45f8-80d6-d808bcd66bc9)

This is how it is handled if we click on `confirm` when fields are empty or in wrong format.

**Comment by SahilKr24** [comment]
> @SahilKr24
> 
> ![image](https://private-user-images.githubusercontent.com/92683836/305948068-2a147f83-b6ee-45f8-80d6-d808bcd66bc9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzNDYwMDksIm5iZiI6MTcwODM0NTcwOSwicGF0aCI6Ii85MjY4MzgzNi8zMDU5NDgwNjgtMmExNDdmODMtYjZlZS00NWY4LTgwZDYtZDgwOGJjZDY2YmM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDEyMjgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyZjk0YWIwNmI3YTM4YjBiOWRmMmUwOTQwYTc4OGNjOGRlN2M5NzljZDMxMzFmM2UxODcyMTdiNWU2ZDAxMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TKMJ9EjlPNMF2BHmU8knfxl1s2_XlObckJeVR2hvDxc)
> 
> This is how it is handled if we click on `confirm` when fields are empty or in wrong format.
> 
> So should I disable the button at the start? or we should keep it as it is?

This should also be fine 👍🏻
