### ISSUE TITLE
Improvements in `User Management` screen

### ISSUE THREAD

**Issue by hrishavjha** [litmuschaos/litmus#4450]
- The table has no pagination in the User Management screen. With more users coming in the screen will become weirdly scrollable.
`Suggested change: Provide pagination to the table to limit the number of users in each page. For reference look into ExperimentDashboardV2 files.`
- The `useUsersQuery` API which is used in the User Management screen doesn't support pagination as well as filters, due to which the search is in FE only. For a large number of users this will create performance issues in FE.
`Suggested change: Add pagination and filters in the BE and update the controller in AccountSettingsUserManagement.`

**Comment by kartikaysaxena** [comment]
Can I work on this?

**Comment by Saranya-jena** [comment]
Sure @kartikaysaxena

**Comment by aryan-bhokare** [comment]
;) I was also working on this one. Thought should take a proper look at it.
Will it be okay to open a pr for this?
