### ISSUE TITLE
`registerInfra` API allows registering Infra even with invalid `environmentID`

### ISSUE THREAD

**Issue by smitthakkar96** [litmuschaos/litmus#4463]
**What happened**:

A project was created without specifying an environment. Surprisingly, when invoking the registerInfra API with a non-existent environmentID, the call returned a success response. Moreover, execution plane components appear to operate normally despite the absence of an associated environment. Although the infrastructure is not listed on the environments page, it does show up in the list when constructing a chaos experiment.

**What you expected to happen**:

The anticipation was that the API would detect the invalid environmentID and return a validation error message, indicating that the provided environmentID does not correspond to a valid environment.

**Where can this issue be corrected? (optional)**

https://github.com/litmuschaos/litmus/blob/5df01f1c386ab142015c03d998f6c18587e01d20/chaoscenter/graphql/server/pkg/chaos_infrastructure/service.go#L74

**Comment by Dhanush0369** [comment]
Hi @smitthakkar96 , I can solve this issue if u are not working. Let me know.

**Comment by smitthakkar96** [comment]
Sure go ahead!

**Comment by Saranya-jena** [comment]
Assigned it to you @Dhanush0369

**Comment by kartikaysaxena** [comment]
Can I take this up? I think I. know how to fix this.

**Comment by Dhanush0369** [comment]
@kartikaysaxena I am working on this, I will make a pr by today.

**Comment by Dhanush0369** [comment]
@SarthakJain26 Made a pr is being reviewed.

**Comment by SarthakJain26** [comment]
Can you please link the PR to this issue
