### ISSUE TITLE
Need to formatting text in probe card

### ISSUE THREAD

**Issue by namkyu1999** [litmuschaos/litmus#4560]
**What happened**:

When we named probes long, ugly formatting happened in `chaoscenter`. String formatting is needed

![Screenshot 2024-03-31 at 3 19 41 PM](https://github.com/litmuschaos/litmus/assets/53862866/ac7e5a15-f930-4e48-bcd8-b72802178b03)

**Anything else we need to know?**:

Anyone who wants to contribute to this issue, Let me know :)
I think we need to edit this file

https://github.com/litmuschaos/litmus/blob/master/chaoscenter/web/src/views/ExperimentCreationFaultConfiguration/Tabs/Probes/Probes.tsx

**Comment by satya19977** [comment]
Hey @namkyu1999. Can i work on this ?

**Comment by namkyu1999** [comment]
sure, go ahead @satya19977 😄

**Comment by ChaitanyaD48** [comment]
Hey @satya19977 what's the status ? should I raise the PR as I have solved the issue!

**Comment by satya19977** [comment]
Hey@ChaitanyaD48 Please go ahead and raise the PR. I am just curious, what's the solution? Did you change the line clamp from 1 to 2?
