### ISSUE TITLE
Improvement to Documentation

### ISSUE THREAD

**Issue by alininja** [litmuschaos/litmus#4564]
Hi 👋 

I was using these docs to get Litmus working on an OpenShift cluster:
- https://litmuschaos.github.io/litmus/experiments/categories/pods/pod-memory-hog-exec/#experiment-tunables
- https://litmuschaos.github.io/litmus/experiments/categories/pods/pod-cpu-hog-exec/#experiment-tunables

In order for the kill command to work on my OpenShift cluster and pod, I had to update the suggested alternative kill commands to the following:
- for memory: `kill -9 $(ps afx | grep "[dd] if=/dev/zero" | awk '{print $1}' | tr '\n' ' ')`
- for cpu: `$(ps afx | grep "[md5sum] /dev/zero" | awk '{print $1}' | tr '\n' ' ') `

I am not familiar enough to know if the suggested alternative kill commands have a typo or is intended for Windows or is intended for other pod configurations or something else.
- suggested alternative kill command for memory: `kill -9 $(ps afx | grep \"[dd] if=/dev/zero\" | awk '{print $1}' | tr '\n' ' ')`
- suggested alternative kill command for cpu: `kill -9 \((ps afx | grep \"[md5sum] /dev/zero\" | awk '{print\)1}' | tr '\n' ' ')`

Hopefully, this can be helpful to someone else.

Thank you for making this project 🙏

**Comment by prithvi1307** [comment]
@Saranya-jena can you PTAL? @alininja would you like to raise a PR on this?

**Comment by alininja** [comment]
> @alininja would you like to raise a PR on this?

@prithvi1307 sure thing.  I was trying to find the source for the documentation, but could not find it.  Would you be able to link me to it?  Thanks 🙏

**Comment by Saranya-jena** [comment]
Hi @alininja you can raise a PR here: https://github.com/litmuschaos/litmus-docs

**Comment by alininja** [comment]
> Hi @alininja you can raise a PR here: https://github.com/litmuschaos/litmus-docs

Thank you @Saranya-jena for the link to the repo.  Sorry, but I am still unable to find the source file that corresponds to these pages:
- https://litmuschaos.github.io/litmus/experiments/categories/pods/pod-memory-hog-exec/#experiment-tunables
- https://litmuschaos.github.io/litmus/experiments/categories/pods/pod-cpu-hog-exec/#experiment-tunables
I tried searching the repository for the keywords from the pages, but am unable to find the source file.

Sorry for the newbie confusion.  :pray:

**Comment by Saranya-jena** [comment]
> > Hi @alininja you can raise a PR here: https://github.com/litmuschaos/litmus-docs
> 
> Thank you @Saranya-jena for the link to the repo. Sorry, but I am still unable to find the source file that corresponds to these pages:
> 
> * https://litmuschaos.github.io/litmus/experiments/categories/pods/pod-memory-hog-exec/#experiment-tunables
> * https://litmuschaos.github.io/litmus/experiments/categories/pods/pod-cpu-hog-exec/#experiment-tunables
>   I tried searching the repository for the keywords from the pages, but am unable to find the source file.
> 
> Sorry for the newbie confusion. 🙏

Hey @neelanjan00 Can you please help here?

**Comment by neelanjan00** [comment]
Hi @alininja, sorry I missed this! You can find the docs here: https://github.com/litmuschaos/litmus/blob/master/mkdocs/docs/experiments/categories/pods/pod-memory-hog-exec.md
https://github.com/litmuschaos/litmus/blob/master/mkdocs/docs/experiments/categories/pods/pod-cpu-hog-exec.md

Thanks for the contribution! 🙏🏽

**Comment by neelanjan00** [comment]
Hi @alininja, sorry I missed this! Here are the docs link:
https://github.com/litmuschaos/litmus/blob/master/mkdocs/docs/experiments/categories/pods/pod-cpu-hog-exec.md
https://github.com/litmuschaos/litmus/blob/master/mkdocs/docs/experiments/categories/pods/pod-memory-hog-exec.md

Thanks for the contribution! 🙏🏽

**Comment by alininja** [comment]
Thanks @neelanjan00 for the links.
I've created the PR here: https://github.com/litmuschaos/litmus/pull/4609

I hope that works.  It sounds like the original alternative kill command had typo's so I replaced it instead of adding an additional alternative kill command.

Thank you for making such a wonderful product 🙏

**Comment by alininja** [comment]
Marking this issue as closed since the branch has been merged.
