### ISSUE TITLE
Not able to connect infra with older version(3.1.0) with the newer version of Chaoscenter(3.5.0)

### ISSUE THREAD

**Issue by Saranya-jena** [litmuschaos/litmus#4584]
**What happened**:

Not able to connect infra with older version(3.1.0) with the newer version of Chaoscenter(3.5.0)
Getting the following error:
time="2024-04-15T06:37:38Z" level=error msg="Error response from the server : {\"payload\":{\"errors\":[{\"message\":\"ERROR: infra VERSION MISMATCH (need 3.5.0 got 3.1.0)\",\"path\":[\"infraConnect\"]}],\"data\":null},\"type\":\"data\"}\n"

**What you expected to happen**:

**Where can this issue be corrected? (optional)**

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by Baalekshan** [comment]
@Saranya-jena I like to work on this.

**Comment by Saranya-jena** [comment]
@Baalekshan are you still willing to work on this?

**Comment by Baalekshan** [comment]
Yeah @Saranya-jena
