### ISSUE TITLE
Incorrect Syntax in GitHub Actions Workflow File (e2e.yml)

### ISSUE THREAD

**Issue by andoriyaprashant** [litmuschaos/litmus#4695]
**What happened**:

The e2e.yml workflow file contains incorrect syntax in the GitHub Actions configuration, resulting in errors during workflow execution. Specifically, the syntax used for fetching PR commits is invalid. The correct format should be employed to avoid these errors and ensure smooth workflow functioning.

- Unexpected value 'branches'
- Invalid action input 'repo' and 'pull_number'

**What you expected to happen**:

The e2e.yml workflow file should have accurate syntax in the GitHub Actions configuration, ensuring smooth workflow execution without encountering errors.

**Where can this issue be corrected? (optional)**
.github\workflows\e2e.yml

**How to reproduce it (as minimally and precisely as possible)**:

- Open .github\workflows\e2e.yml

**Comment by ayushrakesh** [comment]
Hey @andoriyaprashant I am interested to work on this issue. Please assign this to me.
