### ISSUE TITLE
Not getting experiment logs in the UI during experiment execution

### ISSUE THREAD

**Issue by Saranya-jena** [litmuschaos/litmus#4723]
**What happened**:
During experiment execution only helper pod logs are available in the UI and not the experiment pod logs. And logs are not formatted properly.
![image (15)](https://github.com/litmuschaos/litmus/assets/28081206/719618e3-9fea-4f15-9589-40220b1dbd3f)

**What you expected to happen**:
Both the experiment and helper pod logs should be available in the UI with proper formatting so that it is easy to read.

**Where can this issue be corrected? (optional)**

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by Baalekshan** [comment]
@Saranya-jena Can you tell how the formatting should be ?
