### ISSUE TITLE
how to develop chaoscenter/web

### ISSUE THREAD

**Issue by kwx4957** [litmuschaos/litmus#4793]
## Question
I am developing chaoscenter/web in a local environment. While following this ChaosCenter [Development Guide](https://github.com/litmuschaos/litmus/wiki/ChaosCenter-Development-Guide), I encountered an issue.

After installing [litmusctl](https://github.com/litmuschaos/litmusctl/blob/master/Usage_0.23.0.md), when I run `litmusctl config set-account`, I need to input the host endpoint. If I enter localhost, I receive the error `x509 certificate signed by unknown authority` because it is a self-signed certificate. How can I resolve this issue or is there another way to develop chaoscenter/web locally?

**Comment by Saranya-jena** [comment]
cc: @SarthakJain26 @Nageshbansal

**Comment by namkyu1999** [comment]
He raised a PR about this issue. PTAL @Saranya-jena ^^

https://github.com/litmuschaos/litmus-docs/pull/282
