### ISSUE TITLE
Can create project with litmusctl even without resetting password

### ISSUE THREAD

**Issue by Calvinaud** [litmuschaos/litmus#4904]
**What happened**:
When trying to create a project with litmusctl without resetting the password you will receive the following error message: 
```
❌ Error creating project: Unmatched status code:{"error":"default password not updated","errorDescription":"Please update your default password"}{"data":{"updatedAt":1727248855440,"createdAt":1727248855440,"createdBy":{"userID":"xxx","username":"admin","email":""},"updatedBy":{"userID":"xxxx","username":"admin","email":""},"isRemoved":false,"projectID":"xxxx","name":"random","members":[{"userID":"xxx","username":"","email":"","name":"","role":"Owner","invitation":"Accepted","joinedAt":1727248855440}],"state":"active","tags":null,"description":null}}
```
It's this error message it say that there was an error created the project because the password was not rotate but still the project is created.

**What you expected to happen**:
The project is not created because there is an error message.

**How to reproduce it (as minimally and precisely as possible)**:
- Deploy a new ChaosCenter
- Configure litmusctl to connect to the ChaosCenter with `litmusctl config set-account`
- Try to create a project  with `litmusctl create project --name test`

**Anything else we need to know?**:
Litmusctl version used: 1.10.0
LitmusChaos version used: 3.11.0

**Comment by kwx4957** [comment]
can i take issue?
