### ISSUE TITLE
Reduce the turn-around time for testing apps with production like data. 

### ISSUE THREAD

**Issue by kmova** [litmuschaos/litmus#51]
Here is my usecase:

Felix is a DevOps admin who is responsible for maintaining Staging Databases for a large enterprise corporation with 400+ developers working on 200+ applications. The Staging database contains a pruned (for user information) and is constantly updated with production data. When developers make some data schema changes, they would like to test them out on the Staging setup with real data before pushing the changes for Review.
- The staging database PV, PVC and the associated application are created in a separate namespace called “staging”. Only Felix has access to this namespace. He creates snapshots of the production database volume. Along with creating the snapshots, he appends some information into the snapshots that will be helpful for developers like the: like the version of the applications that are running in the staging database when this snapshot was taken. 
- Each developer has their own namespace. For example Simon, runs his development application in “dev-simon-app” namespace. 
- The cluster admin authorize Simon to access (read/get) the snapshots from the staging setup. 
- Simon gets the list of snapshots that are available. Picks up the snapshot or snapshots that are best suited for testing his application. 
- Simon creates a PVC / PV with the select snapshot and launches his applications with modified changes on it.
- Simon then runs the integration tests on his application which is now accessing production like data - which helps him to identify issues with different types of data and running at scale. 
- After completing the tests, Simon deletes the application and the associated cloned volumes.

**Comment by ksatchit** [comment]
Moving this issue to the OpenEBS e2e-tests repository: https://github.com/openebs/e2e-tests/issues/660
