### ISSUE TITLE
Make it easy to debug the build (CI) failures with stateful apps 

### ISSUE THREAD

**Issue by kmova** [litmuschaos/litmus#52]
Here is my usecase:

Tim is a DevOps engineer at a large Retail store who is responsible for running a complex build pipeline that involves several mico-services. The microservices that implement a order and supply management functionalities - store the states in a set of common datastores. The Jenkins CI pipeline simulates real world interactions with the system that begin with simulating customers placing the orders to the backend systems optimizing the supply and delivery of these orders to the customers.  Time has setup the Job execution pipeline in such a way that, if there are failures, the developers can back trace the state of the database and the logs associated with each stage.
- The build (or job) logs are saved onto OpenEBS PV, say Logs PV 
- The datastores are created on OpenEBS Volumes, say Datastore PVs. 
- At the end of each job, either on success of failure, snapshots are taken of the Logs PV and the Datastore PVs. 
- When there is a build failure, the volume snapshot information is sent to all the developers whose service were running when the job was getting executed. 
- Each developer can bring up their own debug session in their namespace by creating a environment with cloned volumes. Either they re-run the tests manually by going back to the previous state with higher debug level or analyze the data currently available that is causing the issue.

**Comment by ksatchit** [comment]
The OpenEBS specific functional litmusbooks will be developed and maintained at: https://github.com/mayadata-io/litmus
