### ISSUE TITLE
Pass volume capacity as env in elasticsearch deployment litmusbook.

### ISSUE THREAD

**Issue by gprasath** [litmuschaos/litmus#555]
Currently, litmusbook deploys elasticsearch statefulset with 20GB volumes. This needs to be obtained from user and execute the same.

Procedure:
- Keep a placeholder for capacity in elasticsearch deployment manifest file.
- Obtain the capacity from user as env.
- Replace the placeholder before applying it.

**Comment by ksatchit** [comment]
The app deployment litmusbooks will be developed and maintained at https://github.com/mayadata-io/litmus
