### ISSUE TITLE
Create litmus chaoslib utils for ElasticSearch

### ISSUE THREAD

**Issue by ksatchit** [litmuschaos/litmus#587]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 Choose one: BUG REPORT or FEATURE REQUEST

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by boddumanohar** [comment]
I would like to work on this task. Can you please give more details about this? 

Thanks,
Manohar.

**Comment by dbgoytia** [comment]
Hi @ksatchit, is this issue still relevant? If so I'd like to give it a go!

**Comment by ksatchit** [comment]
Limtus has enhanced its fault suite along with supported probe types, which allows users to test any application workload app-native constraints/health-validations, thereby removing the need for separate workload-specific experiments to a large extent.
