### ISSUE TITLE
Need analytics of chaos-experiments

### ISSUE THREAD

**Issue by umamukkara** [litmuschaos/litmus#695]
## Is this a BUG REPORT or FEATURE REQUEST?
 
FEATURE REQUEST

- Just like docker pulls, it would be good to have a badge on both litmuschaos/litmus repo as well as litmuschaos.io website that representing the number of experiments executing. Each time the ansible-runner container runs an experiment, this analytic counter should be incremented. We can have this metadata through Google Analytics

- We can capture, type of experiment, success/failure/k8s version/region etc

**Comment by ksatchit** [comment]
This is now available on the charthub as metrics against each experiment/chart category. The charthub also features a footer with information on installation counts.
