### ISSUE TITLE
openebs deployment refactoring

### ISSUE THREAD

**Issue by somesh2905** [litmuschaos/litmus#699]
**Description**
Perform modification in the source code for openebs deployers.
(For openebs deployment there are two directories under litmus repository. One is litmusbook and other one is ansible -- litmusbook contains two runner for ansible plays and there are various plays under ansible directory for openebs setup and cleanup.)  
The runner for openebs setup and cleanup has to be merged into single runnner & plays of setup and cleanup has to be merged into single play.

**Comment by ksatchit** [comment]
The OpenEBS deployment books will be maintained at https://github.com/mayadata-io/litmus
