### ISSUE TITLE
Create a contributing.md

### ISSUE THREAD

**Issue by rahulchheda** [litmuschaos/litmus#710]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 Choose one: BUG REPORT or FEATURE REQUEST
FEATURE REQUEST

**What happened**:

**What you expected to happen**:
This doc should have all the necessary information needed to any developer who wants to contribute to the code.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by ksatchit** [comment]
There is one available [here](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md). Needs to be refactored for litmus specifics and removal of references to OpenEBS
