### ISSUE TITLE
To iterate the until condition for different items in ansible

### ISSUE THREAD

**Issue by uditgaurav** [litmuschaos/litmus#734]
The playbook code is :
```
  k8s_facts:
    kind: Pod
    namespace: "{{ app_ns }}"
    label_selectors:
      - "{{app_lkey}}={{app_lvalue}}"
  register: containerStatus
  until: "{{ item.status.phase }}" == 'Running'
  delay: 2
  retries: 150
  with_items: "{{containerStatus.resources}}"

```

EXPECTED OUTPUT:

The ` until ` condition should check for 'n' numbers of Pod in `containerStatus` that it is in `Running` state or not with the given delay and retries. So i was expecting a loop on the until  for different pods status checking. Let suppose we have 3 pods in output so It may looks like:
For first iteration -
until: containerStatus.resources.0.status.phase == 'Running'
For second iteration -
until: containerStatus.resources.1.status.phase == 'Running'
For third iteration -
until: containerStatus.resources.2.status.phase == 'Running' 

ACTUAL OUTPUT/ERROR:

```
[WARNING]: when statements should not include jinja2 templating delimiters
such as {{ }} or {% %}. Found: {{ containerStatus.resources.item.status.phase
}} == 'Running'
fatal: [127.0.0.1]: FAILED! => {"msg": "The conditional check '{{ containerStatus.resources.item.status.phase }} == 'Running'' failed. The error was: error while evaluating conditional ({{ containerStatus.resources.item.status.phase }} == 'Running'): 'list object' has no attribute 'item'"}

```
WHAT'S NEEDED:

 Is there any way of doing that , can we iterate on the until conditions for different outputs as we can't use `stdout`  , `stderr` or `stdout_lines` in k8s module for directly getting output. we can only filter the JSON to get the required output.

**Comment by satyajittarai** [comment]
Please provide the code path to change

**Comment by ksatchit** [comment]
Will be moved to the knowledgebase repo with follow up discussions, as it is more specific to ansible than litmus itself!
