### ISSUE TITLE
(refactor): Refactor the Reconcile function

### ISSUE THREAD

**Issue by Sanjay1611** [litmuschaos/litmus#750]
## REFACTOR

**What happened**:

- Some pods and services are being built and created in the reconcile function. There's a check for the resources to be already present before being created.

**What you expected to happen**:

- All the pods and services should be created only after it is verified that they are not present.

**Anything else we need to know**:

- ChaosEngine is a controller and built on top of operator-sdk framework. As all the operator-sdk controllers, it has a reconcile function. Reconcile function runs in a recursive manner checking all the resources needed to be up. If any of the resource is not available it again calls itself.
- Issue related to Repository: https://github.com/litmuschaos/chaos-operator

**Comment by ksatchit** [comment]
This has been fixed as part of the overall chaosengine controller refactor in 1.0 release. Further refactor items are being tracked as part of https://github.com/litmuschaos/chaos-operator/pull/176

**Comment by rahulchheda** [comment]
With the github issue corresponding to this: https://github.com/litmuschaos/chaos-operator/issues/175
