### ISSUE TITLE
Refactoring of Docs Page: https://docs.litmuschaos.io/docs/next/co-chaosengine.html

### ISSUE THREAD

**Issue by rahulchheda** [litmuschaos/litmus#758]
After understanding the ChaosEngine, please update the docs.

**Comment by cTxplorer** [comment]
@rahulchheda Can I take up this issue?

**Comment by cTxplorer** [comment]
Also, can me point to the doc (co-chaosengine.md) which I am supposed to refractor and update.

Steps taken:
* I searched in this repo (litmuschaos/litmus) but could not find anything.
* Moreover, on clicking edit button at https://docs.litmuschaos.io/docs/next/co-chaosengine.html, take me to 404 Github page.

**Comment by ksatchit** [comment]
cc: @ksatchit

**Comment by ksatchit** [comment]
The refactored litmus-docs doesn't contain this page.
