### ISSUE TITLE
(chaos-operator): Add unit test cases for function engineRunnerPod()

### ISSUE THREAD

**Issue by chandankumar4** [litmuschaos/litmus#767]
## UNIT TEST
 
**What happened**:

- Write the unit-test

**What you expected to happen**:

- The test case should be written for function **engineRunnerPod()** of file https://github.com/litmuschaos/chaos-operator/blob/master/pkg/controller/chaosengine/chaosengine_controller.go

**Anything else we need to know?**:
- Issue related to Repository: https://github.com/litmuschaos/chaos-operator
- Reference:- https://github.com/litmuschaos/chaos-operator/blob/master/pkg/controller/chaosengine/chaosengine_controller_test.go

**Comment by ksatchit** [comment]
The chaosengine controller code has undergone significant refactor as part of effort to be compliant with the betterCodeHub coding standards. 

A similar/corresponding unit test is available here: https://github.com/litmuschaos/chaos-operator/blob/master/pkg/controller/chaosengine/chaosengine_controller_test.go#L32
