### ISSUE TITLE
(chaos-operator): Add unit test cases for function getChaosRunnerENV() and getChaosExporterENV()

### ISSUE THREAD

**Issue by chandankumar4** [litmuschaos/litmus#769]
## UNIT TEST
 
**What happened**:

- Write the unit-test

**What you expected to happen**:

- The test case should be written for function **getChaosRunnerENV()** and **getChaosExporterENV()** of file https://github.com/litmuschaos/chaos-operator/blob/master/pkg/controller/chaosengine/chaosengine_controller.go

**Anything else we need to know?**:
- Issue related to Repository: https://github.com/litmuschaos/chaos-operator
- Reference:- https://github.com/litmuschaos/chaos-operator/blob/master/pkg/controller/chaosengine/chaosengine_controller_test.go

**Comment by sureshpathipati** [comment]
@chandankumar4 
I have worked on this.
PR raised.
Plz have a look

https://github.com/litmuschaos/chaos-operator/pull/79
