### ISSUE TITLE
(chaos-operator): Add unit test cases for function Reconcile() 

### ISSUE THREAD

**Issue by chandankumar4** [litmuschaos/litmus#770]
## UNIT TEST
 
**What happened**:

- Write the unit-test

**What you expected to happen**:

- The test case should be written for function **Reconcile()**  of file https://github.com/litmuschaos/chaos-operator/blob/master/pkg/controller/chaosengine/chaosengine_controller.go

**Anything else we need to know?**:
- Issue related to Repository: https://github.com/litmuschaos/chaos-operator
- Reference:- https://github.com/litmuschaos/chaos-operator/blob/master/pkg/controller/chaosengine/chaosengine_controller_test.go

**Comment by ksatchit** [comment]
Most of the unit tests for reconcile have been covered across 1.5 & 1.6 releases
