### ISSUE TITLE
(chaos-operator):Add unit test cases for file cmd/manager/main.go

### ISSUE THREAD

**Issue by chandankumar4** [litmuschaos/litmus#774]
## UNIT TEST
 
**What happened**:

- Write the unit-test

**What you expected to happen**:

- The test case should be written for file https://github.com/litmuschaos/chaos-operator/blob/master/cmd/manager/main.go

**Anything else we need to know?**:
- Issue related to Repository: https://github.com/litmuschaos/chaos-operator
- Reference:- https://github.com/litmuschaos/chaos-operator/blob/master/pkg/controller/chaosengine/chaosengine_controller_test.go

**Comment by Athulpai12** [comment]
I would like to work on this issue

**Comment by Athulpai12** [comment]
Raised a PR for this issue:
https://github.com/litmuschaos/chaos-operator/pull/78

**Comment by uzaxirr** [comment]
Hey @chandankumar4 
Is that file still un-tested? I'm not able to find the file `cmd/manager/main.go` in the `chaos-operator` repo. It is moved to a new destination?

**Comment by ispeakc0de** [comment]
It is no longer exists after operator-sdk upgrade
