### ISSUE TITLE
(refactor): Refactor the reconcile function according to the BCH(Better Code Hub) rule

### ISSUE THREAD

**Issue by chandankumar4** [litmuschaos/litmus#775]
## Refactoring
 
**What happened**:

- Refactor the **reconcile()** function according to the Better Code Hub rule

**What you expected to happen**:

- This refactoring will remove all the issue related to reconcile function from Better Code Hub

**Anything else we need to know?**:
- Issue related to Repository: https://github.com/litmuschaos/chaos-operator

Getting started:
- Fork the Repo https://github.com/litmuschaos/chaos-operator
- Refactor the reconcile function and push the changes to `master` branch
- Configure the Better Code Hub to analyze the forked repository

**Comment by aswathkk** [comment]
Hi @chandankumar4,
I would like to take up this issue.

**Comment by chandankumar4** [comment]
Sure @aswathkk

**Comment by mathagician** [comment]
@chandankumar4  I am working on the issue

**Comment by aswathkk** [comment]
@chandankumar4 I'm not working on this one. Let @mathagician work on this.
