### ISSUE TITLE
(chaos-operator) (refactor): Refactor the pkg/controller/chaosengine/chaosengine_controller.go

### ISSUE THREAD

**Issue by chandankumar4** [litmuschaos/litmus#776]
## Refactoring
 
**What happened**:

- Refactor the **pkg/controller/chaosengine/chaosengine_controller.go** file leaving **Reconcile()** function according to the Better Code Hub rule

**What you expected to happen**:

- This refactoring will remove all the issue related to file **pkg/controller/chaosengine/chaosengine_controller.go** from Better Code Hub

**Anything else we need to know?**:
- Issue related to Repository: https://github.com/litmuschaos/chaos-operator

Getting started:
- Fork the Repo https://github.com/litmuschaos/chaos-operator
- Refactor the reconcile function and push the changes to `master` branch
- Configure the Better Code Hub to analyze the forked repository

**Comment by bh6erk** [comment]
Hi @chandankumar4 !

I would like to try and solve this issue. If I got it right, the only task is to refactor the code so Better Code Hub shows 10/10 for the analyzation of the forked repository?

**Comment by chandankumar4** [comment]
Yes!! @bh6erk, The BCH will not show any error related to chaosengine_controller.go

**Comment by ksatchit** [comment]
The BCH score is now 10/10!! Thanks for your efforts @chandankumar4.
