### ISSUE TITLE
(chaos-exporter): Add Unit Test Cases for function contains()

### ISSUE THREAD

**Issue by Sanjay1611** [litmuschaos/litmus#778]
## UNIT TEST
 
**What happened**:

- Write the unit-test

**What you expected to happen**:

- The test case should be written for function **contains()** - https://github.com/litmuschaos/chaos-exporter/blob/master/cmd/exporter/main.go

**Anything else we need to know?**:
- Issue related to Repository: https://github.com/litmuschaos/chaos-exporter
- Reference:- https://github.com/litmuschaos/chaos-operator/blob/master/pkg/controller/chaosengine/chaosengine_controller_test.go

**Comment by sebast26** [comment]
Hi, if this issue is not taken I would like to start working on that :-)

**Comment by rahulchheda** [comment]
Sure, go ahead! Don't forget to list this issue number in your PR, and please provide a link to PR here aswell.

**Comment by 3sky** [comment]
@sebast26 Do you still working on this? If it's free I can take it.
