### ISSUE TITLE
(chaos-exporter): Add Unit Test Cases for function getNamespaceEnv() 

### ISSUE THREAD

**Issue by Sanjay1611** [litmuschaos/litmus#779]
## UNIT TEST
 
**What happened**:

- Write the unit-test

**What you expected to happen**:

- The test case should be written for function **getNamespaceEnv()** - https://github.com/litmuschaos/chaos-exporter/blob/master/cmd/exporter/main.go

**Anything else we need to know?**:
- Issue related to Repository: https://github.com/litmuschaos/chaos-exporter
- Reference:- https://github.com/litmuschaos/chaos-operator/blob/master/pkg/controller/chaosengine/chaosengine_controller_test.go

**Comment by dravog7** [comment]
@Sanjay1611  @chandankumar4 May I take up this issue?
