### ISSUE TITLE
(chaos-exporter): Add Unit Test Cases for function getOpenebsEnv()

### ISSUE THREAD

**Issue by Sanjay1611** [litmuschaos/litmus#780]
## UNIT TEST
 
**What happened**:

- Write the unit-test

**What you expected to happen**:

- The test case should be written for function **getOpenebsEnv()** - https://github.com/litmuschaos/chaos-exporter/blob/master/cmd/exporter/main.go

**Anything else we need to know?**:
- Issue related to Repository: https://github.com/litmuschaos/chaos-exporter
- Reference:- https://github.com/litmuschaos/chaos-operator/blob/master/pkg/controller/chaosengine/chaosengine_controller_test.go

**Comment by sureshpathipati** [comment]
@chandankumar4 
I have worked on this.
Plz have a look on this 
https://github.com/litmuschaos/chaos-exporter/pull/26

**Comment by sureshpathipati** [comment]
@chandankumar4 
We can close this issue. PR got merged.
Kindly update
