### ISSUE TITLE
(chaos-exporter): Add Unit Test Cases for file chaos-exporter

### ISSUE THREAD

**Issue by Sanjay1611** [litmuschaos/litmus#781]
## UNIT TEST
 
**What happened**:

- Write the unit-test

**What you expected to happen**:

- Write the unit test cases for the chaos-exporter repo

**Anything else we need to know?**:
- Issue related to Repository: https://github.com/litmuschaos/chaos-exporter
- Reference:- https://github.com/litmuschaos/chaos-operator/blob/master/pkg/controller/chaosengine/chaosengine_controller_test.go

**Comment by dedifferentiator** [comment]
Does this file exist? I don't see it in [chaos-exporter/pkg](https://github.com/litmuschaos/chaos-exporter/tree/master/pkg)

**Comment by chandankumar4** [comment]
@debojitkakoti It's moved to **controller/scrape.go**

**Comment by HokhyTann** [comment]
Can I take on this one?

**Comment by jignyasamishra** [comment]
> ## UNIT TEST
> **What happened**:
> 
> * Write the unit-test
> 
> **What you expected to happen**:
> 
> * Write the unit test cases for the chaos-exporter repo
> 
> **Anything else we need to know?**:
> 
> * Issue related to Repository: https://github.com/litmuschaos/chaos-exporter
> * Reference:- https://github.com/litmuschaos/chaos-operator/blob/master/pkg/controller/chaosengine/chaosengine_controller_test.go

Hello @Sanjay1611 I was going through this issue can you tell me which packages need unit test coverage here or do I need to add unit tests in all packages that have no unit tests present in -[https://github.com/litmuschaos/chaos-exporter](https://github.com/litmuschaos/chaos-exporterl)

**Comment by prithvi1307** [comment]
@ispeakc0de have we resolved this issue?
