### ISSUE TITLE
(chaos-exporter): Add Unit Test Cases for file pkg/version/kubernetesVersion.go

### ISSUE THREAD

**Issue by Sanjay1611** [litmuschaos/litmus#782]
## UNIT TEST
 
**What happened**:

- Write the unit-test

**What you expected to happen**:

- The test case should be written for file **pkg/version/kubernetesVersion.go**

**Anything else we need to know?**:
- Issue related to Repository: https://github.com/litmuschaos/chaos-exporter
- Reference:- https://github.com/litmuschaos/chaos-operator/blob/master/pkg/controller/chaosengine/chaosengine_controller_test.go

**Comment by imazik** [comment]
Hi @chandankumar4  I would like to work on it.

**Comment by chandankumar4** [comment]
Thanks @imazik for taking up this issue

**Comment by ksatchit** [comment]
This test is now available: https://github.com/litmuschaos/chaos-exporter/blob/master/pkg/version/kubernetesVersion_test.go! Thank you @shovanmaity !
