### ISSUE TITLE
(chaos-exporter): Add Unit Test Cases for file pkg/version/openebsVersion.go

### ISSUE THREAD

**Issue by Sanjay1611** [litmuschaos/litmus#783]
## UNIT TEST
 
**What happened**:

- Write the unit-test

**What you expected to happen**:

- The test case should be written for file **pkg/version/openebsVersion.go**

**Anything else we need to know?**:
- Issue related to Repository: https://github.com/litmuschaos/chaos-exporter
- Reference:- https://github.com/litmuschaos/chaos-operator/blob/master/pkg/controller/chaosengine/chaosengine_controller_test.go

**Comment by princerachit** [comment]
I am working on this issue.

**Comment by harshvkarn** [comment]
Sure @princerachit go ahead!
