### ISSUE TITLE
(chaos-operator) (refactor): Refactor the clientset code used in pkg/clientset/v1alpha1

### ISSUE THREAD

**Issue by Sanjay1611** [litmuschaos/litmus#784]
## Refactoring
 
**What happened**:

- Refactor the **chaos-exporter** repo importing the clienset code, used in the repo, from the clienset generated in **chaos-operator** repo

**What you expected to happen**:

- This refactoring will leave the repo using the clienset code generated in **chaos-operator** repo 

**Anything else we need to know?**:
- Issue related to Repository: https://github.com/litmuschaos/chaos-operator

**Comment by jainsaarthak** [comment]
Unable to find file `clientset` in `pkg/clientset/v1alpha1`

**Comment by mathagician** [comment]
The path no longer exists. Please close this issue.

**Comment by rahulchheda** [comment]
@jainsaarthak, try to find this in this repo: github.com/litmuschaos/chaos-operator
https://github.com/litmuschaos/chaos-operator/tree/master/pkg/client/listers/litmuschaos/v1alpha1

**Comment by chandankumar4** [comment]
This issue is no longer valid, Closing this issue
