### ISSUE TITLE
(chaos-exporter) (refactor): Refactor the file pkg/version/openebsVersion.go

### ISSUE THREAD

**Issue by Sanjay1611** [litmuschaos/litmus#786]
## Refactoring
 
**What happened**:

- Refactor the file **pkg/version/openebsVersion.go**

**What you expected to happen**:

- Refactor the function [**GetOpenebsVersion(cfg *rest.Config, namespace string)**](https://github.com/litmuschaos/chaos-exporter/blob/7c332d75ead1cbaa94ac7200d6fabc5d48f0a48f/pkg/version/openebsVersion.go#L13-L37) for refactoring, which is a unit of **23** lines of code.

Here's the gist of this guideline:
- **Definition** 📖 
Limit the length of code units to 15 lines of code.
- **Why**❓ 
Small units are easier to analyse, test and reuse.
- **How** 🔧 
When writing new units, don't let them grow above 15 lines of code. When a unit grows beyond this, split it in smaller units of no longer than 15 lines.

**Anything else we need to know?**:
- Issue related to Repository: https://github.com/litmuschaos/chaos-exporter

**Getting started**
- Fork the Repo https://github.com/litmuschaos/chaos-exporter
- Refactor the reconcile function and push the changes to master branch
- Configure the Better Code Hub to analyze the forked repository

**Comment by rampreeth** [comment]
Hey, the only BCH rule that pkg/version/openebsVersion.go is not complying to writing shorter units of code.

**Comment by rahulchheda** [comment]
Yes, so try to shorten the code length by calling multiple functions or use interfaces to lessen the length.

**Comment by rampreeth** [comment]
Okay, I will pick this up.

**Comment by rahulchheda** [comment]
Sure @rampreeth. Go ahead. Don't forget to put the link of your PR, in this issue.

**Comment by rampreeth** [comment]
Sure 👍

**Comment by rampreeth** [comment]
https://github.com/litmuschaos/chaos-exporter/pull/25
