### ISSUE TITLE
(ui-frontend-implementation): Changing breadcrumbs on charts and experiments

### ISSUE THREAD

**Issue by aditya109** [litmuschaos/litmus#787]
## UI-FRONTEND-IMPLEMENTATION
 
 **What happens**:

- Changing the look of breadcrumbs to charts and experiments

**What you expected to happen**:

- The breadcrumbs will look like something like this :-
![Screenshot from 2019-10-05 15-17-37](https://user-images.githubusercontent.com/22005947/66253293-7ae3eb00-e783-11e9-8f1e-37e173b54e37.png)

**Anything else we need to know?**:

- Issue related to Repository : https://github.com/litmuschaos/charthub.litmuschaos.io

**Comment by cTxplorer** [comment]
@aditya109 The breadcrumb image seems to be of version number.. You might want to update that :)

**Comment by mohatagarvit** [comment]
I would like to take up this issue.

**Comment by aditya109** [comment]
> @aditya109 The breadcrumb image seems to be of version number.. You might want to update that :)

Hi @cTxplorer, you are correct about the description. I have changed the image as you pointed out.

**Comment by aditya109** [comment]
> I would like to take up this issue.

Sure @mohatagarvit you can take this issue up.

**Comment by mohatagarvit** [comment]
![Litmus1](https://user-images.githubusercontent.com/16732393/66397749-15e5fa80-e9fa-11e9-819d-f3438ace96b3.PNG)
Is this the desired view?

**Comment by mohatagarvit** [comment]
I also tried a couple of other edits but I don't think they look that good.
![Litmus2](https://user-images.githubusercontent.com/16732393/66398063-bb996980-e9fa-11e9-9b60-05f1a35e3062.PNG)

![Litmus3](https://user-images.githubusercontent.com/16732393/66398076-c2c07780-e9fa-11e9-8564-344a7d91c359.PNG)

**Comment by mohatagarvit** [comment]
Currently, I am giving spaces by creating a new class and adding padding around '>'. Should I instead go for &nbsp; or &ensp;?

**Comment by aditya109** [comment]
No @mohatagarvit this is good enough. Please raise a PR so that I can review your code and don't forget star the **litmus repo** [https://github.com/litmuschaos/litmus]().

**Comment by mohatagarvit** [comment]
Made a [PR](https://github.com/litmuschaos/charthub.litmuschaos.io/pull/43) for the agreed upon changes.
