### ISSUE TITLE
(ui-frontend-implementation): Adding version label to the side-panel

### ISSUE THREAD

**Issue by aditya109** [litmuschaos/litmus#788]
## UI-FRONTEND-IMPLEMENTATION
 
**What happens**:

- Adding a **Version Label** to sidepanel of each chart/subchart

**What you expected to happen**:

- The version label  will look like some thing like this :-
https://lh5.googleusercontent.com/yWVCEXflkDLpGqeqmkdXpK0Nssii_uvpAsvH0s3GQgSkKWgBlyI1VJ7qCEnDoNHXTAAcrTls--TQF85t38_koww8qRQsPI-dw_doTotQElp8WxNjTgrT3eJHmC8M7qxfWu49ow45gw

**Anything else we need to know?**:

- Issue related to Repository : https://github.com/litmuschaos/charthub.litmuschaos.io

**Comment by mkkhedawat** [comment]
From where are you planning to read the version? Package.json?

**Comment by aditya109** [comment]
@mkkhedawat we have to pick the version from the charts directory, parsing the yaml of the charts. The maintainer label has been implemented in a similar fashion.

**Comment by aditya109** [comment]
Also @mkkhedawat don't forget to add this issue number in your PR, and add a link to your PR here as well.

**Comment by kmjayadeep** [comment]
@mkkhedawat are you working on this? Or can i take it up?

**Comment by kmjayadeep** [comment]
It seems that the Server API already have the version parameter. It's just the matter of modifying the component to show it up on UI

**Comment by aditya109** [comment]
Hi @kmjayadeep, I will assign this task to you.
