### ISSUE TITLE
(ui-frontend-implementation): Adding a "JOIN US ON SLACK" button

### ISSUE THREAD

**Issue by aditya109** [litmuschaos/litmus#789]
## UI-FRONTEND-IMPLEMENTATION
 
 **What happens**:

- Adding a "JOIN US ON SLACK" which directs us to slack channel

**What you expected to happen**:

- The button goes in bottom-right corner when we open any window and should redirect to [https://app.slack.com/client/T09NY5SBT/CNXNB0ZTN](url). 
The button will look like something like this :-
https://www.stickpng.com/img/icons-logos-emojis/tech-companies/slack-new-logo-icon
**Anything else we need to know?**:

- Issue related to Repository : https://github.com/litmuschaos/charthub.litmuschaos.io

**Comment by Sweta271097** [comment]
@aditya109 Can I take up this issue?

**Comment by chandankumar4** [comment]
sure!! @Sweta271097 You can take up this issue

**Comment by sakkshm** [comment]
how can I create a pull request on this issue?
should I create the pull request on https://github.com/litmuschaos/charthub.litmuschaos.io repo?

**Comment by aditya109** [comment]
@Sweta271097 for sure.. Comment out whatever help you need.

**Comment by aditya109** [comment]
Also @Sweta271097 don't forget to add this issue number in your PR, and add a link to your PR here as well.

**Comment by sakkshm** [comment]
Can I get a chance on this one?

**Comment by mohatagarvit** [comment]
Hi, are we looking to add this on [homepage](https://litmuschaos.io/) or on the localhost or a different site since the community link on the homepage already has it? Also, is there any specific location that we want this to appear on the site?

**Comment by aditya109** [comment]
> Can I get a chance on this one?

@sakkshm As an open source culture, its first-come-first-serve for the open issue. If you still want to this task, you have to wait for a week, and if there is no PR raised, the current assignee would be relieved, and if you are still up for this task, I would gladly assign it to you. For the time being I would suggest you to take up other open issues, it'd be great.

**Comment by aditya109** [comment]
> Hi, are we looking to add this on [homepage](https://litmuschaos.io/) or on the localhost or a different site since the community link on the homepage already has it? Also, is there any specific location that we want this to appear on the site?

Hi @mohatagarvit, we want it on this button to appear on the [homepage](https://hub.litmuschaos.io)

**Comment by ambaresthete** [comment]
Can I work on this? is it Done?

**Comment by aditya109** [comment]
Hi @ambaresthete, actually as per open source culture it is FCFS for taking issues. So I will have to assign this @sakkshm. If he does not reply for next 2-3 hours, on his interest, I will assign this issue to you.

**Comment by sakkshm** [comment]
@aditya109 I'll do it!

**Comment by ambaresthete** [comment]
Okay, @aditya109. I have my PR ready. Let me know if there's no response.

**Comment by sakkshm** [comment]
@aditya109 I will not be able to do it. Kindly assign it to someone else.

**Comment by aditya109** [comment]
> @aditya109 I will not be able to do it. Kindly assign it to someone else.

Its okay @sakkshm, take a look at other issues and give them a try.

**Comment by mspyder** [comment]
hi @aditya109  can you put more description about the issue,
like where the button goes in UI, what is slack URL?

**Comment by inyee786** [comment]
Hi @aditya109, can you put more description of the issue,
like where the button goes in UI, what is slack URL?

**Comment by aditya109** [comment]
> Hi @aditya109, can you put more description of the issue,
> like where the button goes in UI, what is slack URL?

@inyee786, I have updated the details in the description of this issue.

**Comment by aditya109** [comment]
> Okay, @aditya109. I have my PR ready. Let me know if there's no response.

Hi @ambaresthete, please take a look at the updated details in the description and make changes if required. Also please don't forget to star the [https://github.com/litmuschaos/litmus](repo).

**Comment by ambaresthete** [comment]
@aditya109  are you sure it goes to bottom-right corner? I guess top-right corner would be appropriate, as there is no footer and it goes along with header.

**Comment by aditya109** [comment]
@ambaresthete there is going to be a footer in the near future. So for now if you think it looks better in the top right, raise the PR and attach a screenshot of the UI. I will ask @inyee786 to review the feel of your change and ask for his opinion on the matter as well.

**Comment by ambaresthete** [comment]
I made the PR. Check the below link:

https://github.com/litmuschaos/charthub.litmuschaos.io/pull/39

**Comment by ksatchit** [comment]
Available in the revamped charthub
