### ISSUE TITLE
(ui-frontend-implementation): Adding an Experiment Run Count metric on each experiment

### ISSUE THREAD

**Issue by aditya109** [litmuschaos/litmus#790]
## UI-FRONTEND-IMPLEMENTATION
 
 **What happens**:

- Add a Experiment Run Count metric on each subcharts which updates itself on each experiment pull/install

**What you expected to happen**:

- The metric is to placed on each experiment card

**Anything else we need to know?**:

- Issue related to Repository : https://github.com/litmuschaos/charthub.litmuschaos.io

**Comment by hoshank** [comment]
Started looking into this. Hacktoberfest

**Comment by aditya109** [comment]
Sure go ahead @hoshank. Will assign this task to you. And please forget to raise a PR and put the link in the description.

**Comment by ksatchit** [comment]
Fixed as part of https://github.com/litmuschaos/charthub.litmuschaos.io/pull/92. This is part of the requirements mentioned in these issues: 

- https://github.com/litmuschaos/litmus/issues/986
- https://github.com/litmuschaos/litmus/issues/695

This issue (specific to individual experiment count) will be closed while the above mentioned issues will continue to track the overall availability of the feature in website.
