### ISSUE TITLE
(ui-frontend-implementation): Adding maturity label to the side-panel

### ISSUE THREAD

**Issue by aditya109** [litmuschaos/litmus#791]
(ui-frontend-implementation): Adding Maturity label to the side-panel

**What happens**:
- Adding a **Maturity Label** to to sidepanel of each chart/subchart

**Anything else we need to know?**:
- Issue related to Repository : https://github.com/litmuschaos/charthub.litmuschaos.io

**Comment by dravog7** [comment]
@aditya109  I would like to work on this issue. Is there anything I should know more?

**Comment by rahulchheda** [comment]
Go ahead @dravog7, don't forget to add this issue number in your PR, and add a link to your PR here as well.

**Comment by aditya109** [comment]
For sure @dravog7 you can go ahead and work on this issue.
If you want to know what the labels should look like :
![Screenshot from 2019-10-03 12-25-23](https://user-images.githubusercontent.com/22005947/66105713-ca86b300-e5d9-11e9-9083-7c8435c4735e.png)

**Comment by dravog7** [comment]
Should I add all the labels or just the maturity label? @aditya109

**Comment by aditya109** [comment]
@dravog7 Only Maturity Label is fine. We will add separate issues for other labels.

**Comment by ksatchit** [comment]
Fixed by https://github.com/litmuschaos/charthub.litmuschaos.io/pull/79. Experiment maturity levels are now available on the charthub website.
