### ISSUE TITLE
(ui-frontend-implementation): Adding Repository label to the side-panel

### ISSUE THREAD

**Issue by aditya109** [litmuschaos/litmus#792]
## UI-FRONTEND-IMPLEMENTATION
 
**What happens**:

- Adding a **Repository Label** to sidepanel of each chart/subchart

**Anything else we need to know?**:

- Issue related to Repository : https://github.com/litmuschaos/charthub.litmuschaos.io

**Comment by susw12** [comment]
Can I take up this issue?

**Comment by Niladri24dutta** [comment]
hi @aditya109 and @chandankumar4 can I work on this issue? How should the repository label look like? I mean is there any URL for that repository?

**Comment by aditya109** [comment]
Sure @Niladri24dutta , you can work on this issue.
The repository should look like this :
![Screenshot from 2019-10-03 12-25-23](https://user-images.githubusercontent.com/22005947/66105488-374d7d80-e5d9-11e9-8c2c-96db6edce8c0.png)
The repo in which you can change is mentioned above.

**Comment by aditya109** [comment]
Yes @Niladri24dutta. Don't forget to put the link of your PR, in this issue.

**Comment by Niladri24dutta** [comment]
> 
> 
> Yes @Niladri24dutta. Don't forget to put the link of your PR, in this issue.

Will do it once done

**Comment by jainsaarthak** [comment]
Hi, is this issue still open? I can start working on this issue.

**Comment by jainsaarthak** [comment]
Is this still open? I would like to work on this.

**Comment by chandankumar4** [comment]
@jainsaarthak You can you start working on this issue

**Comment by jainsaarthak** [comment]
Please approve if this is the required change:

![image](https://user-images.githubusercontent.com/16264215/66251792-9e059f00-e771-11e9-9faf-9aa4d5a7d028.png)

**Comment by aditya109** [comment]
@jainsaarthak no its is correct what you did... you don't need to hard code anything we had to get it through component itself. Kindly raise a PR for us to review.

**Comment by jainsaarthak** [comment]
https://github.com/litmuschaos/charthub.litmuschaos.io/pull/31

**Comment by ksatchit** [comment]
Fixed by litmuschaos/charthub.litmuschaos.io#31
