### ISSUE TITLE
need docker compose file in charthub repo

### ISSUE THREAD

**Issue by kmjayadeep** [litmuschaos/litmus#806]
## Is this a BUG REPORT or FEATURE REQUEST?
 
FEATURE REQUEST

charthub.litmuschaos.io has 2 docker files for client and server. It would be better to add a docker compose file to make it easy to run the application using the command
```docker-compose up```

Also, the docker commands provided in the readme are wrong.

I would like to work on this

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by kmjayadeep** [comment]
Please add the label Hactoberfest to the issue

**Comment by ksatchit** [comment]
> Please add the label Hactoberfest to the issue

Done!
