### ISSUE TITLE
Wrong installation instructions in README

### ISSUE THREAD

**Issue by aswathkk** [litmuschaos/litmus#807]
Docker section of Installation is wrong in the repository https://github.com/litmuschaos/charthub.litmuschaos.io
There are 2 Docker files which are `Dockerfile.client` and `Dockerfile.server`. But the Installation instruction in the [README](https://github.com/litmuschaos/charthub.litmuschaos.io/blob/master/README.md) doesn't mention how to use these Dockerfiles. And it also mentions a non-existing `Dockerfile-prod`

**Comment by aswathkk** [comment]
It's better to work on this issue after the issue #806 gets resolved.

**Comment by ksatchit** [comment]
Added the Hacktoberfest label to this issue. in case you would like to pick it up.

**Comment by aswathkk** [comment]
@ksatchit A PR has been already raised by @kmjayadeep
Please look into it. If it's all fine, then we can close this issue.
