### ISSUE TITLE
Kill Service experiment

### ISSUE THREAD

**Issue by crazyglasses** [litmuschaos/litmus#809]
FEATURE REQUEST

**What happened**:

Similar to kill pod, have a experiment to kill service. 
**What you expected to happen**:

The kill service experiment will remove the service associated with the pod or disrupt the type of service to observe the effect of how the environment would respond if the service were to be killed. 
**How to reproduce it (as minimally and precisely as possible)**:

New feature request 
**Anything else we need to know?**:

The kill service would help in deeper understanding of application deployment as well as add a new feature set. 

I would be happy to work on this issue.

**Comment by ksatchit** [comment]
Sure! Would be a great addition. Could you place your approach & steps on this issue as well?

**Comment by kmjayadeep** [comment]
@crazyglasses Are you working on this? else I would like to give a shot
@ksatchit This is the approach I'm thinking:

1. Inject the variables just like in pod-delete experiment
2. Get the IP and port of the service (maybe it can be injected through env, I'm not sure)
3. Make sure Service is up and port is accessible
4. Delete the service multiple times (same as pod-delete)
5. Verify whether the same Ip and port is accessible
6. Update results

I think the same service-delete logic can be reused for more app specific test cases also, for example hitting mongodb service through port 27017 should return 200 status (with some kind of message i don't remember)

**Comment by ksatchit** [comment]
We would love to have an introductory mongodb chart with the above service kill experiment! So the approach I would suggest is to have a base (generic experiment) with above described steps & then introduce a new experiment category called mongodb - which, while reusing the same service failure chaoslib, has additional exit criteria checks (with the 200 status, for example). Let me know what you think about this. 

(The idea is to always have a base experiment set/lib which is reused by apps with their own pre-post chaos checks)

**Comment by kmjayadeep** [comment]
@ksatchit Sure! great idea. For mongodb, we can use pod-delete and container-kill also.
I will start with service-delete then
