### ISSUE TITLE
(ui-frontend-implementation): Adding Home button in the Header

### ISSUE THREAD

**Issue by aditya109** [litmuschaos/litmus#814]
(ui-frontend-implementation): Adding Home button in the Header

**What happens**:
- Adding a Home button in the top header left to **Search-Box**. The button should be just contain **Home** and navigate back to [hub.litmuschaos.io](url)

**Anything else we need to know?**:
- Issue related to Repository :[https://github.com/litmuschaos/charthub.litmuschaos.io](url)

**Comment by GavinAF** [comment]
I'll take this up.

**Comment by aditya109** [comment]
For sure @GavinAF you can take this up. Please don't forget to raise a PR and link this issue to the raised PR.

**Comment by GavinAF** [comment]
https://github.com/litmuschaos/charthub.litmuschaos.io/pull/35

**Comment by aditya109** [comment]
> [litmuschaos/charthub.litmuschaos.io#35](https://github.com/litmuschaos/charthub.litmuschaos.io/pull/35)

Hi @GavinAF , great work on this issue. Will review your PR. 
It would be great if you could just star this repository.
The link is this:
[https://github.com/litmuschaos/litmus](url)

**Comment by ksatchit** [comment]
Fixed by: https://github.com/litmuschaos/charthub.litmuschaos.io/pull/35
