### ISSUE TITLE
(ui-frontend-implementation): Adding Copy-to-clipboard button in the Install pop-up

### ISSUE THREAD

**Issue by aditya109** [litmuschaos/litmus#815]
### (ui-frontend-implementation): Adding Copy-to-clipboard button in the Install pop-up

**What happens**:
-  Adding Copy-to-clipboard button in the modal code of crdlink in Install pop-up.
![q](https://user-images.githubusercontent.com/22005947/66259141-27958b00-e7cb-11e9-9172-acee3559b3bb.PNG)

**Anything else we need to know?**:
- Issue related to Repository :[https://github.com/litmuschaos/charthub.litmuschaos.io)](url)

**Comment by agarwalrounak** [comment]
Hi @aditya109, I need a bit more help here. Where can I find the Install pop-up?

**Comment by aditya109** [comment]
Hi @agarwalrounak In regards to your doubt.. If you browse to [hub.litmuschaos.io](url), and click any of the charts, on your right hand side column you have an install button. It is the one which is referred to here.

**Comment by PatOConnor43** [comment]
Hi @aditya109 I created a PR [here](https://github.com/litmuschaos/charthub.litmuschaos.io/pull/36) that I think should work for you.

**Comment by aditya109** [comment]
Hi @PatOConnor43, great work on this issue. Will review your PR. 
It would be great if you could just star this repository, it would be great.
The link is this:
[https://github.com/litmuschaos/litmus](url)

**Comment by aditya109** [comment]
@PatOConnor43 I have reviewed your PR. I would like you
 to make the UI look like this:
![Screenshot from 2019-10-09 19-20-41](https://user-images.githubusercontent.com/22005947/66488381-6f6a2a00-eacb-11e9-9bed-7818c798af14.png)
The button works just like but just requires a tinge of UI change
