### ISSUE TITLE
Litmus example is not working

### ISSUE THREAD

**Issue by kmjayadeep** [litmuschaos/litmus#817]
## Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT

**What happened**:

Tried to run the example provided in [Litmus Docs](https://docs.litmuschaos.io/docs/next/example.html). The result is not getting populated in chaosresult CR. The nginx pod was never killed and the chaosresult `engine-nginx-pod-delete` was never created. However when I ran `kubectl get pods -n litmus` the pod `engine-nginx-runner` is shown as completed.

**What you expected to happen**:

running `kubectl describe chaosresult engine-nginx-pod-delete` should return something like this from the example docs
```
Name:         engine-nginx-pod-delete
Namespace:    default
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
              {"apiVersion":"litmuschaos.io/v1alpha1","kind":"ChaosResult","metadata":{"annotations":{},"name":"engine-nginx-pod-delete","namespace":"de...
API Version:  litmuschaos.io/v1alpha1
Kind:         ChaosResult
Metadata:
  Creation Timestamp:  2019-05-22T12:10:19Z
  Generation:          9
  Resource Version:    8898730
  Self Link:           /apis/litmuschaos.io/v1alpha1/namespaces/default/chaosresults/engine-nginx-pod-delete
  UID:                 911ada69-7c8a-11e9-b37f-42010a80019f
Spec:
  Experimentstatus:
    Phase:    <nil>
    Verdict:  pass
Events:       <none>
```

**How to reproduce it (as minimally and precisely as possible)**:

- Open [Litmus example docs](https://docs.litmuschaos.io/docs/next/example.html) (version 0.6.0)
- Follow the steps as provided
- When I ran `kubectl describe chaosresult engine-nginx-pod-delete` it throws the error `Error from server (NotFound): chaosresults.litmuschaos.io "engine-nginx-pod-delete" not found`

**Anything else we need to know?**:

`kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

Host OS : MacOS using Docker for Desktop with Kubernetes 1.14.3

**Comment by ksatchit** [comment]
@kmjayadeep , can you share the logs of the engine-nginx-runner pod?

**Comment by kmjayadeep** [comment]
```

PLAY [localhost] ***************************************************************
2019-10-06T03:56:40.908523 (delta: 0.031031)         elapsed: 0.031031 ******** 
=============================================================================== 

TASK [Gathering Facts] *********************************************************
2019-10-06T03:56:40.915079 (delta: 0.006531)         elapsed: 0.037587 ******** 
ok: [127.0.0.1]

TASK [debug] *******************************************************************
2019-10-06T03:56:45.741971 (delta: 4.82687)         elapsed: 4.864479 ********* 
ok: [127.0.0.1] => {
    "msg": [
        "List of Chaos Experiments: [u'pod-delete']", 
        "Each experiment will be launched & monitored by the executor", 
        "Beginning Execution, view experiment logs on respective job"
    ]
}

TASK [debug] *******************************************************************
2019-10-06T03:56:45.805465 (delta: 0.063463)         elapsed: 4.927973 ******** 
ok: [127.0.0.1] => {
    "msg": [
        "c_rand value is: ", 
        "c_max value is: "
    ]
}

TASK [include] *****************************************************************
2019-10-06T03:56:45.869706 (delta: 0.064208)         elapsed: 4.992214 ******** 
included: /executor/executor.yml for 127.0.0.1

TASK [Verify if ChaosExperiment CR is available] *******************************
2019-10-06T03:56:45.976147 (delta: 0.106409)         elapsed: 5.098655 ******** 
fatal: [127.0.0.1]: FAILED! => {"changed": true, "cmd": "kubectl get chaosexperiment pod-delete --no-headers -o custom-columns=:metadata.name", "delta": "0:00:00.553590", "end": "2019-10-06 03:56:46.738373", "failed_when_result": true, "msg": "non-zero return code", "rc": 1, "start": "2019-10-06 03:56:46.184783", "stderr": "Error from server (NotFound): chaosexperiments.litmuschaos.io \"pod-delete\" not found", "stderr_lines": ["Error from server (NotFound): chaosexperiments.litmuschaos.io \"pod-delete\" not found"], "stdout": "", "stdout_lines": []}
	to retry, use: --limit @/executor/test.retry

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=4    changed=0    unreachable=0    failed=1   

2019-10-06T03:56:46.764939 (delta: 0.78876)         elapsed: 5.887447 ********* 
=
```

**Comment by kmjayadeep** [comment]
When I ran the command `kubectl get chaosexperiment`
I get :
```
NAME                AGE
container-kill      3h18m
pod-delete          3h18m
pod-network-delay   3h18m
```

**Comment by rahulchheda** [comment]
Sir, make your deployment in litmus namespace, and change the chaosengine's yaml to get the apps in litmus namespace, give the chaosServiceAccount as 'litmus' , appns: 'litmus',metadata.namespace: 'litmus'.
And then use the instruction in this PR, it just changes the chaosExperiments namespace to 'litmus'.
PR link : https://github.com/litmuschaos/litmus-docs/pull/39

**Comment by kmjayadeep** [comment]
Thanks @rahulchheda 
It worked after some trial and error. I think we have few more changes to be done in [https://docs.litmuschaos.io/docs/next/example.html](https://docs.litmuschaos.io/docs/next/example.html) page. Here are the changes I did to make it work.

Added `-n litmus` to
```bash
kubectl create -f https://raw.githubusercontent.com/litmuschaos/chaos-charts/master/charts/generic/experiments.yaml
```

Added `-n litmus` to
```bash
kubectl run myserver --image=nginx
```

Change `appns` from `default` to `litmus` in `chaosengine.yaml`

And finally

Added `-n litmus` to
```bash
kubectl describe chaosresult engine-nginx-pod-delete
```

Following these exact steps (with the changes above) worked for me. I have tested in 2 different devices and 1 cluster. I think these should me added to the doc as well. I can create a PR if it is okay.

Also I would suggest, `getting started` section should contain instructions to run experiments on already running deployments and the example page should contain step by step instructions for a newbie to try it out and see it in action. 
I'm still not able to run it for default namespace though :(

**Comment by ksatchit** [comment]
Great! Thanks @kmjayadeep , please go ahead & raise the PR with the working steps.

**Comment by kmjayadeep** [comment]
Thanks for the detailed explanation @ksatchit 
I'm trying out these as you explained

> generally, the idea is to keep chaos resources in the same ns as the one where the app ns is present (just FYI ..as this will help to isolate app-specific chaos ..or even run parallel chaos for different apps, the chaos operator however, can continue to stay in litmus ns).In such cases, the following changes should be made. The same should work for existing/already deployed apps as well. (Taking example of default ns):Note: Right now this is supported only on K8s deployments with support for other types (statefulsets, daemonsets coming up in 0.7 release)# Annotate the deployment Annotate the app in default ns with the same one used in your earlier trial (litmuschaos.io/chaos="true")# Pull the experiments into default ns- This time without the |-n litmus` flag# Create ChaosEngine manifest yaml like this:- Provide metadata.namespace of ChaosEngine as default
- Provide spec.appinfo.appns as default
- Identify a unique label of the app (one by which it can filtered). Typically this should be present at metadata.labels & spec.template.metadata.labels of the app deployment (you can get this via kubectl get deploy <app deploy name> -o yaml) or via a -- show-labels` cmd.
- Provide above label in spec.appinfo.applabel of the ChaosEngine yaml.
- Create an serviceaccount in the default ns and provide it in spec.chaosServiceAccount (link to example provided on this thread &GitHub  issue - you can apply this yaml to create one svcAcc). - Apply/Create the chaosEngine.# ChaosResults- This can be viewed/described in the default ns itself (edited) 

I will try to run it on default and litmus namespaces as you suggested and create a PR with changes to be made on the doc

Thanks for all the help!
