### ISSUE TITLE
Litmus-Docs mobile view has to be fixed

### ISSUE THREAD

**Issue by umamukkara** [litmuschaos/litmus#818]
Visit https://docs.litmuschaos.io on your phone. You will see the header and content mixed up a bit.

One option is to remove the links to Github, Slack and Chaos Hub from the header links, as we have already mentioned them in footer.

File to edit is 
https://github.com/litmuschaos/litmus-docs/blob/staging/website/siteConfig.js

## Is this a BUG REPORT or FEATURE REQUEST?
 
 Choose one: BUG REPORT or FEATURE REQUEST

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by umamukkara** [comment]
![image](https://user-images.githubusercontent.com/19591814/66265296-bd640100-e831-11e9-9da6-bee911306ac8.png)

**Comment by aswathkk** [comment]
May I take up this one?

**Comment by inyee786** [comment]
@aswathkk, you can take it up

**Comment by aswathkk** [comment]
Looks like we are using an old version of Docusauraus.
They already resolved these problems in the newer versions.
See this [PR](https://github.com/facebook/docusaurus/pull/444)

**Comment by chandankumar4** [comment]
Thanks @aswathkk For upgrading the Docusauraus version

**Comment by chandankumar4** [comment]
There is still some improvement is required for mobile view anyone can take this UP

**Comment by aswathkk** [comment]
@chandankumar4 What are those?
I think we can add it as issues.

**Comment by msj2** [comment]
Thanks for taking my query @aswathkk 
I'll pick this up & try to fix this today.
നന്ദി സുഹൃത്ത്

**Comment by gshanbhag525** [comment]
I WANT TO WORK ON THIS

**Comment by aswathkk** [comment]
@gshanbhag525 
Sorry, @msj2 is already working on it.

**Comment by aravindvnair99** [comment]
@aswathkk Sorry for not informing prior working on it. I've fixed it in https://github.com/aravindvnair99/litmus-docs/commit/35aee6d797065be335ab6513235446ff43815e1d and submitted a pull request as well at https://github.com/litmuschaos/litmus-docs/pull/70

**Comment by Anand-Theertha** [comment]
**Is this fixed or still open?**@umamukkara

**Comment by aravindvnair99** [comment]
@umamukkara I've fixed this in  https://github.com/litmuschaos/litmus-docs/issues/68

**Comment by ksatchit** [comment]
There are some improvements in mobile view post docusaurus upgrade https://github.com/litmuschaos/litmus-docs/pull/44 & https://github.com/litmuschaos/litmus-docs/pull/70, but issues do exist. These will be raised separately & tracked.
