### ISSUE TITLE
ChaosHub - Fix mobile view of Generic charts

### ISSUE THREAD

**Issue by umamukkara** [litmuschaos/litmus#819]
## Is this a BUG REPORT or FEATURE REQUEST?
 
BUG REPORT

Browse ChaosHub on your mobile (https://hub.litmuschaos.io). Browse generic charts. The chaos experiments have to be stacked one below the other. 

The same in the charts view is looking correctly.

![image](https://user-images.githubusercontent.com/19591814/66265421-d968a200-e833-11e9-9987-48dbe7e8fa5b.png)

**Anything else we need to know?**:
- Issue related to Repository :[https://github.com/litmuschaos/charthub.litmuschaos.io)](url)

**Comment by umamukkara** [comment]
@aditya109 can you post the repo details on where this needs to be fixed?

**Comment by agarwalrounak** [comment]
Hi @umamukkara:wave: I have figured out the repo details and the necessary correction needed. I will take this up. Please assign it to me.

**Comment by inyee786** [comment]
Hi, @agarwalrounak assigned this issue to you. 
Do add a screenshot of your UI change in the pull request.

**Comment by aditya109** [comment]
> @aditya109 can you post the repo details on where this needs to be fixed?

Posted @umamukkara

**Comment by umamukkara** [comment]
Thanks @agarwalrounak . If you have any questions, the community channel is at https://kubernetes.slack.com/messages/CNXNB0ZTN

**Comment by agarwalrounak** [comment]
Please review PR https://github.com/litmuschaos/charthub.litmuschaos.io/pull/37
