### ISSUE TITLE
Upgrade Docusaurus to latest version

### ISSUE THREAD

**Issue by aswathkk** [litmuschaos/litmus#820]
## Is this a BUG REPORT or FEATURE REQUEST?
 
FEATURE REQUEST

The latest version of Docusaurus is 1.13.0, but what we use for [Litmus-docs](https://github.com/litmuschaos/litmus-docs) is 1.0.12 which is far behind the latest one.
The latest version has got better features and it will resolve all the issue with the responsiveness of the docs website.

**Comment by kmjayadeep** [comment]
Also, it is better to remove node_modules from repo and commit only one of package-lock.json or yarn.lock
