### ISSUE TITLE
Update README.md at charthub.litmuschaos.io

### ISSUE THREAD

**Issue by agarwalrounak** [litmuschaos/litmus#821]
The `usage` section of `README.md` at https://github.com/litmuschaos/charthub.litmuschaos.io should be updated to include more information about starting up the charthub on localhost.

**Comment by agarwalrounak** [comment]
I am taking this up.

**Comment by sahilbhosale63** [comment]
Hi, is anyone working on this issue or should I take it?

**Comment by agarwalrounak** [comment]
Hi @sahilbhosale63, there is already a PR https://github.com/litmuschaos/charthub.litmuschaos.io/pull/38 opened for this issue.
