### ISSUE TITLE
Typo in litmuschaos.io

### ISSUE THREAD

**Issue by juliosueiras** [litmuschaos/litmus#823]
Not sure which repo to raise the issue, but on https://litmuschaos.io , the Features section have a typo

> Bring GitOps into chaos engineering. Define chaos, run chaos and observe chaos using Kubernetes Customer Resources.

Kubernetes Customer Resources should be Kubernetes Custom Resources

**Comment by IsAmrish** [comment]
Thanks @juliosueiras for reporting it. The typo has been fixed!!

**Comment by Kerl1310** [comment]
@IsAmrish Can this be closed if so?
