### ISSUE TITLE
Icon for Pod Delete experiment.

### ISSUE THREAD

**Issue by ajeshbaby** [litmuschaos/litmus#826]
Design icons to show case the following experiments. Each experiment should have an icon in
https://hub.litmuschaos.io/charts/generic
This issue is to track the icon for **Pod Delete**

**Comment by ManishAradwad** [comment]
Hii! I'd like to work on this one.. Can you plz assign this to me

**Comment by aditya109** [comment]
Thankyou for your contribution @mevrouwdevries! Please check your PR for my comment. Keep up the good work.
