### ISSUE TITLE
Icon for Container Kill experiment

### ISSUE THREAD

**Issue by ajeshbaby** [litmuschaos/litmus#827]
Design icons to show case the following experiments. Each experiment should have an icon in
https://hub.litmuschaos.io/charts/generic
This issue is to track the icon for **Container Kill** experiment

**Comment by ven-k** [comment]
@ajeshbaby do you have any specific design in mind? (Are there any restrictions or format that we need to follow?)

**Comment by ven-k** [comment]
@ajeshbaby could you assign this to me?

**Comment by aditya109** [comment]
Thankyou for your contribution @ven-k ! Please check your PR for my comment. Keep up the good work.
