### ISSUE TITLE
Icon for Network Delay experiment

### ISSUE THREAD

**Issue by ajeshbaby** [litmuschaos/litmus#828]
Design icons to show case the following experiments. Each experiment should have an icon in
https://hub.litmuschaos.io/charts/generic
This issue is to track the icon for **Network Delay**

**Comment by mevrouwdevries** [comment]
I'd like to work on this issue. Can you assign me please?

**Comment by chandankumar4** [comment]
Thanks @mevrouwdevries for picking up this issue, Go ahead

**Comment by aditya109** [comment]
Thankyou for your contribution @mevrouwdevries! Please check your PR for my comment. Keep up the good work.

**Comment by aditya109** [comment]
Thankyou for your contribution @mevrouwdevries! Please check your PR for my comment. Keep up the good work.
