### ISSUE TITLE
Icon for Network loss experiment

### ISSUE THREAD

**Issue by ajeshbaby** [litmuschaos/litmus#829]
Design icons to show case the following experiments. Each experiment should have an icon in
https://hub.litmuschaos.io/charts/generic
This issue is to track the icon for **Network Loss** experiment.

**Comment by mevrouwdevries** [comment]
I'd like to work on this. Can you assign me please?

**Comment by chandankumar4** [comment]
Thanks, @mevrouwdevries for picking up this issue.
/assigned

**Comment by aditya109** [comment]
Thankyou for your contribution @mevrouwdevries! Please check your PR for my comment. Keep up the good work.
