### ISSUE TITLE
(ui-frontend-implementation): fixing the spacing in the side panel of the charts and link styling changes

### ISSUE THREAD

**Issue by aditya109** [litmuschaos/litmus#840]
### (ui-frontend-implementation): fixing the spacing in the side panel of the charts and link styling changes

**What happens**:
-  The labels don't have equal spacings. Requires changes in css :
![Screenshot from 2019-10-11 18-41-25](https://user-images.githubusercontent.com/22005947/66654204-568e7f80-ec57-11e9-91a5-b9fe1103c656.png)

- Also the repository link clips through the side panel div. This needs a fix as well.

**Anything else we need to know?**:
- Issue related to Repository :[https://github.com/litmuschaos/charthub.litmuschaos.io)](url)
- Please raise a PR linking this issue to it and also attach the screenshot of your fix.

**Comment by PseudoNerd** [comment]
Can I take this up ?

**Comment by chandankumar4** [comment]
Sure @PseudoNerd you can take this issue

**Comment by RajTG** [comment]
Hi, can I contribute to this?

**Comment by aditya109** [comment]
Hi @RajTG,  you can contribute to this issue by fixing whatever is required to be fixed. Then you raise a PR correspondingly, and link this issue in your PR.

**Comment by ikmrgrv** [comment]
Is someone already working to resolve this issue ??

**Comment by aditya109** [comment]
No contributions yet @ikmrgrv. You can go ahead and start working on this.

**Comment by ikmrgrv** [comment]
How can I replicate this on my system ??
Can you add the steps of project-setup ?

**Comment by aditya109** [comment]
Please go through README.md and if you still don't get it, contact me.

**Comment by ikmrgrv** [comment]
@aditya109 can you at least point me to the correct package.json file in order to be able to locate where the code for the app is ??
There is no instruction for the project setup in Readme.md, it has all things to do with the product description.

**Comment by gshanbhag525** [comment]
I WANT TO WORK ON THIS

**Comment by aditya109** [comment]
> @aditya109 can you at least point me to the correct `package.json` file in order to be able to locate where the code for the app is ??
> There is no instruction for the project setup in Readme.md, it has all things to do with the product description.

@ikmrgrv First go to the [hub-repo](https://github.com/litmuschaos/charthub.litmuschaos.io), fork it and then clone it. Browse to the `repo-directory` and then run
```
yarn install 
```
or,
```
npm install
```
and then run npm start. 
> This would run your client.

Open another terminal and navigate to `server` directory.
 and then run 
```
go run *.go
```

**Comment by aditya109** [comment]
> I WANT TO WORK ON THIS

Hi @gshanbhag525 I am sorry but this issue is already taken. In the next 10-12 hours if there is no further response and if you are still interested, you issue can be assigned to you. Please take a look at other issues.

**Comment by ikmrgrv** [comment]
@aditya109 Hey, thanks for pointing me to the correct repo. I am able to clone and setup the project in my local system.

However, while running `npm run start`, it points out that file `./src/components/ChartDetails.js` requires `react-markdown` which is not included in project dependencies.

I am raising a PR for it. Can you please check it asap so that I can proceed with the changes required for this issue.
I guess the package `react-markdown` is installed globally in the maintainer's system.

**Comment by ikmrgrv** [comment]
![Screenshot 2019-10-26 at 3 00 41 PM](https://user-images.githubusercontent.com/14366411/67617511-6d110b00-f801-11e9-8c40-0a99b1d3af0b.png)
I think you  are referring to this component, where the icons are slightly disaligned with the text.
Can you confirm if I am pointing to the same issue, so that I can take it up ??

**Comment by ikmrgrv** [comment]
> @aditya109
> ![Screenshot 2019-10-26 at 3 00 41 PM](https://user-images.githubusercontent.com/14366411/67617511-6d110b00-f801-11e9-8c40-0a99b1d3af0b.png)
> I think you are referring to this component, where the icons are slightly disaligned with the text.
> Can you confirm if I am pointing to the same issue, so that I can take it up ??


![Screenshot 2019-10-26 at 3 14 00 PM](https://user-images.githubusercontent.com/14366411/67617704-713e2800-f803-11e9-85bb-14acb9560dfc.png)

Can you suggest which way you want it to be displayed ??
    - The first way (highlighted in red rounded box) where the icon aligns with the first line of the text following it.
    - Or the second way (highlighted in skyblue rounded box) where the icon aligns with the centre of the text following it.

**Comment by aditya109** [comment]
Sorry @ikmrgrv this issue is termed for a later time. I will close this issue.
