### ISSUE TITLE
(ui-frontend-implementation): changing the placement of the experiments

### ISSUE THREAD

**Issue by aditya109** [litmuschaos/litmus#841]
### (ui-frontend-implementation): changing the placement of the experiments

**What happens**:
-  Currently we have this:
![image](https://user-images.githubusercontent.com/22005947/66656539-d4ed2080-ec5b-11e9-91f8-679b505f4469.png)
- What is needed is the experiments should be moved closer to the description to remove the blank space
![Screenshot from 2019-10-11 19-13-49](https://user-images.githubusercontent.com/22005947/66656612-f948fd00-ec5b-11e9-93a5-4b7bdcb64cbf.png)

- Also the repository link clips through the side panel div. This needs a fix as well.

**Anything else we need to know?**:
- Issue related to Repository : https://github.com/litmuschaos/charthub.litmuschaos.io
- Please raise a PR linking this issue to it and also attach the screenshot of your fix.

**Comment by ambaresthete** [comment]
Can i work on this?

**Comment by inyee786** [comment]
yes, @ambaresthete you can take it up

**Comment by aditya109** [comment]
Yes @ambaresthete you can definitely go ahead with this issue. I have assigned this issue to you.

**Comment by devbihari** [comment]
I'll fix this issue :fire:

**Comment by aditya109** [comment]
Hi @devbihari. No contributions yet. If you like this issue, go ahead and work on this.

**Comment by gshanbhag525** [comment]
I want to work on this

**Comment by aditya109** [comment]
> I want to work on this

Hi @gshanbhag525 I am sorry but this issue is already taken. In the next 10-12 hours if there is no further response and if you are still interested, you issue can be assigned to you. Please take a look at other issues.

**Comment by devbihari** [comment]
closed with https://github.com/litmuschaos/charthub.litmuschaos.io/pull/67

**Comment by aditya109** [comment]
Please check my comment on your PR.
