### ISSUE TITLE
[Feat.] Collect the list of chaos specific experiments for Elasticsearch 

### ISSUE THREAD

**Issue by ErrEss** [litmuschaos/litmus#859]
1. Develop an experiment to test the replication of shards in different nodes, if the data in a node (or the whole node) is deleted accidentally.
2. An experiment to test if the indexing service breaks when the index is queried at the time it is being indexed.

**Comment by kapilmodi** [comment]
We can also add this feature.
3. An experiment to test the cross cluster replication process

**Comment by ksatchit** [comment]
Thanks @ErrEss @kapilmodi ! Keep the usecases coming!!

**Comment by atulabhi** [comment]
All above test cases are good to have.
I am working  to add litmus book to check the health of the cluster before and after introducing chaos.

**Comment by ksatchit** [comment]
This being an umbrella issue, will be kept live to track more scenarios. Moving out of 1.3 milestone.

**Comment by ghoshankur1983** [comment]
Someone please assign the issue to me.

**Comment by ghoshankur1983** [comment]
Use Case 1 - Stop and Start elastcisearch service.

**Comment by ksatchit** [comment]
Please reference: https://github.com/litmuschaos/litmus/issues/587
