### ISSUE TITLE
(feat): Request for adding Disk Loss GCP chaos experiment

### ISSUE THREAD

**Issue by rajdas98** [litmuschaos/litmus#862]
1. Required a good approach for disk loss experiment
2. Required separate chaos experiment for GCP

**Comment by rajdas98** [comment]
As per the discussion with @ksatchit we have decided the following things for this experiment:
- user input
  - platform name
  - project name
  - disk name
  - api keys/ssh
  - app label (optional)
  - app namespace (optional)
- prechecks
  - disk status
  - pod status (optional)
- postchecks
  - disk status
  - pod status (optional)
- injection approach
  - detach disk 
  - attach disk

**Comment by ksatchit** [comment]
The application specific experiments that reuse the disk loss chaoslib are expected to introduce their own checks - thereby rendering this experiment an app level chaos OR infra-level chaos.

**Comment by ksatchit** [comment]
Fixed by #896
