### ISSUE TITLE
(refactoring): Addition of new icon to each experiment

### ISSUE THREAD

**Issue by aditya109** [litmuschaos/litmus#879]
##### What needs to be done ?

- [ ] Each experiment needs to have a different icon. 
- [ ] Charts' icons should be moved to one single folder in [chaos-charts](https://github.com/litmuschaos/chaos-charts/).
> This would make [charthub-repo](https://github.com/litmuschaos/charthub.litmuschaos.io) completely independent. 

##### Take-A-Point

- [ ] changes required in `server` and `src > components` directories of the [charthub.litmuschaos.io](https://github.com/litmuschaos/charthub.litmuschaos.io "charthub.litmuschaos.io") repo
> Note: Directory-structure might require of charts from [chaos-charts](https://github.com/litmuschaos/chaos-charts/) repo.

**Comment by aditya109** [comment]
@ksatchit @ajeshbaby @chandankumar4 can you please suggest how should I go about it?

**Comment by ajeshbaby** [comment]
I would suggest to have an icon folder in an experiment folder. 
for example --  Generic Chaos
-- Generic/icons/generic.png  
    Generic/icons/container-kill.png
    Generic/icons/pod-delete.png
    Generic/icons/.....

**Comment by aditya109** [comment]
@ajeshbaby until any other approach is suggested I will begin working with your approach. Also we need to decide the association of the icons.

**Comment by chandankumar4** [comment]
> I would suggest to have an icon folder in an experiment folder.
> for example -- Generic Chaos
> -- Generic/icons/generic.png
> Generic/icons/container-kill.png
> Generic/icons/pod-delete.png
> Generic/icons/.....

I'm good with this approach

**Comment by ven-k** [comment]
Do I add even the svg format images in the same folder?
