### ISSUE TITLE
Resolve security vulnerability reported by sonarqube on autoescape policy used by jinja2

### ISSUE THREAD

**Issue by ksatchit** [litmuschaos/litmus#889]
**What happened**:

The quality check by sonarqube is failed due to non-compliant autoescape policy for jinja2 template rendering. It is disabled by default. The scanning rule requires enabling it to prevent cross-scripting vulnerabilities. 

![image](https://user-images.githubusercontent.com/21166217/67478846-7e7bdb00-f67a-11e9-81e1-2751279165ab.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by vharsh** [comment]
I'd recommend using plugins like [Snyk](snyk.io) or GitHub's own [Dependabot](https://github.com/marketplace/dependabot-preview) for vulnerability reports. The latter sends in a PR by modifying the `requirements.txt`, `Pipfile.lock`.
