### ISSUE TITLE
(litmus-docs) broken link in getting started page

### ISSUE THREAD

**Issue by kmjayadeep** [litmuschaos/litmus#893]
**What happened**:
There is a broken link in getting started page of litmus docs

**How to reproduce it (as minimally and precisely as possible)**:

Go to https://docs.litmuschaos.io/docs/getstarted/
navigate to example section
click on example link

**Anything else we need to know?**:
The link should be https://docs.litmuschaos.io/docs/example/

**Comment by GauravMohla** [comment]
can I take this one ?

**Comment by ksatchit** [comment]
This is fixed in the latest docs version.
