### ISSUE TITLE
[litmus-docs] Need to update instructions as per 0.7

### ISSUE THREAD

**Issue by kmjayadeep** [litmuschaos/litmus#905]
The instructions in `getting started` and `chaos example` are not working since the installation step has changed to install version 0.7 of litmus. This is a blocker for new users who are trying to get started with litmus.

Only one change I know is that chaosengine.yaml `spec.appinfo` now requires `kind` attribute to be specified.

If someone from the contributors can help with the changelog, I can help to test and create PR with the updated instructions.

### Steps to reproduce

1. Open https://docs.litmuschaos.io/docs/getstarted/
2. Follow the guide to setup an experiment
3. Observe that experiment is not being run
4. Repeat 1-3 with https://docs.litmuschaos.io/docs/example/

**Comment by ksatchit** [comment]
Hey @Jayadeep KM, yes this will not work without the `appkind: <deployment/statefulset>` : https://docs.litmuschaos.io/docs/example/

This was a change that went in post 0.7. 

cc: @rahulchheda @rajdas98

**Comment by kmjayadeep** [comment]
@ksatchit Thanks, I will give a try!

**Comment by ksatchit** [comment]
The docs are updated based on the latest developments in 0.8.
