### ISSUE TITLE
Typo in link in getting started documentation

### ISSUE THREAD

**Issue by LaumiH** [litmuschaos/litmus#936]
**What happened**: I tried to follow the [getting started guide](https://docs.litmuschaos.io/docs/getstarted/) and found a dead [link](https://raw.githubusercontent.com/litmuschaos/chaos-charts/master/charts/generic/experiment.yaml) in the [install chaos experiments section](https://docs.litmuschaos.io/docs/getstarted/#install-chaos-experiments). The cli command therefore fails with a 404. An 's' is missing in the link.

**What you expected to happen**: The command executes and creates the CRDs.

**How to reproduce it (as minimally and precisely as possible)**: Copy and try to execute the command.

**Anything else we need to know?**: The correct link is https://raw.githubusercontent.com/litmuschaos/chaos-charts/master/charts/generic/experiments.yaml.

**Comment by ksatchit** [comment]
Thank you @LaumiH for bringing it to notice! Would you like to raise a PR on this?

**Comment by LaumiH** [comment]
When I go to the [github page](https://github.com/litmuschaos/litmus-docs/blob/staging/docs/getstarted.md), there is a completely different link which is working ...

**Comment by LaumiH** [comment]
Ah nevermind, I was on staging branch. So it seems it was already corrected with a different link and has to be merged to master.
