### ISSUE TITLE
Documentation outcome not working and not matching code basis

### ISSUE THREAD

**Issue by LaumiH** [litmuschaos/litmus#949]
**What happened**: I tried to follow several documentations now: [first](https://github.com/litmuschaos/community/tree/master/feature-demos/chaos-operator-workflow), [second](https://docs.litmuschaos.io/docs/getstarted/) and none of the chaos experiments works. Nothing happens.

**What you expected to happen**: The documentation actually describes steps that match the code basis in the git repos (links do not work, resources are named differently, yaml files have different content). I really wanted to give litmus a try as it seems to be a cool project. But if you cannot even use it as a noob following a simple documentation, it really is no good. What worked for me was this (external!) [guide](https://medium.com/faun/how-to-inject-chaos-on-kubernetes-resources-using-litmuschaos-c5ddee457b12).

**How to reproduce it (as minimally and precisely as possible)**: Simply follow any of your documentations and tutorials step by step and try to understand what is (not) happening from the perspective of a noob.

**Anything else we need to know?**: I cannot file any PRs because I do not understand the code basis and currently have no time to work myself into it. I really want to give Litmus a try though. How can I help?

**Comment by ksatchit** [comment]
@LaumiH , apologies on the trouble you have been facing! We have been trying to make changes to the docs as the project sees newer developments in terms of schema of the CRs etc., but understand that there are gaps we need to address in the process wrt documentation. Rest assured, we will look into this. 

Now, getting to this issue: 

- The first link you tried should ideally be updated for newer schemas, but isn't something we really are recommending as the steps to look at. So, I suppose both need (the source pointing to this link as reference and the doc itself) needs to be re-looked. 

- The second link (the getting started page) assumes availability of an application on which you would like to do chaos v/s the [example](https://docs.litmuschaos.io/docs/example/) page which has steps to both setup the application as well as perform chaos on it. These were updated during the 0.8 release AFAIK, so if they haven't been working, then we may need to relook the doc sanity testing procedure. 

The guide you mentioned is an alternate, but less preferred way of running litmus,i.e, directly using the experiment jobs. Good to know it helped you, but we would be more interested in fixing the getting-started page and litmus-docs to do that. 

Really regret your experience with docs and yes, you could help with fixing this.  Are you on the litmus slack OR if you have a bit of time to spare, we could get onto a quick call/google hangout to have a quick discussion what are the pitfalls you are observing.

**Comment by ksatchit** [comment]
@LaumiH , I shall post updates here as we go about repairing any issue with the docs. Would help greatly if you could verify if the updated steps work for you. 

- Community Link for Chaos-Operator-Workflow: Is being fixed via https://github.com/litmuschaos/community/pull/18

**Comment by LaumiH** [comment]
I really appreciate the quick and informative answer, and I think I cannot complain about the docu and then in return not tell you where my problems are :D 
So I decided to spend a bit more time trying to find the reasons for my problems.

The first problem I had were different tutorial steps and links on the website and on the github staging branch (which is the default you see when visiting the repo). As far as I can see this was already fixed and the links in the commands work. So I think [#936](https://github.com/litmuschaos/litmus/issues/936) can be closed now.

I will try out the new getting started docu now.

**Comment by LaumiH** [comment]
I noticed a difference in the [getting started](https://docs.litmuschaos.io/docs/getstarted/) docu and the [chaos example](https://docs.litmuschaos.io/docs/example/) docu. The command for installing the generic chaos experiments should be 
`kubectl create -f https://hub.litmuschaos.io/api/chaos?file=charts/generic/experiments.yaml -n litmus` (I guess). 

My confusion with the namespaces is now solved, as the tutorials now make very clear that everything should be in the same namespace. Cool!

**Comment by LaumiH** [comment]
The [chaos example](https://docs.litmuschaos.io/docs/example/) using the above command now works :) !

Before all the steps completed, but the chaosengine did not start and there were no chaosresults, neither in the default nor in the litmus namespace. I am running on minikube with full admin access. I suspect there was some confusion on my side with the namespaces, which is now made clear in the docs.

**Comment by LaumiH** [comment]
Update on the getting started tutorial: it now works for me, maybe I made a mistake because it was not clear to me in which namespace components have to be deployed to.

So the chaosexperiment container-kill starts and is running, but then it fails. The logs show this trace:

```
ansible-playbook 2.7.3
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]
No config file found; using defaults
/etc/ansible/hosts did not meet host_list requirements, check plugin documentation if this is unexpected
/etc/ansible/hosts did not meet script requirements, check plugin documentation if this is unexpected

PLAYBOOK: container_kill_ansible_logic.yml *********************************
1 plays in ./experiments/generic/container_kill/container_kill_ansible_logic.yml

PLAY [localhost] ***********************************************************
2019-11-20T11:37:04.615292 (delta: 0.071829)         elapsed: 0.071829 **** 
=============================================================================== 

TASK [Gathering Facts] *****************************************************
task path: /experiments/generic/container_kill/container_kill_ansible_logic.yml:2
2019-11-20T11:37:04.632096 (delta: 0.016429)         elapsed: 0.088633 **** 
ok: [127.0.0.1]
META: ran handlers

TASK [Construct chaos result name (experiment_name)] ***********************
task path: /experiments/generic/container_kill/container_kill_ansible_logic.yml:19
2019-11-20T11:37:07.030405 (delta: 2.398017)         elapsed: 2.486942 **** 
ok: [127.0.0.1] => {"ansible_facts": {"c_experiment": "engine-nginx-container-kill"}, "changed": false}

TASK [include_tasks] *******************************************************
task path: /experiments/generic/container_kill/container_kill_ansible_logic.yml:26
2019-11-20T11:37:07.114013 (delta: 0.083582)         elapsed: 2.57055 ***** 
included: /utils/runtime/update_chaos_result_resource.yml for 127.0.0.1

TASK [Generate the chaos result CR to reflect SOT (Start of Test)] *********
task path: /utils/runtime/update_chaos_result_resource.yml:3
2019-11-20T11:37:07.225627 (delta: 0.111589)         elapsed: 2.682164 **** 
changed: [127.0.0.1] => {"changed": true, "checksum": "f5cb4a6ed2da47aa92c9e242adff0753b55ed566", "dest": "./chaos-result.yaml", "gid": 0, "group": "root", "md5sum": "5f6b5e2db38492271adf04b8213596c0", "mode": "0644", "owner": "root", "size": 316, "src": "/root/.ansible/tmp/ansible-tmp-1574249827.26-35001803594811/source", "state": "file", "uid": 0}

TASK [Apply the chaos result CR] *******************************************
task path: /utils/runtime/update_chaos_result_resource.yml:13
2019-11-20T11:37:07.853767 (delta: 0.627959)         elapsed: 3.310304 **** 
changed: [127.0.0.1] => {"changed": true, "cmd": "kubectl apply -f chaos-result.yaml -n default", "delta": "0:00:00.613866", "end": "2019-11-20 11:37:08.708611", "failed_when_result": false, "rc": 0, "start": "2019-11-20 11:37:08.094745", "stderr": "", "stderr_lines": [], "stdout": "chaosresult.litmuschaos.io/engine-nginx-container-kill configured", "stdout_lines": ["chaosresult.litmuschaos.io/engine-nginx-container-kill configured"]}

TASK [Update the chaos result CR to reflect EOT (End of Test)] *************
task path: /utils/runtime/update_chaos_result_resource.yml:23
2019-11-20T11:37:08.752274 (delta: 0.898481)         elapsed: 4.208811 **** 
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Apply the chaos result CR] *******************************************
task path: /utils/runtime/update_chaos_result_resource.yml:33
2019-11-20T11:37:08.794645 (delta: 0.042327)         elapsed: 4.251182 **** 
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Verify that the AUT (Application Under Test) is running] *************
task path: /experiments/generic/container_kill/container_kill_ansible_logic.yml:33
2019-11-20T11:37:08.833317 (delta: 0.038486)         elapsed: 4.289854 **** 
included: /utils
/common/status_app_pod.yml for 127.0.0.1

TASK [Checking whether application pods are in running state] **************
task path: /utils/common/status_app_pod.yml:2
2019-11-20T11:37:08.893298 (delta: 0.059947)         elapsed: 4.349835 **** 
changed: [127.0.0.1] => {"attempts": 1, "changed": true, "cmd": "kubectl get pods -n default -l run=myserver -o custom-columns=:.status.phase --no-headers", "delta": "0:00:00.325852", "end": "2019-11-20 11:37:09.393166", "rc": 0, "start": "2019-11-20 11:37:09.067314", "stderr": "", "stderr_lines": [], "stdout": "Running", "stdout_lines": ["Running"]}

TASK [Get the container status of application.] ****************************
task path: /utils/common/status_app_pod.yml:9
2019-11-20T11:37:09.465019 (delta: 0.571685)         elapsed: 4.921556 **** 
changed: [127.0.0.1] => {"attempts": 1, "changed": true, "cmd": "kubectl get pod -n default -l run=myserver --no-headers -o jsonpath='{.items[*].status.containerStatuses[*].ready}' | tr ' ' '\\n' | uniq", "delta": "0:00:00.430845", "end": "2019-11-20 11:37:10.138287", "rc": 0, "start": "2019-11-20 11:37:09.707442", "stderr": "", "stderr_lines": [], "stdout": "true", "stdout_lines": ["true"]}

TASK [include_tasks] *******************************************************
task path: /experiments/generic/container_kill/container_kill_ansible_logic.yml:41
2019-11-20T11:37:10.206285 (delta: 0.74115)         elapsed: 5.662822 ***** 
included: /chaoslib/pumba/pod_failure_by_sigkill.yaml for 127.0.0.1

TASK [Patch the chaoslib image] ********************************************
task path: /chaoslib/pumba/pod_failure_by_sigkill.yaml:2
2019-11-20T11:37:10.325450 (delta: 0.119131)         elapsed: 5.781987 **** 
changed: [127.0.0.1] => {"changed": true, "checksum": "4b5e4e6c414eee03141c71541411f102a8679072", "dest": "/chaoslib/pumba/pumba_kube.yml", "gid": 0, "group": "root", "md5sum": "afe026415ea679a1cdcad972b4ea0075", "mode": "0644", "owner": "root", "size": 912, "src": "/root/.ansible/tmp/ansible-tmp-1574249830.38-148221185708287/source", "state": "file", "uid": 0}

TASK [Setup pumba chaos infrastructure] ************************************
task path: /chaoslib/pumba/pod_failure_by_sigkill.yaml:11
2019-11-20T11:37:10.588011 (delta: 0.262492)         elapsed: 6.044548 **** 
fatal: [127.0.0.1]: FAILED! => {"changed": true, "cmd": "kubectl apply -f /chaoslib/pumba/pumba_kube.yml -n default", "delta": "0:00:00.521935", "end": "2019-11-20 11:37:11.244721", "msg": "non-zero return code", "rc": 1, "start": "2019-11-20 11:37:10.722786", "stderr": "error: unable to recognize \"/chaoslib/pumba/pumba_kube.yml\": no matches for kind \"DaemonSet\" in version \"extensions/v1beta1\"", "stderr_lines": ["error: unable to recognize \"/chaoslib/pumba/pumba_kube.yml\": no matches for kind \"DaemonSet\" in version \"extensions/v1beta1\""], "stdout": "", "stdout_lines": []}

TASK [set_fact] ************************************************************
task path: /experiments/generic/container_kill/container_kill_ansible_logic.yml:60
2019-11-20T11:37:11.288349 (delta: 0.700305)         elapsed: 6.744886 **** 
ok: [127.0.0.1] => {"ansible_facts": {"flag": "fail"}, "changed": false}

TASK [include_tasks] *******************************************************
task path: /experiments/generic/container_kill/container_kill_ansible_logic.yml:65
2019-11-20T11:37:11.349269 (delta: 0.060891)         elapsed: 6.805806 **** 
included: /chaoslib/pumba/pod_failure_by_sigkill.yaml for 127.0.0.1

TASK [Patch the chaoslib image] ********************************************
task path: /chaoslib/pumba/pod_failure_by_sigkill.yaml:2
2019-11-20T11:37:11.467208 (delta: 0.117907)         elapsed: 6.923745 **** 
ok: [127.0.0.1] => {"changed": false, "checksum": "4b5e4e6c414eee03141c71541411f102a8679072", "dest": "/chaoslib/pumba/pumba_kube.yml", "gid": 0, "group": "root", "mode": "0644", "owner": "root", "path": "/chaoslib/pumba/pumba_kube.yml", "size": 912, "state": "file", "uid": 0}

TASK [Setup pumba chaos infrastructure] ***
*****************************
task path: /chaoslib/pumba/pod_failure_by_sigkill.yaml:11
2019-11-20T11:37:12.053327 (delta: 0.586085)         elapsed: 7.509864 **** 
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Confirm that the pumba ds is running on all nodes] *******************
task path: /chaoslib/pumba/pod_failure_by_sigkill.yaml:25
2019-11-20T11:37:12.091772 (delta: 0.038407)         elapsed: 7.548309 **** 
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Select the app pod] **************************************************
task path: /chaoslib/pumba/pod_failure_by_sigkill.yaml:39
2019-11-20T11:37:12.128651 (delta: 0.036833)         elapsed: 7.585188 **** 
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Record application pod name] *****************************************
task path: /chaoslib/pumba/pod_failure_by_sigkill.yaml:48
2019-11-20T11:37:12.169483 (delta: 0.040785)         elapsed: 7.62602 ***** 
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Record application pod name] *****************************************
task path: /chaoslib/pumba/pod_failure_by_sigkill.yaml:55
2019-11-20T11:37:12.214723 (delta: 0.045203)         elapsed: 7.67126 ***** 
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Identify the application node] ***************************************
task path: /chaoslib/pumba/pod_failure_by_sigkill.yaml:61
2019-11-20T11:37:12.249190 (delta: 0.034427)         elapsed: 7.705727 **** 
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Record the application node name] ************************************
task path: /chaoslib/pumba/pod_failure_by_sigkill.yaml:69
2019-11-20T11:37:12.283140 (delta: 0.033909)         elapsed: 7.739677 **** 
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Record the application container] ************************************
task path: /chaoslib/pumba/pod_failure_by_sigkill.yaml:75
2019-11-20T11:37:12.317301 (delta: 0.034027)         elapsed: 7.773838 **** 
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Record the app_container] ********************************************
task path: /chaoslib/pumba/pod_failure_by_sigkill.yaml:82
2019-11-20T11:37:12.354888 (delta: 0.037561)         elapsed: 7.811425 **** 
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Record the pumba pod on app node] ************************************
task path: /chaoslib/pumba/pod_failure_by_sigkill.yaml:88
2019-11-20T11:37:12.389343 (delta: 0.03436)         elapsed: 7.84588 ****** 
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Record restartCount] *************************************************
task path: /chaoslib/pumba/pod_failure_by_sigkill.yaml:97
2019-11-20T11:37:12.424662 (delta: 0.035278)         elapsed: 7.881199 **** 
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Force kill the application pod using pumba] **************************
task path: /chaoslib/pumba/pod_failure_by_sigkill.yaml:105
2019-11-20T11:37:12.456746 (delta: 0.032045)         elapsed: 7.913283 **** 
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Verify restartCount] *************************************************
task path: /chaoslib/pumba/pod_failure_by_sigkill.yaml:114
2019-11-20T11:37:12.488462 (delta: 0.031693)         elapsed: 7.944999 **** 
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Check if pumba is indeed running] ************************************
task
 path: /chaoslib/pumba/pod_failure_by_sigkill.yaml:129
2019-11-20T11:37:12.520224 (delta: 0.031729)         elapsed: 7.976761 **** 
FAILED - RETRYING: Check if pumba is indeed running (60 retries left).
[ ... ]
FAILED - RETRYING: Check if pumba is indeed running (1 retries left).
fatal: [127.0.0.1]: FAILED! => {"attempts": 60, "changed": true, "cmd": "kubectl get pod -l app=pumba --no-headers -o custom-columns=:status.phase -n default | sort | uniq", "delta": "0:00:00.350347", "end": "2019-11-20 11:38:49.291565", "rc": 0, "start": "2019-11-20 11:38:48.941218", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
...ignoring

TASK [Delete the pumba daemonset] ******************************************
task path: /chaoslib/pumba/pod_failure_by_sigkill.yaml:144
2019-11-20T11:38:49.355207 (delta: 96.834958)         elapsed: 104.811744 * 
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Confirm that the pumba ds is deleted successfully] *******************
task path: /chaoslib/pumba/pod_failure_by_sigkill.yaml:151
2019-11-20T11:38:49.422026 (delta: 0.066693)         elapsed: 104.878563 ** 
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [include_tasks] *******************************************************
task path: /experiments/generic/container_kill/container_kill_ansible_logic.yml:73
2019-11-20T11:38:49.474811 (delta: 0.052726)         elapsed: 104.931348 ** 
included: /utils/runtime/update_chaos_result_resource.yml for 127.0.0.1

TASK [Generate the chaos result CR to reflect SOT (Start of Test)] *********
task path: /utils/runtime/update_chaos_result_resource.yml:3
2019-11-20T11:38:49.556899 (delta: 0.082046)         elapsed: 105.013436 ** 
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Apply the chaos result CR] *******************************************
task path: /utils/runtime/update_chaos_result_resource.yml:13
2019-11-20T11:38:49.608421 (delta: 0.051486)         elapsed: 105.064958 ** 
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Update the chaos result CR to reflect EOT (End of Test)] *************
task path: /utils/runtime/update_chaos_result_resource.yml:23
2019-11-20T11:38:49.670085 (delta: 0.061603)         elapsed: 105.126622 ** 
changed: [127.0.0.1] => {"changed": true, "checksum": "1a4efc335f745d207ead1e1d8e1e67d86cc66017", "dest": "./chaos-result.yaml", "gid": 0, "group": "root", "md5sum": "871e997a8eecc1fe95f472797c3aa5f7", "mode": "0644", "owner": "root", "size": 313, "src": "/root/.ansible/tmp/ansible-tmp-1574249929.74-73976955164223/source", "state": "file", "uid": 0}

TASK [Apply the chaos result CR] *******************************************
task path: /utils/runtime/update_chaos_result_resource.yml:33
2019-11-20T11:38:50.454364 (delta: 0.783878)         elapsed: 105.910901 ** 
changed: [127.0.0.1] => {"changed": true, "cmd": "kubectl apply -f chaos-result.yaml -n default", "delta": "0:00:00.445953", "end": "2019-11-20 11:38:51.364104", "failed_when_result": false, "rc": 0, "start": "2019-11-20 11:38:50.918151", "stderr": "", "stderr_lines": [], "stdout": "chaosresult.litmuschaos.io/engine-nginx-container-kill configured", "stdout_lines": ["chaosresult.litmuschaos.io/engine-nginx-container-kill configured"]}
META: ran handlers
META: ran handlers

PLAY RECAP *****************************************************************
127.0.0.1                  : ok=17   changed=8    unreachable=0    failed=1   

2019-11-20T11:38:51.432678 (delta: 0.978273)         elapsed: 106.889215 ** 
===============================================================================```

**Comment by LaumiH** [comment]
I figured out the possible problem: the pumba.j2 file under chaoslib/pumba tries to create a deamonset from extensions/v1beta1. My kubernetes version is newer, deamonsets are now in apps/v1. I have to see how I can test this before I do a PR ^^.

**Comment by ksatchit** [comment]
Thank you for your patience & trying out the updated steps @LaumiH ! We shall look into how newer K8s versions can be supported & get back on this thread.  And yes, a PR would be awesome!!

**Comment by LaumiH** [comment]
What version of Kubernetes are you officially supporting? A hint in the documentation would be cool (or maybe I just didn't find it).

Also I managed to get pumba working by addressing the problem with the daemonset. 

Now I run into the problem that pumba cannot find the container with r2 regex [here](https://github.com/litmuschaos/litmus/blob/master/chaoslib/pumba/pod_failure_by_sigkill.yaml) on line 108. I will stay focused on fixing this so that the container-kill experiment works for me.

**Comment by ksatchit** [comment]
@LaumiH , We have tested it 1.11 onwards (Pre-requisites on getting-started page says it :) but I suppose we can make it more prominent. However, this could depend on an experiment in future as well, so I suppose the charthub/experiment docs should specify that as well) 

apps/v1 for daemonset is supported since 1.11. So I suppose we could change the extensions/v1beta1 used in the pumba.j2 without breaking any other setups/users. 

What is the issue you are seeing with the regex?

**Comment by ksatchit** [comment]
@LaumiH , thanks for the PR to add the missing selector, hope to add a better CI soon :(  !! Any info you would like to share on the regex?

**Comment by LaumiH** [comment]
I am still searching for the reason it is not working correctly. 

The problem is not the re2 regex I found out, but the pumba command itself (as it seems). I executed the job in container_kill_k8s_job.yml manually with ENV params hardcoded. The [ansible playbook](https://github.com/litmuschaos/litmus/blob/master/chaoslib/pumba/pod_failure_by_sigkill.yaml) gives error: unable to upgrade connection: container not found (\"pumba\") when executing step Force kill the application pod using pumba.

When I execute pumba on its own by creating the deamonset via [this](https://github.com/alexei-led/pumba/blob/master/deploy/pumba_kube.yml) yaml, everything seems fine. 

What I also did was executing the problematic command on its own, so creating a pumba pod manually like [here](https://github.com/litmuschaos/litmus/blob/master/chaoslib/pumba/pumba.j2) and executing kubectl exec pumba_pod -- pumba kill --signal SIGKILL re2:k8s_regex_to_container on this pod. The command successfully kills the specified container.

I will investigate further into this as I am getting new issues today.

**Comment by LaumiH** [comment]
Running the container-kill experiment by hand, so deploying my [container_kill_k8s_job_2.yml](https://raw.githubusercontent.com/LaumiH/litmus/master/experiments/generic/container_kill/container_kill_k8s_job_2.yml) as a job now works for me up to a certain point. The job successfully kills the nginx inside myserver pod. 

But then it fails asserting the pod restarted successfully, so the verify restartCount part fails as the pod takes to long getting up again. As I run on minikube with only 2 cores and 2GB ob RAM I suppose this is an artifact of my cluster, but probably the restart count should be set to a higher value or should be configurable or there should be more delay.

**Comment by ksatchit** [comment]
Configuring the delay is a good one! We have started doing this in some of the newer experiments, albeit not in a fully tunable (at least as an external user-tunable param) way, where delay/retries can be tuned based on the action or the pod (newly launched, recovery from failure etc.,): 

https://github.com/litmuschaos/litmus/blob/master/experiments/kafka/kafka-broker-pod-failure/kafka-broker-pod-failure-ansible-logic.yml#L84

https://github.com/litmuschaos/litmus/blob/master/utils/common/status_app_pod.yml#L6

**Comment by ksatchit** [comment]
As an immediate step, we could increase the retries to 60. A potential long term solution could be to take some parameter, say, such as `platform_type: slow, normal` -- which can accordingly tune timeouts in the playbooks. Would like to know your thoughts, @LaumiH !

**Comment by LaumiH** [comment]
So I cannot say what was the issue earlier today. I hat the `unable to upgrade connection: container not found (\"pumba\")` error again, then started pumba by hand as descibed in the comment above, which worked. Then I started the experiment job again and it just worked ...

Having the retries scaled up to 60 the full "chaos workflow", so creating the chaosengine runner, which then creates the container-kill experiment job, which then creates the pumba pod, works now and runs successfully :) I am so happy to have worked this out! And thank you for your patience and support @ksatchit !

**Comment by LaumiH** [comment]
Making the retries configurable is a good thing, as otherwise you have to build your own ansible runner everytime you change something on your own (as far as I understand). 

But I would rather keep the configuration with numbers instead of terms like normal and slow and annotate that normal restart lookups would be 30 and that it could be increased for slower machines (or people who just forgot to give minikube more power ;) ).

**Comment by ksatchit** [comment]
Agreed @LaumiH (the normal/slow was just a random thought for cases where one is  a bit unsure of actual values to provide, but I suppose a better way of addressing this is to let users provide a higher upper bound).  

(just rambling along for a bit more..)

Also, the `runner->job->pumba/integration` can look like a bit of an overkill :) However, the runner is meant to be a umbrella executor that *can* run a batch of experiments (or schedule/repeatedly run the specified one according to a policy -- still under construction) & the job is expected to fill in more exit/post checks for an experiment to measure an applications resilience against chaos (say, like in case of kafka, verify if a message stream is unbroken etc.,). The jobs inside the "generic" folder today are more of  *templates* on how experiments can be constructed and do not contain much other checks than verifying if a pod is back up in a specified time. 

@LaumiH , thanks to you too for the patience and persisting with the experiment. The litmus team would be really happy to have you added as a member to the project (just sent out an invite)! Also, here is the slack channel where you can share more thoughts/provide your feedback on how to improve this project: https://app.slack.com/client/T09NY5SBT/CNXNB0ZTN

**Comment by LaumiH** [comment]
@ksatchit I have a few questions concerning the experiments in the general folder. They are the most interesting to me, as I want to start chaos engineering by doing simple pod delete/ container kill/ network loss experiments. Maybe I can improve the existing experiments and make them more similar in their structure to each other.

I don't know how I can join the slack channel though.

**Comment by ksatchit** [comment]
Sure, @LaumiH , sounds good.  You can invite yourself into the kubernetes slack channel using this link: https://slack.kubernetes.io/ . Once in the workspace, you can join the  #litmus channel.
