### ISSUE TITLE
[Feat.] Collect the list of chaos specific experiments for Fluentd

### ISSUE THREAD

**Issue by slalwani97** [litmuschaos/litmus#960]
1. Chaos where Fluentd is sending logs to Elasticsearch and for some reason Elasticsearch goes down (service inaccessible) for some time, check if it is able to connect to Elasticsearch after the Elasticsearch is up and running again.

2. Chaos where Fluentd is sending logs to Elasticsearch. Killing the process of Fluentd should be able to connect to Elasticsearch again and send logs.

**Comment by ksatchit** [comment]
Litmus has enhanced its fault suite along with supported probe types, which allows users to test any application workload app-native constraints/health-validations, thereby removing the need for separate workload-specific experiments to a large extent.
