### ISSUE TITLE
(chaoslib): remove chaoskube library from pod-kill experiment

### ISSUE THREAD

**Issue by LaumiH** [litmuschaos/litmus#963]
@ksatchit told me the chaoskube lib is not supported any more, so I suggest to remove it from the README and the pod-kill experiment. The library I would keep, but give a hint in its files that it is not supported any more.

**Comment by ksatchit** [comment]
@LaumiH , thanks for taking this up! I suppose we could add a note (README/any other way you plan to include the hint) saying that it can be chosen as a supported LIB for pod-deletes only if the `chaosServiceAccount` has cluster-scope.

**Comment by LaumiH** [comment]
Alright, I will do as you suggest :)
