### ISSUE TITLE
documentation: refactor getting started tutorial

### ISSUE THREAD

**Issue by LaumiH** [litmuschaos/litmus#967]
**What happened**: I followed the steps on the [getting started](https://docs.litmuschaos.io/docs/getstarted/) page and tried to understand the part about the [ENV variables](https://docs.litmuschaos.io/docs/getstarted/#over-ride-default-chaos-experiments-variables). It is not explained very well and could be the reason beginners have problems starting with the experiments.

**What you expected to happen**: The tutorial (or maybe even a seperated page dedicated to experiment env variables) explains how the variables are set and how to override them.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**: If such page/ explanation exists, a link needs to be provided so that it can be found from the getting started page. This is most likely the "entry point" where most beginners start exploring the project, so information should be accessible.

**Comment by rahulchheda** [comment]
@LaumiH , Please refer to this page: https://docs.litmuschaos.io/docs/getstarted/#prepare-chaosengine. Apart from this, to know which ENV's have to be over-ridden, please check the README.md(for eg: https://github.com/litmuschaos/litmus/tree/master/experiments/generic/container_kill) of respective experiments, the variables marked as Mandatory and Optional, Mandatory one's (from Chaos Engine) have to be over-ridden for proper execution of the experiments.
Apart from this, we are working on implementing a "Download ChaosEngine" button on hub.litmuschaos.io, which would allows users to customize the chaosEngine, making it easier. And on the docs part, we are coming up with separate pages for separate experiment, which would contain all the information and resources required for it's execution!
Thanks for raising this issue, and please do track it's updates.

**Comment by LaumiH** [comment]
Very nice, I have one thing that I find is missing: it is unclear that some env variables are derived from the appinfo part inside the specs of a chaosengine and others can be added in the definition of an experiment inside the chaosengige. This led to huge confusion on my side and was explained to me by @ksatchit in #966 .

The README of an experiments says which env variables are needed, but for me it doesn't explain that some of them are derived from the appinfo and don't necessarily need to be overridden. There is no difference between those and the mandatory ones which have to be overridden manually. To add this peace of info to the getting started page would suffice imho.

**Comment by ksatchit** [comment]
Agreed @LaumiH . We do need to explain, on a per experiment basis on which ENV need to be provided as overrides always (mandatory) as against other optional ones. There are user docs we will start populating into the docs website. We shall place some example templates there & seek your feedback on them.

**Comment by LaumiH** [comment]
So this issue is already worked on, I see :) I hope it is alright that I create issues for (major) problems I come across while working into litmuschaos. 

I am looking forward to see the improvements in the documentation! I also undestand that the project is very young.

**Comment by ksatchit** [comment]
Yes, please go ahead @LaumiH . Appreciate the issues. Also, we could definitely do with help on adding these user-docs for the experiments, once we get the first ones in/decide the template :)

**Comment by ksatchit** [comment]
Several changes have been made to the getting started page since this issue was raised. To summarize: 

- The getting started page now uses a non-default ns to make it closer to real world usage
- The mandatory/optional ENVs are explicitly called out in the individual experiment docs
- Each experiment page now hosts a sample chaosengine definition which can be reused with minimal modification (ex: app info)
- A separate page explaining chaosengine construction which explains each flag in detail has been added.
