### ISSUE TITLE
version auto increment functionality in chaos charts repo seen to change spec items.

### ISSUE THREAD

**Issue by amitbhatt818** [litmuschaos/litmus#980]
**What happened**
Verison auto increment functionality in chaos-charts is also making few changes inside experiments spec.

**What you expected to happen:**
 The auto increment functionality should only change version of chaos-charts.
 PR link: https://github.com/litmuschaos/chaos-charts/pull/66
 Travis commit link: https://github.com/litmuschaos/chaos-charts/commit/7592f0bdcadb46200f3748ecb90cbeaebc9d94d0#diff-d9ce35cc3bd6286b73e4b74ed9d0efbeR176

**How to reproduce it (as minimally and precisely as possible)**:
**Anything else we need to know?**:
![bug](https://user-images.githubusercontent.com/33670159/70211815-fb12d680-175b-11ea-93eb-45559a214cd2.png)

**Comment by amitbhatt818** [comment]
@rajdas98  can you look into this issue.

**Comment by ksatchit** [comment]
This has not been reproduced seen in recent times. Will be reopened upon occurring again.
