### ISSUE TITLE
Usage Analytics for Litmus

### ISSUE THREAD

**Issue by umamukkara** [litmuschaos/litmus#986]
**This is a feature request:**
Feature description:
Chaos Hub (hub.litmuschaos.io) displays the meta data of chaos experiments. Following usage metrics will be helpful

- Number of Litmus installations
- Total number of experiments run
- Number of runs of an individual experiments
- Geographic details of usage

**Comment by ksatchit** [comment]
@aditya109 can you elaborate here on the approach used for the same? Thanks!

**Comment by aditya109** [comment]
Sure @ksatchit. First, of all I will be needing to setup a GA-server and add four additionals metrics for it to keep record.
Regarding the the first metric, i.e., `Number of Liitmus Installations`, which could be interpreted as **`Count for Chaos-Operator Installations`** and last metric, i.e., **`Geographic details of usage`**. I can insert the relative-function in the implementation of `Reconcile function`.
As for the third metric, i.e., **`Number of runs of an individual experiments`**, we can do the same in the `Executor code`, when it sends call for `chaos-result`. We can use the these individuals counts and add them up as to show our second metric, i.e., **`Total number of experiments run`**.

**Comment by aditya109** [comment]
@ksatchit  Can we have the **analytics** shown as this?
![Screenshot from 2019-12-23 13-12-58](https://user-images.githubusercontent.com/22005947/71343714-a6a68e00-2586-11ea-90a0-634e86c3a70f.png)
Of course, we will change the parameters. I wanted to ask if we can implement **analytics** similar to this??

**Comment by umamukkara** [comment]
This issue can be closed.
