### ISSUE TITLE
Rewrite Litmus Chaos Runner in GO

### ISSUE THREAD

**Issue by ksatchit** [litmuschaos/litmus#989]
This issue is the main feature request tracking the general availability of the enhanced Litmus Chaos Runner. The task-level issues & PRs created towards achieving this are recommended to reference this issue

### Chaos Runner Description

The chaos Runner is an operational bridge between the Chaos-Operator and the LitmusChaos experiment jobs, acting as an umbrella chaos runner which: 

- Is launched as a pod in the app namespace & reconciled by the Litmus Chaos Operator
- Reads the chaos parameters experiment CR / Overrides with values from the ChaosEngine,  constructs the experiment job (including managing dependencies such as configmap/secret volumes & launches it (along with the monitor/chaos-exporter deployment if engine's `monitoring` policy is `true`) 
- Monitors the experiment job until completion
- Cleans up the experiment job post completion based on the engine's `jobCleanUpPolicy` (`delete` or `retain`) 
- Patches the ChaosEngine with the verdict of the experiment

The above steps are repeated sequentially across the different experiments listed in the engine (typically used in case of batch execution of experiments).

### Problem Statement

Today, the chaos runner is written in ansible, which doesn't scale very well to meet some advanced requirements (see below section on requirements) 

While there is a case to continue with ansible as a primary/preferred language for creation of experiments themselves (while switching to other languages such as python/go on a need basis) considering that the common users looking at adopting these are from the SRE/DevOps community with potentially a lot of ansible usage, and also because workflow of the experiments are mostly simple `kubectl` operations or infra manipulation, the Chaos-Runner can be classified as being tasked with orchestration and is part of the core infrastructure piece of litmus, along with the operator/exporter etc.,  which demands it to be rewritten in Go (in tune with the other infra pieces) 

Some of the requirements which would need more out of the Chaos-Runner, in terms of capabilities, include the following.
 
-  Support a contextual/audit logging framework in litmus where the sequence of events from creation of the engine to its eventual removal (with the experiment execution summary in b/w) is traceable

-  Support termination/abort of experiments in progress,  Removal of all chaos residue with single operation etc., One of the ways to achieve this, is to ensure that the OwnerReference of the ChaosEngine is passed to the experiment jobs (which can be arguably termed the child resources along with the runner itself) to allow the garbage collection to take care of the deletePropagation.

- Create and/or mount volume (configmaps, secrets) resources with validation for availability of these resources. 

- Support dependency management of experiments in case of batch runs with possible parallel / asynchronous execution & thereby patching of the ChaosEngine. 

- Increased execution performance (today, the time taken to construct and launch the experiment job is directly proportional to the number of environment variables passed to it. The Kafka chaos experiments are seen to take, on an average, ~60-70s before launching the job itself.)

- Allow multiple combinations of random execution in case of future support for Chaos Scheduling, where it may be necessary for the job execution to be randomized based on different conditions (iteration count, minimum intervals etc.,) 

### Recommendation

While the ansible runner  today is capable of some of the above functions (and will continue to be supported for few more releases), they are far more efficiently achievable via the Kubernetes Go-Client, with inherent scalability, scope for code-reuse in case of refactor etc.,

**Comment by ksatchit** [comment]
An alpha version of the go chaos runner can be found here: https://github.com/litmuschaos/chaos-executor

**Comment by rahulchheda** [comment]
Reference Issues, related to improvement of go-based Litmus Chaos runner, can be found here: https://github.com/litmuschaos/chaos-executor/issues

**Comment by umamukkara** [comment]
@rahulchheda , please check  if you can use https://github.com/cloudevents/sdk-go for generating events and sequence them for various actions happening at the chaos-runner.

**Comment by ksatchit** [comment]
The beta version of the Go Chaos Runner is available in https://github.com/litmuschaos/chaos-executor. 
The documentation has been updated to use the right chaosengine spec properties to use the same. Further bug-fixes/stabilisation & enhancements, new-features will be tracked with separate issues.
